### ISSUE TITLE
BACKGROUND GEOLOCATION 'GETLOCATIONS' IOS REACT NATIVE

### ISSUE THREAD

**Issue by Txaskel** [mauron85/react-native-background-geolocation#100]
## Your Environment

* Plugin version:
* Platform: iOS 
* OS version: 10.3.3
* Device manufacturer and model: Iphone 6
* React Native version: 0.40.0
* Plugin configuration options: 
BackgroundGeolocation.configure({
    desiredAccuracy: 0,
    stationaryRadius: 50,
    distanceFilter: 0,
    debug: true,
    stopOnTerminate: false,
    interval: 1000,
  }, function () {});

## Context

Hi people!

i´m developing an app for IOS with react native and i need to get the locations every second in background. But 'GETLOCATIONS' doesnt work.

Could someone help me?

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 91 days. You may reopen this issue if it has been closed in error.
