### ISSUE TITLE
java.util.zip.ZipException: duplicate entry: com/google/android/gms/auth/api/signin/zzc.class

### ISSUE THREAD

**Issue by FredyC** [mauron85/react-native-background-geolocation#102]
Trying to build basic RN app ejected to Expokit (SDK 20.0.0). Before adding this module it worked just fine. I am quite a rookie to all Java and stuff. I've noticed the note about a version of `play-services-location` in the readme. Expo is using react-native-maps, but there is no mention of this module. Only these two in `build.gradle` which is matching to the version used by this module currently.

```
  compile "com.google.android.gms:play-services-base:10.2.4"
  compile "com.google.android.gms:play-services-maps:10.2.4"
```

## Your Environment

* Plugin version: latest master + PR #101 
* Platform: Android
* OS version: 25 (I guess)
* React Native version: 0.47.2
* Link to your project: https://bitbucket.org/fredyc/tracker/src

## Context
I am not exactly sure if it's a bug in a module or some kind of misconfiguration on my side. Tried to follow instructions as you can see in a linked project.

## Actual Behavior
```
Execution failed for task ':app:transformClassesWithJarMergingForRelease'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/gms/internal/zzasf$zza.class
```

## Steps to Reproduce
I am using Microsoft Mobile Center for a build. It's extremely easy to setup, just point it out to bitbucket repo above, configure build (no need to change any setting)

## Debug logs
Here are the [logs from Mobile Center](https://github.com/mauron85/react-native-background-geolocation/files/1272848/logs_52.zip) run

**Comment by FredyC** [comment]
Ok, I've probably messed up somewhere along the way. Setting version of `com.google.android.gms:play-services-location` to 9.8.0 has solved the issue.

However, I am wondering if this is the correct solution. I mean Expo is getting pretty widely used and if everyone has to make their own fork to change the version, it will be rather weird.

As I said, I am Java rookie. Why is it actually a problem? Can Java not handle different versions of packages as NPM can? That's rather surprising given the maturity of Java. Isn't there really a better solution? Even if it would be on a level our an actual app, it would be much better than forking one of the dependencies.

**Comment by SCasarotto** [comment]
@FredyC Did you ever find a specific reason you received this error? Freshly linked RNBG and followed these instructions: https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/INSTALL-ANDROID-RNPM.md and I am now getting this same error.

**Comment by christocracy** [comment]
@SCasarotto if you followed the instructions for `/transistorsoft/react-native-background-geolocation`, you're commenting at the wrong repo.  You need to go [here](https://github.com/transistorsoft/react-native-background-geolocation)

**Comment by SCasarotto** [comment]
Oh wow thank you. Sorry when you run around the github issues all day you lose where you are. Thank you.
