### ISSUE TITLE
[iOS] Build is failing with 'React/RCTDefines.h' file not found

### ISSUE THREAD

**Issue by FredyC** [mauron85/react-native-background-geolocation#103]
We have a successful build of an app using ExpoKit. Trying to add this module had various issues we have solved, but we cannot get past this one.

## Your Environment

* Plugin version: master branch + PR #101 
* Platform: iOS
* XCode: 8.3.3
* React Native version: https://github.com/expo/react-native/archive/sdk-20.0.0.tar.gz
* Link to your project: https://bitbucket.org/fredyc/tracker/src/9cff22e83aa7c4376a36eca2aace0a5300e1f34c?at=ios

## Context
I am totally unsure what's going on here. From my basic understanding when RCTBrdigeModule.h is looking for `<React/RCTDefines.h>` and that file is in there, it should find it. Obviously, I don't know anything about this so I am fishing in a dark here :)

## Actual Behavior
```
In file included from /Users/ci/agent/vstsagent/_work/1/s/node_modules/react-native-mauron85-background-geolocation/ios/RCTBackgroundGeolocation/RCTBackgroundGeolocation.m:9:
In file included from /Users/ci/agent/vstsagent/_work/1/s/node_modules/react-native-mauron85-background-geolocation/ios/RCTBackgroundGeolocation/RCTBackgroundGeolocation.h:10:
../../react-native/React/Base/RCTBridgeModule.h:12:9: fatal error: 'React/RCTDefines.h' file not found
#import <React/RCTDefines.h>
```

## Steps to Reproduce
You can probably just clone the project, switch to `ios` branch, `yarn install` and then try to build it in XCode.

## Debug logs
[logs_15.zip](https://github.com/mauron85/react-native-background-geolocation/files/1285231/logs_15.zip)

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 74 days. You may reopen this issue if it has been closed in error.

**Comment by FredyC** [comment]
@mauron85 No, it's not really possible to reopen... It's inactive because you are kinda inactive ;)

**Comment by mauron85** [comment]
That message was auto generated by script. So don't take it personally. Message was general. Feel free to reopen ;)

**Comment by mauron85** [comment]
I'm not familiar with Expo. But I tell you what I know. Maybe it will be helpful.

So bit of history.

Starting React 0.40 facebook decided to namespace of all ios headers with "React/" prefix.
The reason to do so, was to make it work with their proprietary closed build system.

Qote from https://github.com/facebook/react-native/wiki/Breaking-Changes#040
>This improves interoperability with FB's internal build system and makes it easier to use React Native in a mixed hybrid environment

If you ask me, I consider that as extremely selfish move from facebook side. But...

Plugin has been adjusted to be compatible with version prior 0.40 and also after.

Now the question is why it doesn't work in Expo. Can you tell me what version of react-native is Expo based on?

**Comment by mauron85** [comment]
FIY: repo is not available anymore

**Comment by FredyC** [comment]
@mauron85 I am sorry, I was kinda teasing you here since you were rather unresponsive in the past. Thank you for responding. I am no longer using Expo, but using your lib (with my fork) successfully in pure RN app, so thank you for making it. I am closing it again :)
