### ISSUE TITLE
WRITE_SYNC_SETTINGS Permission

### ISSUE THREAD

**Issue by Emeriko** [mauron85/react-native-background-geolocation#106]
Hi, maybe someone can explain. 
The WRITE_SYNC_SETTINGS Permission, for what is this permission needed in the plugin. 

BR
Emeriko

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 59 days. You may reopen this issue if it has been closed in error.

**Comment by florindumitru** [comment]
+1
