### ISSUE TITLE
java.util.zip.ZipException: duplicate entry: android/arch/core/internal/SafeIterableMap$ListIterator.class

### ISSUE THREAD

**Issue by thepinyo** [mauron85/react-native-background-geolocation#113]
how to solve this problem

Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/arch/core/internal/SafeIterableMap$ListIterator.class

react-native v0.49.3 with react-native-mauron85-background-geolocation v0.3.1

**Comment by Jose4gg** [comment]
+1 Same problem here

**Comment by sandipgupta09** [comment]
trouble processing "javax/xml/namespace/QName.class":
.
.
.
Execution failed for task ':app:transformClassesWithPreDexForRelease'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: Unable to pre-dex

**Comment by mauron85** [comment]
Is this still an issue?
