### ISSUE TITLE
navigator.geolocation difference 

### ISSUE THREAD

**Issue by gusilveiramp** [mauron85/react-native-background-geolocation#119]
First, thank you for the excellent work.
Everything working perfectly here.

I have a question: I would like to get a real-time user position with maximum accuracy when in  foreground, but when in background only every 30 seconds.

What is the most indicated in this case? Use navigator.geolocation.getCurrentPosition in foreground and BackgroundGeolocation in Background or could I do everything with BackgroundGeolocation?

What is the difference between them?

Once again, thank you!

**Comment by mauron85** [comment]
You can do it for Android with just react-native-background-geolocation. But you'll need to use unreleased [v4](https://github.com/mauron85/react-native-background-geolocation/tree/next) version, or react-native [Appstate](https://facebook.github.io/react-native/docs/appstate.html) to detect when app is in background and reconfigure plugin. 

for v4:
```
BackgroundGeolocation.on('background', () => {
    console.log('[INFO] App is in background');
    BackgroundGeolocation.configure({
        locationProvider: BackgroundGeolocation.RAW_PROVIDER,
        interval: 30000,
        fastestInterval: 30000,
    });
    BackgroundGeolocation.stop();
    BackgroundGeolocation.start();
});

BackgroundGeolocation.on('foreground', () => {
    console.log('[INFO] App is in foreground');
    BackgroundGeolocation.configure({
        locationProvider: BackgroundGeolocation. DISTANCE_FILTER_PROVIDER,
        desiredAccuracy: 10,
        interval: 30000,
        fastestInterval: 30000,
    });
    BackgroundGeolocation.stop();
    BackgroundGeolocation.start();
});
```

**Comment by gusilveiramp** [comment]
Thank you very much!
Whats difference between RAW_PROVIDER and DISTANCE_FILTER_PROVIDER?
I was using the ANDROID_ACTIVITY_PROVIDER

**Comment by mauron85** [comment]
RAW_PROVIDER acts much more like navigator.geolocation.watchPosition, while DISTANCE_FILTER_PROVIDER and ANDROID_ACTIVITY_PROVIDER apply some processing to save battery power.

**Comment by gusilveiramp** [comment]
Perfect. In my app I get the location and check if the user is close to a certain location, if it is, the app sends a push notification.
I need to run this every 1 min if it's in the background, because if the user is near the location, even if the application is in background, the user will be notified.

I could run this function only inside the BackgroundGeolocation.on ('background', () => {... without needing any other plugin or AppState?

That makes sense?

Eg.:

`BackgroundGeolocation.on('background', () => {
  console.log('[INFO] App is in background');
  BackgroundGeolocation.configure({
      locationProvider: BackgroundGeolocation.RAW_PROVIDER,
      interval: 30000,
      fastestInterval: 30000,
  });
  BackgroundGeolocation.stop();
  BackgroundGeolocation.on('location', (location) => {
    loc = Object.assign({}, location);
    console.log('[DEBUG] BackgroundGeolocation location', location);
    let isNearme = this.arePointsNear({lat:location.latitude, lng:location.longitude}, geofenceLoc, 25);
          this.setState({nearme: isNearme, loc: loc}); // show notification switched to true when user leaves geo-fence. if he is still near. ont show again. 


     if(this.state.nearme && this.state.showNotification){
      PushNotification.localNotification({
        title: "My Notification Title", // (optional, for iOS this is only used in apple watch, the title will be the app name on other iOS devices)
        message: "My Notification Message", // (required)
        soundName: 'default'
      });
      this.setState({showNotification : false});
    }
    if(!isNearme){
      this.setState({showNotification : true});
    }
  });
  BackgroundGeolocation.start();
});`

**Comment by mauron85** [comment]
Probably in your use case it will better to use some kind of geofencing library. Like https://github.com/transistorsoft/react-native-background-geolocation. But it's not free for Android.

There is free one https://github.com/surialabs/react-native-geo-fencing. However it's not really using native geofencing capabilities, only mimic them using navigator.geolocation.getCurrentPosition, similar way, you're planning to do.

There is free geofencing library https://github.com/cowbell/cordova-plugin-geofence. However it's for cordova not react-native. It could be probably easily ported to react-native. (Actually I've already begun, but didn't have time to finish it). https://gitlab.com/mauron85/react-native-geofence

I mean you can continue to use your approach. But for best results I recommend to take advantage of native geofencing.

**Comment by gusilveiramp** [comment]
I'll take a look at the Cordova library and see what you've done to try to understand a little more about how to adapt to React Native. You have no idea how you helped me. Thank you very much.

**Comment by gusilveiramp** [comment]
Sorry for reopening this, but this implementation that I quote is not working. Would you know why?
`BackgroundGeolocation.on('background',` () => {
  console.log('[INFO] App is in background');
  BackgroundGeolocation.configure({
      locationProvider: BackgroundGeolocation.RAW_PROVIDER,
      interval: 30000,
      fastestInterval: 30000,
  });
  BackgroundGeolocation.stop();
  BackgroundGeolocation.on('location', (location) => {
    loc = Object.assign({}, location);
    console.log('[DEBUG] BackgroundGeolocation location', location);
    let isNearme = this.arePointsNear({lat:location.latitude, lng:location.longitude}, geofenceLoc, 25);
          this.setState({nearme: isNearme, loc: loc}); // show notification switched to true when user leaves geo-fence. if he is still near. ont show again. 

     if(this.state.nearme && this.state.showNotification){
      PushNotification.localNotification({
        title: "My Notification Title", // (optional, for iOS this is only used in apple watch, the title will be the app name on other iOS devices)
        message: "My Notification Message", // (required)
        soundName: 'default'
      });
      this.setState({showNotification : false});
    }
    if(!isNearme){
      this.setState({showNotification : true});
    }
  });
  BackgroundGeolocation.start();
});`

**Comment by GillesVercammen** [comment]
@mauron85 In the example you presented above.

this one: 
```
BackgroundGeolocation.on('background', () => {
    console.log('[INFO] App is in background');
    BackgroundGeolocation.configure({
        locationProvider: BackgroundGeolocation.RAW_PROVIDER,
        interval: 30000,
        fastestInterval: 30000,
    });
    BackgroundGeolocation.stop();
    BackgroundGeolocation.start();
});

BackgroundGeolocation.on('foreground', () => {
    console.log('[INFO] App is in foreground');
    BackgroundGeolocation.configure({
        locationProvider: BackgroundGeolocation. DISTANCE_FILTER_PROVIDER, // or RAW it depends on your needs
        desiredAccuracy: 10,
        interval: 30000,
        fastestInterval: 30000,
    });
    BackgroundGeolocation.stop();
    BackgroundGeolocation.start();
});
```
You put RAW_PROVIDER for the background config and DISTANCE_FILTER_PROVIDER for foreground.
Shouldn't this be the other way around according to your next comment:

> RAW_PROVIDER acts much more like navigator.geolocation.watchPosition, while DISTANCE_FILTER_PROVIDER and ANDROID_ACTIVITY_PROVIDER apply some processing to save battery power.

Or am i missing something?

**Comment by mauron85** [comment]
@GillesVercammen Yes, you're right. Thanks for pointing out.
