### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by vendramini** [mauron85/react-native-background-geolocation#120]
I'm trying to compile this library on my project for hours, and I just can't find a solution. Sorry for the generic title, but I don't know how to be specific.

First, I tried to compile without any modification, and it throws me this error:
> Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.3.1) from [com.android.support:cardview-v7:25.3.1] AndroidManifest.xml:24:9-31
        is also present at [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38 value=(26.0.0-alpha1).
        Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:22:5-24:34 to override.

I realized that `react-native-background-geolocation` is trying to use a higher version of `support-v4`. So I downgraded it on `build.gradle` to fit my needs: `compile 'com.android.support:support-v4:25.3.1'`. Also, changed the gms version: `compile 'com.google.android.gms:play-services-location:10.2.4'`.

Tried to compile and it say:

> FAILURE: Build failed with an exception.
*What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
*Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED

As i said, on past with other libraries, I just excluded the library with `exclude group: "com.android.support"`, for example. Adding this:
```
compile (project(':react-native-mauron85-background-geolocation')) {
        exclude group: "com.google.android.gms" //or com.android.support, whatever
    }
```
It gives me the same error above.

My `app/build.gradle`: https://pastebin.com/FkJc28b2

I appreciate any help.

**EDIT**
On my `app/buid.gradle` is `compile "com.android.support:appcompat-v7:25.0.0"` but I also tried 25.3.1; even tried 25.0.0 on `build.gradle` of this library.

**Comment by mauron85** [comment]
Will your app compile if you remove this plugin?

**Comment by vendramini** [comment]
Yes, it does. I just commented your imports in `MainApplication.java`, `app/build.gradle' and `settings.gradle`.

**Comment by vendramini** [comment]
I did a test here: I created a project with RN 0.50.3 from scratch and added just this library. It's compiling and working, so it's not the newest RN version incompatible.

**Comment by mauron85** [comment]
>com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536

According to https://stackoverflow.com/questions/36912079/com-android-dex-dexindexoverflowexception-method-id-not-in-0-0xffff-65536-i

>Android has a pre-defined upper limit of Methods of 65536.

Is there any chance you're including jars with many methods in total?

**Comment by vendramini** [comment]
Well, I did what is here: https://developer.android.com/studio/build/multidex.html and it's compiling now. I added support for multidex. Apparently, when I added your library the limits was reached.

But I don't know if this is good, bad or doesn't matter... Do you?

Thanks for your attention =)

**Comment by mauron85** [comment]
You actually add quite lot libraries:
>    compile project(':react-native-mauron85-background-geolocation')
    compile project(':react-native-fabric')
    compile (project(':react-native-fcm')) {
        exclude group: "com.google.firebase"
    }
    compile 'com.google.firebase:firebase-core:10.2.4'
    compile 'com.google.firebase:firebase-messaging:10.2.4'
    compile project(':react-native-image-crop-picker')
    compile project(':react-native-vector-icons')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:25.0.0"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile 'com.facebook.android:facebook-android-sdk:4.+'
    compile 'com.google.android.gms:play-services-auth:10.2.4'
    compile 'com.google.android.gms:play-services-iid:10.2.4'
    compile 'com.google.android.gms:play-services-location:10.2.4'
    compile (project(':react-native-device-info')) {
        exclude group: "com.google.android.gms"
    }
    compile('com.crashlytics.sdk.android:crashlytics:2.6.8@aar') {
        transitive = true;
    }
