### ISSUE TITLE
turn off notifications which are coming from plugin

### ISSUE THREAD

**Issue by shaikhussian** [mauron85/react-native-background-geolocation#124]
I want to turn of all the notification which are coming from plugin, but i want to track the location every 5secs, 
i made debug:false, in my code and in
```
componentDidMount(){
BackgroundGeolocation.on('location', (location) => {
      console.log("location123:"+JSON.stringify(location))
      // handle your locations here
      // to perform long running operation on iOS
      // you need to create background task
      BackgroundGeolocation.startTask(taskKey => {
        console.log("taskKey123:"+taskKey)

      //here i will call my api and send the locations to db
       })
  })
}
```

i don't those notifications which are coming from plugin and i want to store my location in db when app is in background for every 5 secs.

Please help me or give me some suggestions  how can i use this module for that.

**Comment by shaikhussian** [comment]
@mauron85 please respond

**Comment by mauron85** [comment]
I don't understand your problem. Please fill issue template, so I can help.

**Comment by jeffreymendez1993** [comment]
@mauron85 his problem is that on iOS there is a local notification constantly being sent.

**Comment by mauron85** [comment]
Please post output of:

```
BackgroundGeolocation.getConfig(function(config) { console.log(config); });
```
