### ISSUE TITLE
RCTDefines.h file not found

### ISSUE THREAD

**Issue by pira22** [mauron85/react-native-background-geolocation#127]
* Plugin version: 0.4.0-rc.2
* Platform: iOS
I'm trying to setup your library but when i try to build my project through xcode always he show me this error:
<img width="360" alt="screen shot 2017-11-23 at 12 40 45 am" src="https://user-images.githubusercontent.com/6685663/33164311-05deeb6c-cfe7-11e7-95ce-3f64f8a4a079.png">

**Comment by MichielDeMey** [comment]
Did you ever get around fixing this issue?
Seems to pop up when trying to archive the project, building works fine though.

**Comment by bportman** [comment]
+1
