### ISSUE TITLE
'RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by MarshMelon** [mauron85/react-native-background-geolocation#128]
Build project , get 'RCTBridgeModule.h' file not found .. Can you help me, please . :(

#if __has_include(<React/RCTBridgeModule.h>)
  #import <React/RCTBridgeModule.h>
#else
  #import "RCTBridgeModule.h"                 get 'RCTBridgeModule.h' file not found .
#endif
#import "LocationManager.h"

**Comment by mauron85** [comment]
This should be already fixed. Reopen if you still having this issue.
