### ISSUE TITLE
iOS blue indicator on status bar

### ISSUE THREAD

**Issue by mrnix** [mauron85/react-native-background-geolocation#129]
Hi everyone! 
Is it possible to show blue indicator on status bar in iOS while this plugin is active?

![image](https://user-images.githubusercontent.com/310143/33166859-c6895856-d04c-11e7-80d0-1987753096bb.png)

**Comment by mrnix** [comment]
Sorry, found that is shown under `when in use` option

**Comment by sozkahya** [comment]
BackgroundGeolocation.configure({
      ...
      stopOnTerminate: true,
      ...
});

@mrnix you can show blue indicator with this stopOnTerminate true.
