### ISSUE TITLE
Question: Tracking by distance and interval at the same time (android)

### ISSUE THREAD

**Issue by kholiavko-roman** [mauron85/react-native-background-geolocation#132]
Hello. First of all thanks for you work it great!
I have a little question about using plugin, can I set up it for android device, using `DISTANCE_FILTER_PROVIDER` and at the same time use interval ? I try it, but it does not work when user not moving, maybe it possible ?
I need send location periodically when user is standing still.

**Comment by leograde** [comment]
I also would like to know that.
