### ISSUE TITLE
undefined is not an object (evaluating 'a.configure')

### ISSUE THREAD

**Issue by Promaethius** [mauron85/react-native-background-geolocation#134]
* Plugin version: v0.4.0-rc.2
* Platform: Android
* OS version: 8.0
* Device manufacturer and model: Pixel 2 XL
* React Native version: Expo SDK v23.0.0
* Plugin configuration options: 
* Link to your project: https://snack.expo.io/@promaethius/geolocation-test

## Context
I'm having difficulty incorporating this library in an Expo project. The error that occurs is reminiscent of library linking errors however I can not see why this library would not work as is in an Expo project. Can it work in Expo?

## Expected Behavior
'a' would be a defined object as BackgroundGeolocation.configure.

## Actual Behavior
BackgroundGeolocation.configure is missing somehow even though the error is not thrown during compile but during the installation of dependencies on the app.

## Steps to Reproduce
1. Run the snack linked above.

## Context
Creating an augmented reality game for runners.

**Comment by pixelhijack** [comment]
+1

**Comment by pixelhijack** [comment]
Getting the same with create-react-native-app, Android 6, running on Expo: 

8:26:43 AM: Finished building JavaScript bundle in 266ms
8:26:47 AM: TypeError: undefined is not an object (evaluating 'RNBackgroundGeolocation.configure')

This error is located at:
    in App (created by AwakeInDevApp)
    in RCTView (at View.js:113)
    in View (created by AwakeInDevApp)
    in AwakeInDevApp (at registerRootComponent.js:34)
    in RootErrorBoundary (at registerRootComponent.js:33)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)
- node_modules/react-native-mauron85-background-geolocation/index.js:64:28 in configure
* App.js:14:36 in componentDidMount
- node_modules/react-proxy/modules/createPrototypeProxy.js:61:45 in proxiedComponentDidMount
- node_modules/react-native/Libraries/Renderer/ReactNativeFiber-dev.js:2171:16 in commitLifeCycles
- ... 21 more stack frames from framework internals

**Comment by mauron85** [comment]
You can use expo with third party plugins I guess. You need to eject.

https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md
