### ISSUE TITLE
Posting the location data to the db is not working

### ISSUE THREAD

**Issue by bbeckk** [mauron85/react-native-background-geolocation#135]
I've the following configurations, with parameters in httpHeaders. It is not working. I want to update the location values to the database(using post method). How can I do that?

 componentDidMount() {
        BackgroundGeolocation.configure({
            desiredAccuracy: 10,
            stationaryRadius: 50,
            distanceFilter: 50,
            locationTimeout: 30,
            debug: false,
            startOnBoot: true,
            stopOnTerminate: false,
            locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
            interval: 10000,
            fastestInterval: 10000,
            activitiesInterval: 50000,
            stopOnStillActivity: false,
            url: 'http://zzz.com/uploadData',
            httpHeaders: {
                 userid: '432',
                 lat: this.state.latitude,
                 long: this.state.longitude,
                 velocity: "11",
                 alititude: "11",
                date_time: "2017-12-06 19:16:48",
                 battery_percent: "11",
             }
        });

**Comment by HaswinVidanage** [comment]
@bbeckk do you have access to the state in BackgroundGeolocation ?

**Comment by mauron85** [comment]
Please fill issue template. I cannot simply guess what platform are using...
