### ISSUE TITLE
GPS provider

### ISSUE THREAD

**Issue by gadjevb** [mauron85/react-native-background-geolocation#137]
Is there a way to use only the GPS provided coordinates with this library? If not, are there any plans to implement a GPS only provider?

**Comment by AE0011** [comment]
I need this option too! I want to get location just by GPS
Is it possible?

**Comment by mauron85** [comment]
Some manufacturers eg. Samsung allows disabling specific provider (GPS..). In that case plugin will use next best provider. So my question is what you expect plugin do if GPS is explicitly disabled and was the only option?

Also if you set `desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY` and GPS is enabled, you can be sure GPS will be used.

**Comment by AE0011** [comment]
In this case I want to disable tracking and show a proper message to user.
So how can we sure that GPS provider is on or GPS is enabled?

**Comment by mauron85** [comment]
Right now you can check `provider` parameter of Location event. In you case make sure it is`gps`.

https://github.com/mauron85/react-native-background-geolocation#location-event

**Comment by AE0011** [comment]
But when I log location there is no provider parameter!

**Comment by mauron85** [comment]
True. I just added in alpha 15

**Comment by mauron85** [comment]
> Is there any event to listen when user change ALLOW LOCATION ACCESS?

are you talking about android or ios? In case of android, it's not possible. When user changes location permission, app is just simply restarted.

**Comment by AE0011** [comment]
> True. I just added it in alpha 15

Still I don't get any provider info in my logs.
I'm testing in IOS device
```
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 9.6.1
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.0 => 0.53.0
```

```    "react-native-mauron85-background-geolocation": "^0.5.0-alpha.16"```
```
const configure = {
    locationProvider: BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,
    desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
    stationaryRadius: 50, 
    debug: true,
    distanceFilter: 5,
    stopOnTerminate: true,
    startOnBoot: false,
    startForeground: true,
    activityType: 'OtherNavigation',
};
```

**Comment by mauron85** [comment]
Oh I was talking about Android only. iOS doesn't expose that information.

**Comment by AE0011** [comment]
@mauron85 
> are you talking about android or ios? In case of android, it's not possible. When user changes location permission, app is just simply restarted.

I'm talking about ios...
![locationaccess](https://user-images.githubusercontent.com/37038198/38293621-7b773a2c-37fd-11e8-8c43-7af3ae474793.jpg)

Is there any callback when user change these above options( some how I have to sure that always is checked)
