### ISSUE TITLE
check the app is stationary or moving

### ISSUE THREAD

**Issue by shaikhussian** [mauron85/react-native-background-geolocation#139]
Hi,
i want to check the status of the app i.e whether the app is in moving or stationary.
for that i wrote like this
` BackgroundGeolocation.on('stationary', (stationaryLocation) => {
      console.log("stationaryLocation:"+JSON.stringify(stationaryLocation))
    });`

but it is not showing any response , any on please give me suggestions that how to resolve it.

**Comment by shaikhussian** [comment]
Please respond for it

**Comment by Shagamii** [comment]
+1 Same problem here

**Comment by mauron85** [comment]
What is your configuration? Please fill issue template next time.
