### ISSUE TITLE
Rare onLocationChanged events on iOS

### ISSUE THREAD

**Issue by priezz** [mauron85/react-native-background-geolocation#14]
Running the module `0.2.0-alpha.5` with RN 0.33 on the iPhone6 simulator (iOS 10) I have very rare `onLocationChanged` events. I would like to get them every 5 meters. Or, ideally, every 1 second, but this is not available under iOS, as I got from the readme. The configure options are:

```
desiredAccuracy: 0,
stationaryRadius: 0,
distanceFilter: 5,
```

For the testing purposes I use "City bicycle ride" gps mode. 

In average I have the event push on every 40 meters. I also see the following lines in the logs rather often (several times more often than I have the event fired):

```
<Warning>: LocationManager updated distanceFilter, new: 30.000000, old: 105.000000
...
<Error>: LocationManager#flushQueue has to kill an out-standing background-task!
<Warning>: LocationManager#sync Location: id=-5764607523034207997 time=105553124672096 lat=37.33193356 lon=-122.03785871 accu=5 aaccu=-1 speed=7.6 head=93.40000000000001 alt=0 type=current
...
<Warning>: LocationManager updated distanceFilter, new: 25.000000, old: 100.000000
<Error>: LocationManager#flushQueue has to kill an out-standing background-task!
```

Is this something wrong with the configuration?

**Comment by priezz** [comment]
I have to add that I have message like
```
<Warning>: Better location found: Location: id=0 time=106102880514304 lat=37.33759314 lon=-122.03673258 accu=10 aaccu=-1 speed=7.19 head=270.41 alt=0 type=current
```
In the log every second. I am not sure about the source of this message, but that means that something is getting the location updates much more often. Ideally, I would like to get them all as well.

**Comment by mauron85** [comment]
That warning is fine (should not be warning at all), it is just comparing received location with previous one.

Also you get every seconds, because that's how often you're receiving location updates.

You will not receive location every x minutes, because plugin is recalculating distanceFilter. That's the whole point of existence. You can read more about it:

https://github.com/mauron85/cordova-plugin-background-geolocation/blob/master/ANDROID_DISTANCE_FILTER_PROVIDER.md#distancefilter

**Comment by mauron85** [comment]
it does not matter what value you set, it will be auto recalculated when new position is recieved. Currently it is not possible to disable it. There is ongoing discussion about creating bare version of the plugin instead.

https://github.com/mauron85/cordova-plugin-background-geolocation/issues/124

**Comment by priezz** [comment]
I see... Thanks for the explanation!

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 219 days. You may reopen this issue if it has been closed in error.

**Comment by iKrushYou** [comment]
Was this ever resolved? I'm getting really slow times as well. It seems like it goes quickly at first and then slows down gradually -- i guess due to the recalculation of the distance filter?
