### ISSUE TITLE
incompatible with FCM with android. App crashes unexpectedly.

### ISSUE THREAD

**Issue by sagark1510** [mauron85/react-native-background-geolocation#140]
Plugin works fine for some seconds and after that suddenly app gets crashed, error log as attached.

## Your Environment

* Plugin version: 0.4.0
* Platform: Android 
* OS version: 7.1.1
* Device manufacturer and model: Moto G5s Plus
* React Native version: 0.48.3
* Plugin configuration options: 
* Link to your project:

## Context

I feel the issue is related to notification, as I am not good at native android development I don't understand what is the exact issue.

## Expected Behavior

It should not affect other plugins listeners on notification or related it as per error I shared.

## Possible Fix

I don't have idea whether it can be handled from FCM or this library.

## Steps to Reproduce

1. install both plugin in single app
2. start the background location using `.start` method
3. wait for 5-10 seconds 
4. app will get crashed and if you have logcat you will see fcm error throw

## Context

Tracking location and sending the updates to server.

**Comment by mauron85** [comment]
What is the name of fcm plugin?

**Comment by dobrynia** [comment]
Probably it's a react-native-fcm plugin.

**Comment by vendramini** [comment]
I'm using both plugins in 2 projects and works pretty well.

Where's the error attached?

**Comment by sagark1510** [comment]
@vendramini  I am sorry I don't know why it's not showing the attachment. here is the link https://user-images.githubusercontent.com/2134076/34071459-ab87c968-e29c-11e7-9429-5315b13959d3.png.


@mauron85  react-native-fcm plugin.

**Comment by mauron85** [comment]
@sagark1510 I'm using react-native-fcm-plugin without any issues. So not sure what causes your problems.

And according picture you've posted, I doubt it's related to this plugin.

**Comment by sagark1510** [comment]
@mauron85 I might be wrong but as I shown in the image it works properly for the first 5-10 seconds and suddenly due to some notification reason fcm gets executed with JSON error. And this happens only after integrating geolocation plugin, so I feel there must be some sort conflict between both of them as both are showing notification.

**Comment by mauron85** [comment]
Is this still valid? If so, please provide crash dump.
