### ISSUE TITLE
Doesnt compile out of the box with proguard

### ISSUE THREAD

**Issue by DevNamedZed** [mauron85/react-native-background-geolocation#141]
The example project does not compile when proguard is enabled. 

1.  Clone the example project

2. set the enableProguardInReleaseBuilds to true in the android/app/build.gradle to enable proguard.

3. attempt to build 

result
proguard crashes.

Seems like the issue is with this logging library. The line below should be added to the proguard-rules.pro.

-dontwarn ch.qos.logback.core.net.**

Initially thought my build failure was the react-native maps version issue, so I spent a while debugging. Please add proguard instructions to the readme.

**Comment by mauron85** [comment]
Is this still relevant?

**Comment by Nodonisko** [comment]
Still relevant, this should be added to rules if you want make this plugin work with proguard.
