### ISSUE TITLE
iOS only calls 'location' once. Android works periodically.

### ISSUE THREAD

**Issue by vendramini** [mauron85/react-native-background-geolocation#142]
## Your Environment

* Plugin version: "react-native-mauron85-background-geolocation": "^0.4.1",
* Platform: iOS and Android
* OS version: iOS: 10.3, Android: 6.0
* Device manufacturer and model: Apple and Motorola Moto MAXX.
* React Native version: 0.51.0
* Plugin configuration options: 
```javascript
BackgroundGeolocation.configure({
            desiredAccuracy: 10,
            stationaryRadius: 50,
            distanceFilter: 50,
            locationTimeout: 30,
            debug: false,
            startOnBoot: false,
            stopOnTerminate: true,
            locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
            interval: 10000,
            fastestInterval: 30000,
            activitiesInterval: 20000,
            stopOnStillActivity: false,
            maxLocations: 1,
            startForeground: false,
        });
```

## Context
Same code for both platform: Android calls the `BackgroundGeolocation.on('location')` method periodically. iOS doesn't.

## Expected Behavior
iOS also calls the method.

## Actual Behavior
iOS calls only once.

## Steps to Reproduce
1. Start an app with config above.
2. Android works as expected. iOS don't.

## Context
Request user's position from time to time to request some data from server based on his location.

**Comment by dobrynia** [comment]
If you read about the types of providers on this [page](https://github.com/mauron85/react-native-background-geolocation/blob/master/PROVIDERS.md#activity_provider-android-only), you might notice that **ACTIVITY_PROVIDER** works only for android devices. For iOS you should choose **DISTANCE_FILTER_PROVIDER** or **RAW_PROVIDER**.
