### ISSUE TITLE
How to send a PR for a version that is not included in releases list?

### ISSUE THREAD

**Issue by efratyo** [mauron85/react-native-background-geolocation#144]
## Your Environment

* Plugin version: 0.2.0-alpha.5
* Platform: Android
* React Native version: 0.40.0

Hi there, 
I'm having an issue that [#116](https://github.com/mauron85/react-native-background-geolocation/issues/116) fixes.
I'm using an old version of this package - 0.2.0-alpha.5, with RN-0.40.0.
I can't upgrade RN right now, so I can't also upgrade this package to 0.3.x and above.
And It's wrong to have this fixed inside my node_modules.
How can I send a PR with the fix for my relevant version when it doesn't appear in the releases list nor the tags list under master branch?

Thanks

**Comment by mauron85** [comment]
@efratyo you can maintain forked version of this plugin, if you need to stay on 0.2.x for some reason. Only reason not to use forks are build systems having issues with packages installed from github (thinking of PhoneGap build). But as far I know, there is no build system like PhoneGap Build for react-native. So I think you can safely install and use forked version from github.

But if you have special reason write it here. If it's good, I can probably find and tag commit with proper version number for you.

**Comment by vendramini** [comment]
@efratyo try this https://github.com/ds300/patch-package so you can change things inside node_modules and save the new version on your repository. I use it, it's very useful.

**Comment by efratyo** [comment]
Thanks you guys! I'm now able to upgrade my RN versions.
