### ISSUE TITLE
Syncing all locations on every sync run

### ISSUE THREAD

**Issue by L3V147H4N** [mauron85/react-native-background-geolocation#146]
Environment
* Plugin version: 0.4.1
* Platform: Android
* OS version: Windows 10 Pro
* Device manufacturer and model: Multiple Real Devices (Samsung, Sony, Motorola, BLU)
* React Native version: 0.50.0
* Plugin configuration options: 
```javascript
{
  desiredAccuracy: 10,
  stationaryRadius: 50,
  distanceFilter: 50,
  locationTimeout: 30,
  notificationTitle: 'Background tracking',
  notificationText: 'enabled',
  debug: false,
  startOnBoot: true,
  stopOnTerminate: false,
  interval: 60000,
  fastestInterval: 30000,
  startForeground: false,
  activitiesInterval: 60000,
  stopOnStillActivity: false,
  url: '<serverurl>',
  syncUrl: '<serverurl>',
  syncThreshold: 50,
  maxLocations: 1000
}
```
* Link to your project: private

## Context
I provided a Sync URL to send all locations to my server and the service is sending all locations every time or every once in a while.

## Expected Behavior
When sync after the 200 Response the locations should "be marked as deleted or sent" and later just send the locations that could not be sent

## Actual Behavior
The service is sending all locations almost every time

Is there a way to check if the locations saved on the device have been sent? when I get the locations with `getLocations()` I don't see any property indicating sent status

**Comment by goblinbr** [comment]
check the status code that your server is returning, it has to return code 200, had the same issue when my server was returning 204

**Comment by L3V147H4N** [comment]
I guess it's a possibility; I previously hijack the response to send code 200 (instead of 201) because the lib only accepted 200 but I saw that a PR was merged and now supposedly accepts 200 and 201 but I guess I will have to do some more checking.

**Comment by mauron85** [comment]
As said check if your server is returning code 200 or 201.
