### ISSUE TITLE
Can not Delete Location stored

### ISSUE THREAD

**Issue by pacozaa** [mauron85/react-native-background-geolocation#147]
## My Environment

* Plugin version: 0.4.1
* Platform: Android
* OS version: Android 6.0.1
* Device manufacturer and model: SAMSUNG GalaxyJ7
* React Native version: 0.50.3
* Plugin configuration options:  
``` javascript 
{
 desiredAccuracy: 10,
  stationaryRadius: 50,
  distanceFilter: 50,
  debug: false,
  startOnBoot: false,
  stopOnTerminate: false,
  locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
  notificationTitle: 'Driver Apps',
  notificationText: 'GPS is On',
  interval: 20000,
  fastestInterval: 5000,
  activitiesInterval: 10000,
  stopOnStillActivity: false,
  maxLocations: 5
}
```

## Context
I am working on application that update user location about every 30 seconds

## Expected Behavior
I am trying to limit and control size of locations store in the apps. I expect it to be control.

## Actual Behavior
`deleteLocation`and `deleteAllLocations` actually do nothing and they always return success status. I know it because I `console.log` in location event nothing happen after mentioned method. When the stored location reach its limit. it stay maximum no less

Best

**Comment by mauron85** [comment]
If you delete location it will not be automatically synced (if you use option `syncUrl`) and it will not be returned by `getValidLocations` method. However it still might appear in `getLocations` until it is overwritten by new location.
