### ISSUE TITLE
Closed notifications and get instant location

### ISSUE THREAD

**Issue by juancafe4** [mauron85/react-native-background-geolocation#148]
Hi, I have been having some issues. I need to get an actual location instantly getAllLocations does not help because when the app starts, there is not locations stored. So How can I initially get an actual location? 

Another questions I have startForeground on true which show a local notification. How can I stop showing this notification?

**Comment by mauron85** [comment]
1. You can use `https://facebook.github.io/react-native/docs/geolocation.html` to get initial location.
2. With `startForeground : true` you can't.  If you don't like the notification set it to false, but keep in mind service might get killed by the system unpredictably.
