### ISSUE TITLE
Post Locations whilst in background to Firebase

### ISSUE THREAD

**Issue by mrnadaara** [mauron85/react-native-background-geolocation#150]
I have been developing an app for a while and everything seems great, but one tedious problem is bugging me. I can't update locations on my firebase database whilst in background. I tried to create a background task using .startTask(), I even tried to use the background eventType to start it up but there was no luck. Apparently you can only update or post locations when you define a url or syncUrl but I can't use this because I am using GeoFire to post locations. Everything else works fine when in foreground mode. Anyway I can execute JS Code in the background??? Or provide a function object that will execute JS code natively??? I really would love if you could help.

**Comment by mauron85** [comment]
You can try new headless task that was added in alpha 15.
