### ISSUE TITLE
What is startOnBoot

### ISSUE THREAD

**Issue by pacozaa** [mauron85/react-native-background-geolocation#152]
I am using this library on Android and wondering how to make `location` event fire on background mode.

Does `startOnBoot: true` do the job?

What exactly `startOnBoot` do? Could you give me an example?

Best,
Sarin

**Comment by nyenye** [comment]
@pacozza Look at the example given in the readme. It works on background mode. And if you look through the options, you shold find the one that handles it.

**Comment by kholiavko-roman** [comment]
`startOnBoot: true` means that after restarting your phone background tracking will be starting automatically.
