### ISSUE TITLE
Notification title and text does not work on Android 8

### ISSUE THREAD

**Issue by sercanov** [mauron85/react-native-background-geolocation#154]
## Your Environment

* Plugin version:0.4.1
* Platform:  Android
* OS version: 8
* Device manufacturer and model: OnePlus 3T
* React Native version: 0.50

## Context

Started tracking with the following configuration
```javascript
{
      desiredAccuracy: BackgroundGeolocation.accuracy.HIGH,
      stationaryRadius: 5,
      distanceFilter: 5,
      notificationTitle: 'This is title',
      notificationText: 'This is text',
      debug: true,
      startOnBoot: false,
      stopOnTerminate: false,
      locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
      startForeground: true,
      interval: 5000,
      fastestInterval: 5000,
      activitiesInterval: 10000,
      stopOnStillActivity: false,
      url: `${BASEURL}/api/users/location2`,
      httpHeaders: {
        Authorization: token,
        'Content-Type': 'application/json'
      }
    }
```
## Expected Behavior

Foreground service notification should include "This is title" and "This is text"

## Actual Behavior

It shows default Android notification similar to screenshot below.
![ximg_20170907_122102 jpg pagespeed gp jp jw pj ws js rj rp rw ri cp md ic rywrezzvgy](https://user-images.githubusercontent.com/10291644/35619811-3bdac508-0690-11e8-9463-216c474a4092.jpg)

## Possible Fix

Android 8 Notification channel causes that maybe ?

**Comment by kholiavko-roman** [comment]
On my nexus 5x all works fine on Android 8.
