### ISSUE TITLE
on location not being called when app has been forcefully killed (android)

### ISSUE THREAD

**Issue by davidmessem** [mauron85/react-native-background-geolocation#155]
When I have my react native app open and the location updates, `BackgroundGeolocation.on('location'` get's called fine, but when I forcefully kill the app, it is no longer called.

I am running with debug mode on, so I can see that the plugin is still getting updates (toasts and sounds are being activated)

## Your Environment
* Plugin version: 0.4.1
* Platform: Android
* OS version: 4.3 and 7.1.1
* Device manufacturer and model: Samsung Galaxy S3 and Nexus 5 (emulated)
* React Native version: 0.52.0
* Plugin configuration options: 
         locationProvider: BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,
         desiredAccuracy: 100,
         stationaryRadius: 1,
         debug: true,
         distanceFilter: 1,
         stopOnTerminate: false,
         startOnBoot: true,
         interval: 1000,
         fastestInterval: 1000,
         activitiesInterval: 1000,
         stopOnStillActivity: false,
         startForeground: false
* Link to your project: No

## Context
When I have my react native app open and the location updates, `BackgroundGeolocation.on('location'` get's called fine, but when I forcefully kill the app, it is no longer called.

I am running with debug mode on, so I can see that the plugin is still getting updates (toasts and sounds are being activated)

## Expected Behavior
The on location function get's called even after the app is forcefully terminated

## Actual Behavior
The on location function does not get called after the app is forcefully terminated

## Possible Fix
Recreate React Native context if it is not present when a location update is registered

## Steps to Reproduce
1. Install and configure plugin in React Native app (plugin debug: true)
2. Launch App
3. See location updates and on location being called
4. Forcefully kill app 
5. See debug toasts and sounds but on location not being called

## Context
I am trying to periodically track user's location even if app is forcefully killed by user

## Debug logs
Lot's of the following, can provide more logs upon request

2-03 13:07:38.171 27474-27497/com.myapp D/com.tenforwardconsulting.bgloc.DistanceFilterLocationProvider: Location change: Location[gps -26,095993,28,025247 acc=6 et=+1d17h34m30s646ms alt=1538.010931396014 vel=0.0 {Bundle[mParcelledData.dataSize=44]}] isMoving=true
02-03 13:07:38.241 27474-27497/com.myapp D/com.marianhello.bgloc.LocationService: New location BGLocation[gps -26,095993,28,025247 id=null acc=6 t=1517656057999 et=+1d17h34m30s646ms alt=1538.010931396014 vel=0.0 {Bundle[mParcelledData.dataSize=44]} locprov=0]
02-03 13:07:38.336 27474-27497/com.myapp D/com.marianhello.bgloc.LocationService: Persisted location: BGLocation[gps -26,095993,28,025247 id=62 acc=6 t=1517656057999 et=+1d17h34m30s646ms alt=1538.010931396014 vel=0.0 {Bundle[mParcelledData.dataSize=44]} locprov=0]

**Comment by mauron85** [comment]
This is normal behaviour. When you kill app there also js callback are destroyed. You need to set options `url` or `syncUrl to send locations to your server.

**Comment by tugorez** [comment]
Just being curious here @mauron85: so when I reboot my phone this won't work either right?

**Comment by mauron85** [comment]
@tugorez you mean reboot with option startOnBoot: true? if so, then answer is yes, it won't work. App (activity) must be running to receive location events.

**Comment by tugorez** [comment]
@mauron85 thank you very much for your quick answer.

**Comment by GrishmaM** [comment]
@mauron85 is there any possible way to listen to location events even after the app is killed from the background

**Comment by mauron85** [comment]
@GrishmaM on Android using headless task only. https://github.com/mauron85/react-native-background-geolocation#android-headless-task-experimental

**Comment by GrishmaM** [comment]
@GrishmaM thank you for the above info, I'm facing one more issue
In Android when the app is running in background location event is nor rasing, it works only in forground
