### ISSUE TITLE
libsqlite3.tbd is not an object file

### ISSUE THREAD

**Issue by VinZenTz1989** [mauron85/react-native-background-geolocation#16]
I got this message when using this lib on macOS Sierra and xCode 8.

Anyone knows how to fix the problem? Plz help 

Best Regards

**Comment by mauron85** [comment]
Follow my comment https://github.com/mauron85/react-native-background-geolocation/issues/12#issuecomment-248241564

**Comment by VinZenTz1989** [comment]
Thx you. It's resolved
