### ISSUE TITLE
iOS - How to track location on background in interval

### ISSUE THREAD

**Issue by NgKhanh** [mauron85/react-native-background-geolocation#160]
I have a project require track background location each 15s even phone not moving (no distance change). It works on Android but dont work on iOS. Anyhelp ?

**Comment by jacobbeasley** [comment]
This isn't enough information to help. Could you perhaps share your project and/or a sample project where it isn't working?

**Comment by dmarkowski** [comment]
According to 'Configure options' in Readme, tracking location in interval is not supported on iOS only Android. Is that true? Is there any way to use intervals on iOS?

**Comment by mauron85** [comment]
@dmarkowski this not possible on iOS. Background timers will not work in background. Latest Android versions are also becoming more and restrictive about how often can you run your code in the background. But android location manager still supports polling locations in intervals. However iOS does not.
