### ISSUE TITLE
[Android ] App build fails on Windows

### ISSUE THREAD

**Issue by Rall3n** [mauron85/react-native-background-geolocation#161]
## Your Environment

* Plugin version: `0.4.0`, `0.4.1`, `0.5.0-alpha.4`, `0.5.0-alpha.7`
* Platform: Android
* OS version: 23
* Device manufacturer and model: Emulator Nexus 5x
* React Native version: 0.52.2
* Plugin configuration options: ?
* Link to your project: None
* Environment: Windows 10
* Installed Android APIs`: 27, 26, 23, 21, 16
* Installed SDK Tools: `Androis SDK Build-Tools`, `Android SDK Platform-Tools`, `Android SDK Tools`, `Google Play services`, `Android Support Repository`, `Google Repository`

## Context
A colleague of mine has implemented this package into our app. It seems to work on his MacOS device, but when I want to build on my Windows pc, it fails. I have followed many solutions with a similar context to help with my problem, but everything failed.

This makes it impossible for me to continue on the project while using this package.

## Expected Behavior
App builds with no errors.

## Actual Behavior
App build fails with following error:
```
Execution failed for task ':react-native-mauron85-background-geolocation:processReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt
``` 
Which seemed to be caused by following errors:
```
C:\usr\local\google\buildbot\repo_clients\https___googleplex-android.googlesource.com_a_platform_manifest.git\mnc-sdk-release\frameworks\support\v7\appcompat\res\drawable\abc_list_selector_holo_light.xml:22: AAPT: No resource found that matches the given name (at 'drawable' with value '@drawable/abc_list_selector_disabled_holo_light').

[...]

C:\Users\USER\Projects\REACTAPP\node_modules\react-native-mauron85-background-geolocation\android\lib\tmp\gpxtracker\react-native-mauron85-background-geolocation\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.8.0\res\drawable\common_google_signin_btn_text_dark.xml:11:27-79: AAPT: No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_dark_focused').
```
(Username and projectname obfuscated due to privacy reasons)

## Possible Fix

None currently

## Steps to Reproduce

1. Install package with npm/yarn
2. Follow installation instructions
3. Start app debug build
4. Results

## Debug logs

[assembleDebugLog.txt](https://github.com/mauron85/react-native-background-geolocation/files/1788168/assembleDebugLog.txt)
[package.json, build.gradle and app/build.gradle](https://gist.github.com/Rall3n/c0d939913c117c72fafd31d38beb1bc2)

**Comment by Rall3n** [comment]
I fixed my error.
I solved the issue by deleting the maven repo url from google out of my gradle files.

**Comment by pacozaa** [comment]
@Rall3n I got the same error what if I need maven repo url from google?
