### ISSUE TITLE
Accessing state and async storage.

### ISSUE THREAD

**Issue by HaswinVidanage** [mauron85/react-native-background-geolocation#162]
Hi , first of all hats off to you on making this. Everything works perfectly.

The question I have is 
1. whether the state is accessible to BackgroundGeolocation for example if I have to set a header for the post template using a value on my state can this be achieved?

2. Can async storage be used within BackgroundGeolocation .

Thanks in advance and sorry that this is not a issue.

**Comment by kholiavko-roman** [comment]
1. Yes
2. Yes, you can do this.

**Comment by mauron85** [comment]
according 1. yes, but any change on state of value will not be reflected. It's your responsibility to call configure when state changes. You don't have to provide all configure options, only postTemplate (partial reconfiguration).

```
BackgroundGeolocation.configure({
  postTemplate: ['@latitude', '@longitude', state.someValue]
});;
```

**Comment by HaswinVidanage** [comment]
noted and thanks.
