### ISSUE TITLE
Background location updates

### ISSUE THREAD

**Issue by theebi** [mauron85/react-native-background-geolocation#163]
Does background location updates work in Android (I mean when user force quit the application)

**Comment by kholiavko-roman** [comment]
You can configure this with `stopOnTerminate` option.

**Comment by mauron85** [comment]
@theebi @kholiavko-roman answer is correct one. Closing. Please don't open issue for these kind of question, where answers can be found in documentation. It just take additional burden to me as single person developer of this plugin. Thanks for understanding.
