### ISSUE TITLE
please someone help me out

### ISSUE THREAD

**Issue by lokeshpayani** [mauron85/react-native-background-geolocation#165]
## Your Environment

* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer and model:
* React Native version:
* Plugin configuration options: 
* Link to your project:

## Steps to Reproduce

1.
2.
3.
4.

**Comment by lokeshpayani** [comment]
please help me out 
the configuration file for my application its perfectly logging the and posting data in IOS but in android its not showing correct route map 

BackgroundGeolocation.configure({
     

            desiredAccuracy:50,
            stationaryRadius: 100,
            distanceFilter: 100,
            notificationTitle: 'Background tracking',
            notificationText: 'enabled',
            debug: false,
            startOnBoot: false,
            stopOnTerminate: true,
            locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,           
            interval: 120000,
            fastestInterval: 5000,
            activitiesInterval: 120000,
            stopOnStillActivity: false,*/
            
               });
        }else{
            BackgroundGeolocation.configure({
            desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
            stationaryRadius: 200,
            distanceFilter: 100,
            notificationTitle: 'Background tracking',
            notificationText: 'enabled',
            debug: false,
            startOnBoot: false,
            stopOnTerminate: true,
            locationProvider: BackgroundGeolocation.ACTIVITY_FILTER,
            activityType: 'OtherNavigation',
            interval: 60000,
            fastestInterval: 6000,
            activitiesInterval: 60000,
            stopOnStillActivity: false
          });

**Comment by lokeshpayani** [comment]
first block is android and else part is IOS

**Comment by mauron85** [comment]
Please don't post question asking for help as issue. It makes traversing issue more difficult if there are too many issues. Also fill issue template properly, if you think you're effected by bug. Thank you for understanding.
