### ISSUE TITLE
Implement support for applicationIdSuffix

### ISSUE THREAD

**Issue by mjgallag** [mauron85/react-native-background-geolocation#167]
Android auto configure sync (https://github.com/mauron85/react-native-background-geolocation/commit/57619948ae2255ba51b27fe49ca48f8261da1cf7) doesn't handle `applicationIdSuffix` ([Change the application ID for build variants](https://developer.android.com/studio/build/application-id.html#change_the_application_id_for_build_variants)).

I've worked around it in my app's `build.gradle` as follows:
```gradle
buildTypes.all { buildType ->
    buildType.resValue "string", "content_authority",
        "${defaultConfig.applicationId}${buildType.applicationIdSuffix ?: ''}.provider"
    buildType.resValue "string", "account_type",
        "${defaultConfig.applicationId}${buildType.applicationIdSuffix ?: ''}"
}
```

**Comment by mjgallag** [comment]
FYI, the [`${applicationId}`](https://developer.android.com/studio/build/manifest-build-variables.html) `AndroidManifest.xml` merge variable correctly includes `applicationIdSuffix`. For exmaple `react-native-image-picker`'s provider correctly includes it in the follow way https://github.com/react-community/react-native-image-picker/blob/develop/android/src/main/AndroidManifest.xml.

**Comment by mauron85** [comment]
Just thinking if this is actually necessary. Currenly plugin is using DummyContentProvider, which basically does nothing. As result one sync account in theory could handle any app that is using this plugin!
