### ISSUE TITLE
java.lang.IllegalArgumentException: Receiver not registered

### ISSUE THREAD

**Issue by kristfal** [mauron85/react-native-background-geolocation#169]
We're seeing quite a few production crashes with this plugin. Here are the stacks:

```java
com.marianhello.react.BackgroundGeolocationModule.unregisterLocationModeChangeReceiver
BackgroundGeolocationModule.java - line 276
java.lang.IllegalArgumentException: Receiver not registered: com.marianhello.react.BackgroundGeolocationModule$2@58d1045

android.app.LoadedApk.forgetReceiverDispatcher LoadedApk.java:766
android.app.ContextImpl.unregisterReceiver ContextImpl.java:1686
android.content.ContextWrapper.unregisterReceiver ContextWrapper.java:511
android.content.ContextWrapper.unregisterReceiver ContextWrapper.java:511
com.marianhello.react.BackgroundGeolocationModule.unregisterLocationModeChangeReceiver BackgroundGeolocationModule.java:276
com.marianhello.react.BackgroundGeolocationModule.onHostDestroy BackgroundGeolocationModule.java:119
com.facebook.react.bridge.ReactContext.onHostDestroy ReactContext.java:228
com.facebook.react.ReactInstanceManager.moveToBeforeCreateLifecycleState ReactInstanceManager.java:705
com.facebook.react.ReactInstanceManager.onHostDestroy ReactInstanceManager.java:614
com.facebook.react.ReactInstanceManager.onHostDestroy ReactInstanceManager.java:628
com.facebook.react.ReactActivityDelegate.onDestroy ReactActivityDelegate.java:142
com.facebook.react.ReactActivity.onDestroy ReactActivity.java:72
android.app.Activity.performDestroy Activity.java:6200
```

Our config is:

```
{
  desiredAccuracy: HIGH_ACCURACY,
  stationaryRadius: 30,
  distanceFilter: 10,
  notificationTitle: I18n.t('background_tracking'),
  notificationText: I18n.t('enabled'),
  debug: false,
  startOnBoot: false,
  stopOnTerminate: true,
  locationProvider: DISTANCE_FILTER_PROVIDER,
  activityType: 'Fitness',
  interval: 2500,
  fastestInterval: 2500,
  activitiesInterval: 5000,
  stopOnStillActivity: false,
};
```

## Your Environment
* Plugin version: 0.4
* Platform: Android
* OS version: 23 - 26
* Device manufacturer and model: Wide range
* React Native version: 0.51
* Plugin configuration options:

## Possible Fix
This is quite possibly related to #46, and as stated there – this seems to be caused by a race condition.

We also code pushed a hotfix by setting `stopOnTerminate` to `false`, and that fixed the crashing.

**Comment by mauron85** [comment]
Please upgrade to latest 0.5 alpha. I guess it's fixed there.

**Comment by reetou** [comment]
Happens to me on 0.5.alpha-19

**Comment by mauron85** [comment]
@reetou can you post crash log. because 0.5.alpha-19 has done quite big refactoring so lines from origin crash doesn't match anymore. I'll take look then on it.

**Comment by mauron85** [comment]
There are already guards to not try unregistered receiver when it was not registered, but apparently there is something strange. So please post configuration options and steps how to reproduce the crash and also crash log from adb logcat.

**Comment by kristfal** [comment]
@mauron85 Happy to test alpha-19, but master install seems broken as the subproject is not included when installed with yarn/npm.

**Comment by mauron85** [comment]
@kristfal Not it should not be. Read my comment https://github.com/mauron85/react-native-background-geolocation/pull/168#issuecomment-380144164
