### ISSUE TITLE
undefined is not an object (evaluating 'RNBackgroundGeolocation.configure')

### ISSUE THREAD

**Issue by nodegin** [mauron85/react-native-background-geolocation#17]
* Plugin version: 0.2.0-alpha.5"
* Platform: iOS
* OS version: 10.0 (14A345)
* Device manufacturer and model: Simulator iPhone 6
* React Native version: 0.34.0

Here's the code snippet:

```
BackgroundGeolocation.configure({
  desiredAccuracy: 10,
  stationaryRadius: 1,
  distanceFilter: 1,
  interval: 5000,
  fastestInterval: 5000,
  saveBatteryOnBackground: false,
  activityType: 'Fitness',
  url: apiUrl,
  stopOnStillActivity: false,
})
BackgroundGeolocation.start()
```

## Expected Behavior
Getting the location to work

## Actual Behavior
Nothing worked, log message shows `undefined is not an object (evaluating 'RNBackgroundGeolocation.configure')`

## Steps to Reproduce
1. Install the library
2. Run the code snippet

**Comment by nodegin** [comment]
Fixed by removing all references and reinstalling the library

**Comment by DanielCarns** [comment]
@nodegin  Could you elaborate on your fix please? I'm on Version: 0.2.0-alpha.7. I've tried reinstalling the library and it's still giving me this: 
![simulator screen shot jun 28 2017 12 02 59 pm](https://user-images.githubusercontent.com/23421970/27647550-bd69d7ae-5bf9-11e7-9da1-5fcecfe2bbb8.png)

**Comment by nodegin** [comment]
@DanielCarns You need remove all references in XCode, however I forgot the details

**Comment by DanielCarns** [comment]
@nodegin Okay, thanks for the speedy reply.

**Comment by michael-gillett** [comment]
@DanielCarns Did you figure this one out? I'm facing the same issue right now

**Comment by DanielCarns** [comment]
@michael-gillett Yeah, so I found out I was missing the libsqlite3.tbd file under Build Phases -> Link Binary with Libraries. If you aren't missing that then I suggest deleting the Xcode project and restarting and following this process:

1.) In XCode, in the project navigator, right click Libraries ➜ Add Files to [your project's name]
2.) add ./node_modules/react-native-mauron85-background-geolocation/ios/RCTBackgroundGeolocation.xcodeproj
3.) In the XCode project navigator, select your project, select the Build Phases tab and in the Link Binary With Libraries section add libRCTBackgroundGeolocation.a
4.) add UIBackgroundModes location to Info.plist
5.) add NSLocationAlwaysUsageDescription App requires background tracking to Info.plist

For more information check https://github.com/mauron85/react-native-background-geolocation

**Comment by michael-gillett** [comment]
@DanielCarns Thanks a bunch, I didn't have the libsqlite3 file linked

**Comment by RWOverdijk** [comment]
I have this same issue and libsqlite3 is linked.

**Comment by prathammehta** [comment]
I'm having the same issue. libsqlite3 is linked. for me too.

**Comment by qq912276337** [comment]
I'm having the same issue after auto link.how to solve it?
