### ISSUE TITLE
java.lang.IllegalAccessError: Class com.google.android.gms.internal.zzbfm is inaccessible

### ISSUE THREAD

**Issue by matthieugayon** [mauron85/react-native-background-geolocation#171]
I'm experiencing crashes on Android with this plugin, as soon as the lib gets instanciated, here is the error stack : 

```
java.lang.IllegalAccessError: Class com.google.android.gms.internal.zzbfm extended by class com.google.android.gms.location.DetectedActivity is inaccessible (declaration of 'com.google.android.gms.location.DetectedActivity' appears in /data/app/com.ariane-1/split_lib_dependencies_apk.apk)
        at com.marianhello.bgloc.provider.LocationProviderFactory.getInstance(LocationProviderFactory.java:40)
        at com.marianhello.bgloc.LocationService.onStartCommand(LocationService.java:273)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3685)
        at android.app.ActivityThread.-wrap23(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1740)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

My Config : 

```
{
  locationProvider: BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,
  debug: true,
  stationaryRadius: 50,
  distanceFilter: 50,
  notificationTitle: 'Background tracking',
  notificationText: 'activé',
  maxLocations: 10,
  stopOnTerminate: false,
  startOnBoot: true,
  stopOnStillActivity: true,
  desiredAccuracy: BackgroundGeolocation.LOW_ACCURACY,
  interval: 1000 * 60 * 30,
  fastestInterval: 1000 * 60 * 10, 
  activitiesInterval: 30000,
  syncThreshold: 10
}
```

###  My Environment 
* Plugin version: 0.5.0-alpha.16
* Platform: Android
* OS version: 23 - 26
* React Native version: 0.54.4

### Possible Fix
I seriously don't know ... :(

**Comment by mauron85** [comment]
According to your crash dump there is is line [LocationProviderFactory.java:40](https://github.com/mauron85/background-geolocation-android/blob/b756b368e497a02fad452cd93827776d1b9cb204/src/main/java/com/marianhello/bgloc/provider/LocationProviderFactory.java#L40), on which `ACTIVITY_PROVIDER` is initialized, but in your config I see `DISTANCE_FILTER_PROVIDER`.

Activity provider may possibly crash like this, if google play services are not present.

**Comment by matthieugayon** [comment]
Yes the crash dump is the same whether I use ACTIVITY_PROVIDER or DISTANCE_FILTER_PROVIDER. 

Also I guess I have one the latest version of the google play services library ...
<img width="864" alt="screen shot 2018-04-08 at 23 13 25" src="https://user-images.githubusercontent.com/3694172/38472619-c19d9d6a-3b82-11e8-98b5-8ebe8ee4061a.png">

**Comment by mauron85** [comment]
@matthieugayon check google play services on a phone not on a computer

**Comment by matthieugayon** [comment]
@mauron85 finally it's working. May i suggest you to add a few precisions in the Android Manual setup especially for the app build.gradle part ( in general the average native plugin do not require you to add any dependency in the build.gradle file and react-native link for sure skips that part ... )  : 

![screen shot 2018-04-09 at 11 00 17](https://user-images.githubusercontent.com/3694172/38488963-494942de-3be5-11e8-8b6a-0001d18799b8.png)

**Comment by matthieugayon** [comment]
And btw great plugin man :)

**Comment by mauron85** [comment]
@matthieugayon I don't get what you did. Did you add something to build.gradle?

**Comment by matthieugayon** [comment]
I had to add "implementation 'com.google.android.gms:play-services-location:11.8.0'" in my app build.gradle file to have it fixed, weird cause it's supposed to be compiled in the react-native-mauron85-background-geolocation module ...

**Comment by mauron85** [comment]
Like you said alpha.16 already has play-services-location in its build.gradle -> https://github.com/mauron85/react-native-background-geolocation/blob/b1f24756fe9930c0317c9c204250c0a7866b28eb/android/lib/build.gradle#L34

I think by adding it also to your app build.gradle, you forced gplay version for another plugin react-native-notifications, which is using older 10 version, which was causing your difficulties - https://github.com/wix/react-native-notifications/blob/master/android/build.gradle

TD;DR
You can check `./gradlew app:dependencies --configuration compile` before adding play-services-location and after. The generated graph should explain a lot.

**Comment by matthieugayon** [comment]
This did the trick : 

![screen shot 2018-04-09 at 14 03 55](https://user-images.githubusercontent.com/3694172/38496743-df7588a8-3bfe-11e8-96bb-fa27b9dc6935.png)

**Comment by mauron85** [comment]
Yes, exclude is better. One can immediately deduct from exclude that module is using some incompatible version of shared libraries.  My answer is still valid though. Adding dependencies higher in the hierarchy has sometimes same effect as exclude. But I would go for exclude like you did.
