### ISSUE TITLE
Unable to start service Intent on calling BackgroundGeolocation.start()

### ISSUE THREAD

**Issue by rohithramachandran** [mauron85/react-native-background-geolocation#172]
## Your Environment

* Plugin version:0.5.0-alpha.10
* Platform: Android
* OS version: 7
* Device manufacturer and model: Galaxy Note 5
* React Native version: 0.54.0-rc.3
* Plugin configuration options: 

## Context
When I simply copy the Configuration from Readme , BackgroundGeolocation.start(); is showing not throwing any error but location is not getting shared.and no notification is getting popped up
getting error in logcat as 
``Unable to start service Intent { flg=0x4 cmp=com.onewaycorp.daddysroad/com.marianhello.bgloc.LocationService launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } (has extras) } U=0: not found``

``BackgroundGeolocation.on('error', (error) => {`` also not throwing any error

## Expected Behavior
Location sharing should be active and a notification pops up saying background tracking enabled

## Actual Behavior
Notification not coming

## Logs
``
04-07 15:18:31.030 30215 31964 D com.marianhello.bgloc.data.sqlite.SQLiteConfigurationDAO: Configuration persisted with rowId = 1
04-07 15:18:31.031 30215 31964 D com.marianhello.bgloc.BackgroundGeolocationFacade: Service configured with: Config[distanceFilter=50 stationaryRadius=50.0 desiredAccuracy=0 interval=10000 fastestInterval=5000 activitiesInterval=10000 isDebugging=true stopOnTerminate=false stopOnStillActivity=false startOnBoot=false startForeground=true locationProvider=1 nTitle=Background tracking nText=enabled nIconLarge= nIconSmall= nIconColor= url=http://192.168.81.15:3000/location syncUrl=http://192.168.1.2:3000/location syncThreshold=10 httpHeaders={X-FOO=bar} maxLocations=10000 postTemplate={"lat":"@latitude","lon":"@longitude","foo":"bar"}]
04-07 15:18:31.037 30215 31966 D com.marianhello.bgloc.BackgroundGeolocationFacade: Starting service
04-07 15:18:31.051 30215 31966 I com.marianhello.bgloc.BackgroundGeolocationFacade: Starting bg service
04-07 15:18:31.066  3739  4024 W ActivityManager: Unable to start service Intent { flg=0x4 cmp=com.onewaycorp.daddysroad/com.marianhello.bgloc.LocationService launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } (has extras) } U=0: not found
04-07 15:18:31.130 30215 30215 D com.marianhello.bgloc.BackgroundGeolocationFacade: Binding to service
04-07 15:18:31.140  3739 13976 W ActivityManager: Unable to start service Intent { cmp=com.onewaycorp.daddysroad/com.marianhello.bgloc.LocationService launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } } U=0: not found
``

I dont know whether this one is same or not.. just referring here #89

**Comment by felansu** [comment]
+1

**Comment by mauron85** [comment]
fixed in 0.5.0-alpha.36

**Comment by Amsvartner** [comment]
I'm having the exact same problem, using version **3.0.0-alpha.50** on the emulator running Android 8.1 (API 27).

`02-04 09:04:57.034  5194  5270 I com.marianhello.bgloc.BackgroundGeolocationFacade: Initializing plugin
02-04 09:04:57.082  5194  5270 D com.tenforwardconsulting.bgloc.cordova.BackgroundGeolocationPlugin: Registering event listeners
02-04 09:04:57.109  5194  5270 W PluginManager: THREAD WARNING: exec() call to BackgroundGeolocation.addEventListener blocked the main thread for 27ms. Plugin should use CordovaInterface.getThreadPool().
02-04 09:04:57.117  5194  5230 D NetworkSecurityConfig: No Network Security Config specified, using platform default
02-04 09:04:57.362  5194  5194 D SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-android-softinputmode/www/interface.js: Line 3 : Success
02-04 09:04:57.362  5194  5194 I chromium: [INFO:CONSOLE(3)] "Success", source: file:///android_asset/www/plugins/cordova-plugin-android-softinputmode/www/interface.js (3)
02-04 09:04:57.462  5194  5272 D com.marianhello.bgloc.data.sqlite.SQLiteConfigurationDAO: Configuration persisted with rowId = 1
02-04 09:04:57.466  5194  5272 D com.marianhello.bgloc.BackgroundGeolocationFacade: Service configured with: Config[distanceFilter=50 stationaryRadius=100.0 desiredAccuracy=0 interval=3000 fastestInterval=5000 activitiesInterval=10000 isDebugging=true stopOnTerminate=true stopOnStillActivity=true startOnBoot=false startForeground=true notificationsEnabled=true locationProvider=1 nTitle=PolarFleet GPS tracking nText=enabled nIconLarge= nIconSmall= nIconColor= url=http://fleet.proconx.net:5055 syncUrl=http:// syncThreshold=100 httpHeaders={Content-Type=application/json} maxLocations=1 postTemplate={"heading":"@bearing","foo":"bar","lon":"@longitude","id":"ADG198","lat":"@latitude","speed":"@speed","timestamp":""}]
02-04 09:04:57.490  5194  5251 D EGL_emulation: eglMakeCurrent: 0xa9205d80: ver 3 0 (tinfo 0x9563a050)
02-04 09:04:57.508  1638  1941 W ActivityManager: Unable to start service Intent { cmp=net.proconx.truckapp/com.marianhello.bgloc.service.LocationServiceImpl (has extras) } U=0: not found`
