### ISSUE TITLE
how can I disable the notification in iOS ?

### ISSUE THREAD

**Issue by EdwinJDiaz** [mauron85/react-native-background-geolocation#173]
## Your Environment

* Plugin version:
* Platform: iOS 
* OS version: 8
* Device manufacturer and model:
* React Native version:0.53
* Plugin configuration options: 
  BackgroundGeolocation.configure({
      desiredAccuracy: 10,
      stationaryRadius: 50,
      distanceFilter: 50,
      debug: false,
      startOnBoot: true,
      stopOnTerminate: true, 
      startForeground: false, 
      locationProvider: soDevice == 'android' ?  BackgroundGeolocation.ACTIVITY_PROVIDER : BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,
      interval: 300000,
      stopOnStillActivity: false,
    });
* Link to your project:

## Context

how can I disable the notification in iOS ?

![captura de pantalla 2018-04-09 a la s 7 20 51 p m](https://user-images.githubusercontent.com/11430535/38529605-6b751d38-3c2b-11e8-8c21-ac823d537fa5.png)

## Expected Behavior
that the notification is not presented

## Actual Behavior
The notification is present in the background

## Steps to Reproduce

1.
start the application
2.
put it in the background
3.
4.

## Context
the tried: 
  debug: false,
 startForeground: false

works very well on Android!!

**Comment by kristfal** [comment]
iOS shows that notification regardless of what you do if the user selects "While app is running" for location permissions. If the user selects "Always", the bar doesn't show.

**Comment by Luckygirlllll** [comment]
@kristfal How is possible to disable notification for Android?

**Comment by mauron85** [comment]
@Luckygirlllll as far I understood your usecase from https://github.com/mauron85/react-native-background-geolocation/issues/233, you won't see notification if you apply my advice from that thread and keep option  `startForeground` to false (default).

**Comment by Luckygirlllll** [comment]
@mauron85 Okay, thanks!
