### ISSUE TITLE
Disable Local notifications

### ISSUE THREAD

**Issue by jeffreymendez1993** [mauron85/react-native-background-geolocation#174]
Notifications fire constantly in the background

![image uploaded from ios](https://user-images.githubusercontent.com/8095978/38571414-6f5e81d0-3cbe-11e8-9655-3a2b879a3f5a.png)

## Your Environment

* Plugin version: latest
* Platform: iOS
* OS version: High Sierra
* Device manufacturer and model:
* React Native version: .53
* Plugin configuration options: 
* Link to your project:

## Steps to Reproduce

1.
2.
3.
4.

**Comment by mauron85** [comment]
Ok. I think I found where the problem is. Will fix soon. Thank you for reporting

**Comment by mauron85** [comment]
Nothing personal. Just for easier tracking of this issue, I marked this as duplicate of https://github.com/mauron85/react-native-background-geolocation/issues/124.

**Comment by jeffreymendez1993** [comment]
@mauron85 Thank you for getting back to me so fast was literally about to waste time reconfiguring your package.

**Comment by mauron85** [comment]
The problem is in https://github.com/mauron85/background-geolocation-ios/blob/master/BackgroundGeolocation/AbstractLocationProvider.m#L38 It doesn't check config option debug at all.

**Comment by mauron85** [comment]
I will work on this

**Comment by jeffreymendez1993** [comment]
@mauron85 closing since your latest build fixes this.

**Comment by hlbp** [comment]
hi!! did you fixed the error on iOS??
