### ISSUE TITLE
cannot install latest on android

### ISSUE THREAD

**Issue by jeffreymendez1993** [mauron85/react-native-background-geolocation#175]
## Your Environment

* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer and model:
* React Native version:
* Plugin configuration options: 
* Link to your project:

## Context

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :react-native-mauron85-background-geolocation-common.
## Steps to Reproduce

1. Link all modules manually 
2.
3.
4.

**Comment by jeffreymendez1993** [comment]
Looks like there is a issue with the common folder not being resolved correctly.

**Comment by mauron85** [comment]
read my comment https://github.com/mauron85/react-native-background-geolocation/pull/168#issuecomment-380144164

**Comment by mauron85** [comment]
just run `react-native link react-native-mauron85-background-geolocation` it should do the job

**Comment by jeffreymendez1993** [comment]
negative @mauron85 getting some issues with the referencing of :app

**Comment by mauron85** [comment]
@jeffreymendez1993 if you have this flavor issue related to gradle3, then please wait I'm working on it.

**Comment by jeffreymendez1993** [comment]
@mauron85 downgraded my gradle I think I got it working now. Issue is with firebase. Try using firebase and gmaps together on a install and tell me if its painless haha. Also perks on gradle 3 the builds are drastically faster, but I guess not everyone is ready yet for it.

**Comment by mauron85** [comment]
@jeffreymendez1993 that sound like project related

**Comment by jeffreymendez1993** [comment]
not sure why I cant easily install this module on android. I used a older version that was compatible with my newer gradle that worked locally but then I cannot build it to production.

**Comment by jeffreymendez1993** [comment]
removed the package and my project built for release just perfect. I guess ill sit tight until the gradle changes are in there. If I was better at java id help.

**Comment by gtaylor44** [comment]
I'm having the same issue. Firebase made breaking changes to use gradle 3 about 18 days ago.

**Comment by equesteo** [comment]
I'm trying to use this library with push messaging from Firebase, but am forced to use Gradle 3 to get that installed, which is forcing me into the same problem @jeffreymendez1993 and @gtaylor44 are having. Which is a long-winded way of saying, +1 to getting this fixed. Thanks for your work, @mauron85!

**Comment by gtaylor44** [comment]
If we want to fix this ourselves, where should we be looking?

**Comment by mauron85** [comment]
@gtaylor44 I've seen it done. https://github.com/mauron85/react-native-background-geolocation/compare/master...vivekkiran:master

**Comment by kruyvanna** [comment]
FYI,
I have created a temporary workaround based on the work of vivekkiran.
https://github.com/kruyvanna/react-native-background-geolocation_gradle3

**Comment by kruyvanna** [comment]
@gtaylor44 another option
https://github.com/kruyvanna/react-native-background-geolocation

**Comment by mauron85** [comment]
FYI: there is experimental support for gradle3. https://github.com/mauron85/react-native-background-geolocation/issues/176#issuecomment-392015665

**Comment by mauron85** [comment]
Marking as duplicate of #176. Closing. Let's continue discussion there.
