### ISSUE TITLE
Could not get unknown property 'android' for project ':app' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by jeffreymendez1993** [mauron85/react-native-background-geolocation#177]
downgraded gradle and now this issue .All I have done was install@latest and react-native link 'project;
## Your Environment

* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer and model:
* React Native version:
* Plugin configuration options: 
* Link to your project:

## Steps to Reproduce

1.
2.
3.
4.

**Comment by jeffreymendez1993** [comment]
Issue occurs with firebase and google not having the same exact version. using versionNumber + was causing a issue.

**Comment by AmeerHamzaRiaz** [comment]
Anyone have solution for this ?

**Comment by mark-slepkov** [comment]
I'm having the same. I just enabled gradle3 like it made in there https://github.com/mauron85/react-native-mauron85-background-geolocation-skeleton
I'm not experienced with android development (web only). Can anyone help me please? Thanks.

**Comment by AmeerHamzaRiaz** [comment]
I had to abandon my project. Just because I couldn't solve this issue :/

**Comment by AmeerHamzaRiaz** [comment]
https://github.com/mauron85/react-native-background-geolocation/issues/217

**Comment by mark-slepkov** [comment]
I downgraded buildToolsVersion and `supportLibVersion
`
ext {
    compileSdkVersion = 26
    targetSdkVersion = 26
    buildToolsVersion = "26.0.2"
    supportLibVersion = "25.3.1"
    googlePlayServicesVersion = "11.8.0"
//    oreoEXPERIMENTAL = "yes"
    gradle3EXPERIMENTAL = "yes"
}
`
so now it builds but appcrashes right on start.
if I comment this string in MainApplication.java
![image](https://user-images.githubusercontent.com/13302780/43457807-b1053740-94d0-11e8-9cc6-f48497fc3156.png)
then no crash on start, but geolocation does not work. ((

**Comment by tmaly1980** [comment]
@j-mendez Why'd you close this? What was the solution?

**Comment by tmaly1980** [comment]
OK Turns out for me the issue was in the android-common submodule:

I needed to change:

        if (findProject('..:app') != null) {
            applicationId = project('..:app').android.defaultConfig.applicationId
        } else if (findProject(':app') != null) {
            applicationId = project(':app').android.defaultConfig.applicationId
        }

to:

        if (findProject('..:app') != null && project('..:app').hasProperty('android')) {
            applicationId = project('..:app').android.defaultConfig.applicationId
        } else if (findProject(':app') != null && project(':app').hasProperty('android')) {
            applicationId = project(':app').android.defaultConfig.applicationId
        }

**Comment by hesa2020** [comment]
@tmaly1980 very nice find.
I think the issue is in settings.gradle

I really wonder why can't it see the android property tho, because for my project it is there.

**Comment by j-mendez** [comment]
@tmaly1980 sorry, should have posted the solution. Setup your project for AndroidX and it should work.

**Comment by hooksoft** [comment]
> OK Turns out for me the issue was in the android-common submodule:
> 
> I needed to change in VERSIONS.gradle:
> 
> ```
>     if (findProject('..:app') != null) {
>         applicationId = project('..:app').android.defaultConfig.applicationId
>     } else if (findProject(':app') != null) {
>         applicationId = project(':app').android.defaultConfig.applicationId
>     }
> ```
> 
> to:
> 
> ```
>     if (findProject('..:app') != null && project('..:app').hasProperty('android')) {
>         applicationId = project('..:app').android.defaultConfig.applicationId
>     } else if (findProject(':app') != null && project(':app').hasProperty('android')) {
>         applicationId = project(':app').android.defaultConfig.applicationId
>     }
> ```

This worked for me on RN 0.62.2 - thank you. I wonder if I could turn it into patch-module..

**Comment by caolong0204** [comment]
> > OK Turns out for me the issue was in the android-common submodule:
> > I needed to change in VERSIONS.gradle:
> > ```
> >     if (findProject('..:app') != null) {
> >         applicationId = project('..:app').android.defaultConfig.applicationId
> >     } else if (findProject(':app') != null) {
> >         applicationId = project(':app').android.defaultConfig.applicationId
> >     }
> > ```
> > 
> > 
> > to:
> > ```
> >     if (findProject('..:app') != null && project('..:app').hasProperty('android')) {
> >         applicationId = project('..:app').android.defaultConfig.applicationId
> >     } else if (findProject(':app') != null && project(':app').hasProperty('android')) {
> >         applicationId = project(':app').android.defaultConfig.applicationId
> >     }
> > ```
> 
> This worked for me on RN 0.62.2 - thank you. I wonder if I could turn it into patch-module..

Why i don't have file VERSION.gradle in my project?

**Comment by caolong0204** [comment]
> @tmaly1980 sorry, should have posted the solution. Setup your project for AndroidX and it should work.

can you say detail about steps to setup?Please

**Comment by luisfuertes** [comment]
@caolong0204 update that code in `node_modules/@mauron85/react-native-background-geolocation/android/common/VERSIONS.gradle`

**Comment by mohammad-chavoshipor** [comment]
> OK Turns out for me the issue was in the android-common submodule:
> 
> I needed to change in VERSIONS.gradle:
> 
> ```
>     if (findProject('..:app') != null) {
>         applicationId = project('..:app').android.defaultConfig.applicationId
>     } else if (findProject(':app') != null) {
>         applicationId = project(':app').android.defaultConfig.applicationId
>     }
> ```
> 
> to:
> 
> ```
>     if (findProject('..:app') != null && project('..:app').hasProperty('android')) {
>         applicationId = project('..:app').android.defaultConfig.applicationId
>     } else if (findProject(':app') != null && project(':app').hasProperty('android')) {
>         applicationId = project(':app').android.defaultConfig.applicationId
>     }
> ```

This worked for me on RN 0.61.2 - thank you
@caolong0204  
++

**Comment by jureczkyb** [comment]
Hello! Anyoone has a pull request for this or a working fork? 

The above solutions just leave the applicationId as default  "com.marianhello.app".  Would that cause any problems later?

**Comment by tgreco** [comment]
Same question as @jureczkyb, when will this be merged?

**Comment by Jeeva-Sanvi** [comment]
where is versions.gradle file?
