### ISSUE TITLE
isLocationEnabled usage?

### ISSUE THREAD

**Issue by kevinnguy** [mauron85/react-native-background-geolocation#18]
Hi there, was wondering how to use the function `isLocationEnabled`. I tried calling it but I keep getting this error:

<img width="375" alt="screen shot 2016-10-06 at 4 28 26 pm" src="https://cloud.githubusercontent.com/assets/1483123/19174209/ee202742-8be1-11e6-9bf9-1f26f6334add.png">

Still a novice in JS so sorry if I misread the docs! 🙏

**Comment by mauron85** [comment]
It's not implemented yet. Sorry for that.

**Comment by mauron85** [comment]
If you only need iOS version then use git master branch. It's implemented there.

**Comment by kevinnguy** [comment]
Thanks @mauron85, I'll check out the master branch. How would you use this function in Javascript?

**Comment by Okipa** [comment]
+1 for this functionality implementation on both platforms ;)

**Comment by pewh** [comment]
I have test this on Android & it's work. I don't know about iOS because I just develop for Android. Maybe this issue can be closed if anyone report that iOS version is working.

**Comment by Okipa** [comment]
Mmmh it seems that this is not available for iOS yet.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 199 days. You may reopen this issue if it has been closed in error.
