### ISSUE TITLE
Error when adding 'activity' event listener

### ISSUE THREAD

**Issue by crossxcell99** [mauron85/react-native-background-geolocation#183]
## Your Environment

* Plugin version:   0.5.0-alpha.21
* Platform: Android
* OS version: 7.1.2
* Device manufacturer and model: LG D410
* React Native version: 0.49.3
* Plugin configuration options: 
desiredAccuracy: BackgroundGeolocation.MEDIUM_ACCURACY,
stationaryRadius: 2,
distanceFilter: 2,
debug: false,
startOnBoot: true,
stopOnTerminate: false,
locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
interval: 600000,
fastestInterval: 300000,
activitiesInterval: 600000,
stopOnStillActivity: false,
startForeground: false,

* Link to your project:

## Context
The following code gives an error:
`
BackgroundGeolocation.on('activity', (activityData) => {
    console.log(activityData)
});
`

## Expected Behavior
The data from activity event should be logged to the console

## Actual Behavior
App displays an error

![rnbg1](https://user-images.githubusercontent.com/23179734/39276807-b048fb28-48e2-11e8-9478-3df051122c80.png)

**Comment by mauron85** [comment]
Good catch. It's not present in array of events. https://github.com/mauron85/react-native-background-geolocation/blob/master/index.js#L9.

**Comment by mauron85** [comment]
fixed in 0.5.0-alpha.27
