### ISSUE TITLE
Compilation Error: No resource found that matches the given name

### ISSUE THREAD

**Issue by test137E29B** [mauron85/react-native-background-geolocation#187]
## Your Environment

* Plugin version: Latest
* Platform: Android
* OS version: I have no idea
* Device manufacturer and model: None because it doesn't compile.
* React Native version: v0.55.3
* Plugin configuration options: 
```
BackgroundGeolocation.configure({
            desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
            stationaryRadius: 2,
            distanceFilter: 2,
            notificationTitle: 'Background tracking',
            notificationText: 'enabled',
            debug: true,
            startOnBoot: false,
            stopOnTerminate: false,
            locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
            interval: 5000,
            fastestInterval: 5000,
            activitiesInterval: 5000,
            stopOnStillActivity: false
});
```
* Link to your project:

## Context
I am attempting to track locations in the background since React's own navigation doesn't work when the screen turns off. I found this module and am trying to get it to work, but I get errors on compilation.

## Expected Behavior
I'm expecting this to compile with react-native run-android, so I can see the location updates.

## Actual Behavior
"node_modules\react-native-mauron85-background-geolocation\android\common\build\intermediates\res\merged\preoreo\debug\drawable\common_google_signin_btn_icon_light_normal.xml:3: error: Error: No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_light_normal_background')."

And other similar for other backgrounds. I have installed every single version of the Android SDK, I've tried editing the build.gradle for this module itself to use Version 23.0.2 like React Native is, I've tried editing both to use 26.0.2 and nothing fixes the errors. I've enabled Long Paths in Windows and restarted multiple times, and it's driving me up the wall that I can't just drop it in and have it work.

## Possible Fix
N/A

## Steps to Reproduce
1. `npm install react-native-mauron85-background-geolocation`
2. `react-native link react-native-mauron85-background-geolocation`
3. `react-native run-android`
4. ???
5. Not Profit.

## Debug logs

:react-native-mauron85-background-geolocation-common:mergePreoreoDebugResources
:react-native-mauron85-background-geolocation-common:processPreoreoDebugManifest UP-TO-DATE
:react-native-mauron85-background-geolocation-common:processPreoreoDebugResources

node_modules\react-native-mauron85-background-geolocation\android\common\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\15.0.1\res\drawable\common_google_signin_btn_icon_dark_normal.xml:3:29-91: AAPT: No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_dark_normal_background').

node_modules\react-native-mauron85-background-geolocation\android\common\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\15.0.1\res\drawable\common_google_signin_btn_icon_light_normal.xml:3:29-92: AAPT: No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_light_normal_background').

node_modules\react-native-mauron85-background-geolocation\android\common\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\15.0.1\res\drawable\common_google_signin_btn_text_dark_normal.xml:3:29-91: AAPT: No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_dark_normal_background').

node_modules\react-native-mauron85-background-geolocation\android\common\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\15.0.1\res\drawable\common_google_signin_btn_text_light_normal.xml:3:29-92: AAPT: No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_light_normal_background').

node_modules\react-native-mauron85-background-geolocation\android\common\build\intermediates\res\merged\preoreo\debug\drawable\common_google_signin_btn_icon_dark_normal.xml:3: error: Error: No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_dark_normal_background').

node_modules\react-native-mauron85-background-geolocation\android\common\build\intermediates\res\merged\preoreo\debug\drawable\common_google_signin_btn_icon_light_normal.xml:3: error: Error: No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_light_normal_background').

node_modules\react-native-mauron85-background-geolocation\android\common\build\intermediates\res\merged\preoreo\debug\drawable\common_google_signin_btn_text_dark_normal.xml:3: error: Error: No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_dark_normal_background').

node_modules\react-native-mauron85-background-geolocation\android\common\build\intermediates\res\merged\preoreo\debug\drawable\common_google_signin_btn_text_light_normal.xml:3: error: Error: No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_light_normal_background').

:react-native-mauron85-background-geolocation-common:processPreoreoDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-mauron85-background-geolocation-common:processPreoreoDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

**Comment by mauron85** [comment]
reading gradle error log `play-services-base\15.0.1`, I would say this version is incompatible with this plugin (and most other plugins too).

**Comment by test137E29B** [comment]
Hi Mauron, 

Unfortunately this didn't fix the issue, even forcing it to compile with play-services-location 11.8.0, and setting google's maven links in the root build.gradle

Is there anything else I can try? How can I downgrade the `play-services-base`?

**Comment by test137E29B** [comment]
Basically, I need this module or else the entire point of the app I am developing is useless. I'm at a point where I either get this to work, or have to try using the other module that can do this - and that has a $300 license fee for just 1 app.

I am willing to basically try anything to get this to just work.
