### ISSUE TITLE
Not running on iOS

### ISSUE THREAD

**Issue by RWOverdijk** [mauron85/react-native-background-geolocation#188]
On the latest RN version I get:

> undefined is not an object (evaluating 'RNBackgroundGeolocation.configure')

I looked into the other issues and none of the solutions in there worked for me.

I've gone with a different solution for now, but I think that if you have an answer to this it could be good to document it (like in this issue).

**Comment by Luisgm2dev** [comment]
What would be that solution? I'm having the exact same problem there. Did you link manually the library?

**Comment by RWOverdijk** [comment]
@Luisgm2dev I've written my own implementation. It's educational, but I'm toying with changing radio towers, motion sensors, network type etc.

**Comment by aalhaimi** [comment]
1. delete ```node_modules``` folder
2. make sure you close any open rn server terminal
3. do ```npm install``` and then ```react-native run-ios```

This solved it for me.

**Comment by prathammehta** [comment]
Having the same problem here. @aalhaimi did what you mentioned. Still no luck. Do you have any other solution?

**Comment by aalhaimi** [comment]
@prathammehta, I would recommend restarting from a new RN app ```react-native init <app>```. add all your essential packages, link, and run. It should run. If you're still having issues, there might be an incompatible package in your ```node_modules``` that interferes with ```react-native-mauron85-background-geolocation``` dependencies. Hope this helps!

**Comment by prathammehta** [comment]
@aalhaimi thanks for the suggestions. Will do this and update you with the status.
