### ISSUE TITLE
Compilation Error - preoreoDebug not found

### ISSUE THREAD

**Issue by mosgamal** [mauron85/react-native-background-geolocation#190]
## Your Environment

* Plugin version: 0.5
* Platform: Android
* OS version: Win 10
* Device manufacturer and model:
* React Native version: 0.51.0
* Plugin configuration options: 
* Link to your project:

## Context

I'm using the plugin with Shoutem application, using react native maps 0.20.0
Also, the whole setup is under play service 10.2.4, targeting sdk 23

## Expected Behavior

It should compile!

## Actual Behavior

`A problem occurred configuring project ':app'.
Could not resolve all dependencies for configuration ':app:_debugApk'.
A problem occurred configuring project ':react-native-mauron85-background-geolocation'.
Could not resolve all dependencies for configuration ':react-native-mauron85-background-geolocation:_debugPublish'.
Configuration with name 'preoreoDebug' not found.`
## Steps to Reproduce

1. Yarn and Link
2. Change Play Service Version
3. Comment `publishNonDefault true` to disable compiling oreo --> issues happens without doing so
4.  Compile with preoreoDebug

**Comment by mauron85** [comment]
Your issue is related to step 3. You should not remove `publishNonDefault true`.

**Comment by mosgamal** [comment]
@mauron85 Thanks for your reply, actually it never compiles as it compiles Oreo version and never compile preOreo.
please note that the sdk is installed, but when it start compiling Oreo it captures old API:
`\node_modules\react-native-mauron85-background-geolocation\android\common\src\oreo\java\com\marianhello\bgloc\NotificationHelper.java:50: error: constructor Builder in class Builder cannot be applied to given types;
            NotificationCompat.Builder builder = new NotificationCompat.Builder(mContext, NotificationHelper.SERVICE_CHANNEL_ID);
                                                 ^
  required: Context
  found: Context,String
  reason: actual and formal argument lists differ in length`

**Comment by mauron85** [comment]
I've seen this error before. Check your versions in `build.gradle`:
https://github.com/mauron85/react-native-background-geolocation#android-oreo
