### ISSUE TITLE
Having a callback to form a POST template

### ISSUE THREAD

**Issue by gokulanath** [mauron85/react-native-background-geolocation#199]
* Plugin version: ^0.5.0-alpha.25
* Platform: iOS and Android (Both)
* React Native version: 0.55.4

## Context
Having a callback to form a POST template will be more helpful to modify/add some properties and change the structure  to the JSON before sending to the server

## Expected Behavior
BackgroundGeolocation.configure({
      ...
      url: 'http://10.0.0.10:3000/saveGPS',
      // customize post properties
      postTemplate: function(locationArray){
        // Some computation before sending to the server
        return {
          locations: processedArray,
          propertyName1: 'property1',
          propertyName2: 'property2'
          ...
        }
      }
    });

## Actual Behavior
BackgroundGeolocation.configure({
      ...
      url: 'http://10.0.10:3000/saveGPS',
      // customize post properties
      postTemplate: {
        lat: '@latitude',
        lon: '@longitude',
        bearing: '@bearing',
        ...
      }
    });

#### Note:
I don't know is it possible or not. I'm new to react-native.  If it is not possible, help me some alternative solution

### End point accepts only the following format

{  
   "GPSRecords":[  
      {  
         "UUID":"1abc4567-e89b-12d3-a456-426655440000",
         "DeviceID":"1abc4",
         "DateTime":1494979200000.174,
         "Latitude":39.008284,
         "Longitude":-104.797316,
         "Speed":35.4,
         "Altitude":6235.8,
         "Bearing":180.6,
         "Accuracy":1
      }
   ]
}

### Actual:

[  
   {  
      "UUID":"1abc4567-e89b-12d3-a456-426655440000",
      "DeviceID":"1abc4",
      "DateTime":1494979200000.174,
      "Latitude":39.008284,
      "Longitude":-104.797316,
      "Speed":35.4,
      "Altitude":6235.8,
      "Bearing":180.6,
      "Accuracy":1
   }
]

**Comment by mauron85** [comment]
I agree. However this is not easy task to do. You need to interpret that javascript function in native bridge. It's possible and in matter of fact same technique is used in [android headless task](https://github.com/mauron85/react-native-background-geolocation#android-headless-task-experimental). However full blown solution is much more complicated than that.

Consider:
1. iOS support
2. Android consider situation what app is terminated but service is running
3. ...

**Comment by mauron85** [comment]
Alternative implementation came to my mind. Using RCTEventEmitter we can simulate two-way communication between js and native bridge. However it will only work when app (main activity) is not terminated. If it's ok with you, I can try to hack the thing.

**Comment by gokulanath** [comment]
For time being it's ok. Thanks a lot for your effort.

**Comment by mauron85** [comment]
So I decided to add new event `beforepost`, instead of making postTemplate accept callback functions, but outcome is basically same.

You register callback function, which will be called before location is posted to server with location object and what return from that callback function will be posted to `config.url`.

```
    BackgroundGeolocation.on('beforepost', (location) => {
      return {
        location,
        batteryDummy: 99
      };
    });
```

You can already test this on Android by installing following version (not visible by default)
```
yarn add react-native-mauron85-background-geolocation@0.5.0-alpha.32
```

Also please send feedback.

**Comment by gokulanath** [comment]
Thanks

**Comment by gusilveiramp** [comment]
Hi,
I need to get a callback from my API. In my case, the API will return an array of phone numbers for my app and this will need to enable a function, even in the background or with the app disabled. Can I use this beforepost event for this?

Obviously the example below should not work, but just so that you understand what I need:
```
BackgroundGeolocation.configure ({
...
         url: 'https://mysite.com/api/',
   
         httpHeaders: {
           'Authorization': 'Bearer K78slk ...',
           'Content-Type': 'application/json'
         },

         postTemplate: postData
}). then (response => () {
     // MY ARRAY WITH PHONES
});
```
