### ISSUE TITLE
Custom saved locations data

### ISSUE THREAD

**Issue by redwind** [mauron85/react-native-background-geolocation#200]
* Plugin version: 0.5.0-alpha.29
* Platform: iOS & Android
* React Native version: 0.51

## Context
App tracking user locations on background mode in working shift but there isn't internet connection to sync to server. And i want to sync saved locations to server when user open app, but maybe user is in next working shift at this time.

## Expected Behavior
We can custom saved location, add more extra attribute, ex shift_id ...

Thanks !!!

**Comment by mauron85** [comment]
There is forceSync method exactly for that.

**Comment by redwind** [comment]
Hi @mauron85 !
Thanks for your reply. I mean could i custom saved location data, for example : add shift_id property to location,..
forceSync just force to post saved locations to server.
thanks !

**Comment by mauron85** [comment]
Ah ok. Now I understand. What are requesting is currently not possible. Will tag as enhancement.

**Comment by mussaiin** [comment]
> Ah ok. Now I understand. What are requesting is currently not possible. Will tag as enhancement.

One more question about forceSync-ing, I found an issue that forceSync doesn't post locations to my server when data type is cellular, it only does with wifi. What could be the reason for this?
