### ISSUE TITLE
startForeground vs. startOnForeground

### ISSUE THREAD

**Issue by djereg** [mauron85/react-native-background-geolocation#202]
## Your Environment
* Plugin version: 0.5.0-alpha.30
* Platform: Android
* React Native version: 0.55.4

## Context
In README and CHANGES the config property is called as `startOnForeground`, but the [ConfigMapper](https://github.com/mauron85/react-native-background-geolocation/blob/fc743a949b6d4264d148296f28dd6e6217b3bb54/android/lib/src/main/java/com/marianhello/bgloc/react/ConfigMapper.java#L5) reads it as `startForeground`, and the default values are different too. If the property is not set in config, then starts on foreground, and when I set it to `false` then works as documented.

**Comment by mauron85** [comment]
Good catch. Documentation needs to be updated

**Comment by mauron85** [comment]
fixed
