### ISSUE TITLE
close drawer notification on BackgroundGeolocation stop 

### ISSUE THREAD

**Issue by GrishmaM** [mauron85/react-native-background-geolocation#204]
* Plugin version: ^0.5.0-alpha.25
* Platform: Android
* React Native version: 0.55.0
* Plugin configuration options:
          desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
          stationaryRadius: 50,
          distanceFilter: 50,
          debug: false,
          locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
          interval: 10000,
          fastestInterval: 5000,
          activitiesInterval: 10000
* Link to your project: yes

## Context
while tracking it should show the notification, but on stopping the notification should be closed

## Expected Behavior
on stopping notification should go

## Actual Behavior
until I close the app the notification remains

**Comment by mauron85** [comment]
Alpha versions can differ significantly, so please always test and report your issue against latest alpha. As now it is 0.5.0-alpha.34.

**Comment by GrishmaM** [comment]
i tried with 0.5.0-alpha.34, its same

**Comment by mauron85** [comment]
I can't reproduce this. I can only suggest you to try example app. https://github.com/mauron85/react-native-background-geolocation-example to exclude there is issue withing your code.

**Comment by mauron85** [comment]
or post link to your repo. So I can take look on it.

**Comment by GrishmaM** [comment]
can you tell me how to Enable and disable drawer notification

**Comment by GrishmaM** [comment]
@mauron85 can you help me in this
