### ISSUE TITLE
Could not resolve project :react-native-mauron85-background-geolocation-common

### ISSUE THREAD

**Issue by nguyensythinhk7** [mauron85/react-native-background-geolocation#207]
## Your Environment

* Plugin version: ^0.5.0-alpha.34
* Platform: iOS or Android
* OS version:
* Device manufacturer and model:
* React Native version:0.55.2
* Plugin configuration options: 
* Link to your project:

## Context

 - Could not resolve project :react-native-mauron85-background-geolocation-common
- project :react-native-mauron85-background-geolocation declares a dependency from configuration 'debugCompile' to configuration 'oreoDebug' which is not declared in the descriptor for project :react-native-mauron85-background-geolocation-common.

## Expected Behavior

Fix and Run
## Steps to Reproduce

1.Installation
2.
3.Manual setup
4.Dependencies

**Comment by ivosabev** [comment]
What was the fix, why didn't you share?

**Comment by dengue8830** [comment]
@ivosabev  the fix is [here](https://github.com/mauron85/react-native-background-geolocation/issues/176#issuecomment-392015665)

**Comment by mauron85** [comment]
based on @dengue8830 report, marking as duplicate of #176 (comment)
