### ISSUE TITLE
Could not resolve project :react-native-mauron85-background-geolocation-common in Grade 4.4

### ISSUE THREAD

**Issue by nguyensythinhk7** [mauron85/react-native-background-geolocation#208]
## Your Environment

* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer and model:
* React Native version:
* Plugin configuration options: 
* Link to your project:

## Expected Behavior

Plugin not working in gradle 4.4. can't found react-native-mauron85-background-geolocation-common
## Steps to Reproduce

1.
2.
3.
4.

**Comment by xuanduy96** [comment]
+ 1

**Comment by dengue8830** [comment]
@ivosabev  the fix is [here](https://github.com/mauron85/react-native-background-geolocation/issues/176#issuecomment-392015665)

this should be marked as related

**Comment by xuanduy96** [comment]
@dengue8830 I use react native firebase and React-native-Maps with gralde 4.4, these two libraries are important in my project, and now I want to use them with native native background locations mauron85, but here it does not support 4 .x. This is the problem I encountered!
Your link fix gradle will only 3.x. Is there a better way? thank you 😃

**Comment by nguyensythinhk7** [comment]
@dengue8830 thanks you !
