### ISSUE TITLE
DISTANCE_FILTER_PROVIDER Foreground 

### ISSUE THREAD

**Issue by felipecarreramo** [mauron85/react-native-background-geolocation#209]
Instead of an issue this is more like a question or a doubt... the locationProvider DISTANCE_FILTER_PROVIDER works on foreground or just on background mode for Android devices?

thanks

**Comment by djereg** [comment]
Works on foreground too.

On Android sometimes starts monitoring the position continuously, sometimes not. On iOS works perfectly.
