### ISSUE TITLE
Geolocation logging just when app closed

### ISSUE THREAD

**Issue by igor-bv** [mauron85/react-native-background-geolocation#21]
Hello @mauron85 ! 
I need to logging geoposition on server side by sending location payload when app is cilled.
So is it possible to make such logic:
**on app will close - BackgroundLocation.start()**
**on app will start - BackgroundLocation.stop()**
?

thanks in advance!

**Comment by mauron85** [comment]
Hmm. Not sure. It may be possible. I will not try this my self as I consider this as unfair to the user.

**Comment by bo4a10** [comment]
@mauron85 thanks for quick response.
I tried implement your module in the way I described. But it cannot stop service on app start...
Probably because every time app stopps we create new instance for BackgroundLocation, I'm really don't know how it must be on native side, but probably I make `start()` for one instance, and then `stop()` for another instance...

**Comment by satishmane** [comment]
Hi,

Even I have same requirement. After app is closed, I want to leave background location running and storing location local db. When app is launched again, then I want to stop it. I tried to stop service by calling stop(), but it does not stop service. It keeps running. Is there way to stop service after app is restarted.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 224 days. You may reopen this issue if it has been closed in error.

**Comment by Luckygirlllll** [comment]
@mauron85 How is possible to stop location tracking when app is closed or in the background?

**Comment by Luckygirlllll** [comment]
@mauron85 I have in the config right now  stopOnTerminate: true, so it should stop location tracking when user closes the app, right?  however, I'm not sure  will it also stop location tracking when app is in a background? I want to have location tracking only when app is in foreground.

**Comment by mauron85** [comment]
Notice for other readers:

This very old thread and assumptions made here are not valid anymore. Now you can continue tracking, even when app was terminated and location updates are sent to server. So no need to downvote me @AngSin :)

**Comment by mauron85** [comment]
@Luckygirlllll I will answer your question in new thread you created  https://github.com/mauron85/react-native-background-geolocation/issues/233
