### ISSUE TITLE
What went wrong: Execution failed for task ':react-native-mauron85-background-geolocation:processReleaseResources'. > com.android.ide.common.process.ProcessException: Failed to execute aapt

### ISSUE THREAD

**Issue by lorenz199x** [mauron85/react-native-background-geolocation#210]
## Your Environment

* Plugin version:
* Android
* OS version: win 10
* Device manufacturer and model:
* React Native version: "react-native": "^0.53.3",
* Plugin configuration options:  react-native-mauron85-background-geolocation": "^0.5.0-alpha.7","^0.5.0-alpha.25"
* Link to your project:

## Steps to Reproduce

1. clone project from git
2. npm install/yarn install
3. run project
4. 
![image](https://user-images.githubusercontent.com/29396889/41082521-3f5c2ee4-6a61-11e8-931b-0d60caa42981.png)

## Context
I cant run or build my project , can you fix or solved this problem

**Comment by pacozaa** [comment]
+1 same here

**Comment by dengue8830** [comment]
i can't reproduce this problem, that error is from older version, try a fresh install with [this](https://gist.github.com/dengue8830/a1d44a036cb9b83d3e1f2aefae7a4b3d) config
