### ISSUE TITLE
Doesn't send data to the server 

### ISSUE THREAD

**Issue by adriank** [mauron85/react-native-background-geolocation#211]
I try to set up HTTP posting with no luck. Server doesn't receive anything regardless of what I put into config. The code I'm using is:

```
  BackgroundGeolocation.configure({
    desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
    stationaryRadius: 50,
    distanceFilter: 50,
    notificationTitle: i18n.geolocationNotificationTitle,
    notificationText: i18n.geolocationNotificationText,
    debug: true,
    startOnBoot: false,
    stopOnTerminate: false,
    locationProvider: Platform.OS === "ios"
      ? BackgroundGeolocation.DISTANCE_FILTER_PROVIDER
      : BackgroundGeolocation.ACTIVITY_PROVIDER,
    interval: 2000,
    fastestInterval: 1000,
    activitiesInterval: 2000,
    stopOnStillActivity: false,
    autoSync: true,
    url: 'http://localhost:3000',
    httpHeaders: {
      'Content-Type': 'application/json',
      "Authorization": "Bearer " + token
    },
    postTemplate: {
      lat: '@latitude',
      lon: '@longitude'
    }
  })
BackgroundGeolocation.start()
```
It doesn't work on either of platforms.

## Your Environment

* Plugin version: 0.5.0-alpha.34 (newest from NPM right now)
* Platform: iOS and Android
* OS version: iOS 10 and 11, Android 23
* Device manufacturer and model: all
* React Native version: 0.55.4
* Plugin configuration options: in the description
* Link to your project: private

## Expected Behavior

It should send data to http://localhost:3000

## Actual Behavior

It doesn't send anything anywhere, but data is reachable through BackgroundGeolocation.on('location', ...).

## Possible Fix

No idea.

## Steps to Reproduce

Just put the config and run.

## Debug logs

There is absolutely nothing in debug consoles. It looks like there is no code that actually sends something to the server in the repo and the config is ignored.

**Comment by shashanksinghal** [comment]
What android version you are using it on? I have noticed that for some devices you need to turn on data sync in accounts settings in Android for data to come to server.

**Comment by adriank** [comment]
Data sync is on. It occurs on all Android versions and iOS.

**Comment by adriank** [comment]
BackgroundGeolocation.on('location', (location) => {
    axios.post("http://localhost:3000", location)
});

works as expected and sends data to the server.

**Comment by siderakis** [comment]
I'm seeing the same issue.

```
const config = (accessToken: string, desiredAccuracy: number = 100) => ({
  // Desired accuracy in meters. Possible values [0, 10, 100, 1000].
  // The lower the number, the more power devoted to GeoLocation resulting in higher accuracy readings.
  // 1000 results in lowest power drain and least accurate readings. @see Apple docs
  desiredAccuracy,
  // Stationary radius in meters.
  // When stopped, the minimum distance the device must move beyond the
  // stationary location for aggressive background-tracking to engage.
  stationaryRadius: 25,
  // The minimum distance (measured in meters) a device must move horizontally
  // before an update event is generated. @see Apple docs.
  distanceFilter: 50,
  locationTimeout: 30,
  // When enabled, the plugin will emit sounds for life-cycle events of
  // background-geolocation! See debugging sounds table.
  debug: true,
  // Enable this in order to force a stop() when the application
  // terminated (e.g. on iOS, double-tap home button, swipe away the app).
  stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
  // [Android] Start background service on device boot.
  startOnBoot: true, // <-- Auto start tracking when device is powered-up.
  autoSync: true, // <-- POST each location immediately to server
  url: DOMAIN + "/location",
  //[iOS] Switch to less accurate significant changes and region monitory when in background
  saveBatteryOnBackground: false,
  httpHeaders: { accessToken },
})
```

**Comment by dengue8830** [comment]
same problem here, i can get the location updates but it doesn't make the post request

i get location updates
![image](https://user-images.githubusercontent.com/5104213/49697445-3bb23100-fb96-11e8-8b4e-ff9a51f832d4.png)

i and can log network requests
![image](https://user-images.githubusercontent.com/5104213/49697459-5be1f000-fb96-11e8-89fe-86dd9cad3ce6.png)

but the plugin never makes the requests

hint: if i enable "syncUrl" the plugins tries to use it (showing a different notification) but that request never sent, either by logging in network tab or the logs in the server

**Comment by dengue8830** [comment]
yes, mine was a server problem too, you should close this issue
