### ISSUE TITLE
How do I update headers through headless task?

### ISSUE THREAD

**Issue by theebi** [mauron85/react-native-background-geolocation#213]
Thanks for the awesome library.
But I have few problems. I have an app which tracks user location continuously in the background (Android). Im sending token in headers, but token gets expired every month. Is there any way I can reset the headers in the background? Is there a callback or something I can get from headless task when POST request fails?

Thank you

**Comment by mauron85** [comment]
Unfortunately this is no possible as headless task doesn't have access to react native js context.
