### ISSUE TITLE
:react-native-mauron85-background-geolocation       > Project :react-native-mauron85-background-geolocation declares a dependency from configuration 'debugCompile' to configuration 'preoreoDebug' which is not declared in the descriptor for project :react-native-mauron85-background-geolocation-common.

### ISSUE THREAD

**Issue by rayjadore** [mauron85/react-native-background-geolocation#214]
## Your Environment

* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer and model:
* React Native version:
* Plugin configuration options: 
* Link to your project:

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

:react-native-mauron85-background-geolocation
      > Project :react-native-mauron85-background-geolocation declares a dependency from configuration 'debugCompile' to configuration 'preoreoDebug' which is not declared in the descriptor for project :react-native-mauron85-background-geolocation-common.

**Comment by ivosabev** [comment]
How did you resolve this?

**Comment by dengue8830** [comment]
the fix is [here](https://github.com/mauron85/react-native-background-geolocation/issues/176#issuecomment-392015665)

this thread should be marked as related

**Comment by mauron85** [comment]
based on @dengue8830 report, marking as duplicate of https://github.com/mauron85/react-native-background-geolocation/issues/176#issuecomment-392015665

**Comment by rayjadore** [comment]
this package is not compactible with gradle 4.4

**Comment by dengue8830** [comment]
@rayjadore yes it works, [here](https://github.com/mauron85/react-native-background-geolocation/issues/176#issuecomment-398392881) is my full config
