### ISSUE TITLE
Help! Could not find support-v4.jar (com.android.support:support-v4:26.1.0)??

### ISSUE THREAD

**Issue by pacozaa** [mauron85/react-native-background-geolocation#216]
## Your Environment

* Plugin version: ` "react-native-mauron85-background-geolocation": "0.4.1"`
* Platform: Android
* OS version: Android 7.0
* Device manufacturer and model: SAMSUNG A7
* React Native version: `"react-native": "0.50.3"`
* android's `build.gradle` `compileSdkVersion 23, buildToolsVersion "23.0.2"`
## Context

Can not build project, this error shown
```
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-mauron85-background-geolocation'.
      > Could not find support-v4.jar (com.android.support:support-v4:26.1.0).
        Searched in the following locations:
            https://jcenter.bintray.com/com/android/support/support-v4/26.1.0/support-v4-26.1.0.jar

```

**Comment by xuanduy96** [comment]
hahahahahahahahahahahahahahahaha
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
+1 😆

**Comment by pacozaa** [comment]
@mauron85 Any thought or may be suggestion?

**Comment by mauron85** [comment]
I think you're missing google repo in you repositories.

```
allprojects {
    repositories {
        jcenter()
        maven { url 'https://maven.google.com' }
        // OR
        google()
    }
}
```

**Comment by lfiorini** [comment]
I am facing the same problem. What I've found so far is that https://jcenter.bintray.com/com/android/support/support-v4/26.1.0/support-v4-26.1.0.jar return a 404 and the support-v4/ directory has only a maven-metadata.xml file.
If I move jcenter() after the other repos, the app builds but I'm not sure this a solution since I still cannot get a working Android build.

**Comment by pacozaa** [comment]
@mauron85 still not working brother :(

**Comment by catcheshirecat** [comment]
Try https://github.com/airbnb/lottie-react-native/issues/203#issuecomment-334476435
It works for me finally

**Comment by lfiorini** [comment]
I can confirm that I could get my build moving jcenter() AFTER google() repo.

**Comment by pacozaa** [comment]
@lfiorini  @mauron85  @catcheshirecat  after apply you guys tip I found another error which similar to #210 but here is my detail

```
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:font
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontStyle
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontVariationSettings
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontWeight
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:ttcIndex

:react-native-mauron85-background-geolocation:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-mauron85-background-geolocation:processReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt
```

already stuck here for weeks. please help 💯 

Thank you so much!

**Comment by pacozaa** [comment]
Build success by https://github.com/mauron85/react-native-background-geolocation/issues/116#issuecomment-340258780

**Comment by mauron85** [comment]
@pacozaa if you need to edit dependencies, rather do it in `ext` section of `android/build.gradle` than in `node_modules`. All changes in `node_modules` will be lost after module upgrade.

```
ext {
    compileSdkVersion   = 23
    targetSdkVersion    = 23
    buildToolsVersion   = "23.0.3"
    supportLibVersion   = "23+"
    googlePlayServicesVersion = "11+"
    androidMapsUtilsVersion = "0.5"
}
```

Check example project 
https://github.com/mauron85/react-native-background-geolocation-example/blob/master/android/build.gradle

**Comment by guitar9** [comment]
Dont know why...
but this works for me...

```
allprojects {
    repositories {
        mavenLocal()
        maven { url 'https://maven.google.com' } 
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
}
```

**Comment by TarunPurohit1437** [comment]
gfgf

**Comment by guitar9** [comment]
find out that this a generel problem with the version 0.56.0 of react
native. try react-native init --version="0.55.4"

Tarun Purohit <notifications@github.com> schrieb am Do., 19. Juli 2018,
09:21:

**Comment by TarunPurohit1437** [comment]
thanks for reply thnku so much for your valuable reply

**Comment by sirawat93** [comment]
@pacozaa 
please try @guitar9 solution.
it works for me

**Comment by sirawat93** [comment]
Thank you @efajardolopez, you saved my day.
Could you share us why putting jcenter last does the trick? 
Thank you senpai

**Comment by moulanaaidi** [comment]
@efajardolopez solution works for me too!!! thx brother

**Comment by phhuan** [comment]
@lfiorini It's worked for me. Move jcenter() to bottom.

**Comment by radiahub** [comment]
Thanks a lot @efajardolopez it works perfectly for me

**Comment by syedreze** [comment]
I just added following code in Project level gradle and it's working perfectly. My `maven { url "https://maven.google.com" } ` was missing

`allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://maven.google.com" }
    }
}`

**Comment by yangdeyouxi** [comment]
Thanks a lot @efajardolopez it works perfectly for me

**Comment by jordantrain** [comment]
jcenter after google, yep!
