### ISSUE TITLE
Bearing, Speed are coming as null

### ISSUE THREAD

**Issue by dina-ideas2it** [mauron85/react-native-background-geolocation#218]
## Your Environment

* Plugin version: v0.5.0-alpha.24
* Platform: Android
* OS version: 8.1.0
* Device manufacturer and model: One Plus 5T
* React Native version: 0.55.4

## Context

Bearing, Speed are coming as null sometimes. It is not saving in database because of null value. it is accepting only double/float

I look into the code and found that datatype here is float and double, but it is coming as null. 

BackgroundLocation.java
```
    private float bearing = 0.0f;
    private double altitude = 0.0f;
```

## Expected Behavior

Bearing, Speed should be 0.

Give me a suggestion, I'm looking for a fix from the client side

## Actual Behavior

Bearing, Speed are coming as null.

## Steps to Reproduce

This was the response I got from the device during the post.
```
{
    "Speed": 1.113433,
    "Accuracy": 28,
    "Latitude": 12.96563269,
    "Longitude": 80.24624107,
    "DateTime": 1528975666000,
    "Altitude": -56.58819580078125,
    "Bearing": -1
  },
  {
    "Speed": null,
    "Accuracy": 51.343343,
    "Latitude": 12.96563394,
    "Longitude": 80.24624512,
    "DateTime": 1528975687000,
    "Altitude": -56.4327392578125,
    "Bearing": null
  }

```

**Comment by gokulanath** [comment]
+1

**Comment by jacobbeasley** [comment]
I'm also intermittently getting speed and bearing as null. It is intermittent because sometimes I get it and sometimes I don't. I'm thinking I might just "remember" the last poll and re-use the old data for these (assuming they probably haven't changed), but its definitely a weird issue.

**Comment by mauron85** [comment]
It might caused by position determined by network provider (wifi, gsm) which doesn't have such props.

**Comment by jacobbeasley** [comment]
That's possible. I'll post if I notice a pattern. Maybe it's every 3rd ping or so. Could be that I just have to handle it elegantly - not necessarily a problem with this library.

**Comment by nikmartin** [comment]
Yes, I think you'll need to handle these cases yourself. You'll need to check for null/undefined/out of range conditions and handle them according to your own business rules.
