### ISSUE TITLE
Configure sampling rate for gps on iOS

### ISSUE THREAD

**Issue by ufukoe** [mauron85/react-native-background-geolocation#221]
Using the module with an IOS phone, we noticed the previously mentioned effect of a reduced sampling rate when moving with higher velocity. However, for sudden stops this introduced delay is causing us to loose important measurements for up to a minute. We tried to disable the disableElasticity in the module configuration - however without noticing a difference.

Is it possible to configure the sampling rate on iOS for the GPS tracking (foreground and background)?

**Comment by mauron85** [comment]
You can use raw provider. As there is no sampling there.

**Comment by ufukoe** [comment]
Thank you! Works fine
