### ISSUE TITLE
cannot find symbol import android.app.NotificationChannel;

### ISSUE THREAD

**Issue by ddthanhdat** [mauron85/react-native-background-geolocation#222]
## Your Environment

* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer and model:
* React Native version:
* Plugin configuration options: 
* Link to your project:

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs
![image](https://user-images.githubusercontent.com/11143625/41671939-ccff9188-74e2-11e8-9dc0-3a09b489b20e.png)

**Comment by rajeshsmallarc** [comment]
Have you fixed this issue ?

**Comment by ddthanhdat** [comment]
yes, i fixed. thanks

**Comment by Yusiro85** [comment]
How did you fix it?

**Comment by Ashu2245** [comment]
How do we can fix this .

**Comment by rajeshsmallarc** [comment]
I have also fixed this.

I have make following changes:

In android/app/build.gradle add this.

```
compileSdkVersion 26
buildToolsVersion "26.0.1"
```
In android/build.gradle add this.

```
ext {
  compileSdkVersion = 26
  targetSdkVersion = 26
  buildToolsVersion = "26.0.2"
  supportLibVersion = "26.1.0"
  googlePlayServicesVersion = "11.0.2"
  oreoEXPERIMENTAL = "yes"
}
```

**Note:**  _Make sure your google play service version will be same for all dependencies where you are using google play services._

**Comment by josuper** [comment]
@rajeshsmallarc  where can i find **android/app/build.gradle** ? Am using ionic 3 and in my android/app/ theres only one file named google-service.json

Help me please

**Comment by SanjanaTailor** [comment]
I am facing the same problem can not resolve issue with following plugin 
cordova-plugin-local-notification 0.9.0-beta.2

**Comment by SanjanaTailor** [comment]
In android/app/build.gradle add this.

Using Ionic3 can not resolve it so that 
Adde ionic cordova plugin add de.appplant.cordova.plugin.local-notification@0.8.5

**Comment by josuper** [comment]
Thanks for you reply mrs @SanjanaTailor but i didnt understood your explanation

What i have to add in android/app/build.gradle ?

I am using ionic 3, i must add the plugin de.appplant.cordova.plugin.local-notification@0.8.5 ?

See bellow my plugin list:

cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-firebase 1.1.4 "Google Firebase Plugin"
cordova-plugin-ionic-webview 2.3.3 "cordova-plugin-ionic-webview"
cordova-plugin-native-spinner 1.1.3 "Native Spinner"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-toast 2.7.2 "Toast"
ionic-plugin-keyboard 2.2.1 "Keyboard"
