### ISSUE TITLE
Background location not update when device locked

### ISSUE THREAD

**Issue by nopmengkoung** [mauron85/react-native-background-geolocation#223]
## Your Environment

* Plugin version: 0.5.0-alpha.34
* Platform: iOS
* OS version: 11.3
* Device manufacturer and model: iPhone 6s
* React Native version: 0.54
* Plugin configuration options:

```javascript
    BackgroundGeolocation.configure({
      desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
      stationaryRadius: 30,
      distanceFilter: 30,
      debug: false,
      startOnBoot: false,
      stopOnTerminate: false,
      locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
      interval: 10000,
      fastestInterval: 5000,
      activitiesInterval: 10000,
      stopOnStillActivity: false,
      url: 'https://****************.cloudfunctions.net/location',
      postTemplate: {
        lat: '@latitude',
        lng: '@longitude',
        uid: this.props.user.uid
      }
    });
```

## Context

I noticed that background location update is working for me only when device is awake and app is in background. I have some api call url in option.url but its calling only if the device awake when my device locked it is not calling the api to update to location anymore. I need some help.
## Steps to Reproduce

1. Configure option.url
2. Run in simulator or real device
3. Open the app and log when location update
4. Put the app in background(device awake) and change location and see what happen
5. Put the app in background(device locked) and see what happen

**Comment by nopmengkoung** [comment]
Fixed by changing to provider to DISTANCE_FILTER_PROVIDER and it working fine on foreground/background.

**Comment by GrishmaM** [comment]
@nopmengkoung  i'm facing the same issue in android, I tried your solution but it didn't work for me.

**Comment by walterdl** [comment]
@GrishmaM did you solved it?

**Comment by GurjeetLamba** [comment]
I am also facing issue when device lock or sleep mode , Did anyone found a solution to this ?
