### ISSUE TITLE
When buiild generate Apk error: cannot find symbol android.app.NotificationChannel

### ISSUE THREAD

**Issue by khanhvt1** [mauron85/react-native-background-geolocation#227]
## Your Environment

* Plugin version: 0.5.0-alpha.34
* Platform: Android
* OS version: 7.0
* Device manufacturer and model: Xiaomi Red 5A
* React Native version: 0.55.4
* Plugin configuration options:  
* Link to your project: 

## Context

node_modules\react-native-mauron85-background-geolocation\android\common\src\oreo\java\com\marianhello\bgloc\NotificationHelper.java:4: error: cannot find symbol
import android.app.NotificationChannel;

Details : 
symbol:   class NotificationChannel
  location: package android.app
C:\Project\ReactN\vanchuyen\node_modules\react-native-mauron85-background-geolocation\android\common\src\oreo\java\com\marianhello\bgloc\NotificationHelper.java:86: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                                                        ^
  symbol:   variable O
  location: class VERSION_CODES
C:\Project\ReactN\vanchuyen\node_modules\react-native-mauron85-background-geolocation\android\common\src\oreo\java\com\marianhello\bgloc\NotificationHelper.java:89: error: cannot find symbol
            NotificationChannel serviceChannel = new NotificationChannel(SERVICE_CHANNEL_ID, appName, android.app.NotificationManager.IMPORTANCE_DEFAULT);
            ^
  symbol:   class NotificationChannel
  location: class NotificationHelper
C:\Project\ReactN\vanchuyen\node_modules\react-native-mauron85-background-geolocation\android\common\src\oreo\java\com\marianhello\bgloc\NotificationHelper.java:89: error: cannot find symbol
            NotificationChannel serviceChannel = new NotificationChannel(SERVICE_CHANNEL_ID, appName, android.app.NotificationManager.IMPORTANCE_DEFAULT);
                                                     ^
  symbol:   class NotificationChannel
  location: class NotificationHelper
C:\Project\ReactN\vanchuyen\node_modules\react-native-mauron85-background-geolocation\android\common\src\oreo\java\com\marianhello\bgloc\NotificationHelper.java:89: error: cannot find symbol
            NotificationChannel serviceChannel = new NotificationChannel(SERVICE_CHANNEL_ID, appName, android.app.NotificationManager.IMPORTANCE_DEFAULT);
                                                                                                                                     ^
  symbol:   variable IMPORTANCE_DEFAULT
  location: class NotificationManager
C:\Project\ReactN\vanchuyen\node_modules\react-native-mauron85-background-geolocation\android\common\src\oreo\java\com\marianhello\bgloc\NotificationHelper.java:96: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                                                        ^
  symbol:   variable O
  location: class VERSION_CODES
C:\Project\ReactN\vanchuyen\node_modules\react-native-mauron85-background-geolocation\android\common\src\oreo\java\com\marianhello\bgloc\NotificationHelper.java:100: error: cannot find symbol
            NotificationChannel syncChannel = new NotificationChannel(SYNC_CHANNEL_ID, SYNC_CHANNEL_NAME, android.app.NotificationManager.IMPORTANCE_DEFAULT);
            ^
  symbol:   class NotificationChannel
  location: class NotificationHelper
C:\Project\ReactN\vanchuyen\node_modules\react-native-mauron85-background-geolocation\android\common\src\oreo\java\com\marianhello\bgloc\NotificationHelper.java:100: error: cannot find symbol
            NotificationChannel syncChannel = new NotificationChannel(SYNC_CHANNEL_ID, SYNC_CHANNEL_NAME, android.app.NotificationManager.IMPORTANCE_DEFAULT);
                                                  ^
  symbol:   class NotificationChannel
  location: class NotificationHelper
C:\Project\ReactN\vanchuyen\node_modules\react-native-mauron85-background-geolocation\android\common\src\oreo\java\com\marianhello\bgloc\NotificationHelper.java:100: error: cannot find symbol
            NotificationChannel syncChannel = new NotificationChannel(SYNC_CHANNEL_ID, SYNC_CHANNEL_NAME, android.app.NotificationManager.IMPORTANCE_DEFAULT);

## Steps to Reproduce

1.
2.
3.
4.

## Context

I  build app then it's not working as debug. Debug it still working. I can't test on many device
(Sorry, english my bad.)

**Comment by nguyensythinhk7** [comment]
I have  the same issue? @mauron85 can i help you?

**Comment by dobrynia** [comment]
Which version of Android SDK is used in the project?

**Comment by mauron85** [comment]
Check your sdk version.
Also if you're using gradle 4. Please also check https://github.com/mauron85/react-native-background-geolocation/issues/176#issuecomment-392015665

**Comment by nguyensythinhk7** [comment]
@dobrynia , @mauron85  I use gradle 3.5.1

**Comment by mauron85** [comment]
My comment is also true for gradle3.

**Comment by mauron85** [comment]
Update your project to skeleton example mentioned in that thread i’ve linked, because I’ve doubts that gradle3 will work with latest android sdks

**Comment by starba3** [comment]
have the same issue
this is my build.gradle
`
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        applicationId "com.notifications"
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            // minifyEnabled enableProguardInReleaseBuilds
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    configurations.all {
        resolutionStrategy.force 'com.android.support:support-annotations:23.1.1'
    }   
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    androidTestCompile 'com.android.support:support-annotations:23.1.1'
    androidTestCompile 'com.android.support.test:runner:0.5'
    androidTestCompile 'com.android.support.test:rules:0.5'
    compile project(':react-native-mauron85-background-geolocation')
    compile project(':react-native-background-timer')
    compile project(':react-native-background-task')
    compile project(':react-native-vector-icons')
    compile project(':react-native-push-notification')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.4.0"
    compile 'com.android.support:support-v4:+'
    compile "com.facebook.react:react-native:+"  // From node_modules
}
`
