### ISSUE TITLE
Getting Exception while starting app

### ISSUE THREAD

**Issue by rohithramachandran** [mauron85/react-native-background-geolocation#228]
* Plugin version: 0.5.0-alpha.14
* Platform: Android
* OS version: 4.4.4
* Device manufacturer and model: Nexus 4 (Genymotion)
* React Native version: 0.54.0-rc.3
* Gradle version: 4.1

## Context
When starting the app an error is coming.
``
java.lang.RuntimeException: Unable to get provider com.marianhello.bgloc.sync.DummyContentProvider: java.lang.ClassNotFoundException: Didn't find class "com.marianhello.bgloc.sync.DummyContentProvider" on path: DexPathList[[zip file "/data/app/com.onewaycorp.daddysroad-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.onewaycorp.daddysroad-1, /system/lib]]
E/AndroidRuntime( 3072):        at android.app.ActivityThread.installProvider(ActivityThread.java:4777)
E/AndroidRuntime( 3072):        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4369)
E/AndroidRuntime( 3072):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4309)
E/AndroidRuntime( 3072):        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
E/AndroidRuntime( 3072):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
E/AndroidRuntime( 3072):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 3072):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 3072):        at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime( 3072):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 3072):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 3072):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 3072):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 3072):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 3072): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.marianhello.bgloc.sync.DummyContentProvider" on path: DexPathList[[zip file "/data/app/com.onewaycorp.daddysroad-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.onewaycorp.daddysroad-1, /system/lib]]
E/AndroidRuntime( 3072):        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime( 3072):        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/AndroidRuntime( 3072):        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/AndroidRuntime( 3072):        at android.app.ActivityThread.installProvider(ActivityThread.java:4762)
E/AndroidRuntime( 3072):        ... 12 more
W/ActivityManager(  555):   Force finishing activity com.onewaycorp.daddysroad/.MainActivity
``

## Expected Behavior
Application supposed to start 

## Actual Behavior
Application throwing above error

**Comment by rohithramachandran** [comment]
This seems to be working in Android 6.0.

**Comment by mauron85** [comment]
>java.lang.ClassNotFoundException: Didn't find class "com.marianhello.bgloc.sync.DummyContentProvider"

Maybe proguard removed some classes

**Comment by mauron85** [comment]
Or if you included multiple plugins that multiDex can be issue too.

https://developer.android.com/studio/build/multidex

**Comment by rohithramachandran** [comment]
@mauron85 
Thanks for the response.
multidex is enabled and jumboMode=true. And its working for android 5.0 above.
Is there any fixes for this ?

**Comment by ZedUnes** [comment]
If you are enabling  multiDex, you have to enable it correctly.

1. **In app/build.gradle:** make sure `multiDexEnabled true` in your defaultConfig.
2. **MainApplication.java:** extend MultiDexApplication instead of Application, like this:
   - add this line: `import android.support.multidex.MultiDexApplication;`
   - replace this: `public class MainApplication extends Application implements ReactApplication`
      with this: `public class MainApplication extends MultiDexApplication implements ReactApplication`

I used to have the exact same crash in OS version <= 4 and when i have done that the crash has gone.

**NB:** There are other ways to achieve (2), either:
Set your application to a multidex application in your Manifest, by adding this:
```
    <application
            android:name="android.support.multidex.MultiDexApplication" >
        ...
    </application>
```
or override the attachBaseContext() method like this:
 ```
protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }
```

You might want to check this link: [https://developer.android.com/studio/build/multidex](url)
