### ISSUE TITLE
Stopping service

### ISSUE THREAD

**Issue by stevencurtis** [mauron85/react-native-background-geolocation#230]
## Your Environment

* Plugin version: 0.25 
* Platform: Both
* OS version: 11.2.1
* Device manufacturer and model: iPad Air 2
* React Native version:
* Plugin configuration options: 
* Link to your project:

## Context

Cannot simply stop the service, would need to stop and reconfigure the service to not send to the server. This seems counter intuitive.
## Expected Behavior

User can disable service
## Actual Behavior

Can only configure the service

**Comment by mauron85** [comment]
FYI This is all possible in 0.5x version.
