### ISSUE TITLE
Attempt to invoke virtual method 'void com.marianhello.bgloc.LocationService.start()' on a null object reference

### ISSUE THREAD

**Issue by Yusiro85** [mauron85/react-native-background-geolocation#232]
## Your Environment

Plugin version: 0.5.0-alpha.34
Platform: Android
OS version: 7.0
Device manufacturer and model: Huawei VIE-L29
React Native version: 0.51.0
Plugin configuration options:
BackgroundGeolocation.configure({
distanceFilter: 50,
debug: false,
startOnBoot: false,
stationaryRadius: 50,
stopOnTerminate: true,
desiredAccuracy: 10,
interval: 15000
});
Link to your project:

## Expected Behavior
Launch the app and run without issue, start tracking location

## Actual Behavior
Crash after launch and login the app

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

> java.lang.NullPointerException Attempt to invoke virtual method 'void com.marianhello.bgloc.LocationService.start()' on a null object reference 
>     BackgroundGeolocationFacade.java:451 com.marianhello.bgloc.BackgroundGeolocationFacade.startBackgroundService
>     BackgroundGeolocationFacade.java:49 com.marianhello.bgloc.BackgroundGeolocationFacade.access$700
>     BackgroundGeolocationFacade.java:222 com.marianhello.bgloc.BackgroundGeolocationFacade$3.onPermissionGranted
>     PermissionHandler.java:41 com.intentfilter.androidpermissions.PermissionHandler.checkPermissions
>     PermissionManager.java:50 com.intentfilter.androidpermissions.PermissionManager.checkPermissions
>     BackgroundGeolocationFacade.java:215 com.marianhello.bgloc.BackgroundGeolocationFacade.start
>     BackgroundGeolocationModule.java:145 com.marianhello.bgloc.react.BackgroundGeolocationModule.start
>     Method.java:-2 java.lang.reflect.Method.invoke
>     JavaMethodWrapper.java:374 com.facebook.react.bridge.JavaMethodWrapper.invoke
>     JavaModuleWrapper.java:162 com.facebook.react.bridge.JavaModuleWrapper.invoke
>     NativeRunnable.java:-2 com.facebook.react.bridge.queue.NativeRunnable.run
>     Handler.java:761 android.os.Handler.handleCallback
>     Handler.java:98 android.os.Handler.dispatchMessage
>     MessageQueueThreadHandler.java:31 com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage
>     Looper.java:156 android.os.Looper.loop
>     MessageQueueThreadImpl.java:194 com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run
>     Thread.java:776 java.lang.Thread.run

**Comment by Yusiro85** [comment]
Is this due to race condition? Hit this while launching the app.

**Comment by Yusiro85** [comment]
randomly getting this bug as well.


> java.lang.NullPointerException Attempt to invoke virtual method 'java.lang.String android.location.Location.getProvider()' on a null object reference 
>     BackgroundLocation.java:46 com.marianhello.bgloc.data.BackgroundLocation.<init>
>     AbstractLocationProvider.java:113 com.marianhello.bgloc.provider.AbstractLocationProvider.handleStationary
>     DistanceFilterLocationProvider.java:301 com.tenforwardconsulting.bgloc.DistanceFilterLocationProvider.onLocationChanged
>     LocationManager.java:374 android.location.LocationManager$ListenerTransport._handleMessage
>     LocationManager.java:-1 android.location.LocationManager$ListenerTransport.-wrap0
>     LocationManager.java:242 android.location.LocationManager$ListenerTransport$1.handleMessage
>     Handler.java:110 android.os.Handler.dispatchMessage
>     Looper.java:232 android.os.Looper.loop
>     ActivityThread.java:6802 android.app.ActivityThread.main
>     Method.java:-2 java.lang.reflect.Method.invoke
>     ZygoteInit.java:1103 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
>     ZygoteInit.java:964 com.android.internal.os.ZygoteInit.main

@mauron85

**Comment by mauron85** [comment]
@Yusiro85 are you launching your app from notification?

**Comment by Yusiro85** [comment]
nope. I didn't.

**Comment by mauron85** [comment]
Have you modified plugin somehow? Or using vanilla? Because lines from your stack trace doesn't match. Eg.

```
BackgroundGeolocationModule.java:145 
```
Line 145 of plugin in version  0.5.0-alpha.34 is method declaration so it could not crash there.

```
 public void switchMode(Integer mode, Callback success, Callback error) {
```

https://github.com/mauron85/react-native-background-geolocation/blob/4f2be66f159aacdbf9ed49c8ed5cf5a8d7b2360b/android/lib/src/main/java/com/marianhello/bgloc/react/BackgroundGeolocationModule.java#L145

**Comment by Yusiro85** [comment]
Yes, I did apply a wakelock.acquire in Constructor and release it in onHostDestroy.
Is this the cause?

**Comment by mauron85** [comment]
Probably not, but it made error stacktrace useless.

**Comment by Yusiro85** [comment]
> java.lang.NullPointerException Attempt to invoke virtual method 'void com.marianhello.bgloc.LocationService.start()' on a null object reference
> BackgroundGeolocationFacade.java:451 com.marianhello.bgloc.BackgroundGeolocationFacade.startBackgroundService
> BackgroundGeolocationFacade.java:49 com.marianhello.bgloc.BackgroundGeolocationFacade.access$700
> BackgroundGeolocationFacade.java:222 com.marianhello.bgloc.BackgroundGeolocationFacade$3.onPermissionGranted
> PermissionHandler.java:41 com.intentfilter.androidpermissions.PermissionHandler.checkPermissions
> PermissionManager.java:50 com.intentfilter.androidpermissions.PermissionManager.checkPermissions
> BackgroundGeolocationFacade.java:215 com.marianhello.bgloc.BackgroundGeolocationFacade.start
> BackgroundGeolocationModule.java:145 com.marianhello.bgloc.react.BackgroundGeolocationModule.start
> Method.java:-2 java.lang.reflect.Method.invoke
> JavaMethodWrapper.java:374 com.facebook.react.bridge.JavaMethodWrapper.invoke
> JavaModuleWrapper.java:162 com.facebook.react.bridge.JavaModuleWrapper.invoke
> NativeRunnable.java:-2 com.facebook.react.bridge.queue.NativeRunnable.run
> Handler.java:761 android.os.Handler.handleCallback
> Handler.java:98 android.os.Handler.dispatchMessage
> MessageQueueThreadHandler.java:31 com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage
> Looper.java:156 android.os.Looper.loop
> MessageQueueThreadImpl.java:194 com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run
> Thread.java:776 java.lang.Thread.run

what about this error? this is based on Plugin version: 0.5.0-alpha.21.
I didn't modify anything but still hit this error.

**Comment by mauron85** [comment]
Not sure what is your reason to stay on old alpha (since you're not opening app from notification and that for not affected by https://github.com/mauron85/react-native-background-geolocation/issues/201)

But if you need to stay on alpha pick up alpha-22, because of this (from CHANGELOG.md) fix:
 
![image](https://user-images.githubusercontent.com/359450/42683836-c075ac96-868e-11e8-8c4f-dab54b3aa3b1.png)
