### ISSUE TITLE
HELP is needed! How to stop location tracking when app is closed or in background? 

### ISSUE THREAD

**Issue by Luckygirlllll** [mauron85/react-native-background-geolocation#233]
## Your Environment

* Plugin version:  "^0.5.0-alpha.34"
* Platform: iOS or Android: Android
* OS version: All
* Device manufacturer and model: All
* React Native version: 0.55.1
* Plugin configuration options:  
 ```
BackgroundGeolocation.configure({
        stopOnTerminate: true,
        desiredAccuracy: BackgroundGeolocation.MEDIUM_ACCURACY,
        stationaryRadius: 1000,
        distanceFilter: 7000,
        notificationTitle: 'Route verification',
        notificationText: 'enabled',
        startOnBoot: true,
        stopOnTerminate: true,
        locationProvider: BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,
        interval: 10000,
        fastestInterval: 5000,
        activitiesInterval: 10000,
        postTemplate: {
          lat: '@latitude',
          lng: '@longitude',
        },
        url: API.baseUrl + '/driver/location/',
        httpHeaders: {
          'Authorization': `Bearer ${props.accessToken}`,
        },
      })
```

* Link to your project:

## Context

How to stop location tracking when app is closed or in background?

**Comment by mauron85** [comment]
>@mauron85 I have in the config right now stopOnTerminate: true, so it should stop location tracking when user closes the app, right? however, I'm not sure will it also stop location tracking when app is in a background? I want to have location tracking only when app is in foreground.

--
>so it should stop location tracking when user closes the app, right?

yes

> however, I'm not sure will it also stop location tracking when app is in a background?

no, but you can achieve that with event listeners

```
    BackgroundGeolocation.on('background', () => {
      BackgroundGeolocation.stop();
    });

    BackgroundGeolocation.on('foreground', () => {
      BackgroundGeolocation.start();
    });
```
I didn't test the above, but it should work. Not sure if those two event listeners are fired when service is not running. Please try, and report. If it's not working, I'll take look at it.

**Comment by Luckygirlllll** [comment]
@mauron85 Okay, many thanks! I will test it!
