### ISSUE TITLE
Not working in Android 8.0

### ISSUE THREAD

**Issue by theebi** [mauron85/react-native-background-geolocation#234]
This library doesn't work with Android 8.0. With 8.0 they have enabled strict background location access. And I think the library has to support Foreground server to enable it. This works for first 1-2 days after that the OS stops the service to release memory. Is there any alternatives to this?

**Comment by mauron85** [comment]
>And I think the library has to support Foreground server to enable it.

Can you elaborate on this. I'm not aware of any kind of foreground server.

**Comment by theebi** [comment]
Hai sorry, 
I was talking about Foreground service (https://developer.android.com/guide/components/services). I have seen other displaying a notification always and making it as a foreground service so the OS doesn't kill the application.

**Comment by mauron85** [comment]
This is what this plugin is doing since very version 1.

**Comment by theebi** [comment]
If that’s the case, do u know why the library stopped tracking location
updates after 2-3 days ? When I was looking at my logs, I realized the
activity recognization stopped tracking the still or moving activity.

**Comment by mauron85** [comment]
Sorry I don't provide email support. You can ask your questions here.

**Comment by theebi** [comment]
So are u trying to say I should rather use distance filter provider ?

**Comment by mauron85** [comment]
Yes, it should work better.

**Comment by theebi** [comment]
Thanks, will try it out!

**Comment by theebi** [comment]
Hai,
I started using DISTANCE_FILTER_PROVIDER and it works comparatively better. But one problem I have come across is, the plugin stops sending location updates when device slows down the speed. When the device goes to a low speed from a high speed it rejects all those location updates. Just to make things clear, I have been testing it for past week and the problem still remains same.

Below are my configurations. Is it possible for you to see what's wrong with this?

<img width="629" alt="screen shot 2018-07-24 at 9 59 03 am" src="https://user-images.githubusercontent.com/19174530/43117153-f9662aba-8f28-11e8-89bd-ca058df12051.png">
