### ISSUE TITLE
if I manually close the app does not work?

### ISSUE THREAD

**Issue by Richi2293** [mauron85/react-native-background-geolocation#235]
Hi,

when I have the app in the foreground and in the background it works because it sends me notifications but if I manually close the app then everything stops working.
(it does not send me any more notifications and in the logs it does not add anything anymore)

## Your Environment
* Plugin version: ^0.5.0-alpha.35
* Platform: iOS
* OS version: mac 10.13.4, iphone 11.4
* Device manufacturer and model: iPhone 7 plus
* React Native version: 0.56.0
* Plugin configuration options: 
desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
          stationaryRadius: 5,
          distanceFilter: 3,
          notificationTitle: 'Background tracking',
          notificationText: 'enabled',
          debug: true,
          startOnBoot: true,
          stopOnTerminate: false,
          saveBatteryOnBackground: false,
          locationProvider: BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,
          interval: 10000,
          fastestInterval: 5000,
          activitiesInterval: 10000,
          stopOnStillActivity: false

## Context
So what I want to know is, does it work if the app is manually closed or I have a wrong configuration?
Thanks

**Comment by mauron85** [comment]
'stopOnTerminate: false' is currently Android only feature. If you terminate your app on iOS it will just stop sending locations. I was working on iOS implementation, but due lack of time and resources it's progressing slowly.

**Comment by mauron85** [comment]
I should correct docs though.

**Comment by Richi2293** [comment]
Thanks for the quick response.

Ah okok, so theoretically on ios can you implement this thing right?
On ios it's possible (objective c/swift) but in this library it does not work? (at moment)

Because I watched this repo for a feature that I need in an app, I need to detect when a user is near in an area (gps position). 
Could this library fit for this task?

**Comment by StanislavMayorov** [comment]
@mauron85 thank you. Will it start tracking after phone reboot?

**Comment by StanislavMayorov** [comment]
I did pull request in ios implementation. https://github.com/mauron85/background-geolocation-ios/pull/7
It works after phone reboot. `RAW_PROVIDER` and `DISTANCE_FILTER_PROVIDER` are supported.
