### ISSUE TITLE
Conflicts with react-native-push-notification

### ISSUE THREAD

**Issue by aschambers** [mauron85/react-native-background-geolocation#236]
## Your Environment

* Plugin version: 
* Platform: Android
* OS version: macOS High Sierra 10.13.5
* Device manufacturer and model: Android 8.0
* React Native version: RN 0.55.4
* Plugin configuration options: 
* Link to your project: 

## Context

I spent all day troubleshooting this issue, and finally have come to the conclusion that there is some conflict with another package (react-native-push-notification). If I comment out the following lines in MainApplication.Java
**import com.transistorsoft.rnbackgroundgeolocation.*;
import com.transistorsoft.rnbackgroundfetch.RNBackgroundFetchPackage;
new RNBackgroundGeolocation(),
new RNBackgroundFetchPackage(),**
If I also comment out the following in Android/app/build.gradle:
**compile project(':react-native-background-geolocation-android')
compile project(':react-native-background-fetch')**
Then, the app won't crash on start. If I leave these uncommented, and instead either comment
out senderID in pushService.js, used to send remote push notifications, or set requestPermissions: false instead of true, in the same file, used by package (react-native-push-notification), then the app will also not crash
## Expected Behavior

App should not crash on start.
## Actual Behavior

App crashes on start.
## Possible Fix

I haven't been coding that long, but it seems to me, that some background process of this library is conflicting with react-native-push-notification, any help would be greatly appreciated.
## Steps to Reproduce

1. 
2.
3.
4.

**Comment by mauron85** [comment]
You’re reporting to wrong repo.
