### ISSUE TITLE
Sending data to remote link, how can i change the method from POST to PUT

### ISSUE THREAD

**Issue by imjaad9090** [mauron85/react-native-background-geolocation#239]
## Your Environment

* Plugin version: Latest
* Platform: iOS or Android
* OS version: Mac OS Sierra
* Device manufacturer and model: Apple /Mac
* React Native version: 0.55
* Plugin configuration options: 
* Link to your project:

## Context
Hi thanks for a great plugin, i am updating user's location to firebase database, i can post the location to the server successfully, but i need to overwrite the database with updated location. So is it possible to change the POST method to PUT ? or any other solution. 
Thanks

## Steps to Reproduce

1.
2.
3.
4.

**Comment by mauron85** [comment]
Sorry, currently that's not possible. You will to fork this project and change it yourself. Or introduce some proxy before application server, that will translate POST for PUT.

**Comment by imjaad9090** [comment]
I see, can you specify which file i need to look at for the changes in method.
