### ISSUE TITLE
How to stop showing location notification? 

### ISSUE THREAD

**Issue by Luckygirlllll** [mauron85/react-native-background-geolocation#242]
Your Environment

Plugin version: "^0.5.0-alpha.34"
Platform: iOS or Android: Android
OS version: All
Device manufacturer and model: All
React Native version: 0.55.1
Plugin configuration options:
```
BackgroundGeolocation.configure({
       stopOnTerminate: true,
       desiredAccuracy: BackgroundGeolocation.MEDIUM_ACCURACY,
       stationaryRadius: 1000,
       distanceFilter: 7000,
       notificationTitle: 'Route verification',
       notificationText: 'enabled',
       startOnBoot: true,
       stopOnTerminate: true,
       locationProvider: BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,
       interval: 10000,
       fastestInterval: 5000,
       activitiesInterval: 10000,
       postTemplate: {
         lat: '@latitude',
         lng: '@longitude',
       },
       url: API.baseUrl + '/driver/location/',
       httpHeaders: {
         'Authorization': `Bearer ${props.accessToken}`,
       },
     })
```
I disabled location tracking when app is closed or in the background, but when app is opened, users still get notification (notificationTitle: 'Route verification', notificationText: 'enabled',). Is it possible to stop showing this location notification?

**Comment by mauron85** [comment]
Set startForeground false

**Comment by Luckygirlllll** [comment]
@mauron85 startForeground:false, should be inside the BackgroundGeolocation.configure() ?   And it will stop the notification?

**Comment by Luckygirlllll** [comment]
Thanks!

**Comment by mauron85** [comment]
Merged. Thank you!

**Comment by mauron85** [comment]
Fixed with PR https://github.com/mauron85/react-native-background-geolocation/pull/269

**Comment by rewieer** [comment]
Hey @mauron85, i disabled notifications and foreground services, yet the local notification remains.
```js
    BackgroundGeolocation.configure({
      desiredAccuracy: BackgroundGeolocation.PASSIVE_ACCURACY,
      distanceFilter: 1000,
      stationaryRadius: 1000,
      startOnBoot: true,
      stopOnTerminate: false,
      debug: false,
      locationProvider: BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,
      notificationsEnabled: false,
      startForeground: false,
    });
```

![Screenshot 2019-07-18 at 16 33 47](https://user-images.githubusercontent.com/12291995/61466251-e040f080-a979-11e9-904b-0af150022ae5.png)

Any hints on this ? Thanks !

**Comment by rewieer** [comment]
For those interested, my fix have been removed from this package for understandable reasons. Yet i've forked it at https://github.com/rewieer/react-native-background-geolocation.
It might serve as a temporary fix.

**Comment by mauron85** [comment]
@rewieer your "fix" will actually make plugin prone to be killed by the system anytime. This has been discussed many times here. Service must call startForeground when running in background. It may be tempting and also might work in some scenarios (like targeting old android apis), but I highly recommend to avoid this.

**Comment by rewieer** [comment]
I'd highly recommend to avoid this as well, but I needed it for my particular case and decided some people might need it too, albeit with the knowledge of the consequences.
Until now it worked fine on production in Android 9 devices (Samsung and Google phones).

**Comment by tienlongng95** [comment]
can we disable location notification on ios ?

**Comment by kristoff2016** [comment]
can we disable location notification on ios ? there are so many of them
