### ISSUE TITLE
com.marianhello.bgloc.LocationService$PostLocationTask.add (LocationService.java:549)

### ISSUE THREAD

**Issue by ntelkedzhiev** [mauron85/react-native-background-geolocation#243]
## Your Environment
* Plugin version: 0.5.0-alpha.35
* Platform: Android
* OS version: 7.1.2
* Device manufacturer and model: Xiaomi Redmi 5
* React Native version: 0.56.0
* Plugin configuration options: 
   desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
    stationaryRadius: 30,
    distanceFilter: 30,
    debug: false,
    startOnBoot: false,
    stopOnTerminate: true,
    locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
    interval: 60000,
    fastestInterval: FASTEST_INTERVAL,
    activitiesInterval: 30000,
    stopOnStillActivity: false,

## Context
Reported by Crashlytics on a live version.

## Debug logs
Fatal Exception: java.util.concurrent.RejectedExecutionException
Task com.marianhello.bgloc.LocationService$PostLocationTask$1@21f3611 rejected from java.util.concurrent.ThreadPoolExecutor@be96376[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 188]

**Comment by tlacroix** [comment]
I am experiencing the same problem on a Huawei Mate SE running Android 8.0. The app sends 2-3 locations, then I get this message every 10 seconds in `adb logcat`.  

All 3 providers give the same result. I'm using medium accuracy. My updates are sent roughly every 2-3 minutes (depending on the filter). 

The server response time isn't a problem (the whole HTTP request takes about 80ms). 

I'm not using the "location" event, only the `url` parameter.

Once in a blue moon (once every 20-30 tests roughly), it'll work for a few hours.

Everything works fine on iOS.

**Comment by tlacroix** [comment]
@mauron85 Version 3.0.0-alpha.49

**Comment by tlacroix** [comment]
Sorry for the cross-project comment. I've been a bit desperate about this issue! I've been doing more testing on this (4h today, for a total of 40h+ in the past two weeks), and I think I'm starting to see a pattern. Anyhow, I'll open an issue on the right project and document it properly, and reference it here.
