### ISSUE TITLE
Is it possible to show explainers to user before  asking location permission?

### ISSUE THREAD

**Issue by Luckygirlllll** [mauron85/react-native-background-geolocation#244]
Your Environment

Plugin version: "^0.5.0-alpha.34"
Platform: iOS or Android: Android
OS version: All
Device manufacturer and model: All
React Native version: 0.55.1
Plugin configuration options:

```
BackgroundGeolocation.configure({
       stopOnTerminate: true,
       desiredAccuracy: BackgroundGeolocation.MEDIUM_ACCURACY,
       stationaryRadius: 1000,
       distanceFilter: 7000,
       notificationTitle: 'Route verification',
       notificationText: 'enabled',
       startOnBoot: true,
       stopOnTerminate: true,
       locationProvider: BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,
       interval: 10000,
       fastestInterval: 5000,
       activitiesInterval: 10000,
       postTemplate: {
         lat: '@latitude',
         lng: '@longitude',
       },
       url: API.baseUrl + '/driver/location/',
       httpHeaders: {
         'Authorization': `Bearer ${props.accessToken}`,
       },
     })
```

Is it possible to show to the user explainer before the asking for the location permission?

**Comment by Luckygirlllll** [comment]
I mean show Alert before the asking location permission, or customize the text of location permission? Something similar to this picture. 
![unnamed-3](https://user-images.githubusercontent.com/10096433/42884697-adc049cc-8aa7-11e8-8ccb-675010219a03.jpg)

**Comment by imjaad9090** [comment]
If you are using android, you can use  _"react-native-android-location-services-dialog-box": "^2.6.0",_
and you can modify the message as you want. And ios asks for permissions automatically afik

**Comment by mauron85** [comment]
Why not just use plain react-native's Alert component as used in example app?

Similar to https://github.com/mauron85/react-native-background-geolocation-example/blob/master/src/scenes/Main.js#L189

**Comment by Luckygirlllll** [comment]
@mauron85 In the example Alert is shown in case if permission was not granted, right? How to show this alert before asking the permission?

**Comment by mauron85** [comment]
Not sure where do you see problem, but I would go something like this:

```
BackgroundGeolocation.checkStatus(({ isRunning, locationServicesEnabled, authorization }) => {
  if (authorization != BackgroundGeolocation.AUTHORIZED) {
        Alert.alert(
          'App requires location tracking',
          'Please grant permission in following screen',
          [
            {
              text: 'Ok',
              onPress: () => BackgroundGeolocation.start()
            }
          ]
        );
  } else {
    // we have permission so just start
    BackgroundGeolocation.start()
  }
});
```

**Comment by mauron85** [comment]
FYI: if you relly on email notifications. I just updated example from above.

**Comment by Luckygirlllll** [comment]
@mauron85 In the current example it will show that alert, only if user will click Deny button, on this system view, but how to show the alert, before this system view? 

<img width="245" alt="screen shot 2018-07-19 at 11 58 40" src="https://user-images.githubusercontent.com/10096433/42936123-fd72a148-8b53-11e8-839c-0ccb1e525cc1.png">

**Comment by sebastianruehmann** [comment]
Would be interested in a solution too!

**Comment by mauron85** [comment]
@Luckygirlllll can you post fragment of your code?

**Comment by Luckygirlllll** [comment]
@sebastianruehmann I solved the problem using redux store, so before enabling the location tracking, I'm showing to the user explainer, after that I'm saving in store, state that explainer was shown (so explainer will be shown to user only once), after that I'm enabling library, so It shows to user system permission view.
