### ISSUE TITLE
Foreground Service Android

### ISSUE THREAD

**Issue by AlexanderZerg13** [mauron85/react-native-background-geolocation#245]
## Your Environment
* Plugin version:
* Platform: Android
* OS version: 6.0
* Device manufacturer and model: LG Magna
* React Native version: 0.51.0
* Plugin configuration options: 0.5.0-alpha.26

## Context
Hi! Is it possible to hide notification "Background tracking", when app is running in background?

**Comment by nartjie101** [comment]
+ 1
