### ISSUE TITLE
Avoid getCurrentLocation() cached locations

### ISSUE THREAD

**Issue by JoseVf** [mauron85/react-native-background-geolocation#246]
Is there any way to avoid getting any cached location when I call getCurrentLocation? I mean, always ask for actual current location

## Your Environment

* Plugin version: ^0.5.0-alpha.35
* Platform: Both iOS and Android
* OS version: 11 / 6.0.1
* Device manufacturer and model: iPhone 6 / Samsung Galaxy J1 Mini Prime
* React Native version: 0.56
* Plugin configuration options: **Configuration for getCurrentLocation:** {timeout: 15000, enableHighAccuracy: true, maximumAge: 0}

## Expected Behavior
Always ask for current location avoiding cached ones

## Actual Behavior
Almost always return cached locations.

## Context
I want to get the current location of the device when I click a button, no matter if the last position was the same, always ask for the actual current.

**Comment by JoseVf** [comment]
Well, I realized that just fails on iOS with that configuration, on Android works as expected. But to make it work on iOS I had to put `maximumAge: 100` (or a bigger time).

**Comment by Balthazar33** [comment]
Hey @JoseVf 
Can you please share your code for getting the current location?

I use this :

```
let location = await BackgroundGeolocation.getCurrentPosition({
                                                    timeout: 30,          // 30 second timeout to fetch location
                                                    persist: true,        // Defaults to state.enabled
                                                    maximumAge: 5000,     // Accept the last-known-location if not older than 5000 ms.
                                                    desiredAccuracy: 10,  // Try to fetch a location with an accuracy of `10` meters.
                                                    samples: 3,           // How many location samples to attempt.
                                                });
```

I get the error 
`[TypeError: undefined is not a function]`

Thanks.

**Comment by Balthazar33** [comment]
Nevermind, fixed it this way.

 ```
BackgroundGeolocation.getCurrentLocation((success) => {
                                                console.log("Success", success);
                                            },
                                                (err) => {
                                                    console.log("Error", err);
                                                },
                                                {
                                                    // timeout: 30,          // 30 second timeout to fetch location
                                                    persist: true,        // Defaults to state.enabled
                                                    maximumAge: 5000,     // Accept the last-known-location if not older than 5000 ms.
                                                    desiredAccuracy: 10,  // Try to fetch a location with an accuracy of `10` meters.
                                                    samples: 3,           // How many location samples to attempt.
                                                });
```
