### ISSUE TITLE
Question: what is the best way to track the distance using this library? 

### ISSUE THREAD

**Issue by Luckygirlllll** [mauron85/react-native-background-geolocation#248]
Plugin version: "^0.5.0-alpha.34"
Platform: iOS or Android: Android
OS version: All
Device manufacturer and model: All
React Native version: 0.55.1
Plugin configuration options:

BackgroundGeolocation.configure({
       stopOnTerminate: true,
       desiredAccuracy: BackgroundGeolocation.MEDIUM_ACCURACY,
       stationaryRadius: 1000,
       distanceFilter: 7000,
       notificationTitle: 'Route verification',
       notificationText: 'enabled',
       startOnBoot: true,
       stopOnTerminate: true,
       locationProvider: BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,
       interval: 10000,
       fastestInterval: 5000,
       activitiesInterval: 10000,
       postTemplate: {
         lat: '@latitude',
         lng: '@longitude',
       },
       url: API.baseUrl + '/driver/location/',
       httpHeaders: {
         'Authorization': `Bearer ${props.accessToken}`,
       },
     })

What is the best way to track the distance using this library? Is there is an odometer method, build in inside the library, for the distance tracking or something similar?

**Comment by Luckygirlllll** [comment]
@mauron85  Or at least a build-in method for finding distance between two locations?

**Comment by mcmar** [comment]
Use this library for great circle distance between 2 points:
https://github.com/brandon93s/haversine-js

**Comment by Luckygirlllll** [comment]
I used this one library, it's pretty good https://github.com/manuelbieh/geolib
