### ISSUE TITLE
Post Template doesnt work for nested objects

### ISSUE THREAD

**Issue by yabsi** [mauron85/react-native-background-geolocation#250]
## Your Environment
* Plugin version: 0.5
* Platform: iOS or Android: Both 
* OS version: 11.4
* Device manufacturer and model: 11.4
* React Native version: 0.55
* Plugin configuration options: default 

## Context

```
  postTemplate: {
        lat: '@latitude',
        lon: '@longitude',
        foo: 'bar',
      },
``` 
works, but 
``` 
  postTemplate: {
       data {  
        lat: '@latitude',
        lon: '@longitude',
        foo: 'bar',
      },
},
```
doesn't. 
## Expected Behavior
Mapper should put values for location and longitude inside
## Actual Behavior
It sends '@latitude' and '@longitude' without changing their values. 

## Steps to Reproduce

```
    BackgroundGeolocation.configure({
      postTemplate: {
       data {
        lat: '@latitude',
        lon: '@longitude',
        foo: 'bar',
      }
    }
  });
```

## Context
Using 3rd party location APIs that take location and longitude in the format above.

**Comment by mauron85** [comment]
You can use nested objects, but those special  @ values (like @latitude) cannot be in nested object. Not gonna change that, but will accept PR. Thanks.

**Comment by ccoeder** [comment]
@yabsi did you find a solution?

**Comment by mauron85** [comment]
Fixed in alpha.45
