### ISSUE TITLE
TypeError: Cannot read property 'configure' of undefined

### ISSUE THREAD

**Issue by athersharif** [mauron85/react-native-background-geolocation#252]
## Your Environment

* Plugin version: 0.5.0-alpha.35
* Platform: Android
* React Native version: 0.55.0

## Context

When initializing BackgroundGeolocation, seeing `TypeError: Cannot read property 'configure' of undefined`

**Comment by athersharif** [comment]
Seems like this was an odd issue with linking the library if the project was created using `create-react-native-app`. Ejected from it and created it using `react-native init`. Works like a charm. Thanks for the awesome library!

**Comment by evserykh** [comment]
I have the same issue I guess:
```
[06:50:14] TypeError: undefined is not an object (evaluating 'RNBackgroundGeolocation.configure')

This error is located at:
    in App (at registerRootComponent.js:35)
    in RootErrorBoundary (at registerRootComponent.js:34)
    in ExpoRootComponent (at renderApplication.js:33)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:32)
```

The steps to reproduce the issue:
1) create-react-native-app
2) npm run eject
3) add the plugin

**Comment by qq912276337** [comment]
I have the same issue on iOS.how to solve it

**Comment by evserykh** [comment]
I guess you need to run `react-native run-ios` to compile native code

**Comment by athersharif** [comment]
yup, once you eject you should use the `react-native` stuff for compilation and release purposes. learnt it the hard way :)

**Comment by rishabhmathur1693** [comment]
I'm still facing this issue. Does anybody have a solution for it?
Also, BackgroundGeolocation object is not undefined, still it says "Cannot read property 'configure' of undefined"
