### ISSUE TITLE
All flavors must now belong to a named flavor dimension.

### ISSUE THREAD

**Issue by bidofan** [mauron85/react-native-background-geolocation#255]
## Your Environment

* Plugin version: latest
* Platform:  Android
* OS version: ubuntu 16.04
* Device manufacturer and model:
* React Native version: 56
* Plugin configuration options:  
* Link to your project:

## Context
When I'm trying to build my app with **react-native run-android**, i get this error 

## Expected Behavior
Project should compile 

## Actual Behavior
Get error

## Steps to Reproduce

1.
2.
3.
4.

**Comment by mauron85** [comment]
Please specify exact version numbers and don't use terms like "latest", as such reference to numeric version changes over the time
