### ISSUE TITLE
Need a map of Authorization Status. checkStatus method confusing.

### ISSUE THREAD

**Issue by vinceprofeta** [mauron85/react-native-background-geolocation#258]
Can you clarify what the values of these properties when calling checkStatus?

locationServicesEnabled
authorization

I am getting true for locationServicesEnabled when I have not authorized. What does this field mean exactly?

authorization is giving me back a number, but I do not know what that number means. I see 99 and 0. Can you clarify what the numbers indicate? the docs give constants but that doesn't help.

**Comment by mauron85** [comment]
> authorization is giving me back a number, but I do not know what that number means

you should check against constants defined
```
BackgroundGeolocation.checkStatus(({ isRunning, locationServicesEnabled, authorization }) => {
if (authorization == BackgroundGeolocation.AUTHORIZED) {

} else if (authorization == BackgroundGeolocation.NOT_AUTHORIZED) {
}


});
```

status code constants are desribed here https://github.com/mauron85/react-native-background-geolocation#checkstatussuccess-fail 


Or check example https://github.com/mauron85/react-native-background-geolocation-example/blob/master/src/scenes/Main.js#L189

**Comment by pie6k** [comment]
@mauron85 what is meaning of `99` status? I cant find it in the map and it's not matching any of provided values
