### ISSUE TITLE
notification icons not working

### ISSUE THREAD

**Issue by ianaz** [mauron85/react-native-background-geolocation#26]
## Your Environment
* Plugin version: 0.2.0-alpha.5
* Platform: Android
* OS version: Android 7.0
* Device manufacturer and model: Emulator
* React Native version: 0.37.0
* Plugin configuration options: {
            desiredAccuracy: 10,
            stationaryRadius: 50,
            distanceFilter: 10,
            locationTimeout: 10,
            notificationIconLarge: '../../images/ic_directions_walk_black_48dp.png',
            notificationTitle: 'Recording track...',
            notificationText: 'Tap to show more details',
            startOnBoot: false,
            stopOnTerminate: false,
            locationProvider: BackgroundGeolocation.provider.ANDROID_ACTIVITY_PROVIDER,
            interval: 5000,
            fastestInterval: 5000,
            activitiesInterval: 10000,
            stopOnStillActivity: false
        }

## Context
I've tried to set an image based on the current component (../../) and also android folders but doesn't work. How should the image url be formatted?
No icon was shown; I've tried both the icon large and small.

## Possible Fix
Would be nice to be able to set images easily. And one off-topic; would be possible to disable completely the notification or that would not work then in background?

**Comment by mauron85** [comment]
Images must be in res/drawable folder.

**Comment by ianaz** [comment]
Thanks. Made a pull request #27

**Comment by plblueraven** [comment]
@ianaz could you, please, specify how exactly proper configuration looks like?
I mean - I have icon in `android/app/src/main/res/drawable/ic_notification.png`
and cofnig like
```
 BackgroundGeolocation.configure({
            [...]
            notificationIconSmall: 'ic_notification.png',
            notificationIconLarge: 'ic_notification.png'
        });
```
or

```
 BackgroundGeolocation.configure({
            [...]
            notificationIconSmall: 'ic_notification.png'
        });
```
or

```
 BackgroundGeolocation.configure({
            [...]
            notificationIconLarge: 'ic_notification.png'
        });
```
But still just icon placeholder show up in the notification.

Is there any specific resolution notification icon should have?

**Comment by mauron85** [comment]
Remove png extension
