### ISSUE TITLE
Disable Notification Sound and Vibration in Android

### ISSUE THREAD

**Issue by mrtalley** [mauron85/react-native-background-geolocation#260]
## Your Environment

* Plugin version: 0.5.0-alpha.35
* Platform: Android
* React Native version: 0.55.4
* Plugin configuration options: 
```js
{
    notificationTitle: "some-title",
    notificationText: "Posting your location",
    startForeground: false,
    debug: false,
}
```

## Context

When I begin tracking location, I receive a push notification on Android with a sound and vibration. The notification is desired, but I wish to disable the sound and vibration. From everything I can find, this is not possible as of the current version.

## Expected Behavior

I enable location tracking and silently receive a persistent notification in the Android status bar.

## Actual Behavior

I enable location tracking and receive a sound and vibration as well as a persistent notification in the Android status bar.

## Possible Fix

Add a configuration option to either turn off notifications from this library entirely, or to turn off sound and vibration.

If going the route of muting sound, it looks like you set notification priority to `IMPORTANCE_DEFAULT`. Changing it to `IMPORTANCE_LOW` should solve the issue.

## Context

I am trying to silently put a persistent notification in the Android status bar that tells the user their location is being tracked in the background. I want the option to either disable sound and vibration or to disable the notification entirely.

**Comment by mauron85** [comment]
Hi, do you mind creating PR for this?
