### ISSUE TITLE
ReactNativeJS: RNBackgroundGeolocation: Configuration error: Attempt to invoke virtual method 'void com.marianhello.bgloc.LocationService.configure(com.marianhello.bgloc.Config)' on a null object reference

### ISSUE THREAD

**Issue by dcoulter45** [mauron85/react-native-background-geolocation#263]
## Your Environment
* Plugin version: 0.5.0-alpha.35
* Platform: Android
* OS version: 8
* React Native version: 55.4

## Context
Android only issue

## Expected Behavior
App starts as normal

## Actual Behavior
App works in debug mode, but crashes on startup in release mode

## Steps to Reproduce
BackgroundGeolocation settings. App crashes when configure() is called 

```
BackgroundGeolocation.configure({
  desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
  stationaryRadius: 50,
  distanceFilter: 100,
  notificationTitle: 'Background tracking',
  notificationText: 'enabled',
  debug: false,
  startOnBoot: false,
  stopOnTerminate: false,
  locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
  interval: 10000,
  fastestInterval: 5000,
  activitiesInterval: 10000,
  stopOnStillActivity: false,
});
```

## Debug logs
ReactNative: ReactInstanceManager.ctor()
ReactNative: ReactInstanceManager.createReactContextInBackground()
ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
ReactNative: ReactInstanceManager.recreateReactContextInBackgroundFromBundleLoader()
ReactNative: ReactInstanceManager.recreateReactContextInBackground()
ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
ReactNative: ReactInstanceManager.createReactContext()
ReactNative: Initializing React Xplat Bridge.
ReactNative: Initializing React Xplat Bridge before initializeBridge
ReactNative: Initializing React Xplat Bridge after initializeBridge
ReactNative: CatalystInstanceImpl.runJSBundle()
ReactNative: ReactInstanceManager.setupReactContext()
ReactNative: CatalystInstanceImpl.initialize()
ReactNativeJS: RNBackgroundGeolocation: Configuration error: Attempt to invoke virtual method 'void com.marianhello.bgloc.LocationService.configure(com.marianhello.bgloc.Config)' on a null object reference

**Comment by mauron85** [comment]
Try 0.5.0-alpha.36

**Comment by dcoulter45** [comment]
That works, thankyou.

**Comment by mauron85** [comment]
Glad it's working. Closing issue.
