### ISSUE TITLE
Start and Stop BackgroundGeolocation

### ISSUE THREAD

**Issue by manhncse02926** [mauron85/react-native-background-geolocation#266]
## Your Environment

* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer and model:
* React Native version:
* Plugin configuration options: 
* Link to your project:

## Context

It just a question to find the best solution for my situation. Could you help me solved my inquiry?
Sometime I need change the configuration of Backgroundlocation (postTemplate). Is it ok if I just call run call configure and start it again? Should I stop first then start again?
Thank you
## Steps to Reproduce

1.
2.
3.
4.

**Comment by mauron85** [comment]
No need to stop/start. Just call configure
