### ISSUE TITLE
Type Definitions

### ISSUE THREAD

**Issue by djereg** [mauron85/react-native-background-geolocation#274]
I was created a type definitions file to ease my life.

The question is to make PR here with the index.d.ts file or create separate @types/react-native-mauron85-background-geolocation package?

**Comment by BrantApps** [comment]
I too have completed this task. [Here is gist](https://gist.github.com/BrantApps/dc8175fdd00b74c39114c4e8d58a5c23#file-index-d-ts) of what I've got. Happy to help @djereg if you think I can!

**Comment by djereg** [comment]
And [here](https://gist.github.com/djereg/575b71a18961f7bf52def17ac6f466e4) is mine.

**Comment by djereg** [comment]
[@types/react-native-mauron85-background-geolocation](https://www.npmjs.com/package/@types/react-native-mauron85-background-geolocation)
