### ISSUE TITLE
Documentation of ACTIVITY_PROVIDER wrong for IOS. Cant work in background.

### ISSUE THREAD

**Issue by danielgindi** [mauron85/react-native-background-geolocation#275]
As motion activity events are not triggered in the background,
The library will not start tracking location again when there's suitable motion.

The docs say "This one is best to use as foreground location provider (but works in background as well)" - this is misleading.

**Comment by mauron85** [comment]
This is true. It's misleading. Warnings should be added.

**Comment by ccoeder** [comment]
Do we have any clues about the problem? Can I help you with that?

**Comment by mauron85** [comment]
@ccoeder there is not much we can do here (in term of code). Only documentation should be updated, to state this provider has its limitations. Maybe in the future we can add fallback to geofencing when in background.

**Comment by anthonyhumphreys** [comment]
Is there no chance of using the ACTIVITY_PROVIDER? I was hoping to use this to ascertain the user's travel type to enhance the data we collect. Its a big loss to not have this :( Using the raw_provider now. ACTIVITY_PROVIDER simply does not work in the background for me on iOS

**Comment by anthonyhumphreys** [comment]
Damn. Not for this issue really, but reckon i could find the activity type  use BackgroundTask to call the activity api?

**Comment by ShafiqShams** [comment]
What locationProvider should we use for iOS 12.1.2?
Distance filter or Raw ? Which work in background as well.
