### ISSUE TITLE
on location event i am getting continous location object.

### ISSUE THREAD

**Issue by rushabhrakholiya** [mauron85/react-native-background-geolocation#28]
i am getting continous gettting location object on location event i have bind it with firebase and it frequent writing data if device is in steady status(not moving)

it should be return location object only when we move given moving radious.

kindly guide me if i am in wrong direction

please have a look on code which i have written for firebase io
    BackgroundGeolocation.on('location', (location) => {
      //handle your locations here            
      //location = JSON.stringify(location);                 
      timekey = JSON.stringify(location.time);
      timekey = timekey.toString();
      newPostKey = firebase.database().ref().child('gps').push().key;          
      if(uid != 0)
      {
          firebaseApp.database().ref('gps/' + uid+"/"+newPostKey).set({
            location
          });
      }                  
    });

i want location object only in moving status of device
can you please elaborate me more in this that how it would it be possible?

## Steps to Reproduce

1.
2.
3.
4.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 342 days. You may reopen this issue if it has been closed in error.
