### ISSUE TITLE
cant find variable: Actions

### ISSUE THREAD

**Issue by starba3** [mauron85/react-native-background-geolocation#281]
## Your Environment

* Plugin version: 0.5.0-alpha.41
* Platform: Android
* OS version: 7.0
* Device manufacturer and model: galaxy s6 edge
* React Native version: 0.55.4
* Plugin configuration options: 
```
BackgroundGeolocation.configure({
		    desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
	     	stationaryRadius: 5,
	      	distanceFilter: 5,
		    notificationTitle: 'Background tracking',
		    notificationText: 'enabled',
		    debug: false,
		    startOnBoot: false,
		    stopOnTerminate: false,
		    locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
		    interval: 5000,
		    fastestInterval: 10000,
		    activitiesInterval: 5000,
		    stopOnStillActivity: false,
			url: `xxxxxxxxxxxxxxxx`,
		    httpHeaders: {
		    	'Accept': 'application/json',
				'Content-Type' : 'application/json'
		    },
		      // customize post properties
		    postTemplate: {
		    	user_id: this.state.id,
		        lat: '@latitude',
		        long: '@longitude'
		        // foo: 'bar' // you can also add your own properties
		    }
		});
```

## Context
after copying the example in the repo, when i run the app i get the error:
cant find variable: Actions, on the line the Actions.sendLocation() method is called inside of 'location' event.
this causes the app to not send the location to server.

## Expected Behavior
location should be sent to server with user_id attribute(should be static for every post request)

## Actual Behavior
iam getting error: cant find variable: Actions 

## Steps to Reproduce

1.copy the example in readme.
2.run the application.
3.location event fires up.

## Context
without sending location to server, location tracking function wont work.

**Comment by shukerullah** [comment]
`Actions.send` is just example, replace it with your logic.
