### ISSUE TITLE
[ANDROID] How to get speed value?

### ISSUE THREAD

**Issue by Baskerville42** [mauron85/react-native-background-geolocation#282]
## Your Environment

* Plugin version: 0.5.0-alpha.41
* Platform: Android
* OS version: 8.1.0
* Device manufacturer and model: Google Nexus 6P
* React Native version: 0.56.0
* Plugin configuration options: from Example in the repo

## Context
Why I can get `speed` param on iOS but didn't on Android?

## Expected Behavior
Get actual speed value on both platforms

## Actual Behavior
Sometimes I get speed with value 0 or undefined

## Possible Fix
https://stackoverflow.com/a/11625274
https://stackoverflow.com/a/4812005
Maybe we can implement this solutions for cases when speed value is undefined/not available

## Steps to Reproduce

1. Take the code from the example and run on android

## Context

I need to get real-time data from device sensors with position and speed values

**Comment by mauron85** [comment]
Some providers just don't provide speed. Eg. it doesn't make sense for network provider or wifi provider.
