### ISSUE TITLE
Notifications always showing when app in background or terminated

### ISSUE THREAD

**Issue by himanshusharma9400** [mauron85/react-native-background-geolocation#286]
## Your Environment

* Plugin version:0.5.0-alpha.41
* Platform:Android
* OS version: Sdk 23+
* Device manufacturer and model:All
* React Native version:0.56
* Plugin configuration options: 
* Link to your project:Project for company so private

## Context

Unable to dismiss or disable the notification even if "notificationsEnabled=false" "debug=false" "startForeground=false" when app in background or when app is terminated. Notification only doesn't show when app is in foreground 

## Expected Behavior

After applying above options the notification should not be shown when app is in background or terminated. 

## Actual Behavior

After applying above options the notification is still showing when app is in background or terminated

## Steps to Reproduce

1. BackgroundGeolocation.configure({
            desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
            stationaryRadius: 50,
            distanceFilter: 50,
            notificationsEnabled:false,
            notificationTitle: 'Background tracking',
            notificationText: 'enabled',
            debug: true,
            startOnBoot: true,
            stopOnTerminate: false,
            startForeground:false,
            locationProvider: BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,
            interval: 10000,
            fastestInterval: 5000,
            activitiesInterval: 10000,
            stopOnStillActivity: false,
            url: 'https://ptsv2.com/t/pbrcc-1537779600/post',
            httpHeaders: {
            },
            // customize post properties
            postTemplate: {
              lat: '@latitude',
              lon: '@longitude'
               // you can also add your own properties
            }
          });

**Comment by CHOMNANP** [comment]
having the same problem.

I try configure "notificationsEnabled" to false as well but the notification still there.

here the version I'm using. Just install it today.

"react-native-mauron85-background-geolocation": "^0.5.0-alpha.31"

**Comment by mauron85** [comment]
This is normal behaviour. Was discussed couple of times. Android needs that notification when app is in the background or in other case app can be killed by the system anytime. And `notificationsEnabled` only adjust sync progress notification.
