### ISSUE TITLE
App crashes in background when using headlessTask

### ISSUE THREAD

**Issue by himanshusharma9400** [mauron85/react-native-background-geolocation#287]
## Your Environment
* Plugin version:0.5.0-alpha.41
* Platform:Android
* OS version: Sdk 19+
* Device manufacturer and model:Nexus 5
* React Native version:0.56
* Plugin configuration options: 

BackgroundGeolocation.headlessTask(function(event) {
    if (event.name === 'location' ||
      event.name === 'stationary') {
        var xhr = new XMLHttpRequest();
        xhr.open('POST', 'http://192.168.81.14:3000/headless');
        xhr.setRequestHeader('Content-Type', 'application/json');
        xhr.send(JSON.stringify(event.params));
    }
    return 'Processing event: ' + event.name; // will be logged
});
* Link to your project:Private application

## Context
I added BackgroundLocation.headlessTask() function in the example shown in docs but when I terminate the application and when location change event occurs I get an alert that application has stopped working and gives an option to restart the app or mute the app.

## Expected Behavior
I expected that the callback inside the headlessTask function would run successfully and will post data to the server
## Actual Behavior
The application got crashed when app is in background or terminated state.

## Steps to Reproduce
1.BackgroundGeolocation.configure({
            desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
            stationaryRadius: 50,
            distanceFilter: 50,
            notificationsEnabled:false,
            notificationTitle: 'Background tracking',
            notificationText: 'enabled',
            debug: true,
            startOnBoot: true,
            stopOnTerminate: false,
            startForeground:true,
            locationProvider: BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,
            interval: 10000,
            fastestInterval: 5000,
            activitiesInterval: 10000,
            stopOnStillActivity: false,
            url: 'https://ptsv2.com/t/pbrcc-1537779600/post',
            httpHeaders: {
            },
            // customize post properties
            postTemplate: {
              lat: '@latitude',
              lon: '@longitude',
              hello: 'maestro' // you can also add your own properties
            }
          });
          BackgroundGeolocation.on('location', (location) => {
            // handle your locations here
            // to perform long running operation on iOS
            // you need to create background task
            BackgroundGeolocation.startTask(taskKey => {
              // execute long running task
              // eg. ajax post location
              // IMPORTANT: task has to be ended by endTask
              BackgroundGeolocation.endTask(taskKey);
            });
          });
      
          BackgroundGeolocation.on('stationary', (stationaryLocation) => {
            // handle stationary locations here
            //Actions.sendLocation(stationaryLocation);
            console.log(stationaryLocation)
          });
      
          BackgroundGeolocation.on('error', (error) => {
            console.log('[ERROR] BackgroundGeolocation error:', error);
          });
      
          BackgroundGeolocation.on('start', () => {
            console.log('[INFO] BackgroundGeolocation service has been started');
          });
      
          BackgroundGeolocation.on('stop', () => {
            console.log('[INFO] BackgroundGeolocation service has been stopped');
          });
          
          BackgroundGeolocation.on('authorization', (status) => {
            console.log('[INFO] BackgroundGeolocation authorization status: ' + status);
            if (status !== BackgroundGeolocation.AUTHORIZED) {
              // we need to set delay or otherwise alert may not be shown
              setTimeout(() =>
                Alert.alert('App requires location tracking permission', 'Would you like to open app settings?', [
                  { text: 'Yes', onPress: () => BackgroundGeolocation.showAppSettings() },
                  { text: 'No', onPress: () => console.log('No Pressed'), style: 'cancel' }
                ]), 1000);
            }
          });
      
          BackgroundGeolocation.on('background', () => {
            console.log('[INFO] App is in background'); 
          });
      
          BackgroundGeolocation.on('foreground', () => {
            console.log('[INFO] App is in foreground');
          });
      
          BackgroundGeolocation.checkStatus(status => {
            console.log('[INFO] BackgroundGeolocation service is running', status.isRunning);
            console.log('[INFO] BackgroundGeolocation services enabled', status.locationServicesEnabled);
            console.log('[INFO] BackgroundGeolocation auth status: ' + status.authorization);
      
            // you don't need to check status before start (this is just the example)
            if (!status.isRunning) {
              BackgroundGeolocation.start(); //triggers start on start event
            }
            if (!status.locationServicesEnabled) {
                Alert.alert(
                  'Location services disabled',
                  'Would you like to open location settings?',
                  [
                    {
                      text: 'Yes',
                      onPress: () => BackgroundGeolocation.showLocationSettings()
                    },
                    {
                      text: 'No',
                      onPress: () => console.log('No Pressed'),
                      style: 'cancel'
                    }
                  ]
                );
              }
});
BackgroundGeolocation.headlessTask(function(event) {
    if (event.name === 'location' ||
      event.name === 'stationary') {
        var xhr = new XMLHttpRequest();
        xhr.open('POST', 'https://ptsv2.com/t/pbrcc-1537779600/post');
        xhr.setRequestHeader('Content-Type', 'application/json');
        xhr.send(JSON.stringify(event.params));
    }

    return 'Processing event: ' + event.name; // will be logged
});

## Context
I was trying to send data to server when the app is in background or terminated state and a location event or stationary event happened.

## Debug logs
09-27 16:46:23.786 16166-16294/com.maestro E/com.marianhello.logging.UncaughtExceptionLogger: FATAL EXCEPTION: LocationService.Threadjava.lang.RuntimeException: java.lang.Throwable: A WebView method was called on thread 'LocationService.Thread'. All WebView methods must be called on the same thread. (Expected Looper Looper (main, tid 1) {ed11eff} called on Looper (LocationService.Thread, tid 798) {66634d7}, FYI main Looper is Looper (main, tid 1) {ed11eff})

**Comment by Ramesh21071993** [comment]
Hi

App crashes on calling Background.stop() function,
please anyone help on this?
