### ISSUE TITLE
Modifying the request in native code to set request header (firebase auth)

### ISSUE THREAD

**Issue by siderakis** [mauron85/react-native-background-geolocation#288]
Does this library support modifying the request in native code. I'd like to set an auth header using the native firebase library.

Maybe something similar to the "Transforming/filtering locations in native code" feature would work for modifying requests.

Thanks

**Comment by mauron85** [comment]
Yes, it was added recently https://github.com/mauron85/react-native-background-geolocation#transformingfiltering-locations-in-native-code

**Comment by siderakis** [comment]
I'm looking to modify the HTTP request using native code (not the location data).

**Comment by mauron85** [comment]
@siderakis. That is not possible at the moment. BTW isn't setting http header using configure method sufficient?

**Comment by siderakis** [comment]
I need to set an authorization header which expired pretty quickly.

**Comment by mauron85** [comment]
Do you know you can call configure any time you want, just with httpHeaders
param to change headers?

**Comment by siderakis** [comment]
Yup, If I understand correctly if stopOnTerminate is set to false then the app will continue tracking the user and sending their location to the server. In this case we would need native code to keep the authorization header if it expired.

**Comment by mauron85** [comment]
Oh well. In that case yes.
