### ISSUE TITLE
Disable Notifications Completely

### ISSUE THREAD

**Issue by edencakir** [mauron85/react-native-background-geolocation#29]
I wish to remove all the notifications from the app. Is it possible without letting OS to kill it. I want everything the same except notifications.

**Comment by edencakir** [comment]
Just checked the original [repo](https://github.com/transistorsoft/react-native-background-geolocation/issues/146). Setting
` debug: false` 
solves the issue.

**Comment by VlCTORlOUS** [comment]
`debug: false` does not work for me - is there something else?

**Comment by edencakir** [comment]
did you try react-native run-ios again?

**Comment by VlCTORlOUS** [comment]
@edencakir I used android for this but yes, I did build the App again.Please see [the issue I opened](https://github.com/mauron85/react-native-background-geolocation/issues/32) for further information.

**Comment by edencakir** [comment]
@VlCTORlOUS I haven't tested on ios yet. Will look into that

**Comment by VlCTORlOUS** [comment]
@edencakir alright, thank you 👍 
But as I said in my issue - I don't believe there is any way (not an easy, straight forward one anyway) to accomplish this

**Comment by edencakir** [comment]
So isn't here any way to accomplish such background tracking task? Do you have any ideas?

**Comment by sators** [comment]
+1

**Comment by bacancy-suresh** [comment]
Also not work for me
