### ISSUE TITLE
Speed and Heading

### ISSUE THREAD

**Issue by kenobi91** [mauron85/react-native-background-geolocation#291]
Is there any way to get speed and heading information ?

**Comment by NULL-SWEAT** [comment]
+1
I'm not getting speed as well.
Using the ACTIVITY_PROVIDER

When using the react-native-fused-location lib, the location object contains the speed.

**Comment by plblueraven** [comment]
Duplicate of #282

**Comment by mauron85** [comment]
Some providers just don't provide speed. Eg. it doesn't make sense for network provider or wifi provider.

**Comment by mauron85** [comment]
Closing as duplicate.

**Comment by xgenem** [comment]
Sorry for re-opening. How about the heading value?
