### ISSUE TITLE
ios Notifications.

### ISSUE THREAD

**Issue by manujbahl** [mauron85/react-native-background-geolocation#298]
## Your Environment

* 0.5.0-alpha.42:
* iOS
* OS version:11.4.1
* Device manufacturer and model: Apple iphone 7 plus
* React Native version: 16.3.1
* Plugin configuration options: none
* Link to your project: yes

## Context

When i start the tracking, it keeps sending me notifications 

Location update : BG
PD:0 | ....

OR
BgGeo activity detected: STILL activity ...

How can i turn notifications off in iOS. The documentation has a notificationsEnabled API that it says is Android only.

## Expected Behavior

a way to trun iOS notifications off.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by xe4me** [comment]
`debug:false`

**Comment by gabimoncha** [comment]
I can confirm that setting `debug:false` is fixing this problem
