### ISSUE TITLE
react-native run-android build fail

### ISSUE THREAD

**Issue by ddpdev** [mauron85/react-native-background-geolocation#30]
## Your Environment

* Plugin version: react-native-mauron85-background-geolocation": "^0.2.0-alpha.5",
* Platform:  Android 
* OS version: MACOS 10.1
* Device manufacturer and model: N/A 
* React Native version: 0.39.2,   "react": "^15.4.1", "react-native-maps": "^0.12.2",
* Plugin configuration options: N/A
* Link to your project: 

react-native run-ios is OK!

BUT, > react-native run-android ...build fail
:when except 'react-native-mauron85-background-geolocation' module, android build success. 
why? how to fix it? help me please...

## Context

-- StackTrace result =>
       at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: org.gradle.api.UnknownProjectException: Cannot evaluate module react-native-mauron85-background-geolocation : **Configuration with name 'default' not found.
        at** com.android.build.gradle.internal.DependencyManager.ensureConfigured(DependencyManager.java:728)
        at com.android.build.gradle.internal.DependencyManager.resolveDependencyForConfig(DependencyManager.java:240)
  

22:08:37.485 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.oldresult.TransientConfigurationResultsBuilder] Flushing resolved configuration data in Binary store in /private/var/folders/r3/h0j25sqs7l19n4ntqjtq17040000gn/T/gradle2243088338185070650.bin. Wrote root ddpstyleapp:react-native-mauron85-background-geolocation:unspecified:classpath.
22:08:37.489 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on proj remapped class cache for c89y9hb456dzckosaoecwcvdm (/Users/mskim/.gradle/caches/2.14.1/scripts-remapped/build_8cu99wbepomhawmoowtsxpnnw/c89y9hb456dzckosaoecwcvdm/proj-6772558678143434850).
22:08:37.542 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired.
22:08:37.542 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on proj remapped class cache for c89y9hb456dzckosaoecwcvdm (/Users/mskim/.gradle/caches/2.14.1/scripts-remapped/build_8cu99wbepomhawmoowtsxpnnw/c89y9hb456dzckosaoecwcvdm/proj-6772558678143434850).
22:08:37.552 [DEBUG] [org.gradle.configuration.project.BuildScriptProcessor] Timing: Running the build script took 0.081 secs
22:08:37.559 [ERROR] [org.gradle.BuildExceptionReporter] 
22:08:37.559 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
22:08:37.559 [ERROR] [org.gradle.BuildExceptionReporter] 
22:08:37.560 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
22:08:37.560 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred configuring project ':app'.
22:08:37.560 [ERROR] [org.gradle.BuildExceptionReporter] > **Cannot evaluate module react-native-mauron85-background-geolocation : Configuration with name 'default' not found.**
22:08:37.560 [ERROR] [org.gradle.BuildExceptionReporter] 
22:08:37.560 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
22:08:37.560 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
22:08:37.560 [LIFECYCLE] [org.gradle.BuildResultLogger] 
22:08:37.560 [LIFECYCLE] [org.gradle.BuildResultLogger] **BUILD FAILED**
22:08:37.560 [LIFECYCLE] [org.gradle.BuildResultLogger] 
22:08:37.560 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 7.799 secs
22:08:37.578 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.memcache.InMemoryCachedRepositoryFactory] In-memory dependency metadata cache closed. Repos cached: 617, cache instances: 7, modules served from cache: 8433, artifacts: 1128

## Expected Behavior

Build OK

## Actual Behavior

Build Fail

## Steps to Reproduce

1. Android setup OK (following your guide)
2. 
3.
4. Dependencies OK

**Comment by mauron85** [comment]
Check https://github.com/mauron85/react-native-background-geolocation#android-setup. If it helps. (Hint: projectDir must end with app/lib)

**Comment by ddpdev** [comment]
Oh!!! Thanks, you are my hero ^^;
