### ISSUE TITLE
Error 1003

### ISSUE THREAD

**Issue by mattknappchhj** [mauron85/react-native-background-geolocation#300]
## Your Environment

* Plugin version: 0.5.0-alpha.42
* Platform: iOS
* OS version: 12
* Device manufacturer and model: Simulator
* React Native version: 0.57.1
* Plugin configuration options: 
* Link to your project:

## Context

Attempting to follow user location while app is open.

## Expected Behavior

No errors

## Actual Behavior

The below error, not found in docs:

[ERROR] BackgroundGeolocation error: {message: "The operation couldn’t be completed. (com.marianhello error 1003.)", code: 1003}

**Comment by mauron85** [comment]
I can confirm this. Seems like Xcode 10 issue.

https://stackoverflow.com/questions/52430007/xcode-10-ios-12-simulator-location-simulation-fails-on-city-bicycle-ride-city

**Comment by maddoherty** [comment]
For me, I had turned the simulator location on "none". Once I switched it to "Freeway Driving", it started working again.

**Comment by Inayat567** [comment]
For me, 
When my ios location is turn off, I was getting issue,
I simply showed a toast message to user when error code === 3
