### ISSUE TITLE
Android notification icon <Background Tracking>

### ISSUE THREAD

**Issue by manhncse02926** [mauron85/react-native-background-geolocation#309]
## Your Environment

* Plugin version:
* Platform:  Android
* OS version: 7.0
* Device manufacturer and model: Samsung Galaxy S8
* React Native version:55.4
* Plugin configuration options: 
* Link to your project:

## Context

I want to hide the icon tracking on Android device. 
Please refer my below link for more detail. 
https://i.screenshot.net/5gonnh2
my code configuration:

>  desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
      stationaryRadius: 1000,
      distanceFilter: 1000,
      startOnBoot: false,
      stopOnTerminate: false,
      locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
      interval: 10000,
      fastestInterval: 5000,
      activitiesInterval: 1000,
      notificationsEnabled:false,
      stopOnStillActivity: false,

Thanks
## Steps to Reproduce

1.
2.
3.
4.

**Comment by manhncse02926** [comment]
I found the solution already. startForeground : false
Thanks

**Comment by claudineibjr** [comment]
It works for me.

Thanks @manhncse02926
