### ISSUE TITLE
"property has a previous declaration" while building iOS app

### ISSUE THREAD

**Issue by pvomhoff** [mauron85/react-native-background-geolocation#31]
When I setup my project with the newest version, add this library and build the app an error occurs.

## Your Environment

* Plugin version: 0.2.0-alpha.6
* Platform: iOS
* OS version: 10.0
* Device manufacturer and model: iPhone Simulator 6
* React Native version: 0.40.0

## Context
I tried two versions: 0.2.0-alpha.5 (from master) and 0.2.0-alpha.6 (from next).
I followed all the instructions and run `react-native run ios`

## Expected Behavior
The build should not fail and the app should run

## Actual Behavior
The build fails with the error message:
`error: property has a previous declaration`

## Possible Fix
I looks like it occur because of a major change in 0.40.0.
See release: https://github.com/facebook/react-native/releases/tag/v0.40.0

So replacing `#import "RCTBridge.h"` with `#import "React/RCTBridge.h"` solved my problem.

## Steps to Reproduce

1. react-native init ReactNativeGeolocationBackgroundThread
2. npm install react-native-mauron85-background-geolocation --save
3. react-native run-ios

## Debug logs
`~/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTBridge.h:1
70:61: error: property has a previous declaration
@property (nonatomic, weak, readonly) id<RCTBridgeDelegate> delegate;`

**Comment by sators** [comment]
Nice work on the Possible Fix!  Works for me!  

Edit made to /node_modules/react-native-background-geolocation/ios/RCTBackgroundGeolocation/RCTBackgroundGeolocation.m

https://github.com/mauron85/react-native-background-geolocation/blob/master/ios/RCTBackgroundGeolocation/RCTBackgroundGeolocation.m#L11

**Comment by mauron85** [comment]
ok this should be fixed in 0.2.0-alpha.6

**Comment by varipallisrikanth** [comment]
replacing #import "RCTBridge.h" with #import "React/RCTBridge.h" in file react_native_****.m file solved my problem

[blah/blah/blah]/node_modules/react-native-****/ios/react-native-****/react_native_*******.m is the exact path.

Thanks guys
