### ISSUE TITLE
Property 'events' does not exist on type 'typeof BackgroundGeolocationPlugin'.

### ISSUE THREAD

**Issue by djereg** [mauron85/react-native-background-geolocation#311]
## Your Environment
* Plugin version: 0.5.0-alpha.44
* React Native version: 0.57.4

## Context
In [Quick example](https://github.com/mauron85/react-native-background-geolocation#quick-example):

```typescript
componentWillUnmount() {
  // unregister all event listeners
  BackgroundGeolocation.events.forEach(event => BackgroundGeolocation.removeAllListeners(event));
}
```

But `events` in not exported.

### Other:
```typescript
import BackgroundGeolocation, {BackgroundGeolocationError, Location, PositionOptions} from 'react-native-mauron85-background-geolocation';

const options: PositionOptions = {
  maximumAge: 5000,
  timeout: 15000,
  enableHighAccuracy: true,
};

const success = (location: Location) => {
  resolve(locationToCoords(location));
};

const fail = (error: BackgroundGeolocationError) => {
  reject(error)
};

BackgroundGeolocation.getCurrentLocation(success, fail, options);
```

When WebStorm auto imports the types I get the next error, and comp:
`Module 'react-native-mauron85-background-geolocation' has no exported member 'Location'.`

I have to change it to next:
```typescript
import BackgroundGeolocation from 'react-native-mauron85-background-geolocation';

const options: BackgroundGeolocation.PositionOptions = {
  maximumAge: 5000,
  timeout: 15000,
  enableHighAccuracy: true,
};

const success = (location: BackgroundGeolocation.Location) => {
  resolve(locationToCoords(location));
};

const fail = (error: BackgroundGeolocation.BackgroundGeolocationError) => {
  reject(error)
};

BackgroundGeolocation.getCurrentLocation(success, fail, options);
```

Here are the good old working type definitions 😉 
[@types/react-native-mauron85-background-geolocation](https://www.npmjs.com/package/@types/react-native-mauron85-background-geolocation)

**Comment by mauron85** [comment]
FYI just updated definition in master branch.

**Comment by djereg** [comment]
I am happy if I can help, because love this plugin. Used it previously with Cordova and now with React Native.

Now I would do some things differently, in next `@types` update. Half is completed, buy if you made your own type definitions I'll let it go.

Eg. using types for primitives instead of interfaces. The only one reason is, maybe only for me, the annoying parent referencing icons, like next picture:

![image](https://user-images.githubusercontent.com/6384768/47640675-64411700-db64-11e8-972e-a502309cd699.png)

Using the the long type names like `BackgroundGeolocationError` or `BackgroundGeolocationOptions`. Why? If someone using other packages with same types which can conflict, he can alias them.

These are just my thoughts, do not take it as criticism 😉

**Comment by mauron85** [comment]
None criticism taken.

>Using the the long type names like BackgroundGeolocationError or BackgroundGeolocationOptions. 
yes, agree. No need to make the so long.

>Eg. using types for primitives instead of interfaces. 
also make sense

 You can send PR to this repository.

**Comment by djereg** [comment]
If you think, I can merge the two type definitions in next few days. Or do it, and and least I will add my thoughts. What you think?

**Comment by mauron85** [comment]
Yes, that would be great. Just few remarks.

1. I would like to keep using namespace instead of Module, as official typescript doc [recommends for object with properties](https://www.typescriptlang.org/docs/handbook/declaration-files/by-example.html#objects-with-properties) which the exported object literal is.

2. If possible don't include links to react-native github page. The reason is that I would like to use same definitions also for cordova variant. Or maybe we can use placeholders for domain in url and generate definition by script (one for cordova links and one for rn).

Nothing else matters. ;)

**Comment by mauron85** [comment]
Actually reading typescript [official docs](https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html), I'm not sure about namespaces vs modules anymore.

>Namespaces are simply named JavaScript objects in the global namespace.

This is valid probably only for cordova, which exports all modules to global namespace (but plugin can be also imported as module I guess).

So leaving this debate modules vs namespaces as open.

**Comment by mauron85** [comment]
Also one thing. As you can see from my definitions I export definition for every `on` variant as separate function. Which allows you to provide different callback parameter type. Which is kind of nice for autocomplete in IDEs.

https://github.com/mauron85/react-native-background-geolocation/blob/master/index.d.ts#L673

**Comment by djereg** [comment]
When I created the type definitions, tried following the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) "rules". In other words, checked many popular definitions and tried to make some similar. 

> Also one thing. As you can see from my definitions I export definition for every on variant as separate function.
Yes of course, I was saw it and was a good idea, like it.

**Comment by djereg** [comment]
@mauron85  `desiredAccuracy` can be other then `0` `100` `1000` `10000`? E.g. 59?

**Comment by mauron85** [comment]
Yes, in theory. In practice no, because native platform providers doesn't support exact value. But plugin will map accuracy to nearest possible. Eg 59 => 100m. So user can put arbitrary safe integer.

**Comment by djereg** [comment]
Because I'm thinking on Literal Type for this property, limiting only specific values.

```typescript
type AccuracyLevel = 0 | 100 | 1000 | 1000;

{
  desiredAccuracy?: AccuracyLevel;
}
```

So there is "no chance" settings other values, but I think when someone set this property value, he will do it on the reasonable way.
```typescript
{
  desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY
}
```

**Comment by mauron85** [comment]
Let's keep it as number for now. We can change it later. Maybe to smaller numbers 0,1,2,3 or strings to reduce confusion that desiredAccuracy is not exact.

**Comment by mauron85** [comment]
Because even know, there is no guarantee that [ACCURACY_MEDIUM](https://developer.android.com/reference/android/location/Criteria.html#ACCURACY_MEDIUM) is actually 100m as mapped in [RawLocationProvider.java](https://github.com/mauron85/background-geolocation-android/blob/ff789439439b4b943a410a8e071843134a7c66a8/src/main/java/com/marianhello/bgloc/provider/RawLocationProvider.java#L118). Same for other accuracy and also probably same for iOS.

This is just leftover from project I've forked this from.

**Comment by djereg** [comment]
Okay, will keep as number.

For the future, string literals would be better, like log levels.
```typescript
// current
type LogLevel = 'TRACE' | 'DEBUG' | 'INFO' | 'WARN' | 'ERROR';

// in future
type LocationProvider = 'DISTANCE' | 'ACTIVITY' | 'RAW';
type AccuracyLevel= 'HIGH' | 'MEDIUM' | 'LOW' | 'PASSIVE';
type ServiceMode = 'FOREGROUND' | 'BACKGROUND';
```
Because the next is stupid, but working example.
```typescript
{
  locationProvider: BackgroundGeolocation.FOREGROUND_MODE,
  desiredAccuracy: BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,
}
```
It is difficult to avoid human stupidity, but it is not required in all situations, like this, because the user configures the plugin for own use.

**Comment by mauron85** [comment]
>For the future, string literals would be better, like log levels.

well. numbers were meant to be more like Enum. But since there is no types checking in vanilla js, that can lead to absurds like you pointed out. Even we had used string literals, one had to use typescript, meaning that you can't prevent 100% people to not shoot in the foot no matter what you do.

**Comment by mauron85** [comment]
Closing this as resolved with PR https://github.com/mauron85/react-native-background-geolocation/pull/314. Thanks.
