### ISSUE TITLE
How can I disable the notification on android both background and foreground?

### ISSUE THREAD

**Issue by thaimauit** [mauron85/react-native-background-geolocation#315]
When i set startForeground: false the notification was disabled on foreground. But when i let app to background, the notification show again. How can i disable it?

**Comment by mauron85** [comment]
You can’t. The notification is required for plugin  to work in background.

**Comment by ccoeder** [comment]
I have the same issue, why we can't disable it?

**Comment by mauron85** [comment]
This exact question has been asked many times here. Please try use search to find an answer. It's exhausting to repeat myself so many time. Marking as duplicate.

**Comment by ventr1x** [comment]
Then why is there no option whatsoever to disable it anyway? What is the reasoning behind this besides being stubborn and then complaining that people ask about it? Especially with multiple flags for notifications that obviously confuse people.
So what if it might not work (always) in background? A simple correctly documented flag should not be that much work? I'd even donate something if such little things wouldn't cause such big issues (I have a client which does not want the notification and is fine with it not always working in background).
