### ISSUE TITLE
App Crashes when entering / leaving Background

### ISSUE THREAD

**Issue by SeScherer** [mauron85/react-native-background-geolocation#319]
## Your Environment
* Plugin version: 3.0.0-alpha.43
* Platform: Android
* OS version: 8.1.0
* Device manufacturer and model:

* Running in Simulator: No
* Plugin configuration options: 
locationProvider: 1, // hint I could probably do with DISTANCE_FILTER_PROVIDER instead
                desiredAccuracy: 0, 
                stationaryRadius: 25,
                distanceFilter: 20,
                notificationTitle: 'Tracking position in the background',
                notificationText: 'enabled',
                debug: false,
                interval: 10000,
                fastestInterval: 5000,
                activitiesInterval: 5000,
                stopOnTerminate: false, 
                startOnBoot: false, 
                startForeground: true,
                pauseLocationUpdates: false,
                stopOnStillActivity: false, 
                saveBatteryOnBackground: false, 
## Context
I'm using this plugin to track user location while the app is in Background, everything works fine while i only close the application but keep the screen of the device active. As soon as is start using the screen lock hardware button the plugin sometimes receives an error, this leads to an application crash. 

## Expected Behavior
do not crash after entering lock screen

## Actual Behavior
crashes after entering lock screen

## Steps to Reproduce

1. start Logging with this config
2. Use screen Lock hardware Button 
3. after Resuming to app the crash occurs 

## Context
i need to get the geolocation always, ( screen lock, app paused, app foreground...) 

## Debug logs
11-09 12:28:31.764: E/ActivityThread(31819): Service com.marianhello.bgloc.LocationService has leaked IntentReceiver com.marianhello.bgloc.provider.ActivityRecognitionLocationProvider$1@f835c92 that was originally registered here. Are you missing a call to unregisterReceiver()?
11-09 12:28:31.764: E/ActivityThread(31819): android.app.IntentReceiverLeaked: Service com.marianhello.bgloc.LocationService has leaked IntentReceiver com.marianhello.bgloc.provider.ActivityRecognitionLocationProvider$1@f835c92 that was originally registered here. Are you missing a call to unregisterReceiver()?
11-09 12:28:31.764: E/ActivityThread(31819): 	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1503)
11-09 12:28:31.764: E/ActivityThread(31819): 	at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1231)
11-09 12:28:31.764: E/ActivityThread(31819): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1637)
11-09 12:28:31.764: E/ActivityThread(31819): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1610)
11-09 12:28:31.764: E/ActivityThread(31819): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:622)
11-09 12:28:31.764: E/ActivityThread(31819): 	at com.marianhello.bgloc.LocationService.registerReceiver(LocationService.java:479)
11-09 12:28:31.764: E/ActivityThread(31819): 	at com.marianhello.bgloc.provider.AbstractLocationProvider.registerReceiver(AbstractLocationProvider.java:80)
11-09 12:28:31.764: E/ActivityThread(31819): 	at com.marianhello.bgloc.provider.ActivityRecognitionLocationProvider.onCreate(ActivityRecognitionLocationProvider.java:53)
11-09 12:28:31.764: E/ActivityThread(31819): 	at com.marianhello.bgloc.LocationService.onStartCommand(LocationService.java:261)
11-09 12:28:31.764: E/ActivityThread(31819): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3995)
11-09 12:28:31.764: E/ActivityThread(31819): 	at android.app.ActivityThread.-wrap21(Unknown Source:0)
11-09 12:28:31.764: E/ActivityThread(31819): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2021)
11-09 12:28:31.764: E/ActivityThread(31819): 	at android.os.Handler.dispatchMessage(Handler.java:109)
11-09 12:28:31.764: E/ActivityThread(31819): 	at android.os.Looper.loop(Looper.java:166)
11-09 12:28:31.764: E/ActivityThread(31819): 	at android.app.ActivityThread.main(ActivityThread.java:7383)
11-09 12:28:31.764: E/ActivityThread(31819): 	at java.lang.reflect.Method.invoke(Native Method)
11-09 12:28:31.764: E/ActivityThread(31819): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
11-09 12:28:31.764: E/ActivityThread(31819): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
11-09 12:28:32.042: E/AndroidRuntime(31819): FATAL EXCEPTION: main
11-09 12:28:32.042: E/AndroidRuntime(31819): Process: de.geogame.eurokey, PID: 31819
11-09 12:28:32.042: E/AndroidRuntime(31819): java.util.concurrent.RejectedExecutionException: Task com.marianhello.bgloc.LocationService$PostLocationTask$1@8c58233 rejected from java.util.concurrent.ThreadPoolExecutor@3629f0[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
11-09 12:28:32.042: E/AndroidRuntime(31819): 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2078)
11-09 12:28:32.042: E/AndroidRuntime(31819): 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:843)
11-09 12:28:32.042: E/AndroidRuntime(31819): 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1389)
11-09 12:28:32.042: E/AndroidRuntime(31819): 	at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:620)
11-09 12:28:32.042: E/AndroidRuntime(31819): 	at com.marianhello.bgloc.LocationService$PostLocationTask.add(LocationService.java:561)
11-09 12:28:32.042: E/AndroidRuntime(31819): 	at com.marianhello.bgloc.LocationService.onLocation(LocationService.java:387)
11-09 12:28:32.042: E/AndroidRuntime(31819): 	at com.marianhello.bgloc.provider.AbstractLocationProvider.handleLocation(AbstractLocationProvider.java:100)
11-09 12:28:32.042: E/AndroidRuntime(31819): 	at com.marianhello.bgloc.provider.ActivityRecognitionLocationProvider.onLocationChanged(ActivityRecognitionLocationProvider.java:98)
11-09 12:28:32.042: E/AndroidRuntime(31819): 	at com.google.android.gms.internal.zzcfj.zzu(Unknown Source:4)
11-09 12:28:32.042: E/AndroidRuntime(31819): 	at com.google.android.gms.common.api.internal.zzci.zzb(Unknown Source:8)
11-09 12:28:32.042: E/AndroidRuntime(31819): 	at com.google.android.gms.common.api.internal.zzcj.handleMessage(Unknown Source:14)
11-09 12:28:32.042: E/AndroidRuntime(31819): 	at android.os.Handler.dispatchMessage(Handler.java:109)
11-09 12:28:32.042: E/AndroidRuntime(31819): 	at android.os.Looper.loop(Looper.java:166)
11-09 12:28:32.042: E/AndroidRuntime(31819): 	at android.app.ActivityThread.main(ActivityThread.java:7383)
11-09 12:28:32.042: E/AndroidRuntime(31819): 	at java.lang.reflect.Method.invoke(Native Method)
11-09 12:28:32.042: E/AndroidRuntime(31819): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
11-09 12:28:32.042: E/AndroidRuntime(31819): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
11-09 12:28:32.043: E/com.marianhello.logging.UncaughtExceptionLogger(31819): FATAL EXCEPTION: mainjava.util.concurrent.RejectedExecutionException: Task com.marianhello.bgloc.LocationService$PostLocationTask$1@8c58233 rejected from java.util.concurrent.ThreadPoolExecutor@3629f0[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
11-09 12:28:32.043: E/com.marianhello.logging.UncaughtExceptionLogger(31819): 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2078)
11-09 12:28:32.043: E/com.marianhello.logging.UncaughtExceptionLogger(31819): 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:843)
11-09 12:28:32.043: E/com.marianhello.logging.UncaughtExceptionLogger(31819): 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1389)
11-09 12:28:32.043: E/com.marianhello.logging.UncaughtExceptionLogger(31819): 	at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:620)
11-09 12:28:32.043: E/com.marianhello.logging.UncaughtExceptionLogger(31819): 	at com.marianhello.bgloc.LocationService$PostLocationTask.add(LocationService.java:561)
11-09 12:28:32.043: E/com.marianhello.logging.UncaughtExceptionLogger(31819): 	at com.marianhello.bgloc.LocationService.onLocation(LocationService.java:387)
11-09 12:28:32.043: E/com.marianhello.logging.UncaughtExceptionLogger(31819): 	at com.marianhello.bgloc.provider.AbstractLocationProvider.handleLocation(AbstractLocationProvider.java:100)
11-09 12:28:32.043: E/com.marianhello.logging.UncaughtExceptionLogger(31819): 	at com.marianhello.bgloc.provider.ActivityRecognitionLocationProvider.onLocationChanged(ActivityRecognitionLocationProvider.java:98)
11-09 12:28:32.043: E/com.marianhello.logging.UncaughtExceptionLogger(31819): 	at com.google.android.gms.internal.zzcfj.zzu(Unknown Source:4)
11-09 12:28:32.043: E/com.marianhello.logging.UncaughtExceptionLogger(31819): 	at com.google.android.gms.common.api.internal.zzci.zzb(Unknown Source:8)
11-09 12:28:32.043: E/com.marianhello.logging.UncaughtExceptionLogger(31819): 	at com.google.android.gms.common.api.internal.zzcj.handleMessage(Unknown Source:14)
11-09 12:28:32.043: E/com.marianhello.logging.UncaughtExceptionLogger(31819): 	at android.os.Handler.dispatchMessage(Handler.java:109)
11-09 12:28:32.043: E/com.marianhello.logging.UncaughtExceptionLogger(31819): 	at android.os.Looper.loop(Looper.java:166)
11-09 12:28:32.043: E/com.marianhello.logging.UncaughtExceptionLogger(31819): 	at android.app.ActivityThread.main(ActivityThread.java:7383)
11-09 12:28:32.043: E/com.marianhello.logging.UncaughtExceptionLogger(31819): 	at java.lang.reflect.Method.invoke(Native Method)
11-09 12:28:32.043: E/com.marianhello.logging.UncaughtExceptionLogger(31819): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
11-09 12:28:32.043: E/com.marianhello.logging.UncaughtExceptionLogger(31819): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
11-09 12:28:33.329: E/MemoryLeakMonitorManager(32457): MemoryLeakMonitor.jar is not exist!
11-09 12:28:33.330: E/Minikin(32457): Could not get cmap table size!

**Comment by mauron85** [comment]
Also try to reproduce on latest alpha. Some additional guards were added after alpha.43

**Comment by SeScherer** [comment]
testing on a Huawei p20 pro, configuration(as posted above) using @latest (3.0.0-alpha.47):

                locationProvider: 1, 
                desiredAccuracy: 0, 
                stationaryRadius: 25,
                distanceFilter: 20,
                notificationTitle: 'Tracking position in the background',
                notificationText: 'enabled',
                debug: false, 
                interval: 10000,
                fastestInterval: 5000,
                activitiesInterval: 5000,
                stopOnTerminate: false, 
                startOnBoot: false, 
                startForeground: true,
                pauseLocationUpdates: false,
                stopOnStillActivity: false,
                saveBatteryOnBackground: false,

register event listeners (typescript): 
BackgroundGeolocation.on('location', (location: IBackgroundGeolocationEvent): void => {
                    if (this.shouldUseBackgroundGeolocation) {
                        Logger.debugOut('BackgroundGeolocation: location event raised');
                        backgroundGeolocationOptions.events.location(location);
                    }
                });


The crash only occures cause i wanted to turn on the Background geolocation when entering Background, and turn it of when leaving background, if i dont do that the error doesnt occure.

Current ErrorLog when tunring on and off:
11-12 07:58:01.711: D/DeviceMonitor(1900): GPS request stop:de.geogame.eurokey pid:25856 interval(s): -1 reqId:db1b306
11-12 07:58:02.006: D/WorkSource(2137): Insert in WorkSource{} @ 0 uid 10189 name de.geogame.eurokey
11-12 07:58:02.012: W/ProcBatteryStats(1081): timer is not running , not stop, name: de.geogame.eurokey, uid: 10189, tag: NlpWakeLock
11-12 07:58:02.028: E/AndroidRuntime(25856): Process: de.geogame.eurokey, PID: 25856
11-12 07:58:02.047: W/ActivityManager(1081):   Force finishing activity de.geogame.eurokey/.MainActivity
11-12 07:58:02.285: W/InputDispatcher(1081): channel '4aca806 de.geogame.eurokey/de.geogame.eurokey.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
11-12 07:58:02.285: E/InputDispatcher(1081): channel '4aca806 de.geogame.eurokey/de.geogame.eurokey.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
11-12 07:58:02.306: I/WindowManager(1081): WIN DEATH: Window{4aca806 u0 de.geogame.eurokey/de.geogame.eurokey.MainActivity}
11-12 07:58:02.307: V/WindowManager(1081): removeIfPossible: Window{4aca806 u0 de.geogame.eurokey/de.geogame.eurokey.MainActivity} callers=com.android.server.wm.WindowState.-wrap1:0 com.android.server.wm.WindowState$DeathRecipient.binderDied:2601 android.os.BinderProxy.sendDeathNotice:856 <bottom of call stack> <bottom of call stack> 
11-12 07:58:02.307: W/InputDispatcher(1081): Attempted to unregister already unregistered input channel '4aca806 de.geogame.eurokey/de.geogame.eurokey.MainActivity (server)'
11-12 07:58:02.307: V/WindowManager(1081): postWindowRemoveCleanupLocked: Window{4aca806 u0 de.geogame.eurokey/de.geogame.eurokey.MainActivity}
11-12 07:58:02.307: V/WindowManager(1081): Removing Window{4aca806 u0 de.geogame.eurokey/de.geogame.eurokey.MainActivity} from AppWindowToken{5724bff token=Token{b99b71e ActivityRecord{3e36f59 u0 de.geogame.eurokey/.MainActivity t4401}}}
11-12 07:58:02.311: I/ActivityManager(1081): Process de.geogame.eurokey (pid 25856) has died: prcp FGS 
11-12 07:58:02.312: D/ActivityManager(1081): cleanUpApplicationRecord app: ProcessRecord{63ded4f 25856:de.geogame.eurokey/u0a189}, app.bad: false, restarting: false, allowRestart: true

**Comment by mauron85** [comment]
>The crash only occures cause i wanted to turn on the Background geolocation when entering Background, and turn it of when leaving background, if i dont do that the error doesnt occure.

Can you please post exact code, how you do that. I think I know what's going on, but need to be sure.

**Comment by SeScherer** [comment]
i was doing it this way : 
 BackgroundGeolocation.on('foreground', (): void => {
 BackgroundGeolocation.stop();
});
 BackgroundGeolocation.on('background', (): void => {
 BackgroundGeolocation.start();
});

**Comment by VivekSharma-zymr** [comment]
Facing the same issue, On moving to the map from my application the application is getting crash. Also, not showing any errors.

**Comment by mauron85** [comment]
Fixed in 0.5.0-alpha.49

**Comment by mauron85** [comment]
But before you start service in background you need to obtain user permission once or app will crash.
This is probably related to https://github.com/nishkarsh/android-permissions/issues/12.
After that issue will be closed, plugin will display permission notification that user can confirm without app crashing.

**Comment by mauron85** [comment]
FYI Fixed in 0.5.0-alpha.50 also fixed above mentioned crash!

**Comment by VivekSharma-zymr** [comment]
Using the configuration below. Also, After 15-20 mins on Android **POCO F1**  App closes automatic from the background.

- [ ]  desiredAccuracy: BackgroundGeolocation.LOW_ACCURACY, //Desired accuracy in meters. Possible values [HIGH_ACCURACY, MEDIUM_ACCURACY, LOW_ACCURACY, PASSIVE_ACCURACY]. Accuracy has direct effect on power drain. Lower accuracy = lower power drain.
- [ ]     stationaryRadius: 5, //Stationary radius in meters. When stopped, the minimum distance the device must move beyond the stationary location for aggressive background-tracking to engage.
- [ ]     distanceFilter: 10, // 10, meter , The minimum distance (measured in meters) a device must move horizontally before an update event is generated. 
- [ ]     notificationTitle: 'KX Trucker',
- [ ]     notificationText: 'Tracking your journey',
- [ ]     notificationsEnabled: true,
- [ ]     debug: false,
- [ ]     notificationIconSmall: "",
- [ ]     notificationIconLarge: "",
- [ ]     startOnBoot: false, //Start background service on device boot.
- [ ]     startForeground: true, //Android only, Allow location sync service to run in foreground state. Foreground state also requires a notification to be presented to the user.
- [ ]     stopOnTerminate: isAndroid ? false : true, //Enable this in order to force a stop() when the application terminated (e.g. on iOS, double-tap home button, swipe away the app).
- [ ]     locationProvider: BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,
- [ ]     interval: 29000, //  android only, The minimum time interval between location updates in milliseconds.  
- [ ]     fastestInterval: 29000, //android only, Fastest rate in milliseconds at which your app can handle location updates. 
- [ ]     activitiesInterval: 29000, //android only,Rate in milliseconds at which activity recognition occurs. Larger values will result in fewer activity detections while improving battery life.
- [ ]     stopOnStillActivity: false,
- [ ]     notificationIconColor: "Red",
- [ ]     enableHighAccuracy: true,
- [ ]     pauseLocationUpdates: false,
- [ ]     saveBatteryOnBackground: false,
- [ ]     maxLocations: 10000,
- [ ]     //Will uncomment later below 3 linew, If our B.E support locations array sent to server at once
- [ ]     syncThreshold: 100, //Specifies how many previously failed locations will be sent to server at once
- [ ]     // syncUrl: 'https://api.klearexpress.com/dev/v1/events',
- [ ]     syncUrl: "",
- [ ]     url: 'https://api.klearexpress.com/dev/v1/events',
- [ ]     // customize post properties
- [ ]     postTemplate: { "speed": "@speed", "time": "@time", "locationProvider": "@locationProvider", "longitude": "@longitude", "radius": "@radius", "bearing": "@bearing", "accuracy": "@accuracy", "provider": "@provider", "latitude": "@latitude", "altitude": "@altitude" }

**Comment by tSlappy** [comment]
I have the exactly same issue but I am using cordova-plugin-mauron85-background-geolocation spec="2.3.6"

How to fix this issue in that plugin version?
