### ISSUE TITLE
Disable all notifications.

### ISSUE THREAD

**Issue by VlCTORlOUS** [mauron85/react-native-background-geolocation#32]
## Environment

* Plugin version: "react-native-mauron85-background-geolocation": "^0.2.0-alpha.5"
* Platform: Android
* OS version: 7.0
* Device manufacturer and model: Motorola Nexus 6
* React Native version: "react-native": "^0.29.2"

## Context
This bug does not seem to be new (https://github.com/mauron85/react-native-background-geolocation/issues/3)

I also tried this approach (https://github.com/mauron85/react-native-background-geolocation/issues/29), which didn't help either

I also changed the debug value inside of `BackgroundGeolocationModule.java` to `false` to test this - didn't affect it in any way ... help please..

`./gradlew clean` and rebuild does not help either.

The Notification stays even after I manually close the App - the only thing that "helps" is to uninstall the App.

**UPDATE:**
Just looked through the README and found this `debug` description:

> When enabled, the plugin will emit sounds for life-cycle events of background-geolocation! See debugging sounds table.

So ... Is this really just for the debug sounds? Or is the part about "showing the notification" just missing in there?

**Comment by mauron85** [comment]
So did you tried options `startForeground: false`? `Debug: false` is basically for disabling debug sound and toast messages.

**Comment by VlCTORlOUS** [comment]
Yes, but as you said in https://github.com/mauron85/react-native-background-geolocation/issues/3 this approach isn't recommended because it is possible that the service would be killed if the resources are beeing needed elsewhere.

Nevertheless, I am now using `startForeground: false` because it seems that [Androids Notification](https://developer.android.com/reference/android/app/Notification.html) is completely independent and there is no possibility to "siply" hide or disable the shown Notification without causing the described effects

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 314 days. You may reopen this issue if it has been closed in error.
