### ISSUE TITLE
Build fails with minSdkVersion 18

### ISSUE THREAD

**Issue by kenobi91** [mauron85/react-native-background-geolocation#327]
## Your Environment

* Plugin version: 0.5.0-alpha.47 and 0.5.0-alpha.50
* Platform: Android
* OS version: /
* Device manufacturer and model: /

## Context

I linked everything as in the docs and tested it and it works great. Then I added additional package that requires me to set minSdkVersion to 18 (it was 16 before) and when I try to build android app I get this error:

error: invalid file path '/Users/kenan/My Projects/bikeHandlesV2/bikeHandles/node_modules/react-native-mauron85-background-geolocation/android/lib/build/intermediates/manifests/aapt/release/AndroidManifest.xml'.

Is there a possible workaround or something else that I am missing ?

## Expected Behavior

To be able to build app.

## Actual Behavior

Build fails with above lsited error.

## Possible Fix

/

## Steps to Reproduce

1. Make new project
2. Configure everything as described in documentation
3. Change minSdkVersion to 18
4. Try to build .apk 

## Context

This is blocker for me because i need other module to and it requires minSdkVersion to be 18.

**Comment by mauron85** [comment]
post full gradle error

**Comment by kenobi91** [comment]
Sorry issue resolved with latest version, i just deleted module from node_modules and install it again and build passes on version: 0.5.0-alpha.50
