### ISSUE TITLE
location, activity or stationary not fired in background mode.

### ISSUE THREAD

**Issue by manujbahl** [mauron85/react-native-background-geolocation#329]
## Your Environment

 * Plugin version:  React 0.5.0-alpha.42 

* Platform: iOS or Android  ios

* OS version:     12.1.1.
 
* Device manufacturer and model:  iPhone XS

* Running in Simulator:   NO

* React Native version:   0.55.4

* Plugin configuration options:   
         desiredAccuracy: 10,
            stationaryRadius: 10,
            distanceFilter: 10,
            debug: false,
            startOnBoot: true,
            stopOnTerminate: false,
            locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
            interval: 100,
            fastestInterval: 100,
            activitiesInterval: 100,
            stopOnStillActivity: false

* Link to your project:

## Context

I dont get the activity, location or stationary events when the app is in background. Running in the debugger works but when i publish the app in testflight and install via the app store the events do not get fired.

## Expected Behavior

Event should be fired.

## Actual Behavior

Events not fired.

## Steps to Reproduce

1.  Set up the plugin and publish on app store/itunes connect(testflight)
2.  Install the app via testflight
3.   Move around with app in background
4. no events were fired.

## Context

location tarcking.

**Comment by CallumCoombes** [comment]
I appear to have this on the emulator - debug mode triggers the debug Toast message on Android, but the `BackgroundGeolocation.on('location', (location)` callback does not trigger.

**Comment by gigby** [comment]
@CallumCoombes Hi! Did you found the solution? I faced the same issue and don't know what went wrong because this library was working perfectly complete months
