### ISSUE TITLE
continues track location changes when the app get closed

### ISSUE THREAD

**Issue by hamidjafari** [mauron85/react-native-background-geolocation#33]
hi
my app logs location whether app is on forground or background.
when app is on forground or goes background with android "Home" key (not back key) , everything works as expected.
but when the app closed with back key , callback for changing in location not gets fired anymore .

my code is :
`BackgroundGeolocation.on('location',location=>console.log(location))`
## Your Environment

* Plugin version:0.2.0-alpha.5
* Platform: Android
* OS version: 5
* Device manufacturer and model: genymotion
* React Native version:0.39.2
* Plugin configuration options:
`{
  desiredAccuracy: 100,
  stationaryRadius: 50,
  distanceFilter: 10,
  debug: false,
  locationProvider: BackgroundGeolocation.provider.ANDROID_DISTANCE_FILTER_PROVIDER,
  interval: 1000,
  fastestInterval: 100,
  stopOnStillActivity: false,
  stopOnTerminate: false,
  startForeground:false,
  maxLocations: 100,
}`

## Expected Behavior

expected location change callback fired even when the app is goes background with 'Back' key

**Comment by jpmermoz** [comment]
That event won't be fire if you close the app. It is attached to your app's activity.
You need to set the url option in BackgroundGeolocation.configure block so that way your app is going to POST to that url new positions, even if it's closed.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 277 days. You may reopen this issue if it has been closed in error.
