### ISSUE TITLE
Unable to build android project after adding  library.

### ISSUE THREAD

**Issue by prashant2016** [mauron85/react-native-background-geolocation#331]
Searched in the following locations:
    https://maven.google.com/com/android/tools/common/25.2.3/common-25.2.3.pom
    https://maven.google.com/com/android/tools/common/25.2.3/common-25.2.3.jar
    https://jcenter.bintray.com/com/android/tools/common/25.2.3/common-25.2.3.pom
    https://jcenter.bintray.com/com/android/tools/common/25.2.3/common-25.2.3.jar
Required by:
    project :react-native-mauron85-background-geolocation-common > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3
    project :react-native-mauron85-background-geolocation-common > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3 > com.android.tools.build:manifest-merger:25.2.3
    project :react-native-mauron85-background-geolocation-common > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3 > com.android.tools.ddms:ddmlib:25.2.3
    project :react-native-mauron85-background-geolocation-common > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3 > com.android.tools.analytics-library:shared:25.2.3
    project :react-native-mauron85-background-geolocation-common > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3 > com.android.tools.analytics-library:tracker:25.2.3
    project :react-native-mauron85-background-geolocation-common > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3 > com.android.tools:sdklib:25.2.3 > com.android.tools.layoutlib:layoutlib-api:25.2.3
    project :react-native-mauron85-background-geolocation-common > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3 > com.android.tools:sdklib:25.2.3 > com.android.tools:dvlib:25.2.3
    project :react-native-mauron85-background-geolocation-common > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3 > com.android.tools:sdklib:25.2.3 > com.android.tools:repository:25.2.3

**Comment by devbasil** [comment]
@prashant2016  Hi, can you please show your dependency settings under android/app/build.gradle and settings under android/build.gradle so i can be able to identify the problem, also please try and follow "issue template" so that  the community can be able to assist as well...

**Comment by prashant2016** [comment]
thanks for replying, I have fixed problem, its working fine in the simulator, but nor working in real device(not sending data to the server).

**Comment by prashant2016** [comment]
BackgroundGeolocation.on('location', (location) => {
            BackgroundGeolocation.startTask(taskKey => {
                this.setState({
                    isLoading: false,
                    latitude: location.latitude,
                    longitude: location.longitude,
                    region: {
                        latitude: location.latitude,
                        longitude: location.longitude,
                        latitudeDelta: 0.1,
                        longitudeDelta: 0.1,
                    },
                    error: null,
                });
                return fetch(`${Keys.BASE_URL}cabs-location/`, {
                    method: "post",
                    headers: {
                        Accept: "application/json",
                        "Content-Type": "application/json"
                    },
                    body: JSON.stringify({
                        cabId: this.state.user_id,
                        lat: location.latitude,
                        lng: location.longitude,
                        speed: location.speed,
                    })
                })
                BackgroundGeolocation.endTask(taskKey);
            });
        });

        BackgroundGeolocation.on('stationary', (stationaryLocation) => {
            Actions.sendLocation(stationaryLocation);
        });

        BackgroundGeolocation.on('error', (error) => {
            console.log('[ERROR] BackgroundGeolocation error:', error);
        });

        BackgroundGeolocation.on('start', () => {
            console.log('[INFO] BackgroundGeolocation service has been started');
        });

        BackgroundGeolocation.on('stop', () => {
            console.log('[INFO] BackgroundGeolocation service has been stopped');
        });

        BackgroundGeolocation.on('authorization', (status) => {
            console.log('[INFO] BackgroundGeolocation authorization status: ' + status);
            if (status !== BackgroundGeolocation.AUTHORIZED) {
                setTimeout(() =>
                    Alert.alert('App requires location tracking permission', 'Would you like to open app settings?', [
                        {text: 'Yes', onPress: () => BackgroundGeolocation.showAppSettings()},
                        {text: 'No', onPress: () => console.log('No Pressed'), style: 'cancel'}
                    ]), 1000);
            }
        });

        BackgroundGeolocation.on('background', () => {
            console.log('[INFO] App is in background');
        });

        BackgroundGeolocation.on('foreground', () => {
            console.log('[INFO] App is in foreground');
        });

        BackgroundGeolocation.on('abort_requested', () => {
            console.log('[INFO] Server responded with 285 Updates Not Required');
        });

        BackgroundGeolocation.on('http_authorization', () => {
            console.log('[INFO] App needs to authorize the http requests');
        });

        BackgroundGeolocation.checkStatus(status => {
            console.log('[INFO] BackgroundGeolocation service is running', status.isRunning);
            console.log('[INFO] BackgroundGeolocation services enabled', status.locationServicesEnabled);
            console.log('[INFO] BackgroundGeolocation auth status: ' + status.authorization);
            if (!status.isRunning) {
                BackgroundGeolocation.start(); //triggers start on start event
            }
        });
    }

**Comment by devbasil** [comment]
> thanks for replying, I have fixed problem, its working fine in the simulator, but nor working in real device(not sending data to the server).

Hi, if it works on an emulator and not working on a real device then its probably a port forwarding issue try this:  adb reverse tcp:8081 tcp:8081, **NOTE:** only do this  if you are developing on a localhost and connected the device using a USB cable, **HOWEVER** if your server is live (meaning publicly available) or you connected the device using the same wifi,  then you don't need to apply the above suggestion.

Also **IMPORTANT** check if the location icon is really active on your device, finally let me see your configuration settings BackgroundGeolocation.configure({  ..... ...... ...... }); 

And let me know if you are still having any issues..
