### ISSUE TITLE
Compatibility with React Native 0.40

### ISSUE THREAD

**Issue by Okipa** [mauron85/react-native-background-geolocation#34]
I upgraded RN to v0.40 and my project can't build anymore on iOS.
Would this be linked to the breaking changes of the version 0.40 ? https://github.com/facebook/react-native/releases/tag/v0.40.0

I precise that it worked well on RN v0.37.

However, it finds me 9 issues on the build in the RTCBackgroundGeolocation library.

# Problem #1
/node_modules/react-native/React/Base/RCTBridge.h:65:1: Duplicate interface definition for class 'RCTBridge'

# Problem #2
/node_modules/react-native/React/Base/RCTBridge.h:154:55: Property has a previous declaration
/node_modules/react-native/React/Base/RCTBridge.h:159:48: Property has a previous declaration
/node_modules/react-native/React/Base/RCTBridge.h:165:37: Property has a previous declaration
/node_modules/react-native/React/Base/RCTBridge.h:170:61: Property has a previous declaration
/node_modules/react-native/React/Base/RCTBridge.h:175:53: Property has a previous declaration
/node_modules/react-native/React/Base/RCTBridge.h:180:56: Property has a previous declaration
/node_modules/react-native/React/Base/RCTBridge.h:185:54: Property has a previous declaration
/node_modules/react-native/React/Base/RCTBridge.h:190:63: Property has a previous declaration

**Comment by mitch104** [comment]
@Okipa I have put in a pull request to fix this https://github.com/mauron85/react-native-background-geolocation/pull/35

Until this is merged you can use my fork of the repo https://github.com/mitch104/react-native-background-geolocation

**Comment by mauron85** [comment]
should be fixed in 0.2.0-alpha.6
