### ISSUE TITLE
Not working on background mode

### ISSUE THREAD

**Issue by Goraklogicaldna** [mauron85/react-native-background-geolocation#341]
## Your Environment

* Plugin version: ^0.5.0-alpha.50
* Platform: iOS or Android
* OS version:
* Device manufacturer and model:

* Running in Simulator:
* React Native version:
* Plugin configuration options: 
* Link to your project:

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Goraklogicaldna** [comment]
I use this plugin into react-native project. its working fine when application run or open into the background. But if application close from task manager plugin not work. this issue occurs on android above 8.0.

**Comment by xuancong84** [comment]
I have also tested it on Android 8.0 and above. It seems that the high-level RN code components (the listeners such as BackgroundGeolocation.on('location',()=>{}) ) and the low-level Android/IOS native code components (e.g., the debug toast) behaves separately.

The behaviour is that:
1. upon switching out (pressing HOME button or switching to another APP), both continue to function.
2. upon close (the square button followed by CLOSE or CLEAR ALL), the RN code components will stop running while the native code components continue to run.

FYI, I have taken all precautions:
1. in configure(), stopOnTerminate must be set to false; stopOnStillActivity must be set to false
2. in componentWillUnmount(), BackgroundGeolocation.removeAllListeners() must be commented out

To me, this plugin is merely a native implementation of the background geolocation, plus some linkage to RN. Unfortunately, only the native code components can run after APP close, the RN code components do not run after APP close. Thus, it is not of much usefulness.

**Comment by creativemind1** [comment]
Since the name itself says 'BackgroundGeolocation' which contains 'GeoLocation' so I'm wondering if it requires GPS or Location Permission for functioning of this module?

**Comment by karimkhamwani** [comment]
+1 @xuancong84 any work around?

**Comment by stenmuchow** [comment]
A work around for this would be to save the tracking status in redux persist, then you can fetch the status of the tracking when the app opens again.

**Comment by bilsak18** [comment]
So apparently there is no way for this to work if app is killed !

**Comment by lyseiha** [comment]
anything update?
