### ISSUE TITLE
the background service  doesn't working on IOS 

### ISSUE THREAD

**Issue by imansalhi** [mauron85/react-native-background-geolocation#347]
## Your Environment

* Plugin version: 0.5.0-alpha.50
* Platform: iOS 
* OS version:12.1
* Device manufacturer and model: iPhone SE
* Running in Simulator:
* React Native version: "0.57.8"
* Plugin configuration options: -
* Link to your project:

## Context
i have ran [this ](https://github.com/mauron85/react-native-background-geolocation)sample code(but  **stopOnTerminate: false,**) on IOS but some thing is not correct. the background service works for 4 or 5 time (not based on what i set for every 10 sec) and then i get:**BugReporting extraData** .
every thing works perfectly on android but on IOS...

## Expected Behavior
execute the process for every 10 secound 

## Actual Behavior
at first run (until i refresh the app or dismiss the error page) it shows 

> Action is not defined

on device as a red screen error. but the job works for 4 or 5 time frequently not base on what its set in config:    

> fastestInterval: 5000,
>       activitiesInterval: 10000,  

 

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

> RCTBackgroundGeolocation #configure
> App.js:198 is connected: true
> RCTLog.js:47 RCTBackgroundGeolocation #checkStatus
> App.js:152 [INFO] BackgroundGeolocation service is running false
> App.js:153 [INFO] BackgroundGeolocation services enabled true
> App.js:154 [INFO] BackgroundGeolocation auth status: 1
> RCTLog.js:47 RCTBackgroundGeolocation #start
> App.js:111 [INFO] BackgroundGeolocation service has been started
> RCTLog.js:47 RCTBackgroundGeolocation onLocationChanged
> 2RCTLog.js:47 RCTBackgroundGeoLocation activity changed
> RCTLog.js:47 RCTBackgroundGeolocation onStationaryChanged
> ExceptionsManager.js:76 Actions is not defined
> handleException @ ExceptionsManager.js:76
> handleError @ InitializeCore.js:69
> reportFatalError @ error-guard.js:42
> __guard @ MessageQueue.js:299
> callFunctionReturnFlushedQueue @ MessageQueue.js:105
> (anonymous) @ debuggerWorker.js:72
> RCTLog.js:47 RCTBackgroundGeolocation onLocationChanged
> ExceptionsManager.js:84 Unhandled JS Exception: Actions is not defined
> reactConsoleErrorHandler @ ExceptionsManager.js:84
> console.error @ YellowBox.js:59
> logToConsole @ RCTLog.js:47
> logIfNoNativeHook @ RCTLog.js:30
> __callFunction @ MessageQueue.js:349
> (anonymous) @ MessageQueue.js:106
> __guard @ MessageQueue.js:297
> callFunctionReturnFlushedQueue @ MessageQueue.js:105
> (anonymous) @ debuggerWorker.js:72
> infoLog.js:16 BugReporting extraData: {AppRegistry.runApplication1: "Running application "driver" with appParams: {"roo…warning are ON, performance optimizations are OFF"}
> infoLog.js:16 BugReporting extraData: {AppRegistry.runApplication1: "Running application "driver" with appParams: {"roo…warning are ON, performance optimizations are OFF"}
> infoLog.js:16 BugReporting extraData: {AppRegistry.runApplication1: "Running application "driver" with appParams: {"roo…warning are ON, performance optimizations are OFF"}
> infoLog.js:16 BugReporting extraData: {AppRegistry.runApplication1: "Running application "driver" with appParams: {"roo…warning are ON, performance optimizations are OFF"}
> infoLog.js:16 BugReporting extraData: {AppRegistry.runApplication1: "Running application "driver" with appParams: {"roo…warning are ON, performance optimizations are OFF"}

**Comment by sostenesg7** [comment]
Remove "Actions" from your code. This is a piece of code from example, will not work if you have no imported "Actions". Only ignore and put your code.
