### ISSUE TITLE
When I close the application and re-open it, the application hangs on the splash screen and does not start. I close and open a second time, everything works.

### ISSUE THREAD

**Issue by javadoffuad** [mauron85/react-native-background-geolocation#349]
## Your Environment

- desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
- stationaryRadius: 50,
- distanceFilter: 50,
- notificationTitle: 'Background tracking',
- notificationText: 'enabled',
- debug: true,
- startOnBoot: false,
- stopOnTerminate: true,
- saveBatteryOnBackground: false,
- locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
- interval: 10000,
- fastestInterval: 5000,
- activitiesInterval: 10000,
- stopOnStillActivity: false

* Plugin version:
* Platform: Android
* OS version: android 6.0
* Device manufacturer and model: Lenovo K10a40
* Running in Simulator: 
* React Native version: ^0.55.4
* Plugin configuration options: 
* Link to your project:

## Context
when I have the app in the foreground and in the background it works well but if I manually close the app and open again the app hangs on the splash screen and does not start. I close the app and open it second time the app works.
I dont get any problem when I dont use BackgroundGeolocation.start().

## Expected Behavior
The app keeps running and working foreground and background

My code:

![screenshot_4](https://user-images.githubusercontent.com/7090093/51385118-58e00500-1b2f-11e9-8e3a-584e3facade8.png)
![screenshot_5](https://user-images.githubusercontent.com/7090093/51385205-9cd30a00-1b2f-11e9-98eb-a8e0f4fc3f4d.png)
![screenshot_6](https://user-images.githubusercontent.com/7090093/51385245-becc8c80-1b2f-11e9-9f75-eebd11a69b8a.png)
![screenshot_7](https://user-images.githubusercontent.com/7090093/51385291-dc99f180-1b2f-11e9-9a8c-1a57a4e31030.png)

**Comment by javadoffuad** [comment]
In my case there was the problem at the splash screen.
I changed place of SplashScreen.hide().
The react-native-mauron85-background-geolocation library works well.

**Comment by sumesh1993** [comment]
@mauron85 getting the same issue on android ? what could be the cause ? any suggestions ??

**Comment by redwind** [comment]
i guess app hang on at splash screen cause sometime background location failed to bind exits service ( start from last open app). So tried to set
`stopOnTerminal:true`
and manual start it

**Comment by avilaeugeneb** [comment]
I also have this issue. @redwind 

Mine was behaving like this even if the phone newly installed the application.

**Comment by hemandpvkd** [comment]
just add 
  BackgroundGeolocation.stop()
on any entry pages (before BackgroundGeolocation.start() page calls)
