### ISSUE TITLE
Unable to run Android tests

### ISSUE THREAD

**Issue by msmyrk-swiftfare** [mauron85/react-native-background-geolocation#350]
## Your Environment

* Plugin version:
* Platform: Android
* OS version:
* Device manufacturer and model:

* Running in Simulator:
* React Native version:
* Plugin configuration options: 
* Link to your project:

## Context

There's a unit test failing in react-native-mauron85-background-geolocation.  Based on the file comments, it looks like this is a known issue.  It has the test has been copied to the correct location (androidTest), but that the original was never removed.

## Expected Behavior
Tests should run and pass.

## Actual Behavior
A test in react-native-mauron85-background-gealocation 

## Possible Fix

Remove android/lib/src/test/java/com/marianhello/bgloc/react/ConfigMapperTest.java.  

(P.R. incoming)

## Steps to Reproduce

1. Create a new react native app.
2. "yarn add react-native-mauron85-background-geolocation"
3. "cd android; ./gradlew testDebug"

**Comment by mauron85** [comment]
Is this really necessary? I like to keep that file as reference. Specially comments in the beginning are result of soul-destroying experience. I think you can override running tests in manifest or gradle option.

**Comment by mauron85** [comment]
I accept adding Ignore declaration (if you're willing to adjust your PR).

http://junit.sourceforge.net/javadoc/org/junit/Ignore.html

**Comment by msmyrk-swiftfare** [comment]
Yep, that also works for me.  Will adjust my PR.

>
