### ISSUE TITLE
Cannot evaluate module react-native-mauron85-background-geolocation : Configuration with name 'default' not found.

### ISSUE THREAD

**Issue by rakeshiitd** [mauron85/react-native-background-geolocation#36]
Hi,
I am getting this issue while running on my emulator 
Cannot evaluate module react-native-mauron85-background-geolocation : Configuration with name 'default' not found.

Any kind of help would be highly appreciated. Thanks in advance.

**Comment by newbiepub** [comment]
Maybe it was a mistake when you run react-native link 
Try this at your settings.gradle file : 
`include ':react-native-mauron85-background-geolocation', ':app'
project(':react-native-mauron85-background-geolocation').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-mauron85-background-geolocation/android/lib')`

**Comment by juanmanuelarze** [comment]
i have this issue, solve it with rnpm unlink react-native-mauron85-background-geolocation, and link it manually

**Comment by satishmane** [comment]
Hi,
I am facing same issue. I tried both react-native link and manully adding to settings.gradle and build gradle. No luck.

**Comment by satishmane** [comment]
Add lib folder at the end after android, worked.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 244 days. You may reopen this issue if it has been closed in error.
