### ISSUE TITLE
Background service not sending location when app is terminated

### ISSUE THREAD

**Issue by hunzalashakeel1996** [mauron85/react-native-background-geolocation#361]
service work fine  but when i terminate app it send post req to my **url** but not sending body it log undefined when **console** req.body. and i want to use headlessTask but i also not working that function not even execute.
`BackgroundGeolocation.configure({
      stopOnTerminate: false,
      distanceFilter: 8,
      interval: 1000,
      fastestInterval: 1000,
      url: 'http://192.168.4.107:3000/locations',
      postTemplate: {
        lat: '@latitude',
        lon: '@longitude',
        foo: 'bar' // you can also add your own properties
      },
    });`
`BackgroundGeolocation.startTask(taskKey => {
          //this.socket = io(`http://192.168.1.124:3000`);
          this.socket.emit('console', `change location${location}`);
          fetch('http://192.168.1.124:3000/this')
          // execute long running task
          // eg. ajax post location
          // IMPORTANT: task has to be ended by endTask
          BackgroundGeolocation.endTask(taskKey);
        });`

all above methods are inside **componentDidMount** 

## Your Environment

* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer and model:

* Running in Simulator:
* React Native version:
* Plugin configuration options: 
* Link to your project:

## Steps to Reproduce

1.
2.
3.
4.

**Comment by lyseiha** [comment]
anything update?
