### ISSUE TITLE
App suddenly crashed in androiod

### ISSUE THREAD

**Issue by roysG** [mauron85/react-native-background-geolocation#362]
* 0.5.3 -  react-native-background-geolocation
* Android 8
* Huwaweii 
react-native-cli: 1.0.0
react-native: 0.58.3

App Suddenly Crashed.

## Debug logs
IntentService[JobRescheduleService]java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.concurrent.CountDownLatch.countDown()' on a null object reference

**Comment by mauron85** [comment]
Not sure. But I would say you're calling getCurrentLocation and before location was retrieved, app was killed or something like that.

**Comment by roysG** [comment]
Solved my problem

**Comment by habibridho** [comment]
@roysG How did you solve it?

**Comment by TamasFarago** [comment]
> Solved my problem

How did you fix it?
