### ISSUE TITLE
Is this lib supposed to work when iOS app is killed (swiped up)

### ISSUE THREAD

**Issue by pie6k** [mauron85/react-native-background-geolocation#363]
I've tried to search for other issues about my question here (and there are plenty of them)ut I couldn't find a clear answer if this lib is supposed to work when the app is force-closed (swiped up from apps manager) on iOS.

I'm having such config

```ts
  BackgroundGeolocation.configure({
    desiredAccuracy: BackgroundGeolocation.MEDIUM_ACCURACY,
    stationaryRadius: 50,
    distanceFilter: 50,
    debug: false,
    startOnBoot: true,
    stopOnTerminate: false,
    stopOnStillActivity: false,
    locationProvider: BackgroundGeolocation.RAW_PROVIDER,
    interval: 1000,
    fastestInterval: 5000,
    activitiesInterval: 1000,
    url: `SOME_URL`,
    postTemplate: {
      // ...
    },
  });
```

and it works well when the app is active or in the background (ie. returned to home screen), but when the app is hard-closed - location is not tracked anymore (I've waited for 30mins to be sure if there are any low-priority updates)

So I'm not sure if should I still try, or if it's not possible with this lib (if so, it could be clearly stated in the readme as I believe it'd save many hours for many people)

**Comment by jimji1005** [comment]
not much works when app is -killed-
