### ISSUE TITLE
Background Tracking Stop After Inactivity

### ISSUE THREAD

**Issue by divyasundar12** [mauron85/react-native-background-geolocation#367]
Hi, Sir
Background Tracking Stop After 6 minute if the app is minimized mode. Please Help Me.

**Comment by TecladistaProd** [comment]
Did you have any success? if yes, please send how. if not please send the piece of code you configure BackgroundGeolocation

**Comment by chapa** [comment]
Hello,

I'm also facing this problem, tracking stop after some time of inactivity and resume too late (sometimes up to 30 minutes after the phone begin to move).
Did you ever heard of that problem before ?

If it could help, here's how I configure BackgroundGeolocation :
```js
BackgroundGeolocation.configure({
  activitiesInterval: 5000,
  desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
  distanceFilter: 0,
  fastestInterval: 5000,
  interval: 5000,
  locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
  startForeground: true,
  stationaryRadius: 0
})
```

Oh, I just notice I'm using the `ACTIVITY_PROVIDER` (like in the [Quick example](https://github.com/mauron85/react-native-background-geolocation#quick-example) from the README), but it seems it doesn't support `distanceFilter` and `stationaryRadius` options if I understand well the [configure options table](https://github.com/mauron85/react-native-background-geolocation#configureoptions-success-fail).

Do you think it can be related ?

**Comment by jacobbeasley** [comment]
A few things to check: 
1) Does user's device have power save mode enabled? 
2) Does user's device optimize background app data usage? (ie - will it cut your apps' access to the internet off)

**Comment by jacobbeasley** [comment]
We ended up adding a troubleshooting interface to our app that asks them to disable battery saver, whitelist our app in power optimization, and grant our app unrestricted access to the internet (so it didn't lose access in the background). Also, make sure your app has foreground permissions and is set to startForeground.
