### ISSUE TITLE
[QUESTION] Request on location event is a anti-pattern?

### ISSUE THREAD

**Issue by WandersonAlves** [mauron85/react-native-background-geolocation#368]
## Your Environment

* Plugin version: 0.5.3
* Platform: Android
* OS version: 9
* Device manufacturer and model: Samsung S8
* Running in Simulator: No
* React Native version: 0.56
* Plugin configuration options: 
```javascript
BackgroundGeolocation.configure({
      startOnBoot: true,
      startForeground: true,
      stopOnTerminate: false,
      notificationTitle: 'Some text',
      desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
      notificationText: '',
      stationaryRadius: 10,
      distanceFilter: 5,
    });
```
* Link to your project:

## Context
Currently, i don't use the `options.url` attribute to do some request with this lib. Instead, i use Location Event, like this:

```javascript
BackgroundGeolocation.on("location", ({latitude, longitude}) => {
      console.log('[INFO] BackgroundGeoLocation location:', latitude, longitude);
      this.getNearbyClients(latitude, longitude);
    });
```

This approach have any downsides or create problems? First time using your lib, and my approach is working as expected

**Comment by djereg** [comment]
I am using the lib like you, the url is not set, but doing some logic in callback function. Processing the location data, updating state variables and sending the coors if needed. 

Only one important thing, what do not forget:
```js
BackgroundGeolocation.on('location', (location) => {
  // handle your locations here
  // to perform long running operation on iOS
  // you need to create background task
  BackgroundGeolocation.startTask(taskKey => {
    // execute long running task
    // eg. ajax post location
    // IMPORTANT: task has to be ended by endTask
    BackgroundGeolocation.endTask(taskKey);
  });
});
```

**Comment by WandersonAlves** [comment]
Currently, we don't support iOS right now.

`startTask` is iOS only? I can't find anything about this on the README :(
Sometimes, i have the feeling that my app is "freezed" while on background after i put foreground location. Maybe this would help.

Thanks man!
