### ISSUE TITLE
Force Closing IOS Simulator is not sending location updates

### ISSUE THREAD

**Issue by mailyokesh** [mauron85/react-native-background-geolocation#369]
## Your Environment

* Plugin version: 0.5.3
* Platform: iOS 
* OS version: 12.2
* Device manufacturer and model:

* Running in Simulator: Yes
* React Native version: 0.58.6

BackgroundGeolocation.configure({
            desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
            stationaryRadius: 50,
            distanceFilter: 50,
            notificationTitle: "Background tracking",
            notificationText: "enabled",
            debug: false,
            startOnBoot: false,
            stopOnTerminate: false,
            locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
            interval: 10000,
            fastestInterval: 5000,
            activitiesInterval: 10000,
            stopOnStillActivity: false
})

## Context
Force closed the IOS simulator and I stopped getting location updates

## Expected Behavior
Since I had  stopOnTerminate: false I was expecting this to send location updates when app is force closed. 

## Actual Behavior
would expect the plugin to keep sending location updates

**Comment by AwabIjaz** [comment]
Same issue. Were you able to resolve this?

**Comment by VanHop94** [comment]
up
