### ISSUE TITLE
Permission alert opens before service has started

### ISSUE THREAD

**Issue by mernit** [mauron85/react-native-background-geolocation#370]
The "allow location" popup opens automatically at app startup before the user has a change to manually set their app permissions.

## Your Environment

* Plugin version: 2.13.3
* RN version: 0.55.3
* Platform: iOS

* Running in Simulator: Yes
* React Native version: Yes
* Plugin configuration options: Yes
* Link to your project:

## Context

The app is requesting location authorization permission before the background geolocation service has started. 

## Expected Behavior

The permissions alert should not be displayed until the user manually clicks a button to request background location permissions. 

## Actual Behavior

The location request alert opens immediately upon app startup.

## Steps to Reproduce

1.
2.
3.
4.

## Context

I have a page in my app to allow a user to manually configure each required permission. Because the location alert appears before the user has a change to reach this page, I am unable to display the "enable background location" popup, as iOS only allows it to be displayed once.

**Comment by walterdl** [comment]
@mernit how did you solve it? I want to manually request permissions by myself. Also, do you need the `ACCESS_BACKGROUND_LOCATION`?
