### ISSUE TITLE
thank you for your awsome work. i wonder can you write same thing in flutter as well? because there is no background geolocation in flutter

### ISSUE THREAD

**Issue by evangelme** [mauron85/react-native-background-geolocation#375]
## Your Environment

* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer and model:

* Running in Simulator:
* React Native version:
* Plugin configuration options: 
* Link to your project:

## Steps to Reproduce

1.
2.
3.
4.

**Comment by mauron85** [comment]
Sorry, no interest in flutter, but such a plugin can be build on top of 
https://github.com/mauron85/background-geolocation-android
and
https://github.com/mauron85/background-geolocation-ios

(Both cordova and react-native plugins are using those).
