### ISSUE TITLE
Activity_Provider not triggering activity or stationary events on Android

### ISSUE THREAD

**Issue by Mattimus333** [mauron85/react-native-background-geolocation#377]
Pretty much what the title says.  I'm using the activity provider and never seeing activity or stationary events being triggered.  Apologies in advance if I'm missing something obvious.  I set the locationProvider to the Activy_Provider(1).  I set activities to fire every 30 seconds.  I get location updates.  I never see activities nor stationary events.  I've set up the app to console.warn these to me.  

```   
 BackgroundGeolocation.on("activity", activity => {
      console.warn("Activity: ", activity);
      console.log("[DEBUG] BackgroundGeolocation activity:", activity);
    });
```

## Your Environment

* Plugin version: .53
* Platform: Android
* OS version:  Android 28
* Device manufacturer and model:  Pixel 2

* Running in Simulator:  NO
* React Native version:  .57.7
* Plugin configuration options: 
* Link to your project:  Using the example project linked in the readme.  Pretty much only difference is I added a listener for activities.  

## Context

I'm using the example app and trying to get the stationary and activity events to fire with activity_provider but they never do.  I'm not sure why?  

## Expected Behavior
These events should fire.  

## Actual Behavior
They don't.  

## Possible Fix
???

## Steps to Reproduce

1.  Use the example project
2.  Set up an activity listener.  
3.  Switch to activity provider
4.  Make activity events fire every 30 seconds
5.  turn tracking on.

**Comment by Mattimus333** [comment]
Wondering if there are any updates on this issue or anyone else has experienced it?

**Comment by cypherfunk** [comment]
Yes. I'm also not getting activity nor stationary events on Android when using the activity_provider.

**Comment by cypherfunk** [comment]
it's a bug in the library. I've patched it and will share the patch once I get some free time

**Comment by samchanCHS** [comment]
I did patch the library myself. For anyone interested, [here it is](https://github.com/samchan1995/background-geolocation-android/commit/a3de55cdfcfeb56ad2fd03b2e690fb12b604436e)

**Comment by bsor-dev** [comment]
@samchan1995 how was it? is it working to you? 

I found this causing duplicate of sending gps data to server when this set outside 

```
ActivityRecognition.getClient(mContext).requestActivityUpdates(
                    mConfig.getActivitiesInterval(),
                    detectedActivitiesPI
            );
            isWatchingActivity = true;
```
