### ISSUE TITLE
it is not working when app terminates (ios), and events is not fired on android.

### ISSUE THREAD

**Issue by hasanal1995** [mauron85/react-native-background-geolocation#379]
## react native
RN: 0.59.8
* Plugin version: 0.5.3
* Platform: iOS or Android

## Expected Behavior
in android should fire functions
and in ios should send location updates when app terminates

## Actual Behavior
function events not fired in android, and location updates not send in ios

**Comment by sujay-bidchat** [comment]
@mauron85 Yes, I am also getting this issue especially on Android. 

I am using the below listener to get location. But mostly I don't get any location and neither it throws any error. But if I check the status it shows as Running. ( BackgroundGeolocation.on('error', (error) => {
      console.log('[ERROR] BackgroundGeolocation error:', error);
    });
)
```
BackgroundGeolocation.on('location', (location) => {
}
BackgroundGeolocation.on('stationary', (stationaryLocation) => {
});
```

**Comment by Dhanraj-bidchat** [comment]
@hasanal1995 @sujay-bidchat I am also not getting any event on android.
Did you find solution to this?

**Comment by hasanal1995** [comment]
@Dhanraj-bidchat eventually no,
@mauron85  plz we need help here

**Comment by Dhanraj-bidchat** [comment]
@hasanal1995 
after upgrading I restarted android powered device and now its working for me.
Restarting device is not a better way though.

**Comment by hasanal1995** [comment]
sorry, clarify how to fix it plz?
in details @Dhanraj-bidchat

**Comment by Dhanraj-bidchat** [comment]
use this method and check if status is running:
 1. BackgroundGeolocation.checkStatus(status => {
      console.log('[INFO] BackgroundGeolocation service is running', status.isRunning);
      console.log('[INFO] BackgroundGeolocation services enabled', status.locationServicesEnabled);
      console.log('[INFO] BackgroundGeolocation auth status: ' + status.authorization);

      // you don't need to check status before start (this is just the example)
      if (!status.isRunning) {
        BackgroundGeolocation.start(); //triggers start on start event
      }
    });


2. if status is running then, you will get output in one of this methods:
 -> BackgroundGeolocation.on('stationary', (stationaryLocation) => {
      // handle stationary locations here
      console.log('[INFO] BackgroundGeolocation service is running', stationaryLocation);
    });

->  BackgroundGeolocation.on('location', (location) => {
      // handle your locations here
console.log('[INFO] BackgroundGeolocation service is running', location);
    });

**Comment by hasanal1995** [comment]
ok, i will try and tell you with updates.
thank U very much @Dhanraj-bidchat

**Comment by hasanal1995** [comment]
still not working bro @Dhanraj-bidchat 
on location updates not fires
