### ISSUE TITLE
Could not find any version that matches androidx.core:core:28.+.

### ISSUE THREAD

**Issue by nahidmbstu** [mauron85/react-native-background-geolocation#381]
Environment:
  OS: Linux 4.15
  Node: 8.15.0
  Yarn: 1.12.3
  npm: 6.4.1
  Watchman: 4.7.0
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

    "react-native-mauron85-background-geolocation": "^0.5.0-alpha.34",

Could not find any version that matches androidx.core:core:28.+.
     Versions that do not match:
         1.2.0-alpha02
         1.2.0-alpha01
         1.1.0-rc01
         1.1.0-beta01
         1.1.0-alpha05
         + 13 more

**Comment by metractive** [comment]
+1

**Comment by metractive** [comment]
Hey @nahidmbstu , I've resolved the issue by adding:

```
android.useAndroidX=true
android.enableJetifier=true
```

To the file `android/gradle.properties`

And executed the `androidx.sh` from this gist:
https://gist.github.com/janicduplessis/df9b5e3c2b2e23bbae713255bdb99f3c

Clean and build your project!

**Comment by cedced19** [comment]
@metractive where did you executed the script at the root of the project or at the root of the library ?

**Comment by metractive** [comment]
@cedced19 at the root of the project, because he iterates the `node_modules` folder.

**Comment by cedced19** [comment]
@metractive Thank you I found it and I forgot to come back here to say that it was good. It's perfect!
