### ISSUE TITLE
Unable to understand manual iOS setup instructions

### ISSUE THREAD

**Issue by nene** [mauron85/react-native-background-geolocation#387]
## Your Environment
* Plugin version: 0.5.3
* Platform: MacOS Mojave 10.14.5
* XCode: Version 10.2.1 (10E1001)

## Context
I'm trying to follow the manual installation steps (as the automatic ract-native-link installation failed).

The README tells me:
> In the XCode project navigator, select your project, select the Build Phases tab and in the Link Binary With Libraries section add libRCTBackgroundGeolocation.a

I'm pretty poor at navigating around XCode, and I'm unable to locate such a place in XCode UI.
I think this is the project navigator from which I'm supposed to select either the topmost item or the thing below it:

![Screenshot 2019-07-03 at 14 02 02](https://user-images.githubusercontent.com/118201/60586836-99f56a00-9d9b-11e9-9d0b-f5ee88f12267.png)

But no matter which I select, I don't see any "Build Phases" tab anywhere in the UI. Perhaps these instructions are about some older version of XCode?

## Possible Fix
I'm pretty new to the world of react-native and mobile development, but I've managed to install several libraries without any problems. The main difference being: none of them asked me to perform the installation using XCode, instead they provided code that I should include to `Podfile`.

So perhaps these installation instructions could be translated from the language of XCode to Podfile.

## Context
I was trying to install this library.

**Comment by mysport12** [comment]
Select your project in the left pane (the line above the one you have selected in your image). That will open the view in the middle pane of Xcode where you can see the Build Phases tab. Hope that helps
