### ISSUE TITLE
iOS - Header Search Paths Need Updating For Package Name Change

### ISSUE THREAD

**Issue by mysport12** [mauron85/react-native-background-geolocation#390]
## Your Environment

* Plugin version: 0.5.3
* Platform: iOS
* OS version: All
* Device manufacturer and model: Apple

* Running in Simulator: Yes
* React Native version: 0.60.0
* Plugin configuration options: Manual Linkage (React installed via CocoaPods)
* Link to your project:

## Context

The package name change created an additional level of hierarchy in the module folder structure which breaks the relative paths to the iOS headers specified in the Xcode project.
## Expected Behavior

Proper header search paths results in a successful build of the project.
## Actual Behavior

Build fails due to RCTBrdigeModule.h not being found
## Possible Fix

Update the header search paths specified in the Xcode project to include the extra layer of heirarchy

Example:
$(SRCROOT)/../../../ios/Pods/Headers/Public -> $(SRCROOT)/../../../../ios/Pods/Headers/Public

## Steps to Reproduce

1. Fresh install of this package
2. Follow steps in Readme for manual linkage (also added search paths to this package in my main project)
3. Clean Build Folder
4. Build project

## Context

Trying to upgrade from 0.5.2

**Comment by Arnaud-J** [comment]
I had the same problem, and tested what @mysport12 suggested, and it worked for me! (though I can not use it in production since I modified my node_modules manually).

@mauron85 here's the PR: #393
