### ISSUE TITLE
RCTBridgeModule.h file not found error on iOS

### ISSUE THREAD

**Issue by jagaa1103** [mauron85/react-native-background-geolocation#392]
## Your Environment
* Plugin version: ^0.5.3
* Platform: iOS
* OS version: macOS 10.14.5
* Device manufacturer and model: Macbook Pro
* Running in Simulator: Simulator and real device
* React Native version: 0.60
* Plugin configuration options: react-native.config.js added ios platform : null
* Link to your project: manual

## Context

When added manually plugin to iOS and build it's error in plugin RCTBridgeModule.h file not found error. 

## Expected Behavior

Android works well and only iOS has this issue.
## Actual Behavior

not working on iOS
## Possible Fix

I don't know

## Steps to Reproduce

1. add RCTBackgroundGeolocation.xcodeproj to Libraries folder in iOS project.
2. added libRCTBackgroundGeolocation.a to Link Frameworks and Libraries.
3. Build project

## Context
g logs
RCTBackgr
RCTBackgroundGeolocation/RCTBackgroundGeolocation.h:13:9: fatal error: 'RCTBridgeModule.h' file not found
#import "RCTBridgeModule.h"
        ^~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by jagaa1103** [comment]
I tried to change Header Search Paths but it's not a solution

**Comment by Arnaud-J** [comment]
@jagaa1103 I think this is the problem described in #390

**Comment by jagaa1103** [comment]
@Arnaud-J Thanks, works well :)

**Comment by stevenleeg** [comment]
I'm running into this issue as well, adding 

``` $(SRCROOT)/../../../ios/Pods/Headers/Public -> $(SRCROOT)/../../../../ios/Pods/Headers/Public```

didn't seem to solve the issue. Are there any other workarounds or did I miss something with the suggested fix in #390?

As an aside, I've been noticing these sorts of header issues in other projects as well—it seems to be this is a major issue plaguing the RN ecosystem right now (on iOS, at least).

**Comment by DanDance** [comment]
@stevenleeg are you sure you changing search paths of RCTBackgroundGeolocation project, not your project? In your project navigator select Libraries -> RCTBackgroundGeolocation -> Build Settings and find  Header Search Paths sections

**Comment by hugosbg** [comment]
Look at this: https://pasteboard.co/ItBStmr.png

If after the build, a message appears as  "**Metro Bundler has encountered an internal error**", do the following:

1. remove node_modules folder
2. clean all cache:
    - watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf $TMPDIR/metro* && rm -rf $TMPDIR/haste-*
    -  pod cache clean --all
    - npm cache clean --force
3. Reinstall node_modules "npm i"
4. Fix again as picture above

My Environment 

- Xcode: 10.1
- react: 16.8.6
- react-native: 0.60.4
- react-native-cli: 2.0.1

**Comment by NgocLe1001** [comment]
I download and add manually the [common folder](https://github.com/mauron85/react-native-background-geolocation/tree/master/ios) in the node module and it works. hic
