### ISSUE TITLE
Build failed on Android

### ISSUE THREAD

**Issue by MehrdadKhnzd** [mauron85/react-native-background-geolocation#394]
## Your Environment

* Plugin version: 0.5.3
* Platform: Android
* OS version: Windows 10
* Device manufacturer and model: Xiaomi Pocophone F1

* Running in Simulator:
* React Native version: 0.60.3
* Plugin configuration options: 
* Link to your project:

## Context

I used react-native-mauron85-background-geolocation in my app, with React Native 0.59 yesterday I decided to update my React Native to 0.60.3, and I knew that the new repository is @mauron85/react-native-background-geolocation so I change to this new repository and I used React Native 0.60.3 autolinking and I can't run it anymore on my device!
```
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Mehrdad\Desktop\Tozico\New\app\tozico\node_modules\@mauron85\react-native-background-geolocation\android\lib\build.gradle' line: 98

* What went wrong:
A problem occurred evaluating project ':@mauron85_react-native-background-geolocation'.
> Project with path ':@mauron85_react-native-background-geolocation-common' could not be found in project ':@mauron85_react-native-background-geolocation'.
```

## Expected Behavior

The app should be built correctly!

## Actual Behavior

react-native run-android fails!

## Steps to Reproduce

1. Just start a project, add this library and try to run it on Android.

**Comment by MehrdadKhnzd** [comment]
The problem is not with the new repository. It just not works with the new released React Native. There should be a Gradle upgrade problem. Can you fix this for the new React Native? @mauron85

**Comment by marchaos** [comment]
+1 Seeing the same issue, I'm on react 59.

**Comment by pocketcat** [comment]
Hey guys, I had the same problem but noticed that in my settings.grade I had only this:

`include ':@mauron85_react-native-background-geolocation'
project(':@mauron85_react-native-background-geolocation').projectDir = new File(rootProject.projectDir, '../node_modules/@mauron85/react-native-background-geolocation/android/lib')`

and was missing this:

`include ':@mauron85_react-native-background-geolocation-common'
project(':@mauron85_react-native-background-geolocation-common').projectDir = new File(rootProject.projectDir, '../node_modules/@mauron85/react-native-background-geolocation/android/common')`

as indicated in the installation guide.

Please check if this is your case too.

**Comment by prasan2421** [comment]
> Hey guys, I had the same problem but noticed that in my settings.grade I had only this:
> 
> `include ':@mauron85_react-native-background-geolocation' project(':@mauron85_react-native-background-geolocation').projectDir = new File(rootProject.projectDir, '../node_modules/@mauron85/react-native-background-geolocation/android/lib')`
> 
> and was missing this:
> 
> `include ':@mauron85_react-native-background-geolocation-common' project(':@mauron85_react-native-background-geolocation-common').projectDir = new File(rootProject.projectDir, '../node_modules/@mauron85/react-native-background-geolocation/android/common')`
> 
> as indicated in the installation guide.
> 
> Please check if this is your case too.

which RN version are you using?

**Comment by pocketcat** [comment]
> 
> which RN version are you using?

0.59

**Comment by MehrdadKhnzd** [comment]
The problem was with auto-linking and what @pocketcat said fixed the problem. Thanks!

**Comment by gabgomes** [comment]
Can anyone solve this problem? My RN version is 0.58.4

**Comment by tiendung19872005** [comment]
> > Hey guys, I had the same problem but noticed that in my settings.grade I had only this:
> > `include ':@mauron85_react-native-background-geolocation' project(':@mauron85_react-native-background-geolocation').projectDir = new File(rootProject.projectDir, '../node_modules/@mauron85/react-native-background-geolocation/android/lib')`
> > and was missing this:
> > `include ':@mauron85_react-native-background-geolocation-common' project(':@mauron85_react-native-background-geolocation-common').projectDir = new File(rootProject.projectDir, '../node_modules/@mauron85/react-native-background-geolocation/android/common')`
> > as indicated in the installation guide.
> > Please check if this is your case too.
> 
> which RN version are you using?

thank you, you save my time. I just add new line before 'project(':@mauron85_react-native-background....' in your quotation.

**Comment by prettydev** [comment]
How to do on the RN version 0.62.2?

**Comment by yo2rk** [comment]
> 
> 
> Hey guys, I had the same problem but noticed that in my settings.grade I had only this:
> 
> `include ':@mauron85_react-native-background-geolocation' project(':@mauron85_react-native-background-geolocation').projectDir = new File(rootProject.projectDir, '../node_modules/@mauron85/react-native-background-geolocation/android/lib')`
> 
> and was missing this:
> 
> `include ':@mauron85_react-native-background-geolocation-common' project(':@mauron85_react-native-background-geolocation-common').projectDir = new File(rootProject.projectDir, '../node_modules/@mauron85/react-native-background-geolocation/android/common')`
> 
> as indicated in the installation guide.
> 
> Please check if this is your case too.

I get the error:
 `Could not compile settings file 'C:\Users\User\<project name>\android\settings.gradle'.
> startup failed:
  settings file 'C:\Users\User\<project name>\android\settings.gradle': 4: expecting EOF, found '=' @ line 4, column 127.
     ound-geolocation').projectDir = new File`

my settings.gradle looks like: 
`rootProject.name = '<project name>'
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'
include ':@mauron85_react-native-background-geolocation' project(':@mauron85_react-native-background-geolocation').projectDir = new File(rootProject.projectDir, '../node_modules/@mauron85/react-native-background-geolocation/android/lib')
include ':@mauron85_react-native-background-geolocation-common' project(':@mauron85_react-native-background-geolocation-common').projectDir = new File(rootProject.projectDir, '../node_modules/@mauron85/react-native-background-geolocation/android/common')`

Thanks for your help (:

**Comment by ashishonmobile** [comment]
> How to do on the RN version 0.62.2?

has your problem got fixed?

**Comment by TVMD** [comment]
I has this problem on RN 0.62.2 too

**Comment by Bilal112** [comment]
same problem

**Comment by caolong0204** [comment]
i see this problem in RN 0.63.3 :((
How can i solve this issue

**Comment by TVMD** [comment]
I get over this error by following manual link for android and keep auto link for ios.

**Comment by caolong0204** [comment]
> I get over this error by following manual link for android and keep auto link for ios.

many tks

**Comment by bsor-dev** [comment]
Just include these in settings.gradle 

```
include ':@mauron85_react-native-background-geolocation-common'
project(':@mauron85_react-native-background-geolocation-common').projectDir = new File(rootProject.projectDir, '../node_modules/@mauron85/react-native-background-geolocation/android/common')
include ':@mauron85_react-native-background-geolocation'
project(':@mauron85_react-native-background-geolocation').projectDir = new File(rootProject.projectDir, '../node_modules/@mauron85/react-native-background-geolocation/android/lib')
```

**Comment by niraj-rahi-smartdata** [comment]
![Screen Shot 2022-10-10 at 5 40 27 PM](https://user-images.githubusercontent.com/76465694/194863422-1ee55960-e8cc-4156-8252-e4c818557437.png)
Path location in image (gradle.properties)
from : 
android.enableUnitTestBinaryResources=false
to 
android.enableUnitTestBinaryResources=true

**Comment by RanvijayChouhan12** [comment]
android.enableUnitTestBinaryResources=true

it is Alraedy true Still it Doesn't work for me
