### ISSUE TITLE
how to get location when app is killed in ios?

### ISSUE THREAD

**Issue by rishabh8456** [mauron85/react-native-background-geolocation#395]
## Your Environment

* Plugin version:^0.5.3
* Platform: iOS or Android --> IOS
* OS version:
* Device manufacturer and model:

* Running in Simulator: 
* React Native version: 0.59.9
* Plugin configuration options: 
* Link to your project:

## Steps to Reproduce

1.
2.
3.
4.

**Comment by lyseiha** [comment]
+1
