### ISSUE TITLE
Getting many issues in RN version 0.60.4, BackgroundGeolocation.stop(); not working and location tracking dropping every now and then.

### ISSUE THREAD

**Issue by prasan2421** [mauron85/react-native-background-geolocation#397]
## Your Environment

* Plugin version: 0.5.3
* Platform: Android
* OS version: 9
* Device manufacturer and model: oneplus 3

* Running in Simulator:
* React Native version: 0.60.4
* Plugin configuration options: 
* Link to your project:

## Context
actually i need to start the background location and record the location an send it to api every 5 minutes and then stop it in my command but after I start it sends the location but after sending location for few times it drops, and also after i stop it it doesn't stop as i still get background tracking enabled notification. The same code was working fine in RN version 0.57 earlier.

## Expected Behavior
send location to the api every 5 minutes as my time and shouldnt drop after some time. Also BackgroundGeolocation.stop(); should work. 

## Actual Behavior
after I start it sends the location but after sending location for few times it drops, and also after i stop it it doesn't stop as i still get background tracking enabled notification. The same code was working fine in RN version 0.57 earlier.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by prasan2421** [comment]
solved by changing  buildToolsVersion

**Comment by aaronofleonard** [comment]
What version did you change it to?
