### ISSUE TITLE
Source option 6 is no longer supported. Use 7 or later.

### ISSUE THREAD

**Issue by sefatunckanat** [mauron85/react-native-background-geolocation#399]
## Your Environment

* Plugin version: ^0.5.3
* Platform: Android
* OS version: 5.0

* Running in Simulator: Yes
* React Native version: 0.60.4

## Context
- new react project lastest version (0.60.4)
- yarn install current plugin
- react-native link not working
- try manual instalation
must i edit(downgrade) build version? 

## Expected Behavior
Successful debug and build

## Actual Behavior
```
> Task :@mauron85_react-native-background-geolocation-common:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
16 actionable tasks: 14 executed, 2 up-to-date
error: Source option 6 is no longer supported. Use 7 or later.
error: Target option 6 is no longer supported. Use 7 or later.

FAILURE: Build failed with an exception.
```

## Possible Fix
is support 0.60 autolink ?

**Comment by Baivaras** [comment]
Getting the same error. Did you manage to fix it? @sefatunckanat

**Comment by Baivaras** [comment]
@sefatunckanat by removing these compile options from `react-native-background-geolocation-common build gradle ` solved my issue. [See photo here ](https://www.evernote.com/shard/s501/client/snv?noteGuid=f1c5e18b-f0fc-4e5f-8e71-e19dbb86beb7&noteKey=689ae26098e35e34&sn=https%3A%2F%2Fwww.evernote.com%2Fshard%2Fs501%2Fsh%2Ff1c5e18b-f0fc-4e5f-8e71-e19dbb86beb7%2F689ae26098e35e34&title=issue%2Bwith%2BJavaVersion.Version%2Bon%2BGeolocation)

**Comment by sefatunckanat** [comment]
> @sefatunckanat by removing these compile options from `react-native-background-geolocation-common build gradle ` solved my issue. [See photo here ](https://www.evernote.com/shard/s501/client/snv?noteGuid=f1c5e18b-f0fc-4e5f-8e71-e19dbb86beb7&noteKey=689ae26098e35e34&sn=https%3A%2F%2Fwww.evernote.com%2Fshard%2Fs501%2Fsh%2Ff1c5e18b-f0fc-4e5f-8e71-e19dbb86beb7%2F689ae26098e35e34&title=issue%2Bwith%2BJavaVersion.Version%2Bon%2BGeolocation)

waoh !! thanks for help 

## Fix
node_modules/@mauron85/react-native-background-geolocation/android/common/build.gradle
delete line 117 & 118 @Baivaras 

```
compileOptions {
        // sourceCompatibility JavaVersion.VERSION_1_6
        // targetCompatibility JavaVersion.VERSION_1_6
}
```

**Comment by sarmad1995** [comment]
I don't think there is a permanent solution yet.

**Comment by mauron85** [comment]
This need to be addressed

**Comment by sarmad1995** [comment]
@mauron85  I added a PR in your Common repo for this.

**Comment by mauron85** [comment]
FYI: sourceCompatibility was removed in recent commits.

**Comment by joelchehdaynk** [comment]
In my case, the solution was to add the JAVA_HOME environment variable to the PATH. It seems that when I upgraded my mac OS, the configuration was broken.

Just check your java home and add JAVA_HOME path to the .**bashrch** or .**zshrc** file
/usr/libexec/java_home -V | grep jdk
EXAMPLE: /Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home
export JAVA_HOME=[java/path]
export PATH=$JAVA_HOME/bin:$PATH
