### ISSUE TITLE
Status / Plan of this fork

### ISSUE THREAD

**Issue by jesperbjerke** [mauron85/react-native-background-geolocation#4]
Hi! Amazing work of both of these plugins. Just wondering if you're planning on keeping this fork up to date with the cordova counterpart? Im trying to decide on goin with react native or cordova for my app, which will probably be using one of these :)

**Comment by mauron85** [comment]
The plan is to keep both updated. It's a fact that cordova is on faster track now. But priority might change in future in favour to react native.

**Comment by jesperbjerke** [comment]
Good to hear. Keep up the good work!
