### ISSUE TITLE
Unable to access location updates after app is killed and restarted

### ISSUE THREAD

**Issue by joshuakoh7** [mauron85/react-native-background-geolocation#401]
## Your Environment

* Plugin version: Current
* Platform: Android
* OS version: 9
* Device manufacturer and model:

* Running in Simulator: No
* React Native version: 0.59.3
* Plugin configuration options: 
* Link to your project:

## Context

    BackgroundGeolocation.configure({
      desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
      stationaryRadius: 50,
      distanceFilter: 100,
      notificationTitle: 'Background Location',
      notificationText: 'Monitoring location',
      debug: false,
      startOnBoot: true,
      stopOnTerminate: false,
      locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
      interval: 60000,
      fastestInterval: 5000,
      activitiesInterval: 20000,
      stopOnStillActivity: false,
      url: '***/api/user/location/',
      httpHeaders: {
        'Authorization': axios.defaults.headers.common['Authorization']
      },
      // customize post properties
      postTemplate: {
        latitude: '@latitude',
        longitude: '@longitude',
      //  foo: 'bar' // you can also add your own properties
      },
      maxLocations: 1000
    });
## Expected Behavior

When app is relaunched, background location tracking should terminate and foreground location tracking should be relaunched

## Actual Behavior

Location tracking stays as a background task and app now loses access to the location updates. Only works again by going to app manager to force stop the task.

## Steps to Reproduce

1. Kill app
2. Relaunch app

**Comment by sostenesg7** [comment]
when you swipe the app(closing) and keep the service working, your listeners will be losed. the simple solution is stop the background service and restart.
i do:
```javascript
componentDidMount()=>{
    BackgroundGeolocation.configure(...)
    BackgroundGeolocation.on('location', ...)
    BackgroundGeolocation.stop();
    BackgroundGeolocation.start();
}

**Comment by MurtazaEliyas** [comment]
@sostenesg7 I tried your solution but Relaunching does not load the app.
I am facing a similar issue as @joshuakoh7 
I have and empty react native app with the example code in the App.js. When launching for the first time background location is working fine. Once the app is killed from the recent apps screen, check status does not fire and app screen does not load.

**Comment by sostenesg7** [comment]
Can you please share your code?

**LIB VERSIONS**
 "@mauron85/react-native-background-geolocation": "^0.6.3",
 "react": "16.9.0",
 "react-native": "0.61.2"

**Phone: ANDROID 9, Real device**

i'd recorded my screen, look at : https://photos.app.goo.gl/6PLpyS7svG819Eo16  and tell me if is the expected behavior

bellow is my code and are working as expected.
when i enable bggeolocation and close app from recents, the service still working. When i click on notification and open the app, i can use checkstatus and get bggeolocation current running status. 
```
import React from 'react';
import {
  SafeAreaView,
  StyleSheet,
  ScrollView,
  View,
  Text,
  StatusBar,
  TouchableOpacity,
} from 'react-native';
import BackgroundGeolocation from '@mauron85/react-native-background-geolocation';

class App extends React.Component {
  state = {};
  componentDidMount() {
    BackgroundGeolocation.configure({
      desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
      stationaryRadius: 50,
      distanceFilter: 100,
      notificationTitle: 'Background Location',
      notificationText: 'Monitoring location',
      debug: false,
      startOnBoot: true,
      stopOnTerminate: false,
      locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
      interval: 60000,
      fastestInterval: 5000,
      activitiesInterval: 20000,
      stopOnStillActivity: false,
      url: '***/api/user/location/',
      httpHeaders: {},
      // customize post properties
      postTemplate: {
        latitude: '@latitude',
        longitude: '@longitude',
        //  foo: 'bar' // you can also add your own properties
      },
      maxLocations: 1000,
    });

    BackgroundGeolocation.checkStatus(status => {
      this.setState({isRunning: status.isRunning});
    });
  }

  render = () => (
    <View
      style={{
        flex: 1,
        justifyContent: 'center',
        alignContent: 'center',
        alignItems: 'center',
      }}>
      <TouchableOpacity
        onPress={() => {
          BackgroundGeolocation.checkStatus(status => {
            if (!status.isRunning) {
              BackgroundGeolocation.start();
            } else {
              BackgroundGeolocation.stop();
            }

            this.setState({isRunning: !status.isRunning});
            //alert(status.isRunning);
          });
        }}
        style={{
          backgroundColor: '#ffDD11',
          width: '100%',
          height: 40,
          alignItems: 'center',
        }}>
        <Text>{this.state.isRunning ? 'disable' : 'enable'}</Text>
      </TouchableOpacity>
    </View>
  );
}

export default App;

```

**Comment by MurtazaEliyas** [comment]
@sostenesg7 Thank you for the prompt reply. This is my App.js code.

`/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow
 */

import React, {Component} from 'react';
import {
  SafeAreaView,
  StyleSheet,
  ScrollView,
  View,
  Text,
  StatusBar,
  Alert,
} from 'react-native';

import {
  Header,
  LearnMoreLinks,
  Colors,
  DebugInstructions,
  ReloadInstructions,
} from 'react-native/Libraries/NewAppScreen';
import BackgroundGeolocation from '@mauron85/react-native-background-geolocation';
class App extends Component {
  constructor() {
    console.log('constructing');
    super();
  }
  componentDidMount() {
    console.log('Mounting');
    BackgroundGeolocation.configure({
      desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
      stationaryRadius: 50,
      distanceFilter: 50,
      notificationTitle: 'Background tracking',
      notificationText: 'enabled',
      debug: true,
      startOnBoot: true,
      stopOnTerminate: true,
      locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
      interval: 10000,
      fastestInterval: 5000,
      activitiesInterval: 10000,
      stopOnStillActivity: false,
      // url: 'http://192.168.81.15:3000/location',
      // httpHeaders: {
      //   'X-FOO': 'bar',
      // },
      // customize post properties
      // postTemplate: {
      //   lat: '@latitude',
      //   lon: '@longitude',
      //   foo: 'bar', // you can also add your own properties
      // },
    });

    BackgroundGeolocation.on('location', location => {
      // handle your locations here
      // to perform long running operation on iOS
      // you need to create background task
      BackgroundGeolocation.startTask(taskKey => {
        //   // execute long running task
        //   // eg. ajax post location
        //   // IMPORTANT: task has to be ended by endTask
        BackgroundGeolocation.endTask(taskKey);
      });
    });

    BackgroundGeolocation.on('stationary', stationaryLocation => {
      // handle stationary locations here
      // Actions.sendLocation(stationaryLocation);
    });

    BackgroundGeolocation.on('error', error => {
      console.log('[ERROR] BackgroundGeolocation error:', error);
    });

    BackgroundGeolocation.on('start', () => {
      console.log('[INFO] BackgroundGeolocation service has been started');
    });

    BackgroundGeolocation.on('stop', () => {
      console.log('[INFO] BackgroundGeolocation service has been stopped');
    });

    BackgroundGeolocation.on('background', () => {
      console.log('[INFO] App is in background');
    });

    BackgroundGeolocation.on('foreground', () => {
      console.log('[INFO] App is in foreground');
    });

    BackgroundGeolocation.checkStatus(status => {
      console.log(
        '[INFO] BackgroundGeolocation service is running',
        status.isRunning,
      );
      console.log(
        '[INFO] BackgroundGeolocation services enabled',
        status.locationServicesEnabled,
      );
      console.log(
        '[INFO] BackgroundGeolocation auth status: ' + status.authorization,
      );

      // you don't need to check status before start (this is just the example)
      if (!status.isRunning) {
        console.log('will start only');
        BackgroundGeolocation.start(); //triggers start on start event
      } else {
        console.log('will stop then start');
        BackgroundGeolocation.stop();
        BackgroundGeolocation.start();
      }
    });

    // you can also just start without checking for status
    BackgroundGeolocation.start();
  }

  componentWillUnmount() {
    // unregister all event listeners
    console.log('Unmounted');
    BackgroundGeolocation.removeAllListeners();
  }

  render() {
    return (
      <View>
        <Text>Hello World</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({});

export default App;
`

I will send you a screen capture of the case a little later.

**Comment by MurtazaEliyas** [comment]
@sostenesg7 I rebuilt the code so i can send a screen capture of the issue.. the code somehow started to work :s
I did not change anything in the code. It just started to work on its own. I also generated a signed apk and tested it works.. So i guess i will try the library in my original project and see..
will close this for now

**Comment by popstheman** [comment]
@sostenesg7 
This example is working fine. However, if you've installed "react-native-community/react-native-maps" library. The app crashes on 

`BackgroundGeolocation.start();`

**Comment by popstheman** [comment]
Never mind, it clearly states in the documentation to add the following in your android/build.gradle file if you're using react-native-maps.

`ext {
            googlePlayServicesVersion = "9.8.0"
        }`

**Comment by lyseiha** [comment]
How about iOS?

**Comment by lyseiha** [comment]
Hello?
