### ISSUE TITLE
null is not an object (evaluating 'RNBackgroundGeolocation.configure')

### ISSUE THREAD

**Issue by patofet** [mauron85/react-native-background-geolocation#402]
## Your Environment

* Plugin version: ^0.5.3
* Platform: Android real device
* OS version: MIUI Global 10.3.3 (Android 9)
* Device manufacturer and model: Xiaomi
* Running in Simulator: No
* React Native version: https://github.com/expo/react-native/archive/sdk-34.0.1.tar.gz
* Plugin configuration options:  I follow the guide
* Link to your project: -

I use expokit with expo start to test it

## Context

import BackgroundGeolocation from '@mauron85/react-native-background-geolocation';
componentDidMount() {
export default class AppContainer extends React.Component {
BackgroundGeolocation.configure({
		  desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
		  stationaryRadius: 50,
		  distanceFilter: 50,
		  notificationTitle: 'Background tracking',
		  notificationText: 'enabled',
		  debug: true,
		  startOnBoot: false,
		  stopOnTerminate: true,
		  locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
		  interval: 10000,
		  fastestInterval: 5000,
		  activitiesInterval: 10000,
		  stopOnStillActivity: false,
		  url: 'http://192.168.81.15:3000/location',
		  httpHeaders: {
			'X-FOO': 'bar'
		  },
		  // customize post properties
		  postTemplate: {
			lat: '@latitude',
			lon: '@longitude'
		  }
		});
}
}

## Expected Behavior
Not giving the error.

## Actual Behavior
Not work it appears an error on console: TypeError: null is not an object (evaluating 'RNBackgroundGeolocation.configure')

And in my device: TypeError: null is not an object (evaluating 'RNBackgroundGeolocation.configure')'

## Context
I'm trying to save in backgraund  the location of the user

## Debug logs
TypeError: null is not an object (evaluating 'RNBackgroundGeolocation.configure')
- node_modules\@mauron85\react-native-background-geolocation\index.js:84:28 in configure
* screens\notifications\AppContainer.js:48:34 in componentDidMount
- node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:15036:10 in commitLifeCycles
- node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:16636:8 in commitAllLifeCycles
- node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:93:15 in invokeGuardedCallbackImpl
- node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:318:36 in invokeGuardedCallback
- node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:16876:8 in commitRoot
- node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:18501:17 in <unknown>
- node_modules\scheduler\cjs\scheduler.development.js:255:23 in unstable_runWithPriority
- node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:18499:4 in completeRoot
- node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:18427:21 in performWorkOnRoot
- node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:18324:24 in performWork
- node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:18285:14 in performSyncWork
- node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:18169:19 in requestWork
- node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:17969:16 in scheduleWork
- node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:6934:17 in enqueueSetState
- node_modules\react\cjs\react.development.js:335:31 in setState
- node_modules\react-navigation\src\createNavigationContainer.js:190:22 in dispatch
* screens\SplashScreen.js:30:16 in <unknown>
- node_modules\promise\setimmediate\core.js:37:14 in tryCallOne
- node_modules\promise\setimmediate\core.js:123:25 in <unknown>
- ... 8 more stack frames from framework internals

**Comment by patofet** [comment]
If I do an react-native run-android instead of expo start, it can build succsesfull but when I open it in the simulator it give me:

Rejecting re-init on previously-failed class java.lang.Class<host.exp.exponent.network.ExponentNetwork$5>: java.lang.NoClassDefFoundError: Failed resolution of: Lexpolib_v1/okhttp3/Interceptor;
 Rejecting re-init on previously-failed class java.lang.Class<host.exp.exponent.network.ExponentNetwork$5>: java.lang.NoClassDefFoundError: Failed resolution of: Lexpolib_v1/okhttp3/Interceptor;
 Rejecting re-init on previously-failed class java.lang.Class<host.exp.exponent.network.ExponentNetwork$5>: java.lang.NoClassDefFoundError: Failed resolution of: Lexpolib_v1/okhttp3/Interceptor;
Caused by: java.lang.ClassNotFoundException: Didn't find class "expolib_v1.okhttp3.Interceptor" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/cat.vvv.xxx-N0jaFRlA2NRZqtY3S45jVA==/base.apk"],nativeLibraryDirectories=[/data/app/cat.vvv.xxx-N0jaFRlA2NRZqtY3S45jVA==/lib/x86, /data/app/cat.vvv.xxx-N0jaFRlA2NRZqtY3S45jVA==/base.apk!/lib/x86, /system/lib, /system/vendor/lib]]

**Comment by sostenesg7** [comment]
Did you eject the expo app? this library needs to be linked because uses native implementation for Android and IOS. Without eject expo will not work.

**Comment by praveenreddy9** [comment]
@sostenesg7 mine is also Expo Ejected Project getting the same error,
also i tried with Pure React Native it is also getting the same Error (TypeError: undefined is not an object (evaluating 'RNBackgroundGeolocation.configure')).
Can You Please help me to Resolve this issue.....

**Comment by patofet** [comment]
> Did you eject the expo app? this library needs to be linked because uses native implementation for Android and IOS. Without eject expo will not work.

Yes, I eject to expokit

**Comment by MurtazaEliyas** [comment]
Had this issue when I was running on a debug build on my device.. Reread the installation process.. Saw the automatic installation part.. its mentioned to run the following command

node ./node_modules/@mauron85/react-native-background-geolocation/scripts/postlink.js

Did that and the example code started to work for me

**Comment by olatollu** [comment]
read the installation process...

after installing the package, you need to do an automatic linking using node:

node ./node_modules/@mauron85/react-native-background-geolocation/scripts/postlink.js

then navigate to your IOS folder in your project directory and run the command:

pod install

worked for me.

**Comment by hazelf42** [comment]
having this issue

**Comment by mohammedelnady** [comment]
still ill

**Comment by EstefaniDavila** [comment]
![image](https://user-images.githubusercontent.com/76929037/176044441-08019434-537a-459d-a92d-31a43fc347e0.png)
helpme! :C

**Comment by sostenesg7** [comment]
> ![image](https://user-images.githubusercontent.com/76929037/176044441-08019434-537a-459d-a92d-31a43fc347e0.png) helpme! :C

Are you using expo?
What is the plugin version and RN version.
Can you provide the full source code of this file?
Are you requesting GPS permissions before request, and is the GPS enabled?
What is the value in origin variable?
With this answers we can try to help you.
