### ISSUE TITLE
How to use HIGH_ACCURACY for foreground and LOW_ACCURACY when in background/headless?

### ISSUE THREAD

**Issue by joshuakoh7** [mauron85/react-native-background-geolocation#403]
## Your Environment

* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer and model:

* Running in Simulator:
* React Native version:
* Plugin configuration options: 
* Link to your project:

## Expected Behavior

I need the user location to be high accuracy when the app is in foreground/minimized.
I would like to track location updates to a 3 decimal place accuracy (~111m) when the app is terminated and running headless.
Am I supposed to run two separately configured instances of BackgroundGeolocation?

## Steps to Reproduce

1.
2.
3.
4.

**Comment by olckara** [comment]
> Partial reconfiguration is possible by later providing a subset of the configuration options:
> ```
> BackgroundGeolocation.configure({
>   debug: true
> });
> ```
> In this case new configuration options will be merged with stored configuration options and changes will be applied immediately.
