### ISSUE TITLE
Need to install this package from master branch directly

### ISSUE THREAD

**Issue by WebMobi59** [mauron85/react-native-background-geolocation#405]
First of all, thanks for awesome package.  

I'd like to install this package from master branch into my project directly, but I am getting the error.

What I did:
I added this line to package.json.

> "@mauron85/react-native-background-geolocation": "git+https://github.com/mauron85/react-native-background-geolocation.git"

What I am getting:
![image](https://user-images.githubusercontent.com/20356023/62445977-2f698c80-b794-11e9-9511-35ba7a4bd992.png)

Please help me what I need to fix this issue.

**Comment by sostenesg7** [comment]
I did follow this steps and had no problem:  

> 1. Create a new project and navigate to project folder; 

> 2. Add "@mauron85/react-native-background-geolocation": "git+https://github.com/mauron85/react-native-background-geolocation.git" to package.json 

> 3. Run **_"react-native link"_**; 

> 4. And run _**"node ./node_modules/@mauron85/react-native-background-geolocation/scripts/postlink.js"**_; 

I tested on IOs and Android and all is ok;
Can you create a new project and test the steps above?
