### ISSUE TITLE
Cannot do manual linking on Android

### ISSUE THREAD

**Issue by Hyllesen** [mauron85/react-native-background-geolocation#406]
## Your Environment

* Plugin version: 0.5.3
* Platform: Android
* OS version: OS X
* Running in Simulator: Yes
* React Native version: 0.60.4
* Link to your project: [https://github.com/Hyllesen/AndroidBackgroundLocationTest](https://github.com/Hyllesen/AndroidBackgroundLocationTest
)
## Context
Fresh install of react-native init. 
The react-native link command doesn't work, when I try to do manual linking I get the error below.

`Native module BackgroundGeolocation tried to override BackgroundGeolocationModule. Check the getPackages() method in MainApplication.java, it might be that the module is being created twice.`

This is my MainApplication.getPackages():
```
    @Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
      // packages.add(new MyReactNativePackage());
      packages.add(new BackgroundGeolocationPackage());       
      return packages;
    }

```
![Screen Shot 2019-08-05 at 20 40 43](https://user-images.githubusercontent.com/9279498/62487430-1aa3ed80-b7c2-11e9-8cca-1deb845b81ac.png)

**Comment by Hyllesen** [comment]
![Screen Shot 2019-08-05 at 20 40 43](https://user-images.githubusercontent.com/9279498/62487419-0eb82b80-b7c2-11e9-8736-a54df8f72339.png)

**Comment by Hyllesen** [comment]
It seems that you don't have to edit MainApplication.java in this newer React Native version. Can we update the README about this?

**Comment by mauron85** [comment]
The plugin was not updated to RN 0.60.4 yet. Due changes in RN, there are multiple issues, that need to be resolved. But in your case, I would say that linker failed, but it managed to add package to MainApplication.java anyway.

**Comment by WebMobi59** [comment]
@mauron85 is it possible to install this package from master branch directly?

**Comment by jacobbeasley** [comment]
Yeah, in package.json you can use a direct reference to github. https://docs.npmjs.com/files/package.json#github-urls

@WebMobi59

**Comment by shmili** [comment]
> plugin was not updated to RN 0.60.4 yet. Due changes in RN, th

I used your plugin with RN 0.59.X.
Do you have a timeline about updating this plugin to work with RN 0.60.X  ?

**Comment by jacobbeasley** [comment]
I'm using it in RN 0.60.4 without issue. Just had to manually setup the settings.gradle and build.gradle files.

**Comment by shmili** [comment]
> I'm using it in RN 0.60.4 without issue. Just had to manually setup the settings.gradle and build.gradle files.

Thanks will try to play around and see if I can get it to work.

**Comment by bimix** [comment]
> > I'm using it in RN 0.60.4 without issue. Just had to manually setup the settings.gradle and build.gradle files.
> 
> Thanks will try to play around and see if I can get it to work.

did you get it to work yet?

**Comment by hladf** [comment]
I've removed all modifs in `MainApplication.java`, like this lines:
```Java
 import com.marianhello.bgloc.react.BackgroundGeolocationPackage;
...
           packages.add(new BackgroundGeolocationPackage());
```
and the bug is gone

**Comment by daheeahn** [comment]
> I've removed all modifs in `MainApplication.java`, like this lines:
> 
> ```java
>  import com.marianhello.bgloc.react.BackgroundGeolocationPackage;
> ...
>            packages.add(new BackgroundGeolocationPackage());
> ```
> 
> and the bug is gone

I followed same, but it didn't work

**Comment by daheeahn** [comment]
> I've removed all modifs in `MainApplication.java`, like this lines:
> 
> ```java
>  import com.marianhello.bgloc.react.BackgroundGeolocationPackage;
> ...
>            packages.add(new BackgroundGeolocationPackage());
> ```
> 
> and the bug is gone

I followed same, but it didn't work.

**Comment by DagonGH** [comment]
I have same problem and don't understand it, when modify MainApplication.java and add this, i get the same error:

...
import com.marianhello.bgloc.react.BackgroundGeolocationPackage;
...

@Override
 protected List<ReactPackage> getPackages() {
     @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      packages.add(new BackgroundGeolocationPackage());
      return packages;
}
`
But if you remove this lines so return other error "invariant violation: requirenativecomponent: "airmap" was not found in the uimanager" 

This is my package.json

`"dependencies": {
    "@mauron85/react-native-background-geolocation": "^0.6.3",
    "@react-native-community/cli-platform-android": "^4.8.0",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-geolocation-service": "^5.0.0",
    "react-native-maps": "0.27.1",   
  },`

But if you remove this lines so return other error "invariant violation: requirenativecomponent: "airmap" was not found in the uimanager" 

supouse that this is the best option to get location in background (free) but y i feel that be outdated. Shoulding take other way or focus for resolve this issue. helpme please.

**Comment by Tariqfaqira** [comment]
1 install darron1217 package

2 Edited the following in android/settings.gradle
  include ':@darron1217_react-native-background-geolocation-common'
  project(':@darron1217_react-native-background-geolocation-common').projectDir = new File(rootProject.projectDir, 
  '../node_modules/@darron1217/react-native-background-geolocation/android/common')
  include ':@darron1217_react-native-background-geolocation'
  project(':@darron1217_react-native-background-geolocation').projectDir = new File(rootProject.projectDir, 
  '../node_modules/@darron1217/react-native-background-geolocation/android/lib')

3 Edited the following in android/app/build.gradle
   compile project(':@darron1217_react-native-background-geolocation')

4 npm install jetifier

5 npx jetify

thats all dont do anything in MainApplication.java

Thanks
