### ISSUE TITLE
error: Source option 6 is no longer supported. Use 7 or later.

### ISSUE THREAD

**Issue by sarmad1995** [mauron85/react-native-background-geolocation#407]
Hi.
It doesn't install on the build running java 8. Please remove the dependency for java 6.

**Comment by sefatunckanat** [comment]
You can change node_modules/@mauron85/react-native-background-geolocation/android/common/build.gradle 117-116

**Comment by sarmad1995** [comment]
That isn't a good idea. There should be some other solution to it.
