### ISSUE TITLE
API link called only once.

### ISSUE THREAD

**Issue by theonlinenerd** [mauron85/react-native-background-geolocation#41]
## Your Environment

* Plugin version: 0.2.0-alpha.5
* Platform: iOS and Android
* OS version:
* Device manufacturer and model:
* React Native version: 0.40
* Plugin configuration options: 
* Link to your project:

## Context
I was trying to use it for testing and I just follow basic example in the documentation it shows the geolocation started in the debug log and also send the info to api (I add a url) but only once after that it never call the Api or never show anything in debug am I missing something ?

 
## Expected Behavior

Calling the API link after x milliseconds based on interval
## Actual Behavior

only call the API link once on start.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 276 days. You may reopen this issue if it has been closed in error.
