### ISSUE TITLE
Donation Link in README broken

### ISSUE THREAD

**Issue by jacobbeasley** [mauron85/react-native-background-geolocation#412]
The donation link is broken in the documentation. Wanted to find out if you would consider fixing it so we could donate to show appreciation for your continued work.

Also, would you ever be available for some consulting work?

**Comment by mauron85** [comment]
Hmm, working for me from github readme page. Maybe temporary paypal issue. Regarding consultation. I don't normally do that, but I have few spare weeks, so if you want contact me through twitter @mauron85.

**Comment by mauron85** [comment]
Closing this, link seems to be working fine.
