### ISSUE TITLE
Missing podspec for autolinking on RN 0.60.x (IOS)

### ISSUE THREAD

**Issue by jaktonn** [mauron85/react-native-background-geolocation#413]
When upgrading from React Native 0.59.x to 0.60.x as described in the RN upgrade howtos, running `pod install` to install the autolinked native libaries fails due to a missing podspec file with message:
`use_native_modules! skipped the react-native dependency '@mauron85/react-native-background-geolocation'. No podspec file was found.`

## Your Environment

* Plugin version: 0.5.5
* Platform: iOS
* OS version: n/a
* Device manufacturer and model: n/a

* Running in Simulator: yes
* React Native version: 0.60.4
* Plugin configuration options: n/a
* Link to your project: n/a

## Context

After upgrading to RN 0.60.x (from 0.59.x) following the upgrade documentations and unlinking all native libraries to use autolinking, running "pod install" fails with this message:
```
[!] use_native_modules! skipped the react-native dependency '@mauron85/react-native-background-geolocation'. No podspec file was found.
    - Check to see if there is an updated version that contains the necessary podspec file
    - Contact the library maintainers or send them a PR to add a podspec. The react-native-webview podspec is a good example of a package.json driven podspec. See
    https://github.com/react-native-community/react-native-webview/blob/master/react-native-webview.podspec
    - If necessary, you can disable autolinking for the dependency and link it manually. See
    https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-disable-autolinking-for-unsupported-library
```
Disabling autolinking as described does not solve the problem either, all references to BackgroundGeolocation in the app return undefined, which makes this library unusable with RN 0.60.x.

## Expected Behavior

RN 0.60.x autolinking works as expected, `pod install` installs the required native implementations for ios.

## Actual Behavior

see section context above

## Possible Fix

Adding a .podspec file will fix this issue

## Steps to Reproduce

1. Upgrade to RN 0.60.x (or create a new app using RN 0.60.x)
2. install npm package
3. **Do not** run the react-native link command as mentioned in the changes for RN 0.60.x
4. run `pod install` in the `/ios` folder

**Comment by jaktonn** [comment]
Latest version works fine in both IOS and Android when sticking to the instructions, thanks a lot for your effort!

**Comment by ridmal** [comment]
@jaktonn i got the same error , is there any fix with .podspec file ?
