### ISSUE TITLE
Geolocation tracking too frequently

### ISSUE THREAD

**Issue by KarenAF** [mauron85/react-native-background-geolocation#417]
We are still seeing this issue: (We're using geolocation plugin for our React Native app.) Tracking occurs every few minutes, or less than a mile, which is too frequent. We have modified accuracy and tested with different location settings to no avail. 

## Your Environment

* Plugin version: 0.5.41
* Platform: iOS
* OS version: 12.4
* Device manufacturer and model: Apple Iphone XR

* Running in Simulator: yes
* React Native version: 0.59.8
* Plugin configuration options:  
* Link to your project:

## Context

We have set the tracking to occur every 15 minutes or 15 miles, but the tracking occurs every minute or so.

## Expected Behavior

Tracking should only occur every 15 minutes.

## Actual Behavior

Tracking occurs every minute or so.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by mauron85** [comment]
You cannot specify exact times on iOS. Only you can filter distance traveled. `interval` options is Android only.

**Comment by JavyMB** [comment]
Hi I know we closed this ticket but I have a few comments that might help.
With iOS, the key is the "**distance filter**". 
The higher the Distance Filter, the slower the report will be.
The lower the Distance Filter, the fastest the report will be.

Here's how it reports when driving in a Freeway:
purple radius is the "distanceFilter" and the Marker is the reported Lat & Long./
<img width="646" alt="Screen Shot 2020-11-17 at 11 58 08 AM" src="https://user-images.githubusercontent.com/3156785/99428544-63ef5200-28cc-11eb-92c5-e3194884d6fd.png">

**NOTE**:
is reporting after reaching the distance filter (in movement)
