### ISSUE TITLE
i can get location after some time continuously  when app background or foreground  in android 

### ISSUE THREAD

**Issue by Rajesh3R** [mauron85/react-native-background-geolocation#419]
## Your Environment

* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer and model:

* Running in Simulator:
* React Native version:
* Plugin configuration options: 
* Link to your project:

## Steps to Reproduce

1.
2.
3.
4.

**Comment by mauron85** [comment]
Sorry, but this report doesn't meet minimal criteria for bug report. Please check https://github.com/mauron85/react-native-background-geolocation#submitting-issues
