### ISSUE TITLE
Not work with "react-native-push-notification"

### ISSUE THREAD

**Issue by mahesh-vi** [mauron85/react-native-background-geolocation#422]
Your Environment
Plugin version:
Platform: Android
OS version: macOS High Sierra 10.13.5
Device manufacturer and model: Android 8.0
React Native version: RN 0.59.9
Plugin configuration options:
Link to your project:
Context
I spent all day troubleshooting this issue, and finally have come to the conclusion that there is some conflict with another package (react-native-push-notification). If I comment out the following lines in MainApplication.Java
import com.marianhello.bgloc.react.BackgroundGeolocationPackage;  // <--- Import Package
new BackgroundGeolocationPackage() // <---- Add the Package

If I also comment out the following in Android/app/build.gradle:
compile project(':@mauron85_react-native-background-geolocation')

Then, the app won't crash on start. If I leave these uncommented, then the app will crash.

Expected Behavior
App should not crash on start.

Actual Behavior
App crashes on start.

Possible Fix
I haven't been coding that long, but it seems to me, that some background process of this library is conflicting with react-native-push-notification, any help would be greatly appreciated.

Steps to Reproduce
Context

**Comment by nbastoWM** [comment]
Hi,
I have
```    
"react-native-push-notification": "^3.1.3",
"@mauron85/react-native-background-geolocation": "^0.5.3",
```
and it works well. I even tested launching a local notification on each "on location" and it works.
Check your versions and try to get the actual error that causes the crash.
