### ISSUE TITLE
How to remove one level from Firebase Push

### ISSUE THREAD

**Issue by SirKadogan** [mauron85/react-native-background-geolocation#426]
## Your Environment
* Plugin version:^0.6.2
* Platform: Android
* OS version: 21 and above
* Device manufacturer and model: Xiaomi Redmi 5
* React Native version: 0.60
* Plugin configuration options: 
```
BackgroundGeolocation.configure({
      desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
      stationaryRadius: 50,
      distanceFilter: 10,
      notificationTitle: 'Background tracking',
      notificationText: 'enabled',
      debug: true,
      startOnBoot: false,
      stopOnTerminate: true,
      locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
      interval: 10000,
      fastestInterval: 5000,
      activitiesInterval: 10000,
      stopOnStillActivity: false,
      url: 'myURL',
      maxLocations: 1,
      postTemplate: {               // <-- Optional HTTP params
        location: {
          lat: '@latitude',
          lon: '@longitude'
        }
       },
    });

```

## Context
I'm sending my post requests through my Firebase URL and it works fine. However, I can't edit the path, as in: 
```
>PushID
      >0
           >location
                >lat
                >lon
```

That #0 adds an extra level to my database that I don't want, because I'd need to change the structure of other apps that also connect to this database.
I need the following structure:
```
>PushID
     >location
           >lat
           >lon
```

How do I change my postTemplate to remove that extra level?

**Comment by mauron85** [comment]
You need to do it in your server. Plugin always sends location as array.

**Comment by SirKadogan** [comment]
Alright, thanks! I figured I would use a location listener to push into my database while waiting for an answer. I guess that will do.
