### ISSUE TITLE
ios 13: "always" option not showing

### ISSUE THREAD

**Issue by RWOverdijk** [mauron85/react-native-background-geolocation#429]
This template is pure insanity 😄 If the answer to this next question is "no" I'll answer all of it, I promise. But I think this question is simple enough to skip it.

I'm not getting the "always" option on **iOS 13** in the location permissions dialog. I only see "allow while using app", "allow once" and "don't allow".

I have set all the keys in Info.plist (see list), so I'm not sure if that's the issue.

- NSLocationAlwaysAndWhenInUseUsageDescription
- NSLocationAlwaysUsageDescription
- NSLocationWhenInUseUsageDescription

The dialog in the example code does show up, so it's not the end of the world, but it does make me wonder what I might be missing.

**Comment by mauron85** [comment]
Not using template when asking for iOS 13 support is ok. However I don't have good news for you. Plugin was not adjusted to iOS 13 yet.

**Comment by RWOverdijk** [comment]
![image](https://user-images.githubusercontent.com/781745/65538301-54ae8780-df07-11e9-9acd-4c150c08f7f2.png)

Darn. It looked like I might be able to pull it off because it does the check here:

https://github.com/mauron85/background-geolocation-ios/blob/7392e391c3de3ff0d6f5ef2ef19c34aba612bf9b/BackgroundGeolocation/INTULocationManager/INTULocationManager.m#L478

The rest seems to work so far, but I only just started using it.

Is there an issue tracking what's needed for iOS 13? I desperately need it (demo tomorrow ha), meaning I am more than willing to lift some rocks if needed.

**Comment by RWOverdijk** [comment]
I got this link from someone smarter than me 😄  

https://medium.com/q42-engineering/apple-location-permission-ios13-1e0e59002889

It's a start.

**Comment by RWOverdijk** [comment]
All right, I didn't have to change a thing and it still works. All I had to do was remove the auth handler.

**Comment by tkondej** [comment]
Hi @RWOverdijk ! Would you mind sharing the code? (event if it's not final version of iOS 13 adjustments)

**Comment by roysG** [comment]
Yes this will be good to share your code, thanks

**Comment by RWOverdijk** [comment]
It's the same as the readme, minus the auth check.

**Comment by Alaa-Ben** [comment]
It is normal that the "Always" option is not showing in IOS 13. It is not a issue. In this new IOS release, there are 2 popups for location:

> Getting consent to scan for location in the background has gotten a bit harder but in exchange, your users will enjoy more transparency regarding the locations you’ve received in iOS 13. The first notable change is that even when you call `requestAlwaysAuthorization`, the user will only get the ‘just now’ and ‘when in use’ options in the permission dialog. If the user grants you ‘when in use’ permission and you try to scan for location in the background, only then the user will be presented a dialog to grant the background permission.

source and for more information: https://engineering.q42.nl/apple-location-permission-ios13.

**Comment by RWOverdijk** [comment]
@Alaa-Ben Yes, that was established. 😄

**Comment by RWOverdijk** [comment]
Closing this since it does still work. All that seems to be needed so far is a note in the readme.
