### ISSUE TITLE
some acy and v data is toasting every 2-3s

### ISSUE THREAD

**Issue by Prashantrao331** [mauron85/react-native-background-geolocation#435]
## Your Environment

* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer and model:

* Running in Simulator:
* React Native version:
* Plugin configuration options: 
* Link to your project:

## Steps to Reproduce

1.
2.
3.
4.

**Comment by nbastoWM** [comment]
Did you try setting the configuration debug to false?

**Comment by Prashantrao331** [comment]
Its done, thanks
