### ISSUE TITLE
Http not working

### ISSUE THREAD

**Issue by deepak-netsoft** [mauron85/react-native-background-geolocation#436]
## Your Environment

* Plugin version:0.59.9
* Platform: both
* OS version:
* Device manufacturer and model:

* Running in Simulator:No
* React Native version:0.59.9
* Plugin configuration options: 0.5.6
* Link to your project:

## Expected Behavior
data should send to server
## Actual Behavior
Http url not working. Also need events for Http response
BackgroundGeolocation.configure({
            desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
            stationaryRadius: 50,
            distanceFilter: 50,
            notificationTitle: 'Background tracking',
            notificationText: 'enabled',
            debug: false,
            startOnBoot: false,
            stopOnTerminate: true,
            locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
            interval: 10000,
            fastestInterval: 5000,
            activitiesInterval: 10000,
            stopOnStillActivity: false,
            url: 'someurl',  //Not working
            httpHeaders: { 
              'Authorization':'Basic YWRtaW46MTIzNA=='
            },
            // customize post properties
            postTemplate: {
              data: '@latitude',
              
            }
          }); 
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

@mauron85

**Comment by deepak-netsoft** [comment]
@mauron85 I have solve it

**Comment by tuanduc2904** [comment]
> @mauron85 I have solve it

How did you solve it?

**Comment by deepak-netsoft** [comment]
@tuanduc2904  Please check how you are sending data. Open Android studio and look for the class Http.
