### ISSUE TITLE
Error: Can't find variable: Actions. Just on iOS

### ISSUE THREAD

**Issue by gomesbreno** [mauron85/react-native-background-geolocation#438]
Hi!

I am using this library with RN 0.59.8, end the version 0.5.6 of react-native-background-geolocation. When I'm running the exemple code on android everything work fine, however, on iOS I'm getting the error bellow.

Update: the error is in this function:

 BackgroundGeolocation.on("stationary", stationaryLocation => {
      // handle stationary locations here
      Actions.sendLocation(stationaryLocation);      
    });

If a comment the line with the variable Actions, the BackgroundGeolocation doesn't work.

![error on iOS](https://user-images.githubusercontent.com/26438217/67419824-cc71df80-f5a3-11e9-8b68-8b49836c4f2e.jpeg)

**Comment by p4kaidu** [comment]
Fixed this problem by completely removing the handler

**Comment by scsman** [comment]
the same issue, need help !!!
