### ISSUE TITLE
On location event not triggering on android

### ISSUE THREAD

**Issue by Batuhan-Akkaya** [mauron85/react-native-background-geolocation#447]
## Your Environment

* Plugin version: 0.5.0
* Platform: Android
* OS version: 10
* Device manufacturer and model: Redmi 8 pro, Samsung j7 

* Running in Simulator: yes
* React Native version: 0.55.4
* Plugin configuration options: `

BackgroundGeolocation.configure({
      locationProvider: BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,
      desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
      stationaryRadius: 50,
      distanceFilter: 100,
      notificationTitle: '',
      notificationText: 'enabled',
      notificationsEnabled: false,
      debug: true,
      startOnBoot: false,
      stopOnTerminate: false,
      fastestInterval: 10000,
      activitiesInterval: 10000,
      stopOnStillActivity: false,
    });

`
* Link to your project:

## Context

On location event only trigger while app opened. Not trigger while location onchange. This used to be smooth, spontaneously broken.

## Expected Behavior

On location event function should be trigger while location onchange

## Actual Behavior

On location event not triggering while location onchange

## Steps to Reproduce

1.
2.
3.
4.

**Comment by JorenVos** [comment]
Dealing with exactly the same problem, which makes it impossible to use this library. It's all working fine on iOS, but on Android no location updates are received. @mauron85 any idea?

**Comment by sebastienmascha** [comment]
Same issue using : `locationProvider: BackgroundGeolocation.RAW_PROVIDER`

As JorenVos said: switched to locationProvider: `BackgroundGeolocation.DISTANCE_FILTER_PROVIDER `on Android resolved this issue for me.
