### ISSUE TITLE
Location service starts on its own a couple of minutes after turning off the application

### ISSUE THREAD

**Issue by ridik1803** [mauron85/react-native-background-geolocation#451]
Location service starts on its own a couple of minutes after turning off the application
## Your Environment

* Plugin version: 0.5.6
* Platform: Android
* OS version: 9
* Device manufacturer and model: Samsung A50

* Running in Simulator: no
* React Native version: 0.59.10
* Plugin configuration options: 
            desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
            debug: false,
            notificationTitle: 'Водитель 135',
            notificationText: 'Определение местоположения',
            startOnBoot: false,
            stopOnTerminate: true,
            locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
            interval: 5000,
            fastestInterval: 3000,
            activitiesInterval: 10000,
            stopOnStillActivity: false,
            url: null,
            startForeground: true,
            maxLocations: 10      
* Link to your project:

## Steps to Reproduce

1. Execute Start()
2. Execute Stop()
2. Exit app
3. Wait a couple of minutes
4. Location service appears in the notification bar

**Comment by melvinchng** [comment]
I have a similar issue. Whenever I restart my device, the background location will always come back even I stopped it. I tried to look for a solution but unfortunately, I could not find any.
