### ISSUE TITLE
Android build error when plugin version is x >0.5.6

### ISSUE THREAD

**Issue by burhanyilmaz** [mauron85/react-native-background-geolocation#455]
## Your Environment

* Plugin version:
* Platform: Android
* OS version: macOS 10.15
* Device manufacturer and model: simulator

* Running in Simulator: true
* React Native version: 0.59.9
* Plugin configuration options: 
```{
      desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
      stationaryRadius: 50,
      distanceFilter: 50,
      debug: false,
      startOnBoot: true,
      stopOnTerminate: false,
      locationProvider: BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,
      activitiesInterval: 10000,
      stopOnStillActivity: false,
      url:
        "endpoint',
      httpHeaders: {
        "X-FOO": "bar"
      },
      postTemplate: {
        lat: "@latitude",
        lon: "@longitude",
        datePhone: new Date().toString(),
        accuracy: "@accuracy",
        time: "@time",
      }
    }
```

# Expected Behavior

If  plugin version is x >0.5.6, app build success on android.

## Actual Behavior

Android build error when plugin version is x >0.5.6
When Plugin version is 0.5.6, app is work on android and ios
## Steps to Reproduce

1.
2.
3.
4.

## Error logs

```
* What went wrong:
A problem occurred configuring 
project ':@mauron85_react-native-background-geolocation'.
> Cannot change artifacts of configuration 
':@mauron85_react-native-background-geolocation:default' after it has 
been included in dependency resolution.

```

**Comment by nagasaicharan** [comment]
Please read the documentation properly.


Automatic setup
Since version 0.60 React Native does linking of modules automatically. However it does it only for single module. As plugin depends on additional 'common' module, it is required to link it with:

You need to perform below command and it starts working.

**node ./node_modules/@mauron85/react-native-background-geolocation/scripts/postlink.js**

**Comment by burhanyilmaz** [comment]
@nagasaicharan Thanks for the reply. My rn version is 0.59.9. it is not 0.60 or higher.
