### ISSUE TITLE
Crashes with OneSignal (Android)

### ISSUE THREAD

**Issue by akinncar** [mauron85/react-native-background-geolocation#459]
When I tried to install this lib with onesignal I have errors and app don't build

## Your Environment
```
  React Native Environment Info:
    System:
      OS: Linux 5.0 Linux Mint 19.3 (Tricia)
      CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
      Memory: 752.81 MB / 15.36 GB
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 12.14.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native: 0.61.5
```

## Expected Behavior
Exected app builds.

## Actual Behavior
App don't build

## Possible Fix
When I remove OneSignal works, but I need OneSignal

```
// apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
```

## Steps to Reproduce
1. Install and link OneSignal
2. Install and link this lib

## Debug logs
```FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':@mauron85_react-native-background-geolocation'.
> Cannot change artifacts of configuration ':@mauron85_react-native-background-geolocation:default' after it has been included in dependency resolution.```

**Comment by sostenesg7** [comment]
Don't worry. I solved it by following this: [https://github.com/mauron85/react-native-background-geolocation/issues/448#issuecomment-573448334](url)

I'm using onesignal too and we don't need _**apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'**_

Just follow these steps above and tell us if it works for you.

**Comment by akinncar** [comment]
broken url ;/

**Comment by mandaai** [comment]
> Don't worry. I solved it by following this: [https://github.com/mauron85/react-native-background-geolocation/issues/448#issuecomment-573448334](url)
> 
> I'm using onesignal too and we don't need _**apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'**_
> 
> Just follow these steps above and tell us if it works for you.

Edit: https://github.com/mauron85/react-native-background-geolocation/issues/448#issuecomment-573448334

**Comment by akinncar** [comment]
> > Don't worry. I solved it by following this: [https://github.com/mauron85/react-native-background-geolocation/issues/448#issuecomment-573448334](url)
> > I'm using onesignal too and we don't need _**apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'**_
> > Just follow these steps above and tell us if it works for you.
> 
> Edit: [#448 (comment)](https://github.com/mauron85/react-native-background-geolocation/issues/448#issuecomment-573448334)

Solved, closing this issue!
