### ISSUE TITLE
showsBackgroundLocationIndicator for iOS

### ISSUE THREAD

**Issue by RWOverdijk** [mauron85/react-native-background-geolocation#465]
A nice feature to have would be a new config option for ios `showsBackgroundLocationIndicator` ([Documentation](https://developer.apple.com/documentation/corelocation/cllocationmanager/2923541-showsbackgroundlocationindicator)).

When an app actively uses the location of the user some (like myself) want to inform the user of this even when the "Always" permission was given.

**Comment by tuanduc2904** [comment]
Hi bro. I am also having this problem. Do you have any solution?

**Comment by RWOverdijk** [comment]
The solution is literally in my description. 😄

**Comment by tuanduc2904** [comment]
> The solution is literally in my description. 😄

sorry for being stupid. But I can't find showsBackgroundLocationIndicator on the readme of this library.

**Comment by RWOverdijk** [comment]
The link to the docs is literally in my description.

It hasn't been implemented yet, but you can do so yourself using the prop I linked to.

Either do it on a project-level or make a PR, the latter of which I intend to do when I get to it.

**Comment by tuanduc2904** [comment]
> The link to the docs is literally in my description.
> 
> It hasn't been implemented yet, but you can do so yourself using the prop I linked to.
> 
> Either do it on a project-level or make a PR, the latter of which I intend to do when I get to it.

thanks you !!!
