### ISSUE TITLE
null is not an object (evaluating 'RNBackgroundGeolocation.configure')

### ISSUE THREAD

**Issue by Ankit-Reactjs** [mauron85/react-native-background-geolocation#466]
null is not an object (evaluating 'RNBackgroundGeolocation.configure')

**Comment by Anoxy** [comment]
Have the same problem in android, everything works when i go for react-native run-android, but after assembleRelease app crashes with 'ReactNativeJS: TypeError: null is not an object (evaluating 'b.configure')'

**Comment by mohammedelnady** [comment]
reopen it
