### ISSUE TITLE
location.time showing unexpected time

### ISSUE THREAD

**Issue by luisguilhermemsalmeida** [mauron85/react-native-background-geolocation#47]
## Your Environment

* Plugin version: 0.2.0-alpha.6
* Platform: Android
* OS version: 6.0
* Device manufacturer and model: Simulator
* React Native version: 0.40
* Plugin configuration options: 
* Link to your project:

## Context
new Date().toUTCString() is different from the `time` reported by the http posting or location callback (my phone is on GMT-3)

## Expected Behavior
`BackgroundGeolocation.on('location', (location) => {
      console.log(location.time);
    });`
that log should return the current time (UTC) on the phone, which was supposed to be `1489108911353` or `Thu, 09 Mar 2017 22:21:51 GMT` (`Thu Mar 09 2017 19:21:51 GMT-0300 (BRT)`)

## Actual Behavior
It is returning `1489123434000` (`2017-03-10 05:23:54`)
As you can see, the return value is several hours ahead from the correct UTC time.

## Possible Fix
I don't know

## Steps to Reproduce

1. console.log(location.time)

**Comment by L3V147H4N** [comment]
Im having the same issue, location.time is ahead of phone time

**Comment by telkandrew** [comment]
Any luck figuring this issue out?

**Comment by luisguilhermemsalmeida** [comment]
No :(
I haven't been using this package now.

**Comment by kholiavko-roman** [comment]
@luisguilhermemsalmeida, what are you using insted?

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 60 days. You may reopen this issue if it has been closed in error.
