### ISSUE TITLE
compileSdkVersion error

### ISSUE THREAD

**Issue by canerd7u** [mauron85/react-native-background-geolocation#470]
* What went wrong:
A problem occurred configuring project ':@mauron85_react-native-background-geolocation-common'.
> compileSdkVersion is not specified.

**Comment by Daavidaviid** [comment]
Check #468

**Comment by gusilveiramp** [comment]
@canerd7u just add this to your settings.gradle file:

`include ':@mauron85_react-native-background-geolocation-common'
project(':@mauron85_react-native-background-geolocation-common').projectDir = new File(rootProject.projectDir, '../node_modules/@mauron85/react-native-background-geolocation/android/common')
include ':@mauron85_react-native-background-geolocation'
project(':@mauron85_react-native-background-geolocation').projectDir = new File(rootProject.projectDir, '../node_modules/@mauron85/react-native-background-geolocation/android/lib')`

Exactly as described here:
https://github.com/mauron85/react-native-background-geolocation#android-setup

The automatic link is not working correctly for these dependencies.

**Comment by ibrahnerd7** [comment]
Works form me!

**Comment by samuk190** [comment]
> @canerd7u just add this to your settings.gradle file:
> 
> `include ':@mauron85_react-native-background-geolocation-common' project(':@mauron85_react-native-background-geolocation-common').projectDir = new File(rootProject.projectDir, '../node_modules/@mauron85/react-native-background-geolocation/android/common') include ':@mauron85_react-native-background-geolocation' project(':@mauron85_react-native-background-geolocation').projectDir = new File(rootProject.projectDir, '../node_modules/@mauron85/react-native-background-geolocation/android/lib')`
> 
> Exactly as described here:
> https://github.com/mauron85/react-native-background-geolocation#android-setup
> 
> The automatic link is not working correctly for these dependencies.

after that I get this error:

`
C:\PROJETOS\RA VIGILANCIA\ramobile\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:101: error: cannot find symbol
      new BackgroundGeolocationPackage(),
          ^
  symbol:   class BackgroundGeolocationPackage
  location: class PackageList
`

**Comment by samuk190** [comment]
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s

    at makeError (C:\PROJETOS\RA VIGILANCIA\ramobile\node_modules\execa\index.js:174:9)
    at Promise.all.then.arr (C:\PROJETOS\RA VIGILANCIA\ramobile\node_modules\execa\index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by helloeyesimple** [comment]
> error: package com.marianhello.bgloc.react does not exist import com.marianhello.bgloc.react.BackgroundGeolocationPackage;
> 
> Execution failed for task ':app:compileDebugJavaWithJavac'.
> 
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 13s
> 
> ```
> at makeError (C:\PROJETOS\RA VIGILANCIA\ramobile\node_modules\execa\index.js:174:9)
> at Promise.all.then.arr (C:\PROJETOS\RA VIGILANCIA\ramobile\node_modules\execa\index.js:278:16)
> at process._tickCallback (internal/process/next_tick.js:68:7)
> ```

how did you resolved it?
