### ISSUE TITLE
Android Build fails after implementing this library.

### ISSUE THREAD

**Issue by ShubhamBalgujar** [mauron85/react-native-background-geolocation#478]
## Your Environment

* Plugin version:0.6.3
* Platform: iOS or Android
* OS version:
* Device manufacturer and model:

* Running in Simulator: Yes
* React Native version: 0.60.5
* Plugin configuration options: 
* Link to your project:

 Context
 After installing and linking this library i am getting the below error

   What went wrong:
  Execution failed for task ':app:multiDexListDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Error while merging dex archives: 
     Program type already present: org.apache.commons.io.Charsets
The error occurs while realse build.(debug version works). Also the multiDex is enabled.

 Expected Behavior
The library should have automatically linked since the react-native version 60.5 bu i have to fire the manual linking command to link the library.

**Comment by sostenesg7** [comment]
Can you show your package.json libraries?
Have you tried with a clean project?

**Comment by sebastienmascha** [comment]
Have you tried Manual Setup ? https://www.npmjs.com/package/@mauron85/react-native-background-geolocation#android-setup

**Comment by ShubhamBalgujar** [comment]
Yes I did manual linking and setup. It was clashing with another library so I did setup accordingly and the issues got resolved. Thankyou.
