### ISSUE TITLE
Cause react-native-fingerprint-android not working when installed

### ISSUE THREAD

**Issue by UrbanSam** [mauron85/react-native-background-geolocation#48]
## Your Environment

* Platform: Android API 23, Android Simulator
* OS version: Windows 10
* React Native version: 0.41.2
* mauron85/react-native-background-geolocation : 0.2.0-alpha.6
* jariz/react-native-fingerprint-android 0.1.4
[https://github.com/jariz/react-native-fingerprint-android](url)

## Context

When mauron85/react-native-background-geolocation is installed,  jariz/react-native-fingerprint-android not able to work properly. But if the bg geolocation package is removed, it's working fine.

####  Debug logs of fingerprint package when background geolocation package is installed
isHardwareDetected= false        _-->!This should return true_
hasPermission = true
hasEnrolledFingerprints = false   _-->!This should return true_

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 252 days. You may reopen this issue if it has been closed in error.
