### ISSUE TITLE
BackgroundGeolocation.watchPosition() not gives regular location update on iOS simulator

### ISSUE THREAD

**Issue by vikrantnegi** [mauron85/react-native-background-geolocation#481]
Using `BackgroundGeolocation.watchPosition()` on iOS simulator and using location debugging feature "Freeway drive" gives only one location. 

## Your Environment
* Plugin version: 3.6.2
* Platform: iOS
* OS version: 13.3
* Running in Simulator: Yes
* React Native version:  0.61.5
* Plugin configuration options: 

## Context
I'm getting `is_moving: false` maybe because of odometer not working on simulator and due to this it is not giving regular location updates. 

## Expected Behavior
Is there a way I can receive the location updates in iOS simulator since it normally works using native geolocation API?

## Actual Behavior
I'm getting only single location on console from the simulator.

## Steps to Reproduce
```js
    // Traditional API still works:
    BackgroundGeolocation.ready({
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 50,
    })
      .then(state => {
        console.log('- BackgroundGeolocation is ready: ', state);
        BackgroundGeolocation.watchPosition(
          location => {
            console.log('[watchPosition] -', location);
            const {latitude, longitude, speed} = location.coords;
          },
          errorCode => {
            console.log('[watchPosition] ERROR -', errorCode);
          },
          {
            //interval: 1000,
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            persist: true,
            extras: {foo: 'bar'},
            timeout: 60000,
          },
        );
      })
      .catch(error => {
        console.log('- BackgroundGeolocation error: ', error);
      });
```

Thanks.

**Comment by Bashamd455** [comment]
Hi @vikrantnegi, How can I get the location details after every 5 minutes ??

**Comment by vikrantnegi** [comment]
@Bashamd455 You can change the `interval` to `5000` but I would recommend that you should use the `distanceFilter` instead so that you can location updates only when the location changes.

**Comment by Bashamd455** [comment]
@vikrantnegi, Thanks for the quick reply. My requirement is to fetch the location after every 5 minutes so, does this library has any method which can give me the location after every 5 minutes whether the app is in the foreground or background?

**Comment by vikrantnegi** [comment]
You can use `BackgroundGeolocation.watchPosition`, it gives location updates .

**Comment by Bashamd455** [comment]
There is no such method in the latest version of the library i.e., V0.6.3

**Comment by vikrantnegi** [comment]
@Bashamd455 Please read the documentation properly. I'm using the latest version in my app and it is working. Read here [BackgroundGeolocation.watchPosition](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.watchpositionrequest.html)
