### ISSUE TITLE
Get the current location after every 5 min

### ISSUE THREAD

**Issue by Bashamd455** [mauron85/react-native-background-geolocation#482]
## Your Environment

* Plugin version: 0.6.3
* Platform: iOS and Android
* OS version:
* Device manufacturer and model:

* Running in Simulator:
* React Native version: 0.62.2
* Plugin configuration options: 
* Link to your project:

## Expected Behavior

How to get the current location after every 5 minutes

## Steps to Reproduce

1.
2.
3.
4.

**Comment by vikrantnegi** [comment]
Please find the answer here https://github.com/mauron85/react-native-background-geolocation/issues/481#issuecomment-616307310
