### ISSUE TITLE
Modules pointing to the same directory

### ISSUE THREAD

**Issue by szalaybalazs** [mauron85/react-native-background-geolocation#483]
## Your Environment

* Plugin version: 0.6.3
* Platform: Android
* OS version: Any
* Device manufacturer and model:

* Running in Simulator: YES
* React Native version: 0.60
* Plugin configuration options:  0.62.2
* Link to your project:

## Context

I have been trying to implement the module into my application for quite some time now, but I can not get it to work. On iOS it works fine, but on android the compiler says `ERROR: The modules ['@mauron85_react-native-background-geolocation', 'mauron85_react-native-background-geolocation'] point to the same directory in the file system.
Each module must have a unique path.`

My settings.gradle
```apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':@mauron85_react-native-background-geolocation-common'
project(':@mauron85_react-native-background-geolocation-common').projectDir = new File(rootProject.projectDir, '../node_modules/@mauron85/react-native-background-geolocation/android/common')
include ':@mauron85_react-native-background-geolocation'
project(':@mauron85_react-native-background-geolocation').projectDir = new File(rootProject.projectDir, '../node_modules/@mauron85/react-native-background-geolocation/android/lib')
include ':app'
include ':react-native-maps'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/lib/android')
```

## Steps to Reproduce

1. Create a new RN project
2. Add package
3. Run from Android Studio

## Context

I am trying to set up the package

**Comment by ArashYounesi** [comment]
I built it on the command line and it worked.
`npx react-native run-android` 
or
`react-native run-android`

**Comment by olegmilan** [comment]
Any idea how to fix this in order to run exactly on Android studio?
`react-native run-android` works for me as well

**Comment by muhammadrofiq** [comment]
i get same error with android studio, but if i run use terminal its fine

ERROR: The modules ['@mauron85_react-native-background-geolocation', 'mauron85_react-native-background-geolocation'] point to the same directory in the file system.
Each module must have a unique path.

**Comment by muhammadrofiq** [comment]
> Any idea how to fix this in order to run exactly on Android studio?
> `react-native run-android` works for me as well

any solution for this issue ?
