### ISSUE TITLE
Conflicting provider when trying to install multiple build types on one device

### ISSUE THREAD

**Issue by matt33** [mauron85/react-native-background-geolocation#49]
## Your Environment

* Plugin version: 0.2.0-alpha.6
* Platform: Android
* OS version: Android API 25
* React Native version: 0.40.0

## Context
I've created multiple buildTypes for android - debug, releaseStaging and release in order to update the app via code push. When trying to install staging build on the device where there is a debug build already installed I am getting an error:

`INSTALL_FAILED_CONFLICTING_PROVIDER: Package couldn't be installed in /data/app/com.myapp.app.staging-1: Can't install because provider name com.marianhello.authority (in package com.myapp.app.staging) is already used by com.myapp.app.debug`

I already have `applicationId` defined
```
android {
    defaultConfig {
        applicationId 'com.example.myproject'
    }
}
```
Also tried this fix http://gradlewhy.ghost.io/overcoming-install-failed-conflicting-provider/ which did not help - not sure what to write in AndroidManifest.xml in <provider> take as `android:name` as my app has no content provider.

Any ideas how to solve this?

**Comment by mauron85** [comment]
You have to change @account_type and @content_authority in `android/src/main/res/values/strings.xml` like described in https://github.com/mauron85/react-native-background-geolocation#android-setup

**Comment by matt33** [comment]
That sure helped, thanks a lot!!
