### ISSUE TITLE
Android, Build failed

### ISSUE THREAD

**Issue by jesperbjerke** [mauron85/react-native-background-geolocation#5]
Trying to get this up and running, but seems to fail when running "react-native run-android". Totally new at react-native so would very much appreciate some guidance to get this running!

:react-native-mauron85-background-geolocation:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-mauron85-background-geolocation:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\Android\android-sdk\build-tools\23.0.1\aapt.exe'' finished with non-zero exit value 1

**Comment by mauron85** [comment]
Can you post full output?

**Comment by jesperbjerke** [comment]
Starting JS server...
Running D:\Android\android-sdk/platform-tools/adb reverse tcp:80
Building and installing the app on the device (cd android && gra
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:react-native-mapbox-gl:compileLint
:react-native-mapbox-gl:copyReleaseLint UP-TO-DATE
:react-native-mapbox-gl:preBuild UP-TO-DATE
:react-native-mapbox-gl:preReleaseBuild UP-TO-DATE
:react-native-mapbox-gl:checkReleaseManifest
:react-native-mapbox-gl:preDebugAndroidTestBuild UP-TO-DATE
:react-native-mapbox-gl:preDebugBuild UP-TO-DATE
:react-native-mapbox-gl:preDebugUnitTestBuild UP-TO-DATE
:react-native-mapbox-gl:preReleaseUnitTestBuild UP-TO-DATE
:react-native-mapbox-gl:prepareComAndroidSupportAnimatedVectorDr
:react-native-mapbox-gl:prepareComAndroidSupportAppcompatV72340L
:react-native-mapbox-gl:prepareComAndroidSupportDesign2340Librar
:react-native-mapbox-gl:prepareComAndroidSupportRecyclerviewV723
:react-native-mapbox-gl:prepareComAndroidSupportSupportV42340Lib
:react-native-mapbox-gl:prepareComAndroidSupportSupportVectorDra
:react-native-mapbox-gl:prepareComFacebookFrescoDrawee081Library
:react-native-mapbox-gl:prepareComFacebookFrescoFbcore081Library
:react-native-mapbox-gl:prepareComFacebookFrescoFresco081Library
:react-native-mapbox-gl:prepareComFacebookFrescoImagepipeline081
:react-native-mapbox-gl:prepareComFacebookFrescoImagepipelineOkh
:react-native-mapbox-gl:prepareComFacebookReactReactNative0191Li
:react-native-mapbox-gl:prepareComMapboxMapboxsdkMapboxAndroidSd
:react-native-mapbox-gl:prepareComMapzenAndroidLost110Library UP
:react-native-mapbox-gl:prepareOrgWebkitAndroidJscR174650Library
:react-native-mapbox-gl:prepareReleaseDependencies
:react-native-mapbox-gl:compileReleaseAidl UP-TO-DATE
:react-native-mapbox-gl:compileReleaseRenderscript UP-TO-DATE
:react-native-mapbox-gl:generateReleaseBuildConfig UP-TO-DATE
:react-native-mapbox-gl:generateReleaseAssets UP-TO-DATE
:react-native-mapbox-gl:mergeReleaseAssets UP-TO-DATE
:react-native-mapbox-gl:generateReleaseResValues UP-TO-DATE
:react-native-mapbox-gl:generateReleaseResources UP-TO-DATE
:react-native-mapbox-gl:mergeReleaseResources UP-TO-DATE
:react-native-mapbox-gl:processReleaseManifest UP-TO-DATE
:react-native-mapbox-gl:processReleaseResources UP-TO-DATE
:react-native-mapbox-gl:generateReleaseSources UP-TO-DATE
:react-native-mapbox-gl:processReleaseJavaRes UP-TO-DATE
:react-native-mapbox-gl:compileReleaseJavaWithJavac UP-TO-DATE
:react-native-mapbox-gl:extractReleaseAnnotations UP-TO-DATE
:react-native-mapbox-gl:mergeReleaseProguardFiles UP-TO-DATE
:react-native-mapbox-gl:packageReleaseJar UP-TO-DATE
:react-native-mapbox-gl:compileReleaseNdk UP-TO-DATE
:react-native-mapbox-gl:packageReleaseJniLibs UP-TO-DATE
:react-native-mapbox-gl:packageReleaseLocalJar UP-TO-DATE
:react-native-mapbox-gl:packageReleaseRenderscript UP-TO-DATE
:react-native-mapbox-gl:packageReleaseResources UP-TO-DATE
:react-native-mapbox-gl:bundleRelease UP-TO-DATE
:react-native-mauron85-background-geolocation:compileLint
:react-native-mauron85-background-geolocation:copyReleaseLint UP
:react-native-mauron85-background-geolocation:preBuild UP-TO-DAT
:react-native-mauron85-background-geolocation:preReleaseBuild UP
:react-native-mauron85-background-geolocation:checkReleaseManife
:react-native-mauron85-background-geolocation:preDebugAndroidTes
:react-native-mauron85-background-geolocation:preDebugBuild UP-T
:react-native-mauron85-background-geolocation:preDebugUnitTestBu
:react-native-mauron85-background-geolocation:preReleaseUnitTest
:react-native-mauron85-background-geolocation:prepareComAndroidS
:react-native-mauron85-background-geolocation:prepareComAndroidS
:react-native-mauron85-background-geolocation:prepareComAndroidS
:react-native-mauron85-background-geolocation:prepareComFacebook
:react-native-mauron85-background-geolocation:prepareComFacebook
:react-native-mauron85-background-geolocation:prepareComFacebook
:react-native-mauron85-background-geolocation:prepareComFacebook
:react-native-mauron85-background-geolocation:prepareComFacebook
:react-native-mauron85-background-geolocation:prepareComFacebook
:react-native-mauron85-background-geolocation:prepareComFacebook
:react-native-mauron85-background-geolocation:prepareComFacebook
:react-native-mauron85-background-geolocation:prepareComGoogleAn
:react-native-mauron85-background-geolocation:prepareComGoogleAn
:react-native-mauron85-background-geolocation:prepareComGoogleAn
:react-native-mauron85-background-geolocation:prepareComGoogleAn
:react-native-mauron85-background-geolocation:prepareOrgWebkitAn
:react-native-mauron85-background-geolocation:prepareReleaseDepe
:react-native-mauron85-background-geolocation:compileReleaseAidl
:react-native-mauron85-background-geolocation:compileReleaseRend
:react-native-mauron85-background-geolocation:generateReleaseBui
:react-native-mauron85-background-geolocation:generateReleaseAss
:react-native-mauron85-background-geolocation:mergeReleaseAssets
:react-native-mauron85-background-geolocation:generateReleaseRes
:react-native-mauron85-background-geolocation:generateReleaseRes
:react-native-mauron85-background-geolocation:mergeReleaseResour
AAPT out(667469813) : No Delegate set : lost message:Done
AAPT out(1580013939) : No Delegate set : lost message:Done
AAPT out(365730399) : No Delegate set : lost message:Done
AAPT out(1266717903) : No Delegate set : lost message:Done
AAPT out(2007031690) : No Delegate set : lost message:Done
AAPT out(1730837099) : No Delegate set : lost message:Done
AAPT out(107864953) : No Delegate set : lost message:Done
AAPT out(2007031690) : No Delegate set : lost message:Done
AAPT out(1659528560) : No Delegate set : lost message:Done
AAPT out(338923147) : No Delegate set : lost message:Done
AAPT out(104723713) : No Delegate set : lost message:Done
AAPT out(365730399) : No Delegate set : lost message:Done
AAPT out(413781828) : No Delegate set : lost message:Done
AAPT out(667469813) : No Delegate set : lost message:Done
AAPT out(1580013939) : No Delegate set : lost message:Done
AAPT out(338923147) : No Delegate set : lost message:Done
AAPT out(104723713) : No Delegate set : lost message:Done
AAPT out(1266717903) : No Delegate set : lost message:Done
AAPT out(1087063106) : No Delegate set : lost message:Done
AAPT out(1052368712) : No Delegate set : lost message:Done
AAPT out(2007031690) : No Delegate set : lost message:Done
AAPT out(1831080404) : No Delegate set : lost message:Done
AAPT out(1659528560) : No Delegate set : lost message:Done
AAPT out(787242274) : No Delegate set : lost message:Done
AAPT out(1772585588) : No Delegate set : lost message:Done
AAPT out(1730837099) : No Delegate set : lost message:Done
AAPT out(1266717903) : No Delegate set : lost message:Done
AAPT out(338923147) : No Delegate set : lost message:Done
AAPT out(107864953) : No Delegate set : lost message:Done
AAPT out(104723713) : No Delegate set : lost message:Done
AAPT out(1580013939) : No Delegate set : lost message:Done
AAPT out(687694060) : No Delegate set : lost message:Done
AAPT out(338923147) : No Delegate set : lost message:Done
AAPT out(1266717903) : No Delegate set : lost message:Done
AAPT out(413781828) : No Delegate set : lost message:Done
AAPT out(1021397758) : No Delegate set : lost message:Done
AAPT out(1087063106) : No Delegate set : lost message:Done
AAPT out(1831080404) : No Delegate set : lost message:Done
AAPT out(1730837099) : No Delegate set : lost message:Done
AAPT out(2007031690) : No Delegate set : lost message:Done
AAPT out(1400858472) : No Delegate set : lost message:Done
AAPT out(667469813) : No Delegate set : lost message:Done
AAPT out(1052368712) : No Delegate set : lost message:Done
AAPT out(365730399) : No Delegate set : lost message:Done
AAPT out(1772585588) : No Delegate set : lost message:Done
AAPT out(1400858472) : No Delegate set : lost message:Done
AAPT out(1087063106) : No Delegate set : lost message:Done
AAPT out(667469813) : No Delegate set : lost message:Done
AAPT out(2007031690) : No Delegate set : lost message:Done
AAPT out(1831080404) : No Delegate set : lost message:Done
AAPT out(787242274) : No Delegate set : lost message:Done
AAPT out(1021397758) : No Delegate set : lost message:Done
AAPT out(1266717903) : No Delegate set : lost message:Done
AAPT out(338923147) : No Delegate set : lost message:Done
AAPT out(1659528560) : No Delegate set : lost message:Done
AAPT out(107864953) : No Delegate set : lost message:Done
AAPT out(1580013939) : No Delegate set : lost message:Done
AAPT out(1266717903) : No Delegate set : lost message:Done
AAPT out(687694060) : No Delegate set : lost message:Done
AAPT out(1266717903) : No Delegate set : lost message:Done
AAPT out(365730399) : No Delegate set : lost message:Done
AAPT out(1772585588) : No Delegate set : lost message:Done
AAPT out(1087063106) : No Delegate set : lost message:Done
AAPT out(1831080404) : No Delegate set : lost message:Done
AAPT out(787242274) : No Delegate set : lost message:Done
AAPT out(1021397758) : No Delegate set : lost message:Done
AAPT out(2007031690) : No Delegate set : lost message:Done
AAPT out(667469813) : No Delegate set : lost message:Done
AAPT out(104723713) : No Delegate set : lost message:Done
AAPT out(550710551) : No Delegate set : lost message:Done
AAPT out(1052368712) : No Delegate set : lost message:Done
AAPT out(104723713) : No Delegate set : lost message:Crunching D
-v4\common_plus_signin_btn_text_light_normal.9.png
AAPT out(104723713) : No Delegate set : lost message:Crunching s
es\drawable-xhdpi-v4\common_plus_signin_btn_text_light_normal.9.
AAPT out(104723713) : No Delegate set : lost message:   Output f
rmal.9.png
AAPT out(104723713) : No Delegate set : lost message:Done
AAPT err(687694060): D:\Dropbox\www\ConquerorGame\ConquerorGame\
rmal.9.png ERROR: Unable to open PNG file
AAPT err(1772585588): D:\Dropbox\www\ConquerorGame\ConquerorGame
isabled.9.png ERROR: Unable to open PNG file
AAPT err(1831080404): D:\Dropbox\www\ConquerorGame\ConquerorGame
sabled.9.png ERROR: Unable to open PNG file
AAPT err(1659528560): D:\Dropbox\www\ConquerorGame\ConquerorGame
sabled.9.png ERROR: Unable to open PNG file
AAPT err(1052368712): D:\Dropbox\www\ConquerorGame\ConquerorGame
isabled.9.png ERROR: Unable to open PNG file
AAPT err(550710551): D:\Dropbox\www\ConquerorGame\ConquerorGame\
sabled.9.png ERROR: Unable to open PNG file
AAPT err(1400858472): D:\Dropbox\www\ConquerorGame\ConquerorGame
cused.9.png ERROR: Unable to open PNG file
AAPT err(667469813): D:\Dropbox\www\ConquerorGame\ConquerorGame\
ssed.9.png ERROR: Unable to open PNG file
AAPT err(1580013939): D:\Dropbox\www\ConquerorGame\ConquerorGame
abled.9.png ERROR: Unable to open PNG file
AAPT err(104723713): D:\Dropbox\www\ConquerorGame\ConquerorGame\
used.9.png ERROR: Unable to open PNG file
AAPT err(2007031690): D:\Dropbox\www\ConquerorGame\ConquerorGame
ormal.9.png ERROR: Unable to open PNG file
AAPT err(1021397758): D:\Dropbox\www\ConquerorGame\ConquerorGame
essed.9.png ERROR: Unable to open PNG file
AAPT err(1266717903): D:\Dropbox\www\ConquerorGame\ConquerorGame
focused.9.png ERROR: Unable to open PNG file
AAPT err(365730399): D:\Dropbox\www\ConquerorGame\ConquerorGame\
abled.9.png ERROR: Unable to open PNG file
AAPT err(787242274): D:\Dropbox\www\ConquerorGame\ConquerorGame\
abled.9.png ERROR: Unable to open PNG file
AAPT err(1087063106): D:\Dropbox\www\ConquerorGame\ConquerorGame
cused.9.png ERROR: Unable to open PNG file
AAPT err(1087063106): D:\Dropbox\www\ConquerorGame\ConquerorGame
essed.9.png ERROR: Unable to open PNG file
AAPT err(107864953): D:\Dropbox\www\ConquerorGame\ConquerorGame\
bled.9.png ERROR: Unable to open PNG file
AAPT err(338923147): D:\Dropbox\www\ConquerorGame\ConquerorGame\
used.9.png ERROR: Unable to open PNG file
AAPT err(1730837099): D:\Dropbox\www\ConquerorGame\ConquerorGame
abled.9.png ERROR: Unable to open PNG file
AAPT err(413781828): D:\Dropbox\www\ConquerorGame\ConquerorGame\
isabled.9.png ERROR: Unable to open PNG file
AAPT err(1730837099): D:\Dropbox\www\ConquerorGame\ConquerorGame
sabled.9.png ERROR: Unable to open PNG file
AAPT err(338923147): D:\Dropbox\www\ConquerorGame\ConquerorGame\
essed.9.png ERROR: Unable to open PNG file
AAPT err(107864953): D:\Dropbox\www\ConquerorGame\ConquerorGame\
abled.9.png ERROR: Unable to open PNG file
AAPT err(1087063106): D:\Dropbox\www\ConquerorGame\ConquerorGame
cused.9.png ERROR: Unable to open PNG file
AAPT err(787242274): D:\Dropbox\www\ConquerorGame\ConquerorGame\
cused.9.png ERROR: Unable to open PNG file
AAPT err(787242274): D:\Dropbox\www\ConquerorGame\ConquerorGame\
bled.9.png ERROR: Unable to open PNG file
AAPT err(365730399): D:\Dropbox\www\ConquerorGame\ConquerorGame\
bled.9.png ERROR: Unable to open PNG file
AAPT err(365730399): D:\Dropbox\www\ConquerorGame\ConquerorGame\
used.9.png ERROR: Unable to open PNG file
AAPT err(1266717903): D:\Dropbox\www\ConquerorGame\ConquerorGame
ocused.9.png ERROR: Unable to open PNG file
AAPT err(1021397758): D:\Dropbox\www\ConquerorGame\ConquerorGame
ormal.9.png ERROR: Unable to open PNG file
AAPT err(2007031690): D:\Dropbox\www\ConquerorGame\ConquerorGame
ressed.9.png ERROR: Unable to open PNG file
AAPT err(104723713): D:\Dropbox\www\ConquerorGame\ConquerorGame\
cused.9.png ERROR: Unable to open PNG file
AAPT err(1580013939): D:\Dropbox\www\ConquerorGame\ConquerorGame
focused.9.png ERROR: Unable to open PNG file
AAPT err(667469813): D:\Dropbox\www\ConquerorGame\ConquerorGame\
abled.9.png ERROR: Unable to open PNG file
AAPT err(1400858472): D:\Dropbox\www\ConquerorGame\ConquerorGame
normal.9.png ERROR: Unable to open PNG file
AAPT err(1052368712): D:\Dropbox\www\ConquerorGame\ConquerorGame
ormal.9.png ERROR: Unable to open PNG file
AAPT err(1659528560): D:\Dropbox\www\ConquerorGame\ConquerorGame
cused.9.png ERROR: Unable to open PNG file
AAPT err(1831080404): D:\Dropbox\www\ConquerorGame\ConquerorGame
isabled.9.png ERROR: Unable to open PNG file
AAPT err(1772585588): D:\Dropbox\www\ConquerorGame\ConquerorGame
essed.9.png ERROR: Unable to open PNG file
AAPT err(687694060): D:\Dropbox\www\ConquerorGame\ConquerorGame\
ssed.9.png ERROR: Unable to open PNG file
AAPT err(1772585588): D:\Dropbox\www\ConquerorGame\ConquerorGame
isabled.9.png ERROR: Unable to open PNG file
AAPT err(1831080404): D:\Dropbox\www\ConquerorGame\ConquerorGame
essed.9.png ERROR: Unable to open PNG file
AAPT err(1659528560): D:\Dropbox\www\ConquerorGame\ConquerorGame
abled.9.png ERROR: Unable to open PNG file
AAPT err(1052368712): D:\Dropbox\www\ConquerorGame\ConquerorGame
cused.9.png ERROR: Unable to open PNG file
AAPT err(667469813): D:\Dropbox\www\ConquerorGame\ConquerorGame\
ssed.9.png ERROR: Unable to open PNG file
AAPT err(1580013939): D:\Dropbox\www\ConquerorGame\ConquerorGame
abled.9.png ERROR: Unable to open PNG file
AAPT err(104723713): D:\Dropbox\www\ConquerorGame\ConquerorGame\
isabled.9.png ERROR: Unable to open PNG file
AAPT err(2007031690): D:\Dropbox\www\ConquerorGame\ConquerorGame
abled.9.png ERROR: Unable to open PNG file
AAPT err(1021397758): D:\Dropbox\www\ConquerorGame\ConquerorGame
cused.9.png ERROR: Unable to open PNG file
AAPT err(1266717903): D:\Dropbox\www\ConquerorGame\ConquerorGame
pressed.9.png ERROR: Unable to open PNG file
AAPT err(365730399): D:\Dropbox\www\ConquerorGame\ConquerorGame\
abled.9.png ERROR: Unable to open PNG file
AAPT err(1087063106): D:\Dropbox\www\ConquerorGame\ConquerorGame
essed.9.png ERROR: Unable to open PNG file
AAPT err(107864953): D:\Dropbox\www\ConquerorGame\ConquerorGame\
ressed.9.png ERROR: Unable to open PNG file
AAPT err(338923147): D:\Dropbox\www\ConquerorGame\ConquerorGame\
bled.9.png ERROR: Unable to open PNG file
AAPT err(1730837099): D:\Dropbox\www\ConquerorGame\ConquerorGame
ressed.9.png ERROR: Unable to open PNG file
AAPT err(413781828): D:\Dropbox\www\ConquerorGame\ConquerorGame\
ssed.9.png ERROR: Unable to open PNG file
AAPT err(338923147): D:\Dropbox\www\ConquerorGame\ConquerorGame\
essed.9.png ERROR: Unable to open PNG file
AAPT err(1266717903): D:\Dropbox\www\ConquerorGame\ConquerorGame
ressed.9.png ERROR: Unable to open PNG file
AAPT err(2007031690): D:\Dropbox\www\ConquerorGame\ConquerorGame
sabled.9.png ERROR: Unable to open PNG file
AAPT err(104723713): D:\Dropbox\www\ConquerorGame\ConquerorGame\
cused.9.png ERROR: Unable to open PNG file
AAPT err(1580013939): D:\Dropbox\www\ConquerorGame\ConquerorGame
isabled.9.png ERROR: Unable to open PNG file
AAPT err(667469813): D:\Dropbox\www\ConquerorGame\ConquerorGame\
ormal.9.png ERROR: Unable to open PNG file
AAPT err(1831080404): D:\Dropbox\www\ConquerorGame\ConquerorGame
ocused.9.png ERROR: Unable to open PNG file
AAPT err(667469813): D:\Dropbox\www\ConquerorGame\ConquerorGame\
rmal.9.png ERROR: Unable to open PNG file
AAPT err(104723713): D:\Dropbox\www\ConquerorGame\ConquerorGame\
abled.9.png ERROR: Unable to open PNG file
AAPT err(2007031690): D:\Dropbox\www\ConquerorGame\ConquerorGame
cused.9.png ERROR: Unable to open PNG file
AAPT err(1266717903): D:\Dropbox\www\ConquerorGame\ConquerorGame
essed.9.png ERROR: Unable to open PNG file
AAPT err(338923147): D:\Dropbox\www\ConquerorGame\ConquerorGame\
bled.9.png ERROR: Unable to open PNG file
:react-native-mauron85-background-geolocation:processReleaseMani
AAPT err(1266717903): D:\Dropbox\www\ConquerorGame\ConquerorGame
ormal.9.png ERROR: Unable to open PNG file
AAPT err(2007031690): D:\Dropbox\www\ConquerorGame\ConquerorGame
ocused.9.png ERROR: Unable to open PNG file
AAPT err(1266717903): D:\Dropbox\www\ConquerorGame\ConquerorGame
ressed.9.png ERROR: Unable to open PNG file
:react-native-mauron85-background-geolocation:processReleaseReso
D:\Dropbox\www\ConquerorGame\ConquerorGame\node_modules\react-na
hat matches the given name (at 'drawable' with value '@drawable/
D:\Dropbox\www\ConquerorGame\ConquerorGame\node_modules\react-na
that matches the given name (at 'drawable' with value '@drawable
D:\Dropbox\www\ConquerorGame\ConquerorGame\node_modules\react-na
that matches the given name (at 'drawable' with value '@drawable
D:\Dropbox\www\ConquerorGame\ConquerorGame\node_modules\react-na
 that matches the given name (at 'drawable' with value '@drawabl
D:\Dropbox\www\ConquerorGame\ConquerorGame\node_modules\react-na
hat matches the given name (at 'drawable' with value '@drawable/
D:\Dropbox\www\ConquerorGame\ConquerorGame\node_modules\react-na
that matches the given name (at 'drawable' with value '@drawable
D:\Dropbox\www\ConquerorGame\ConquerorGame\node_modules\react-na
that matches the given name (at 'drawable' with value '@drawable
D:\Dropbox\www\ConquerorGame\ConquerorGame\node_modules\react-na
 that matches the given name (at 'drawable' with value '@drawabl

:react-native-mauron85-background-geolocation:processReleaseReso

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-mauron85-background-geo
> com.android.ide.common.process.ProcessException: org.gradle.pr

* Try:
Run with --stacktrace option to get the stack trace. Run with --

BUILD FAILED

Total time: 23.162 secs
Could not install the app on the device, read the error above fo
Make sure you have an Android emulator running or a device conne
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by mauron85** [comment]
Not sure about that aapt error cause, but don't think it is plugin issue.

**Comment by jesperbjerke** [comment]
Did some research. This is most likely due to Windows MAX_PATH limit. I'll try set up a linux environment and try it out again and see if it works.

**Comment by jesperbjerke** [comment]
Build works on linux

**Comment by mauron85** [comment]
glad to hear that

**Comment by kenwu27** [comment]
Thanks for sharing the solution. As i don't have access to Linux machines at my company, i have decided to move all my react native app folders under dev folders in root, problems solved on windows for now.

**Comment by CarlosOV** [comment]
El problema es el Maximum Path Length Limitation de windows, aquí puede ver como quitarle la limitación.
https://msdn.microsoft.com/en-us/library/aa365247(VS.85).aspx
