### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by dinesh8055** [mauron85/react-native-background-geolocation#50]
## Your Environment

* Plugin version: v0.1.1
* Platform: iOS or Android: Android
* OS version: Ubuntu 16.10
* Device manufacturer and model: Nexus 5
* React Native version: 0.42.0
* Plugin configuration options: N/A

## Context

The app does not start. Please help

## Debug logs

:react-native-mauron85-background-geolocation:generateReleaseBuildConfig UP-TO-DATE
:react-native-mauron85-background-geolocation:generateReleaseResValues UP-TO-DATE
:react-native-mauron85-background-geolocation:generateReleaseResources UP-TO-DATE
:react-native-mauron85-background-geolocation:mergeReleaseResources UP-TO-DATE
:react-native-mauron85-background-geolocation:processReleaseManifest UP-TO-DATE
:react-native-mauron85-background-geolocation:processReleaseResources
:react-native-mauron85-background-geolocation:generateReleaseSources
:react-native-mauron85-background-geolocation:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:react-native-mauron85-background-geolocation:compileReleaseJavaWithJavac
Full recompilation is required because at least one of the classes of removed jar 'classes.jar' requires it. Analysis took 0.925 secs.
Note: /home/dinesh/projects/GoLoadDriver/node_modules/react-native-mauron85-background-geolocation/android/lib/src/main/java/com/marianhello/react/BackgroundGeolocationModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:react-native-mauron85-background-geolocation:extractReleaseAnnotations
:react-native-mauron85-background-geolocation:mergeReleaseShaders UP-TO-DATE
:react-native-mauron85-background-geolocation:compileReleaseShaders UP-TO-DATE
:react-native-mauron85-background-geolocation:generateReleaseAssets UP-TO-DATE
:react-native-mauron85-background-geolocation:mergeReleaseAssets UP-TO-DATE
:react-native-mauron85-background-geolocation:mergeReleaseProguardFiles UP-TO-DATE
:react-native-mauron85-background-geolocation:packageReleaseRenderscript UP-TO-DATE
:react-native-mauron85-background-geolocation:packageReleaseResources UP-TO-DATE
:react-native-mauron85-background-geolocation:processReleaseJavaRes UP-TO-DATE
:react-native-mauron85-background-geolocation:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:react-native-mauron85-background-geolocation:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE

## -adb logcat
03-16 00:53:54.375  5137  5152 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
03-16 00:53:54.375  5137  5152 E AndroidRuntime: Process: com.goloaddriver, PID: 5137
03-16 00:53:54.375  5137  5152 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
03-16 00:53:54.375  5137  5152 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
03-16 00:53:54.375  5137  5152 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
03-16 00:53:54.375  5137  5152 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
03-16 00:53:54.375  5137  5152 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
03-16 00:53:54.375  5137  5152 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
03-16 00:53:54.375  5137  5152 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
03-16 00:53:54.375  5137  5152 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
03-16 00:53:54.375  5137  5152 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: com.google.android.gms.maps.GoogleMapOptions
03-16 00:53:54.375  5137  5152 E AndroidRuntime: 	at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:54)
03-16 00:53:54.375  5137  5152 E AndroidRuntime: 	at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39)
03-16 00:53:54.375  5137  5152 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.createAllViewManagers(ReactInstanceManager.java:711)
03-16 00:53:54.375  5137  5152 E AndroidRuntime: 	at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:218)
03-16 00:53:54.375  5137  5152 E AndroidRuntime: 	at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:74)
03-16 00:53:54.375  5137  5152 E AndroidRuntime: 	at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:151)
03-16 00:53:54.375  5137  5152 E AndroidRuntime: 	at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:148)
03-16 00:53:54.375  5137  5152 E AndroidRuntime: 	at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:76)
03-16 00:53:54.375  5137  5152 E AndroidRuntime: 	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:88)
03-16 00:53:54.375  5137  5152 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:950)
03-16 00:53:54.375  5137  5152 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:880)
03-16 00:53:54.375  5137  5152 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:104)
03-16 00:53:54.375  5137  5152 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$ReactContextInitAsyncTask.doInBackground(ReactInstanceManager.java:218)
03-16 00:53:54.375  5137  5152 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$ReactContextInitAsyncTask.doInBackground(ReactInstanceManager.java:197)
03-16 00:53:54.375  5137  5152 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
03-16 00:53:54.375  5137  5152 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)

**Comment by mauron85** [comment]
I don't think it is caused directly by this plugin. According your `adb` log:

```
03-16 00:53:54.375 5137 5152 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: com.google.android.gms.maps.GoogleMapOptions
03-16 00:53:54.375 5137 5152 E AndroidRuntime: at com.airbnb.android.react.maps.AirMapManager.(AirMapManager.java:54)
03-16 00:53:54.375 5137 5152 E AndroidRuntime: at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39)
```

It seems you're also using https://github.com/airbnb/react-native-maps, which cause the crash and might be in conflict.

Try my advice from my example app:

> Module react-native-maps v0.8.2 requires Google Play Services library version 9.4.0, we need to change node_modules/react-native-mauron85-background-geolocation/android/lib/build.gradle
dependencies {
    ...
    compile 'com.google.android.gms:play-services-location:9.4.0'
    ...
}
More info https://github.com/lelandrichardson/react-native-maps/blob/master/docs/installation.md

**Comment by mauron85** [comment]
Also try building your app without this plugin if the error occurs and please report

**Comment by dinesh8055** [comment]
Thanks it works now
