### ISSUE TITLE
Blue indicator visible even after service is stopped

### ISSUE THREAD

**Issue by artmerlop** [mauron85/react-native-background-geolocation#515]
## Your Environment

* Plugin version: 0.6.3
* Platform: iOS
* OS version: 14.0
* Device manufacturer and model: iPhone 11 Pro Max

* Running in Simulator: Both
* React Native version: 0.63.3
* Plugin configuration options: 

`locationProvider: BackgroundGeolocation.RAW_PROVIDER,
  desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
  stationaryRadius: 5,
  distanceFilter: 5,
  debug: false,
  startForeground: false,
  stopOnStillActivity: false,
  stopOnTerminate: true,
  maxLocations: 1000,
  syncThreshold: 100,
  url: api,
  postTemplate: {
    accuracy: '@accuracy',
    altitude: '@altitude',
    altitudeAccuracy: '@altitudeAccuracy',
    latitude: '@latitude',
    longitude: '@longitude',
    speed: '@speed',
    time: '@time'
  }`

* Link to your project:

## Context
The applications keeps showing blue indicator on status bar even if the service is stopped, on background and foreground.

## Expected Behavior
When the service is stopped there should be no indicator, since the app is not processing any location update, when the permissions are "While in use"..

## Actual Behavior
The applications keeps showing blue indicator on status bar even if the service is stopped, on background and foreground, to be more specific if you start a process with this new configuration:

stopOnTerminate = false
startForeground = true

And then return to:

stopOnTerminate = true
startForeground = false

And run stop() function, the status bar is still showing the blue indicator that the app is using the device location, when the permissions are "While in use".

## Steps to Reproduce

1.
2.
3.
4.

**Comment by walterdl** [comment]
@artmerlop how did you solved it?
