### ISSUE TITLE
Location set by GPS notification on Android

### ISSUE THREAD

**Issue by kodemi** [mauron85/react-native-background-geolocation#53]
## Your Environment

* Plugin version: 0.2.0-alpha.6
* Platform: Android API 25
* OS version: Ubuntu 16.04
* Device manufacturer and model: Xiaomi Redmi Note 3 Pro
* React Native version: 0.41.2

configure object:
```
startForeground: false,
desiredAccuracy: 10,
stationaryRadius: 20,
distanceFilter: 50,
locationTimeout: 30,
startOnBoot: false,
stopOnTerminate: true,
locationProvider: BackgroundGeolocation.provider.ANDROID_ACTIVITY_PROVIDER,
interval: 10000,
fastestInterval: 5000,
activitiesInterval: 10000,
stopOnStillActivity: false
```

## Context
When GPS is available I've got notification "Location set by GPS" every several seconds (maybe it's `interval` configure option) and notification badge on app icon. Everytime this notification wakes up device. Only real device is affected, not simulator.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 243 days. You may reopen this issue if it has been closed in error.

**Comment by helloeyesimple** [comment]
Hi, also got this issue too. May I know the solution for this?

**Comment by Cloud9Clone** [comment]
What's the solution for it? It keeps appearing nowadays also.
