### ISSUE TITLE
how to fetch location when app is terminated in Android

### ISSUE THREAD

**Issue by mohammad-chavoshipor** [mauron85/react-native-background-geolocation#532]
## Your Environment

* Plugin version:^0.6.3"
* Platform: Android
* OS version: 10
* Device manufacturer and model:

* Running in Simulator:
* React Native version: 0.61
* Plugin configuration options: 
``` BackgroundGeolocation.configure({
    desiredAccuracy: BackgroundGeolocation.MEDIUM_ACCURACY,
    stationaryRadius: 0,
    distanceFilter: 0,
    notificationTitle: ' Location',
    notificationText: 'فعال',
    debug: false,
    startOnBoot: true,
    stopOnTerminate: false,
    locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
    interval: 5000,
    fastestInterval: 5000,
    activitiesInterval: 5000,
    stopOnStillActivity: false,
    startForeground: true,
```
## Context
i have used stopOnTerminate and set this value to false but i am not able to get location coordinates when app is terminated in Android ?

**Comment by darron1217** [comment]
I've created fork to support Android SDK 29+
https://github.com/darron1217/react-native-background-geolocation

**Comment by dfg31197** [comment]
> I've created fork to support Android SDK 29+
> https://github.com/darron1217/react-native-background-geolocation

It doesn't seem to solve the issue. Plus now, after killing and reopening the app, location doesn't work

**Comment by luciman** [comment]
I have the same problem. Do you find any solution? thank you

**Comment by wazimBadsha** [comment]
Any solution ?
 after terminating and reopening the app location doesn't work

**Comment by kitravee** [comment]
let's try to add gms:play-services-gcm to fix app crash
I hope this may help this issue.

android/app/build.gradle
`implementation 'com.google.android.gms:play-services-gcm:15.0.1'`
`implementation 'com.google.android.gms:play-services-location:15.0.1'`

![image](https://user-images.githubusercontent.com/50334192/126599688-bc62a05f-9729-41e7-90fd-25bfe1185694.png)

@darron1217  if this one help to fix this issue, please add it to https://github.com/darron1217/react-native-background-geolocation

**Comment by kitravee** [comment]
@darron1217  

> let's try to add gms:play-services-gcm to fix app crash
> I hope this may help this issue.
> 
> android/app/build.gradle
> `implementation 'com.google.android.gms:play-services-gcm:15.0.1' implementation 'com.google.android.gms:play-services-location:15.0.1'`
> 
> ![image](https://user-images.githubusercontent.com/50334192/126599688-bc62a05f-9729-41e7-90fd-25bfe1185694.png)

if this one help to fix this issue, please add it to https://github.com/darron1217/react-native-background-geolocation

**Comment by pavelustenko** [comment]
> I've created fork to support Android SDK 29+
> https://github.com/darron1217/react-native-background-geolocation

Thanks a lot! You literally saved me!
