### ISSUE TITLE
Cannot restart the service when users starts to move again if stopOnStillActivity = true

### ISSUE THREAD

**Issue by Assem-Hafez** [mauron85/react-native-background-geolocation#54]
## Your Environment
* Platform: Android

## Context
I want the GPS tracking to stop when the users stop moving and restarts when he starts to move again. so i used the config property stopOnStillActivity=true. then i found no way to know that the service had stopped because of StillActivity so i can restart it again.

## Possible Fix
It would be better if there is an event exposed that informs us with changing the Activity mode

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 243 days. You may reopen this issue if it has been closed in error.
