### ISSUE TITLE
[WRONG ISSUE PLEASE DELETE] Testing For Android 12

### ISSUE THREAD

**Issue by talibbk** [mauron85/react-native-background-geolocation#546]
I am trying to test my app for upcoming Android 12.  
My build fails at :  
> Execution failed for task ':app:installDevDebug'.
> com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl545282450.tmp/base.apk (at Binary XML file line #340): com.transistorsoft.tsbackgroundfetch.BootReceiver: Targeting S+ (version 10000 and above) requires that an explicit value for android:exported be defined when intent filters are present. 

I have fixed other similar errors by adding attribute android:exported to < activity > components that have < intent-filter > s declared in the app’s AndroidManifest.xml file, but i can't find solution for this one.
I am using react-native-background-geolocation which requires react-native-background-fetch as dependency.
I hope you can look into this.
Thankyou
 
## Your Environment

* Plugin version:^3.9.0
* Platform: Android
* OS version: Android 12
* Device manufacturer and model: Google Pixel 4a

* Running in Simulator:
* React Native version:0.61.3
* Plugin configuration options: 
* Link to your project:

## Expected Behavior

Able to build app
## Actual Behavior

get error :
Execution failed for task ':app:installDevDebug'.
> com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl215726433.tmp/base.apk (at Binary XML file line #340): com.transistorsoft.tsbackgroundfetch.BootReceiver: Targeting S+ (version 10000 and above) requires that an explicit value for android:exported be defined when intent filters are present
## Steps to Reproduce

1.
2.
3.
4.

**Comment by Linuhusainnk** [comment]
have you got solution? for me its not working from android 12 onwards
