### ISSUE TITLE
 Could not find com.intentfilter:android-permissions:0.1.7. while building

### ISSUE THREAD

**Issue by Anathapindika** [mauron85/react-native-background-geolocation#551]
## Your Environment

* Plugin version:
* Platform: Android
* OS version: 
* Device manufacturer and model:

* Running in Simulator: yes
* React Native version: 0.66.1
* Plugin configuration options: 
* Link to your project:

## Context

i tried to install it manually and automatically. got the same error.

## Expected Behavior

app should build

## Actual Behavior

app will not build.

## Steps to Reproduce

1. init a new project
2. install the app
3.
4.

## Debug logs

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.intentfilter:android-permissions:0.1.7.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/intentfilter/android-permissions/0.1.7/android-permissions-0.1.7.pom
       - file:/C:/Users/tbaec/.m2/repository/com/intentfilter/android-permissions/0.1.7/android-permissions-0.1.7.pom
       - file:/C:/Users/tbaec/Documents/lolola/lola/node_modules/react-native/android/com/intentfilter/android-permissions/0.1.7/android-permissions-0.1.7.pom
       - file:/C:/Users/tbaec/Documents/lolola/lola/node_modules/jsc-android/dist/com/intentfilter/android-permissions/0.1.7/android-permissions-0.1.7.pom
       - https://dl.google.com/dl/android/maven2/com/intentfilter/android-permissions/0.1.7/android-permissions-0.1.7.pom
       - https://www.jitpack.io/com/intentfilter/android-permissions/0.1.7/android-permissions-0.1.7.pom
     Required by:
         project :app > project :darron1217_react-native-background-geolocation > project :@darron1217_react-native-background-geolocation-common

**Comment by lucacima** [comment]
Add this line on Android/build.gradle file :

allprojects {
    repositories {
         ........................
         maven { url 'https://jcenter.bintray.com' }
         ...............

this work for me.

**Comment by Anathapindika** [comment]
thanks! resolved my issue

**Comment by toothlesstms** [comment]
https://jcenter.bintray.com not work help please
403 Forbidden

**Comment by bsadjetey** [comment]
> maven { url 'https://jcenter.bintray.com' }

this worked

**Comment by vish2595** [comment]
It is not working. Please suggest another solution.

**Comment by Inayat567** [comment]
Thanks issue resolved I have added this to the Android build file:

    allprojects {
        repositories{
            maven { 
                url 'https://jcenter.bintray.com'
            }
        }
    }

at the end of file

**Comment by JayavelAnandh** [comment]
Hey guys, I'm still encountering the issue

I hope I'm using it in right manner.
Your inputs are highly valued

![build_SS_for_resolution](https://github.com/user-attachments/assets/a02a63fc-4443-407d-b6a9-b91f024f55fc)
