### ISSUE TITLE
Location Paused Message

### ISSUE THREAD

**Issue by fozzarelo** [mauron85/react-native-background-geolocation#56]
The app seems to be tracking fine for a while. After some inactivity I get a "Location Updated Paused" Notification, and then no more updates. 
By the looks of it. My CLLocationManager is pausing after 10-20 minutes of inactivity as described in:
http://stackoverflow.com/questions/17484352/iphone-gps-in-background-never-resumes-after-pause.

My questions:
- Am I on the right track?
- Is there a way to prevent the pause from ever coming on? I can handle inactivity on my own. 

** I know this is an apple core issue more that yours. Just wondering if you guys found a way around it. 

* Plugin version: v0.1.1
* Platform: iOS
* OS version: 9
* Device manufacturer and model: Iphone 5 SE
* React Native version: 0.42
* Plugin configuration options: 
BackgroundGeolocation.configure({
      desiredAccuracy: 1,
      stationaryRadius: 1,
      distanceFilter: 1,
      debug: true,
      stopOnTerminate: false,
      interval: 1000,
      httpHeaders: {
        'X-FOO': 'bar'
      }
    }, function () {});
* Link to your project: I'm not allowed..

**Comment by christocracy** [comment]
In the original [`react-native-background-geolocation`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#config-boolean-pauseslocationupdatesautomatically-true) (of which, this project is a fork from over two years ago), you don't have to worry about `pausesLocationupdatesAutomatically`.  Mine uses its own motion-detection-based system, where you simply provide a [`stopTimeout`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#config-integer-minutes-stoptimeout).

Howeveer, if you really do wish to completely disable the stop-detection system, you're free to set [`pausesLocationUpdatesAutomatically: false`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#config-boolean-pauseslocationupdatesautomatically-true) and location-services are going to remain on forever, until you explicitly tell it to [`#stop`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#stopsuccessfn-failurefn) or [`#changePace(false)`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#changepaceenabled-successfn-failurefn)

**Comment by mauron85** [comment]
@fozzarelo I read the stackoverflow issue you've posted and it might be the same issue.

Currently pausesLocationUpdatesAutomatically is hardcoded to YES in.

https://github.com/mauron85/react-native-background-geolocation/blob/master/ios/RCTBackgroundGeolocation/LocationManager.m#L153

You can try to set NO or even add configure option. Also PR will be welcome.

**Comment by fozzarelo** [comment]
Ok sounds good. I'll give it a try.
Thanks guys.
