### ISSUE TITLE
url inside the BackgroundGeolocation.configure.

### ISSUE THREAD

**Issue by fozzarelo** [mauron85/react-native-background-geolocation#57]
I haven't been able to get the automatic post sent on location updates. Do you have any more info on how the fetch is built or how to debug it?

I have been calling a fetch in BackgroundGeolocation.on's callback. This seems to be working great: 
- Are there any downsides to doing it this way instead of using your automatic post?
- Are there limitations in what I can put in that callback?

Thanks for the info. And for an awesome plug-in.
Dan

Plugin version: v0.1.1
Platform: iOS
OS version: 9
Device manufacturer and model: Iphone 5 SE
React Native version: 0.42
Plugin configuration options:
BackgroundGeolocation.configure({
    desiredAccuracy: 1,
    stationaryRadius: 1,
    distanceFilter: 1,
   debug: true,
   stopOnTerminate: false,
   interval: 1000,
   httpHeaders: {
   'X-FOO': 'bar'
}
}, function () {});
Link to your project: I'm not allowed..

**Comment by mauron85** [comment]
Sure. Posting is done here https://github.com/mauron85/react-native-background-geolocation/blob/master/ios/RCTBackgroundGeolocation/LocationManager.m#L410

It should also log errors. Check [sample app](https://github.com/mauron85/react-native-background-geolocation-example) to get the idea how to retrieve and display logs. You can also use console from Xcode.

**Comment by fozzarelo** [comment]
awesome. Thank you Mauron
