### ISSUE TITLE
Location update event not fired

### ISSUE THREAD

**Issue by XPLOT1ON** [mauron85/react-native-background-geolocation#6]
I have just set up on my Android Emulator (Genymotion) and tried changing GPS location from command line tool as well from provided Genymotion GUI but the location doesn't seem to be updated. Did i missed config something?

```
BackgroundGeolocation.configure({
  desiredAccuracy: 0,
  stationaryRadius: 30,
  debug: true,
  distanceFilter: 30,
  startOnBoot: true,
  interval: 1000,
  notificationTitle: "Location Service",
  syncThreshold: 1,
  maxLocations: 1,
  locationProvider: 1,
  fastestInterval: 1000,
  activitiesInterval: 1000,
  stopOnStillActivity: true
});

BackgroundGeolocation.on('location', (location) => {
  console.log("Callback -> Lat: " + location.latitude + ", Long: " + location.longtitude)
  Actions.sendLocation(location);
});

BackgroundGeolocation.on('error', (error) => {
  console.log('[ERROR] BackgroundGeolocation error:', error);
});

BackgroundGeolocation.start(() => {
  console.log('[DEBUG] BackgroundGeolocation started successfully');
});
```

I have checked device log, only the start message came up

**Comment by mauron85** [comment]
Please test on a real device.

**Comment by XPLOT1ON** [comment]
@mauron85 Sure, I'll test on a device and get back to you if the problem continues.

**Comment by priezz** [comment]
This is something strange with Genymotion. When I have just discovered this plugin it worked. However about a week ago I have noticed that it stopped working and I can't explain why. So I have only the first location and no updates as well.

**Comment by mauron85** [comment]
@priezz read my answer regarding genymotion. it is probably the same thing.

https://github.com/mauron85/cordova-plugin-background-geolocation/issues/144#issuecomment-239614011

**Comment by ctubig** [comment]
Same issue with android 6.0 API 23. Location update not firing.

**Comment by mauron85** [comment]
Closing as no response received.
