### ISSUE TITLE
IOS Significant change or Region monitoring only

### ISSUE THREAD

**Issue by UrbanSam** [mauron85/react-native-background-geolocation#61]
Hi, this not an issue or bug. But i would like to know is there a way to have just significant change or region monitoring only. So in ios info.plist the background mode location key would not be necessary.

**Comment by mauron85** [comment]
Sorry, currently not.

**Comment by edencakir** [comment]
@UrbanSam Can you close this?

**Comment by UrbanSam** [comment]
@edencakir ah OK
