### ISSUE TITLE
Incompatible with RN 0.43.3

### ISSUE THREAD

**Issue by pocesar** [mauron85/react-native-background-geolocation#65]
## Your Environment

* Plugin version: 0.2.0-alpha.7
* Platform: Android 6
* OS version: Windows 10 x64
* Device manufacturer and model: Any
* React Native version: 0.43.3
* Plugin configuration options: Any
* Link to your project: Private

## Context

Trying to build with this lib as a dependency is giving:

```
Not using incremental javac compilation.
Evaluating project ':react-native-mauron85-background-geolocation' using build file 'G:\mobile\node_modules\react-native-mauron85-background-geolocation\android\build.gradle'.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > Configuration with name 'default' not found.
```

I removed all other linked dependencies, and it's the only one giving this error

## Expected Behavior

Compile

## Actual Behavior

Doesn't

## Steps to Reproduce

1. Install RN 0.43.3
2. Install 0.2.0-alpha.7
3. Do `react-native link`
4. Try to do `react-native run-android`

**Comment by mauron85** [comment]
Plugin is compatible with react-native link. Please read https://github.com/mauron85/react-native-background-geolocation#android-setup

**Comment by pocesar** [comment]
the library is already linked properly, but it's not allowing the project to build. if I remove it, it will build

**Comment by pocesar** [comment]
@mauron85 maybe put it highlighted in the README, because I've seen other issue with the same problem in #36
