### ISSUE TITLE
Warning:Ignoring Android API artifact com.google.android:android:2.1_r1 for debugAndroidTest

### ISSUE THREAD

**Issue by bennygenel** [mauron85/react-native-background-geolocation#67]
## Your Environment
* Plugin version: 0.2.0-alpha.7
* Platform: Android 
* React Native version: 0.43.3

## Context

When building on Android it gives an error
```
<shortened_for_readability>/node_modules/react-native-mauron85-background-geolocation/android/lib/build.gradle
Warning:Ignoring Android API artifact com.google.android:android:2.1_r1 for debugAndroidTest
```

**Comment by sators** [comment]
+1

**Comment by kolbasa** [comment]
+1

**Comment by RajkumarPR** [comment]
+1

**Comment by FredyC** [comment]
Got same stuff too for with the latest version (0.3.0-alpha.1) and using React Native 0.48.3. It's just a warning though, not an error. The build is successful even with those. Not sure how critical it is or what it can mean for runtime.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 60 days. You may reopen this issue if it has been closed in error.
