### ISSUE TITLE
play services base dependency fail compilation

### ISSUE THREAD

**Issue by ianaz** [mauron85/react-native-background-geolocation#70]
## Your Environment
* Plugin version: tried with both 0.2.0-alpha.6 and alpha.7
* Platform: Android 
* OS version: Windows 10.1
* React Native version: 0.42.0

## Context
After running react-native run-android I get the following error. Can't build

C:\Users\MyName\workspace\MyProject\node_modules\react-native-mauron85-background-geolocation\android\lib\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.4\res\drawable\common_google_signin_btn_icon_dark_normal.xml:3:29-91 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_dark_normal_background').
C:\Users\MyName\workspace\MyProject\node_modules\react-native-mauron85-background-geolocation\android\lib\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.4\res\drawable\common_google_signin_btn_icon_light_normal.xml:3:29-92 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_light_normal_background').
C:\Users\MyName\workspace\MyProject\node_modules\react-native-mauron85-background-geolocation\android\lib\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.4\res\drawable\common_google_signin_btn_text_dark_normal.xml:3:29-91 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_dark_normal_background').
C:\Users\MyName\workspace\MyProject\node_modules\react-native-mauron85-background-geolocation\android\lib\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.4\res\drawable\common_google_signin_btn_text_light_normal.xml:3:29-92 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_light_normal_background').

:react-native-mauron85-background-geolocation:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-mauron85-background-geolocation:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\MyName\AppData\Local\Android\Sdk\build-tools\23.0.3\aapt.exe'' finished with non-zero exit value 1

**Comment by ianaz** [comment]
Fixes somehow by setting 


    compile 'com.google.android.gms:play-services-location:9.8.0'

instead of "...play-services-location:+"
Should be a dependency issue in my project..

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 203 days. You may reopen this issue if it has been closed in error.

**Comment by Zenger** [comment]
A good way to fix this issue especially if you're getting something like this :
`Unknown source file : com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzas;`

First make sure it ignores the google.gms by setting: 
`compile project(':react-native-mauron85-background-geolocation') { 
exclude group: 'com.google.android.gms' \
}`

and then adding this to your `/app/build.gradle` :
`compile ('com.google.android.gms:play-services-location:10.0.1') {
        force = true 
    }`

`10.0.1` being the version you're referencing throughout your project.

**Comment by tugorez** [comment]
@Zenger it works :1st_place_medal: ! Thank you very much.
