### ISSUE TITLE
Warn if Google Play services is out of date

### ISSUE THREAD

**Issue by ivosabev** [mauron85/react-native-background-geolocation#72]
There should be a warning message or something when the Device Google Play services has a lower version than the required by the APK. This is not so common, but it happens and is not easy to find what the real problem is since the RNBG works, but the on('location') events are not called and no on('error') is fired.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 188 days. You may reopen this issue if it has been closed in error.
