### ISSUE TITLE
Sync Failed due to server error (201 HTTP STATUS)

### ISSUE THREAD

**Issue by L3V147H4N** [mauron85/react-native-background-geolocation#73]
I'm using featherjs on the backend and I have set up a route on api/locations to send the locations and the server works fine... it's recording the locations correctly and sending the results with 201 HTTP Status code but it seems that the service is not recognizing the response...
Should the server response have something more specific?

the logs says `Server error while posting locations responseCode: 201`

since 201 means "Created" this should be accepted as a valid response

**Comment by L3V147H4N** [comment]
I believe this could be the problem

https://github.com/mauron85/react-native-background-geolocation/blob/master/android/lib/src/main/java/com/marianhello/bgloc/LocationService.java#L465

HTTP_OK means 200 right?
Normaly every 200 status code means it's ok

**Comment by Roconda** [comment]
@L3V147H4N I noticed this as well. Made a pull request which allows 200 and 201's. 

Try https://github.com/mauron85/react-native-background-geolocation/pull/71

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 178 days. You may reopen this issue if it has been closed in error.
