### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by jorexe** [mauron85/react-native-background-geolocation#75]
It's there a way to insert cookies in the http request? I'm using authenticated users to call the API, but the request does not add those cookies.

**Comment by FredyC** [comment]
@jorexe Cookie is a header :) To be precise it's `Set-Cookie` header that server sends to the browser to instruct setting the cookie. But I guess you have figured it out or you don't need it anymore :)

**Comment by jorexe** [comment]
Hi @FredyC, i couldn't do it, because i don't have that cookie. I'm logging in using the Fetch API from react-native.

**Comment by FredyC** [comment]
@jorexe Then perhaps it would be common courtesy to close this issue ;)

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 78 days. You may reopen this issue if it has been closed in error.
