### ISSUE TITLE
react-native-mauron85-background-geolocation@0.2.0-alpha.7 has incorrect peer dependency react@>=15.3.0

### ISSUE THREAD

**Issue by Okipa** [mauron85/react-native-background-geolocation#76]
## Your Environment
* Plugin version : react-native-mauron85-background-geolocation@0.2.0-alpha.7
* Platform iOS or Android : Both
* React version : 16.0.0-alpha.6
* React Native version : 0.43.4

## Context
React 16.0.0-alpha.6 seems not supported by the package. The following warning is shown on dependencies management with npm or yarn :
`warning "react-native-mauron85-background-geolocation@0.2.0-alpha.7" has incorrect peer dependency "react@>=15.3.0"`

**Comment by mauron85** [comment]
The reason for such a warning is react@16 is currently alpha and alpha packages will not pass range check `react@>=15.3.0`

This warning will be gone, after react team publishes production version of react v16 (no -alpha suffix).

You can try https://semver.npmjs.com/ to check how range checks are applied to various npm packages.

**Comment by Okipa** [comment]
Got it ! Thanks for your quick answer.
