### ISSUE TITLE
What is the lowest Android version supported?

### ISSUE THREAD

**Issue by efratyo** [mauron85/react-native-background-geolocation#77]
I can see the documentations includes the SDK dependencies part, but is that the lowest SDK supported?

**Comment by fqborges** [comment]
minSdkVersion 16
from: https://github.com/mauron85/react-native-background-geolocation/blob/master/android/lib/build.gradle

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 172 days. You may reopen this issue if it has been closed in error.
