### ISSUE TITLE
How to remove listener(component) when activity is destroyed(component is unmounted)

### ISSUE THREAD

**Issue by farruxx** [mauron85/react-native-background-geolocation#79]
Now I get no-op warning, that it can update only mounted component, every time when I get new location. It should be memory leak of older component. Because, it happening after re-entering to the app. 
How to remove references to this component in method componentWillUnmount?

**Comment by farruxx** [comment]
Deeper debugging shows that module is not unregistering the emitter. So component is leaking, but native (android) module doesn't

**Comment by mauron85** [comment]
Yep, if you configure event listeners in component that mounts and unmounts frequently, make sure you also unregister events in componentWillUnmount or register events in component that doesn't not unmounts (root component or outside of any component in index.*.js for example).

Unregistering listeners is easy as on already returns callback you can call:
```
const usubscribe = BackgroundGeolocation.on('location', (location) => {...})
//
unsubsribe();
```

It should be probably mentioned in the docs thought.

**Comment by mauron85** [comment]
I think this is can be considered as resolved
