### ISSUE TITLE
Get location data after app is cleared from task manager.

### ISSUE THREAD

**Issue by nimishpatel19** [mauron85/react-native-background-geolocation#8]
I have integrated this in my app. I want to perform task in background when location meets specific latitude and longitude. 
`BackgroundGeolocation.on('location', (location) => {
     ToastAndroid.show("Location: latitude: " + location.latitude + " longitude: " + location.longitude, ToastAndroid.SHORT);
    }); `

I have tried to toast message here. But it is not working when my app is killed from task manager.

Guide me that how can I make it run in background.

**Comment by nimishpatel19** [comment]
My configurations are:
`stopOnTerminate: false, startOnBoot: true,`

**Comment by mauron85** [comment]
I'm afraid you cannot do this, because main thread is dead.
