### ISSUE TITLE
historic data

### ISSUE THREAD

**Issue by neo125874** [mauron85/react-native-background-geolocation#80]
i search the issues, and want to ask about after i stop the BackgroundGeolocation, and next time get    the previous data;

Is there any way to clear the historic data after i update to the server? 

What if the data collection over the size? would it replace the oldest one?

thanks in advance

**Comment by neo125874** [comment]
sorry, i saw that new one will replace the old one, further question: could it delete manually? 

because instead of using the server url, would firebase trigger the location sent deletion? how and where?

thank you.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 170 days. You may reopen this issue if it has been closed in error.
