### ISSUE TITLE
Cannot read property 'configure' of undefined

### ISSUE THREAD

**Issue by rexlow** [mauron85/react-native-background-geolocation#83]
Did a fresh install into my project. This error only occurs to iOS.

RN Version: 0.44.0

I followed the official guide and include the snippet below into my componentWillMount() but iOS simulator complains.

Any idea? The library is correctly linked.

```
BackgroundGeolocation.configure({
      desiredAccuracy: 0,
      stationaryRadius: 0,
      distanceFilter: 0,
      debug: false,
      startOnBoot: false,
      startForeground: true,
      stopOnTerminate: false,
      locationProvider:
        BackgroundGeolocation.provider.ANDROID_ACTIVITY_PROVIDER,
      saveBatteryOnBackground: false,
      interval: 1000,
      fastestInterval: 1000,
      activitiesInterval: 100,
      stopOnStillActivity: false,
      activityType: "Fitness",
      maxLocations: 0,
      syncThreshold: 0
    });
```

**Comment by Vetalyo** [comment]
I have the same issue, did you find out the solution?

**Comment by rexlow** [comment]
Just found out that the libsqlite3.tbd was not included. It is working now but some methods like getLocations() and a few others are not working for iOS. Just found out that some of the methods have not implemented. --> #18

**Comment by mauron85** [comment]
Yep, usually this kind of errors means the plugin was not installed correctly

**Comment by GregorioDiStefano** [comment]
Same issue here on Android.

**Comment by madbean** [comment]
hello same for me,
if someone have a work around (an "how to" for beginner), could be really great :-)

thx in advance

**Comment by GregorioDiStefano** [comment]
Previous messages were correct. This is simply due to failed integration with native Android layer (missing Gradle changes, source code changes, etc)

**Comment by shavenwalrus** [comment]
I have this issue on Android. I am new to react native and I have no idea what to do to get this working.

I don't know what the poster above means when he says

> This is simply due to failed integration with native Android layer (missing Gradle changes, source code changes, etc)

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 59 days. You may reopen this issue if it has been closed in error.

**Comment by dobrynia** [comment]
Similar situation after update from 0.4.1 to 0.5.0-alpha.* (1, 2, 3, no matter).
On iOS 11.2.5, RN Version: 0.51.0 I get an error `TypeError: Cannot read property 'configure' of undefined`
Android works fine.

**Comment by chinloongtan** [comment]
In my case, it is due to linking the wrong binary. Make sure it is ```libRCTBackgroundGeolocation.a``` and not ```libBackgroundGeolocation.a```.

**Comment by TVMD** [comment]
I got this problem on RN 62.2 too. (iOS)
- Tried with auto link
- Tried manual link
Update :
> In my case, it is due to linking the wrong binary. Make sure it is `libRCTBackgroundGeolocation.a` and not `libBackgroundGeolocation.a`.
 this work for me with manual link, RN 62.2.  ^0.6.3

**Comment by christocracy** [comment]
Do not use *manual link*.  Use only *auto-link* instructions.

This closed issue from 2017 has no correlation to modern version of RN.  I suggest you open a new issue and provide logs.  Are you sure you're terminating / restarting your dev server?
