### ISSUE TITLE
Use this component as listener?

### ISSUE THREAD

**Issue by rexlow** [mauron85/react-native-background-geolocation#85]
## Your Environment

* Plugin version: 0.2.0-alpha.7
* Platform: Android
* OS version: 5.1
* React Native version: 0.44.0
* Plugin configuration options: 

## Context
I'm trying to setup the methods like the official geolocation listener methods, is it possible? I look into the source and did not find any unmounting method. Only ```stop()``` is available but I do not want to stop the service entirely.

Anyway, here's my approach and it works, just that I'm not sure whether it has really unmounted my listeners. Has anyone tried the same approach?

```
// real time update user location even before tracking
  followUser = () => {
    this.startBackgroundGeolocation()
    this.followUserListener = BackgroundGeolocation.on("location", location => {
      this.props.updateLocation(location)
    })
  }

// remove follow user listener
  removeFollowUserListener = () => {
    if (this.followUserListener) {
      this.followUserListener.remove()
    }
  }
```

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 152 days. You may reopen this issue if it has been closed in error.
