### ISSUE TITLE
[IOS] Location never update even when moving

### ISSUE THREAD

**Issue by valehelle** [mauron85/react-native-background-geolocation#86]
## Your Environment

* Plugin version: 0.2.0-alpha.7
* Platform: iOS
* OS version: 10.3.2
* Device manufacturer and model: Apple
* React Native version: 0.43.4
* React version: 16.0.0-alpha.6
* Plugin configuration options: 
        BackgroundGeolocation.configure({
            desiredAccuracy: 100,
            stationaryRadius: 10,
            distanceFilter: 10,
            locationTimeout: 30,
            debug: true,
            startOnBoot: false,
            stopOnTerminate: false,
            locationProvider: BackgroundGeolocation.provider.ANDROID_ACTIVITY_PROVIDER,
            interval: 1000,
            fastestInterval: 5000,
            activitiesInterval: 10000,
            stopOnStillActivity: false,
            saveBatteryOnBackground	: false,
        });
* Link to your project:

## Context
The location of the user does not change. I am using airbnb map and I can see the track user icon moving however the location from react-native-background-location rarely update. Even if it update it will almost be at the same location. The setup works fine on Android.

## Expected Behavior
Should update location when moving

## Actual Behavior
Rarely does the location update. If it does, the location will be the same. Tested using simulator and actual device with the same result

##Running in simulator
![screen shot 2017-06-23 at 7 09 07 am](https://user-images.githubusercontent.com/14258220/27459942-6db7124a-57e3-11e7-9960-a2719d25b5ba.png)
Tested using react-native-background-location-example with the same result. 
As you can see, the user location is way ahead of the current gps location

##Running in real device
![photo](https://user-images.githubusercontent.com/14258220/27462032-6f1a5482-57f0-11e7-82fe-00c667baeae2.jpg)
Testing on actual device while driving. I notice that even though the location is late but it is accurate. Somehow the location is delayed for more than 40 second every time. From the picture below you can see that the track follow my route but I am already more than 10 KM ahead(My location is already out of the map). 

## Steps to Reproduce
1. Run on IOS
2.
3.
4.

## Context
Trying to build a running tracking application.

**Comment by valehelle** [comment]
Forgot to mention tested using using simulator and actual device with the same result

**Comment by valehelle** [comment]
![screen shot 2017-06-23 at 7 09 07 am](https://user-images.githubusercontent.com/14258220/27459942-6db7124a-57e3-11e7-9960-a2719d25b5ba.png)
Tested using react-native-background-location-example with the same result. 
As you can see, the user location is way ahead of the current gps location

**Comment by rexlow** [comment]
Hey man, Malaysian? I'm having the same issue here but on Android. You're using ANDROID_ACTIVITY_PROVIDER and I guess the delay is due to the config. I'm not sure whether the official config does what you want but it sounds to me that you should be doing ANDROID_DISTANCE_FILTER_PROVIDER.

**Comment by valehelle** [comment]
@rexlow yeah Malaysia. My issue is for IOS not android so I don't think that one is related.

**Comment by rexlow** [comment]
I see. Have you enabled this flag ```NSLocationAlwaysUsageDescription``` in Info.plist? I have actually tried some endless combination to make this plugin come to work for android but it never produces accurate GPS coords for walking usage. Let me know if you can get it working nicely.

**Comment by valehelle** [comment]
@rexlow mine is working perfectly on Android. What problem are you having? Is the GPS signal jumps around?

**Comment by rexlow** [comment]
@valehelle my device hardly receives location updates. Not sure if it's a device issue.

**Comment by valehelle** [comment]
@rexlow can I see your config?

**Comment by rexlow** [comment]
Sure!
```
const configureAndroidGeolocation = {
  desiredAccuracy: 0, //highest power
  stationaryRadius: 0,
  distanceFilter: 0, // locationUpdateInterval is ignored!
  notificationTitle: "App",
  notificationText: "Location services enabled",
  locationProvider:
    BackgroundGeolocation.provider.ANDROID_DISTANCE_FILTER_PROVIDER
};
```

We have decided to not use this library anymore as a result of failure to obtain active coords data after tested on multiple devices.

**Comment by valehelle** [comment]
@rexlow based on https://github.com/mauron85/react-native-background-geolocation/blob/master/PROVIDERS.md you should use ANDROID_ACTIVITY_PROVIDER instead of ANDROID_DISTANCE_FILTER_PROVIDER. Try changing stationaryRadius and distancefilter to something realistic like 10. I'm interested to know which library you are going to used beside this one because the only other library I know of is not free and the built in geolocation from facebook is not that accurate.

**Comment by rexlow** [comment]
@valehelle I have tried every possible combination before switching back to the geolocation polyfills that comes with RN. It works surprisingly well for my use case.

**Comment by valehelle** [comment]
@rexlow I see. In my case the accuracy drops below acceptable level when using geolocation polyfills in background. Anyway nice to see you have found your solution.
