### ISSUE TITLE
Possibility to directly access the SQLite database?

### ISSUE THREAD

**Issue by ramsestom** [mauron85/react-native-background-geolocation#87]
Can the SQLite database be directly requested with a module like this: https://github.com/andpor/react-native-sqlite-storage in case we want to perform specific queries (like querying if a specific position exist in the history)?
If yes, what is the name of the SQLite database and is there a scheme of it's tables architecture somewhere?

**Comment by mauron85** [comment]
In theory this could be possible. But you'll have to try it yourself.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 145 days. You may reopen this issue if it has been closed in error.
