### ISSUE TITLE
Adding custom parameters

### ISSUE THREAD

**Issue by kholiavko-roman** [mauron85/react-native-background-geolocation#88]
Hello, can anybody help me, how to add custom params to my POST request ?
I need add some id of user, and send it using GET request is not good idea.
In docs I found only `httpHeaders`  parameters, that allow to send headers, but how to send some extra params I didn't found.

**Comment by anil-kumar-singh** [comment]
I have same requirement to pass location  with user id as params. @kholiavko-roman do you find some thing.

**Comment by tomatopeel** [comment]
@kholiavko-roman @anil-kumar-singh One way of solving this would be to use an authentication token (e.g. JWT) and pass that in the `httpHeaders`.

**Comment by kholiavko-roman** [comment]
@anil-kumar-singh, I sloved my problem by adding option which add custom parameters to request, if you nedd it, I cat make PR. (I made it only for android) 

@tomatopeel, thanks, but I need send not only auth key, but some additional params.

**Comment by mauron85** [comment]
Why don't you add requested params into url? http://server:port/param1=value1&param2=value2. Simple as that.

**Comment by kholiavko-roman** [comment]
As I sad in my case I think this is not safe. Anyway, thanks for advice!

**Comment by mauron85** [comment]
Intentionally I didn't add any POST params, as I don't see any use case, that could not be done with url params or httpHeaders. Why is your use case so special? Really curious.

**Comment by kholiavko-roman** [comment]
My case in not special, just I prefer think that send auth key in get params it is not safe. Maybe I wrong.
