### ISSUE TITLE
Change settings when plugin already started?

### ISSUE THREAD

**Issue by ramsestom** [mauron85/react-native-background-geolocation#9]
Is it possible to change some settings when the plugin is already running, for example to request a higher/lower accuracy depending on what the user is doing in the app? Or do I need to stop the plugin, re-configure it with the new settings and restart it?
Also, is it possible to force a request of the current location? I do not see any function for this...

**Comment by mauron85** [comment]
currently not possible, you have to stop, configure and start service. But I was already thinking about this, that it would be nice to reconfigure service without start/stop step.

**Comment by ramsestom** [comment]
Yes would be great.
Also realized that this plugin, unlike the cordova one, seems to only implement functions `configure`, `start`, `stop` and `on` for now. Might be good to update the README if this is really the case so that users don't try to use functions this plugin do not support yet.

**Comment by mauron85** [comment]
My bad. I thought I'll find time to implement all those methods quickly. But you know...

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 451 days. You may reopen this issue if it has been closed in error.

**Comment by mauron85** [comment]
Implemented in 0.5.x branch
