### ISSUE TITLE
post twice

### ISSUE THREAD

**Issue by chenyi5266** [mauron85/react-native-background-geolocation#91]
post location to server twice every time   ???

**Comment by wbattel4607** [comment]
Is it the same issue as I'm having?

YouTube Video: https://www.youtube.com/watch?v=dt-nwmtusP8&feature=youtu.be

GitHub issue: https://github.com/mauron85/react-native-background-geolocation/issues/98

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 94 days. You may reopen this issue if it has been closed in error.
