### ISSUE TITLE
license

### ISSUE THREAD

**Issue by renehauck** [mauron85/react-native-background-geolocation#93]
I am very grateful for your work and I will also donate :+1: 

However, I am a little confused because the properties `@account_type` and `@content_authority` in the file `android/src/main/res/values/strings.xml`.

I don't need a license, or something like that, for my release builds, right?

**Comment by mauron85** [comment]
No you don't need license. This project is licensed under Apache 2.0 Licence.
>the license allows the user of the software the freedom to use the software for any purpose, to distribute it, to modify it, and to distribute modified versions of the software, under the terms of the license, without concern for royalties.

@Account_type and @content_authority are there for background location syncing (uploading to server), when app is not running. This is normal and all android apps are using "Accounts" to do background syncing.

**Comment by renehauck** [comment]
perfect, thank you
