### ISSUE TITLE
Support RN > 0.47

### ISSUE THREAD

**Issue by kontinuity** [mauron85/react-native-background-geolocation#95]
Due to a breaking change in RN we must remove a method (or remove override on it). Change commit is at https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8

**Comment by serus22** [comment]
+1

**Comment by cinder92** [comment]
+1

**Comment by naren8642** [comment]
+1

**Comment by martinmilev** [comment]
+1

**Comment by andidev** [comment]
The title should say Support RN >= 0.47  or Support RN > 0.46

**Comment by murilodag** [comment]
+1

**Comment by mauron85** [comment]
Should be fixed in 0.3.0-alpha.1
