### ISSUE TITLE
Not getting provider/how to get it

### ISSUE THREAD

**Issue by brainahdev** [mauron85/react-native-background-geolocation#96]
## Your Environment

* Plugin version:
* Platform: Android
* OS version: 6.1
* Device manufacturer and model:
* React Native version:
* Plugin configuration options: 
* Link to your project:

## Context

I am running this project and we get the location Provider where as not the provider callback param.

## Expected Behavior

Actually we need to get the param as mentioned in readme file

## Steps to Reproduce

1.
2.
3.
4.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 98 days. You may reopen this issue if it has been closed in error.
