### ISSUE TITLE
[Request] Hiding the "Syncing locations" notification (Android)

### ISSUE THREAD

**Issue by BuffMcBigHuge** [mauron85/react-native-background-geolocation#97]
## Environment
* Plugin version: 0.3.0-alpha.1
* Platform: Android
* OS version: 7.0
* Device manufacturer and model: Samsung S7
* React Native version: 0.45.1
* Plugin configuration options: 
```
desiredAccuracy: 10,
stationaryRadius: 50,
distanceFilter: 50,
locationTimeout: 30,
notificationTitle: 'Background Tracking',
notificationText: 'Enabled',
debug: false,
startOnBoot: false,
stopOnTerminate: true,
startForeground: true,
locationProvider: BackgroundGeolocation.provider.ANDROID_ACTIVITY_PROVIDER,
interval: 1000,
fastestInterval: 1000,
activitiesInterval: 1000,
stopOnStillActivity: false,
activityType: 'Other',
maxLocations: 0,
syncThreshold: 0,
pauseLocationUpdates: false,
pausesLocationUpdatesAutomatically: false,
url: config.endPoint+'/location?access_token='+token,
httpHeaders: {
    "Authorization" : "Bearer "+token
}
```

## Context
Is there an option to hide the _"Syncing Locations"_ notification? It appears and closes every second or so while my application is running. I didn't see anything in `SyncAdapter.java` that can hide the notification. Also, the there a way to hide the _"Background Tracking"_ notification as well?

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 96 days. You may reopen this issue if it has been closed in error.
