### ISSUE TITLE
iOS Location posted to server twice each time (first of each is inaccurate)

### ISSUE THREAD

**Issue by wbattel4607** [mauron85/react-native-background-geolocation#98]
## Environment
* Plugin version: 0.2.0-alpha.7
* Platform: iOS
* OS version: 10.3.2
* Device manufacturer and model: Apple iPhone 6 Plus
* React Native version: 0.45.1
* Plugin configuration options: 
`desiredAccuracy: 10,`
`stationaryRadius: 10,`
`distanceFilter: 10,`
`locationTimeout: 30,`
`notificationTitle: ‘Background Tracking’,`
`notificationText: ‘Enabled’,`
`debug: false,`
`startOnBoot: false,`
`stopOnTerminate: true,`
`startForeground: true,`
`locationProvider: BackgroundGeolocation.provider.ANDROID_ACTIVITY_PROVIDER,`
`interval: 30000,`
`fastestInterval: 15000,`
`activitiesInterval: 30000,`
`stopOnStillActivity: false,`
`activityType: ‘Other’,`
`maxLocations: 1,`
`syncThreshold: 0,`
`pauseLocationUpdates: false,`
`pausesLocationUpdatesAutomatically: false,`
`url: config.endPoint+‘/location?access_token=‘+token,`
`httpHeaders: {“Authorization” : “Bearer “+token}`

## Context
Context is pretty straight forward. This issue wastes transfer+compute resources and is unprofessional. I am looking for a way to avoid the first location from each update, because the first one is always inaccurate and the second one is always accurate. Everything else works fine.

## Expected Behavior
Location should post one time per update and be reasonably accurate.

## Actual Behavior
Location is posted twice each update and the first one is very inaccurate, causing the user to jump around. This happens both when user is moving (tried walking, running, and biking around the neighborhood) and when they are still. [Watch this video demo I recorded](https://www.youtube.com/watch?v=dt-nwmtusP8&feature=youtu.be).

## Possible Fix
I'm still investigating but right now I have no solid ideas. **Setting maxLocations to 0 only gives 1 location like I want, but the location it gives is inaccurate (similar to the first location given when maxLocations is 1). This makes me think that maybe setting maxLocations to 0 is discarding the more accurate of the two, where setting it to 1 returns both the accurate and inaccurate location.**

**Comment by wbattel4607** [comment]
I've made a temporary fix (seems to be working so far) in a branch I forked but I'd still like to know what was causing the issue so I can permanently avoid it.

https://github.com/wbattel4607/react-native-background-geolocation/commit/36614f92b3e71c24cad11e69386fd16c103be24c

**Comment by wbattel4607** [comment]
Further investigation is leading me to believe that what's happening is both the original location and the "better" location are being posted. Each location update is triggering "Better Location Found" and it seems that both are being sent when only the better location should be sent.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 95 days. You may reopen this issue if it has been closed in error.
